using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem
{
	// Token: 0x02000035 RID: 53
	internal class CampaignBehaviorDataStore
	{
		// Token: 0x0600036A RID: 874 RVA: 0x000178C0 File Offset: 0x00015AC0
		internal CampaignBehaviorDataStore()
		{
			this._behaviorDict = new Dictionary<string, CampaignBehaviorDataStore.BehaviorSaveData>();
		}

		// Token: 0x0600036B RID: 875 RVA: 0x000178D4 File Offset: 0x00015AD4
		internal void SaveBehaviorData(CampaignBehaviorBase campaignBehavior)
		{
			string stringId = campaignBehavior.StringId;
			CampaignBehaviorDataStore.BehaviorSaveData behaviorSaveData = new CampaignBehaviorDataStore.BehaviorSaveData(true);
			campaignBehavior.SyncData(behaviorSaveData);
			if (this._behaviorDict.ContainsKey(stringId))
			{
				Debug.FailedAssert("trying to save multiple behaviors with the same stringid: " + stringId, "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\CampaignBehaviorDataStore.cs", "SaveBehaviorData", 83);
				this._behaviorDict[stringId] = behaviorSaveData;
				return;
			}
			this._behaviorDict.Add(stringId, behaviorSaveData);
		}

		// Token: 0x0600036C RID: 876 RVA: 0x0001793B File Offset: 0x00015B3B
		internal void ClearBehaviorData()
		{
			this._behaviorDict.Clear();
		}

		// Token: 0x0600036D RID: 877 RVA: 0x00017948 File Offset: 0x00015B48
		internal void LoadBehaviorData(CampaignBehaviorBase campaignBehavior)
		{
			string stringId = campaignBehavior.StringId;
			CampaignBehaviorDataStore.BehaviorSaveData behaviorSaveData;
			if (this._behaviorDict.TryGetValue(stringId, out behaviorSaveData))
			{
				campaignBehavior.SyncData(behaviorSaveData);
				return;
			}
			List<KeyValuePair<string, CampaignBehaviorDataStore.BehaviorSaveData>> list = this._behaviorDict.ToList<KeyValuePair<string, CampaignBehaviorDataStore.BehaviorSaveData>>();
			string name = campaignBehavior.GetType().Name;
			foreach (KeyValuePair<string, CampaignBehaviorDataStore.BehaviorSaveData> keyValuePair in list)
			{
				if (keyValuePair.Key.Contains(name))
				{
					this._behaviorDict.Remove(keyValuePair.Key);
					this._behaviorDict.Add(stringId, keyValuePair.Value);
					campaignBehavior.SyncData(keyValuePair.Value);
					break;
				}
			}
		}

		// Token: 0x0600036E RID: 878 RVA: 0x00017A0C File Offset: 0x00015C0C
		internal static void AutoGeneratedStaticCollectObjectsCampaignBehaviorDataStore(object o, List<object> collectedObjects)
		{
			((CampaignBehaviorDataStore)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600036F RID: 879 RVA: 0x00017A1A File Offset: 0x00015C1A
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._behaviorDict);
		}

		// Token: 0x06000370 RID: 880 RVA: 0x00017A28 File Offset: 0x00015C28
		internal static object AutoGeneratedGetMemberValue_behaviorDict(object o)
		{
			return ((CampaignBehaviorDataStore)o)._behaviorDict;
		}

		// Token: 0x040000D0 RID: 208
		[SaveableField(1)]
		private readonly Dictionary<string, CampaignBehaviorDataStore.BehaviorSaveData> _behaviorDict;

		// Token: 0x020004FC RID: 1276
		internal class BehaviorSaveData : IDataStore
		{
			// Token: 0x06004BAF RID: 19375 RVA: 0x0017D3B4 File Offset: 0x0017B5B4
			public BehaviorSaveData(bool isSaving)
			{
				this._isSaving = isSaving;
			}

			// Token: 0x06004BB0 RID: 19376 RVA: 0x0017D3D0 File Offset: 0x0017B5D0
			public bool SyncData<T>(string key, ref T data)
			{
				if (this.IsSaving)
				{
					this._records.Add(key, data);
					return true;
				}
				object obj;
				if (this._records.TryGetValue(key, out obj))
				{
					data = (T)((object)obj);
					return true;
				}
				return false;
			}

			// Token: 0x17000ECC RID: 3788
			// (get) Token: 0x06004BB1 RID: 19377 RVA: 0x0017D41D File Offset: 0x0017B61D
			public bool IsSaving
			{
				get
				{
					return this._isSaving;
				}
			}

			// Token: 0x17000ECD RID: 3789
			// (get) Token: 0x06004BB2 RID: 19378 RVA: 0x0017D425 File Offset: 0x0017B625
			public bool IsLoading
			{
				get
				{
					return !this._isSaving;
				}
			}

			// Token: 0x06004BB3 RID: 19379 RVA: 0x0017D430 File Offset: 0x0017B630
			internal static void AutoGeneratedStaticCollectObjectsBehaviorSaveData(object o, List<object> collectedObjects)
			{
				((CampaignBehaviorDataStore.BehaviorSaveData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06004BB4 RID: 19380 RVA: 0x0017D43E File Offset: 0x0017B63E
			protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				collectedObjects.Add(this._records);
			}

			// Token: 0x06004BB5 RID: 19381 RVA: 0x0017D44C File Offset: 0x0017B64C
			internal static object AutoGeneratedGetMemberValue_records(object o)
			{
				return ((CampaignBehaviorDataStore.BehaviorSaveData)o)._records;
			}

			// Token: 0x0400157C RID: 5500
			[SaveableField(0)]
			private Dictionary<string, object> _records = new Dictionary<string, object>();

			// Token: 0x0400157D RID: 5501
			private readonly bool _isSaving;
		}
	}
}
