using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.CampaignSystem
{
	// Token: 0x02000066 RID: 102
	public sealed class CultureObject : BasicCultureObject
	{
		// Token: 0x06000BCC RID: 3020 RVA: 0x000427AE File Offset: 0x000409AE
		internal static void AutoGeneratedStaticCollectObjectsCultureObject(object o, List<object> collectedObjects)
		{
			((CultureObject)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06000BCD RID: 3021 RVA: 0x000427BC File Offset: 0x000409BC
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x1700026E RID: 622
		// (get) Token: 0x06000BCE RID: 3022 RVA: 0x000427C5 File Offset: 0x000409C5
		// (set) Token: 0x06000BCF RID: 3023 RVA: 0x000427CD File Offset: 0x000409CD
		public CultureTrait[] Traits { get; private set; }

		// Token: 0x06000BD0 RID: 3024 RVA: 0x000427D6 File Offset: 0x000409D6
		public bool HasTrait(CultureTrait trait)
		{
			return this.Traits.Contains(trait);
		}

		// Token: 0x06000BD1 RID: 3025 RVA: 0x000427E4 File Offset: 0x000409E4
		public bool HasFeat(FeatObject feat)
		{
			return this._cultureFeats.Contains(feat);
		}

		// Token: 0x06000BD2 RID: 3026 RVA: 0x000427F2 File Offset: 0x000409F2
		public IEnumerable<FeatObject> GetCulturalFeats(Func<FeatObject, bool> predicate = null)
		{
			foreach (FeatObject featObject in this._cultureFeats)
			{
				if (predicate == null || predicate(featObject))
				{
					yield return featObject;
				}
			}
			List<FeatObject>.Enumerator enumerator = default(List<FeatObject>.Enumerator);
			yield break;
			yield break;
		}

		// Token: 0x1700026F RID: 623
		// (get) Token: 0x06000BD3 RID: 3027 RVA: 0x00042809 File Offset: 0x00040A09
		// (set) Token: 0x06000BD4 RID: 3028 RVA: 0x00042811 File Offset: 0x00040A11
		public CharacterObject BasicTroop { get; private set; }

		// Token: 0x17000270 RID: 624
		// (get) Token: 0x06000BD5 RID: 3029 RVA: 0x0004281A File Offset: 0x00040A1A
		// (set) Token: 0x06000BD6 RID: 3030 RVA: 0x00042822 File Offset: 0x00040A22
		public CharacterObject EliteBasicTroop { get; private set; }

		// Token: 0x17000271 RID: 625
		// (get) Token: 0x06000BD7 RID: 3031 RVA: 0x0004282B File Offset: 0x00040A2B
		// (set) Token: 0x06000BD8 RID: 3032 RVA: 0x00042833 File Offset: 0x00040A33
		public CharacterObject MeleeMilitiaTroop { get; private set; }

		// Token: 0x17000272 RID: 626
		// (get) Token: 0x06000BD9 RID: 3033 RVA: 0x0004283C File Offset: 0x00040A3C
		// (set) Token: 0x06000BDA RID: 3034 RVA: 0x00042844 File Offset: 0x00040A44
		public CharacterObject MeleeEliteMilitiaTroop { get; private set; }

		// Token: 0x17000273 RID: 627
		// (get) Token: 0x06000BDB RID: 3035 RVA: 0x0004284D File Offset: 0x00040A4D
		// (set) Token: 0x06000BDC RID: 3036 RVA: 0x00042855 File Offset: 0x00040A55
		public CharacterObject RangedEliteMilitiaTroop { get; private set; }

		// Token: 0x17000274 RID: 628
		// (get) Token: 0x06000BDD RID: 3037 RVA: 0x0004285E File Offset: 0x00040A5E
		// (set) Token: 0x06000BDE RID: 3038 RVA: 0x00042866 File Offset: 0x00040A66
		public CharacterObject RangedMilitiaTroop { get; private set; }

		// Token: 0x17000275 RID: 629
		// (get) Token: 0x06000BDF RID: 3039 RVA: 0x0004286F File Offset: 0x00040A6F
		// (set) Token: 0x06000BE0 RID: 3040 RVA: 0x00042877 File Offset: 0x00040A77
		public CharacterObject TournamentMaster { get; private set; }

		// Token: 0x17000276 RID: 630
		// (get) Token: 0x06000BE1 RID: 3041 RVA: 0x00042880 File Offset: 0x00040A80
		// (set) Token: 0x06000BE2 RID: 3042 RVA: 0x00042888 File Offset: 0x00040A88
		public CharacterObject Villager { get; private set; }

		// Token: 0x17000277 RID: 631
		// (get) Token: 0x06000BE3 RID: 3043 RVA: 0x00042891 File Offset: 0x00040A91
		// (set) Token: 0x06000BE4 RID: 3044 RVA: 0x00042899 File Offset: 0x00040A99
		public CharacterObject CaravanMaster { get; private set; }

		// Token: 0x17000278 RID: 632
		// (get) Token: 0x06000BE5 RID: 3045 RVA: 0x000428A2 File Offset: 0x00040AA2
		// (set) Token: 0x06000BE6 RID: 3046 RVA: 0x000428AA File Offset: 0x00040AAA
		public CharacterObject CaravanGuard { get; private set; }

		// Token: 0x17000279 RID: 633
		// (get) Token: 0x06000BE7 RID: 3047 RVA: 0x000428B3 File Offset: 0x00040AB3
		// (set) Token: 0x06000BE8 RID: 3048 RVA: 0x000428BB File Offset: 0x00040ABB
		public CharacterObject PrisonGuard { get; private set; }

		// Token: 0x1700027A RID: 634
		// (get) Token: 0x06000BE9 RID: 3049 RVA: 0x000428C4 File Offset: 0x00040AC4
		// (set) Token: 0x06000BEA RID: 3050 RVA: 0x000428CC File Offset: 0x00040ACC
		public CharacterObject Guard { get; private set; }

		// Token: 0x1700027B RID: 635
		// (get) Token: 0x06000BEB RID: 3051 RVA: 0x000428D5 File Offset: 0x00040AD5
		// (set) Token: 0x06000BEC RID: 3052 RVA: 0x000428DD File Offset: 0x00040ADD
		public CharacterObject Blacksmith { get; private set; }

		// Token: 0x1700027C RID: 636
		// (get) Token: 0x06000BED RID: 3053 RVA: 0x000428E6 File Offset: 0x00040AE6
		// (set) Token: 0x06000BEE RID: 3054 RVA: 0x000428EE File Offset: 0x00040AEE
		public CharacterObject Weaponsmith { get; private set; }

		// Token: 0x1700027D RID: 637
		// (get) Token: 0x06000BEF RID: 3055 RVA: 0x000428F7 File Offset: 0x00040AF7
		// (set) Token: 0x06000BF0 RID: 3056 RVA: 0x000428FF File Offset: 0x00040AFF
		public CharacterObject Townswoman { get; private set; }

		// Token: 0x1700027E RID: 638
		// (get) Token: 0x06000BF1 RID: 3057 RVA: 0x00042908 File Offset: 0x00040B08
		// (set) Token: 0x06000BF2 RID: 3058 RVA: 0x00042910 File Offset: 0x00040B10
		public CharacterObject TownswomanInfant { get; private set; }

		// Token: 0x1700027F RID: 639
		// (get) Token: 0x06000BF3 RID: 3059 RVA: 0x00042919 File Offset: 0x00040B19
		// (set) Token: 0x06000BF4 RID: 3060 RVA: 0x00042921 File Offset: 0x00040B21
		public CharacterObject TownswomanChild { get; private set; }

		// Token: 0x17000280 RID: 640
		// (get) Token: 0x06000BF5 RID: 3061 RVA: 0x0004292A File Offset: 0x00040B2A
		// (set) Token: 0x06000BF6 RID: 3062 RVA: 0x00042932 File Offset: 0x00040B32
		public CharacterObject TownswomanTeenager { get; private set; }

		// Token: 0x17000281 RID: 641
		// (get) Token: 0x06000BF7 RID: 3063 RVA: 0x0004293B File Offset: 0x00040B3B
		// (set) Token: 0x06000BF8 RID: 3064 RVA: 0x00042943 File Offset: 0x00040B43
		public CharacterObject VillageWoman { get; private set; }

		// Token: 0x17000282 RID: 642
		// (get) Token: 0x06000BF9 RID: 3065 RVA: 0x0004294C File Offset: 0x00040B4C
		// (set) Token: 0x06000BFA RID: 3066 RVA: 0x00042954 File Offset: 0x00040B54
		public CharacterObject VillagerMaleChild { get; private set; }

		// Token: 0x17000283 RID: 643
		// (get) Token: 0x06000BFB RID: 3067 RVA: 0x0004295D File Offset: 0x00040B5D
		// (set) Token: 0x06000BFC RID: 3068 RVA: 0x00042965 File Offset: 0x00040B65
		public CharacterObject VillagerMaleTeenager { get; private set; }

		// Token: 0x17000284 RID: 644
		// (get) Token: 0x06000BFD RID: 3069 RVA: 0x0004296E File Offset: 0x00040B6E
		// (set) Token: 0x06000BFE RID: 3070 RVA: 0x00042976 File Offset: 0x00040B76
		public CharacterObject VillagerFemaleChild { get; private set; }

		// Token: 0x17000285 RID: 645
		// (get) Token: 0x06000BFF RID: 3071 RVA: 0x0004297F File Offset: 0x00040B7F
		// (set) Token: 0x06000C00 RID: 3072 RVA: 0x00042987 File Offset: 0x00040B87
		public CharacterObject VillagerFemaleTeenager { get; private set; }

		// Token: 0x17000286 RID: 646
		// (get) Token: 0x06000C01 RID: 3073 RVA: 0x00042990 File Offset: 0x00040B90
		// (set) Token: 0x06000C02 RID: 3074 RVA: 0x00042998 File Offset: 0x00040B98
		public CharacterObject Townsman { get; private set; }

		// Token: 0x17000287 RID: 647
		// (get) Token: 0x06000C03 RID: 3075 RVA: 0x000429A1 File Offset: 0x00040BA1
		// (set) Token: 0x06000C04 RID: 3076 RVA: 0x000429A9 File Offset: 0x00040BA9
		public CharacterObject TownsmanInfant { get; private set; }

		// Token: 0x17000288 RID: 648
		// (get) Token: 0x06000C05 RID: 3077 RVA: 0x000429B2 File Offset: 0x00040BB2
		// (set) Token: 0x06000C06 RID: 3078 RVA: 0x000429BA File Offset: 0x00040BBA
		public CharacterObject TownsmanChild { get; private set; }

		// Token: 0x17000289 RID: 649
		// (get) Token: 0x06000C07 RID: 3079 RVA: 0x000429C3 File Offset: 0x00040BC3
		// (set) Token: 0x06000C08 RID: 3080 RVA: 0x000429CB File Offset: 0x00040BCB
		public CharacterObject TownsmanTeenager { get; private set; }

		// Token: 0x1700028A RID: 650
		// (get) Token: 0x06000C09 RID: 3081 RVA: 0x000429D4 File Offset: 0x00040BD4
		// (set) Token: 0x06000C0A RID: 3082 RVA: 0x000429DC File Offset: 0x00040BDC
		public CharacterObject RansomBroker { get; private set; }

		// Token: 0x1700028B RID: 651
		// (get) Token: 0x06000C0B RID: 3083 RVA: 0x000429E5 File Offset: 0x00040BE5
		// (set) Token: 0x06000C0C RID: 3084 RVA: 0x000429ED File Offset: 0x00040BED
		public CharacterObject GangleaderBodyguard { get; private set; }

		// Token: 0x1700028C RID: 652
		// (get) Token: 0x06000C0D RID: 3085 RVA: 0x000429F6 File Offset: 0x00040BF6
		// (set) Token: 0x06000C0E RID: 3086 RVA: 0x000429FE File Offset: 0x00040BFE
		public CharacterObject MerchantNotary { get; private set; }

		// Token: 0x1700028D RID: 653
		// (get) Token: 0x06000C0F RID: 3087 RVA: 0x00042A07 File Offset: 0x00040C07
		// (set) Token: 0x06000C10 RID: 3088 RVA: 0x00042A0F File Offset: 0x00040C0F
		public CharacterObject ArtisanNotary { get; private set; }

		// Token: 0x1700028E RID: 654
		// (get) Token: 0x06000C11 RID: 3089 RVA: 0x00042A18 File Offset: 0x00040C18
		// (set) Token: 0x06000C12 RID: 3090 RVA: 0x00042A20 File Offset: 0x00040C20
		public CharacterObject PreacherNotary { get; private set; }

		// Token: 0x1700028F RID: 655
		// (get) Token: 0x06000C13 RID: 3091 RVA: 0x00042A29 File Offset: 0x00040C29
		// (set) Token: 0x06000C14 RID: 3092 RVA: 0x00042A31 File Offset: 0x00040C31
		public CharacterObject RuralNotableNotary { get; private set; }

		// Token: 0x17000290 RID: 656
		// (get) Token: 0x06000C15 RID: 3093 RVA: 0x00042A3A File Offset: 0x00040C3A
		// (set) Token: 0x06000C16 RID: 3094 RVA: 0x00042A42 File Offset: 0x00040C42
		public CharacterObject ShopWorker { get; private set; }

		// Token: 0x17000291 RID: 657
		// (get) Token: 0x06000C17 RID: 3095 RVA: 0x00042A4B File Offset: 0x00040C4B
		// (set) Token: 0x06000C18 RID: 3096 RVA: 0x00042A53 File Offset: 0x00040C53
		public CharacterObject Tavernkeeper { get; private set; }

		// Token: 0x17000292 RID: 658
		// (get) Token: 0x06000C19 RID: 3097 RVA: 0x00042A5C File Offset: 0x00040C5C
		// (set) Token: 0x06000C1A RID: 3098 RVA: 0x00042A64 File Offset: 0x00040C64
		public CharacterObject TavernGamehost { get; private set; }

		// Token: 0x17000293 RID: 659
		// (get) Token: 0x06000C1B RID: 3099 RVA: 0x00042A6D File Offset: 0x00040C6D
		// (set) Token: 0x06000C1C RID: 3100 RVA: 0x00042A75 File Offset: 0x00040C75
		public CharacterObject Musician { get; private set; }

		// Token: 0x17000294 RID: 660
		// (get) Token: 0x06000C1D RID: 3101 RVA: 0x00042A7E File Offset: 0x00040C7E
		// (set) Token: 0x06000C1E RID: 3102 RVA: 0x00042A86 File Offset: 0x00040C86
		public CharacterObject TavernWench { get; private set; }

		// Token: 0x17000295 RID: 661
		// (get) Token: 0x06000C1F RID: 3103 RVA: 0x00042A8F File Offset: 0x00040C8F
		// (set) Token: 0x06000C20 RID: 3104 RVA: 0x00042A97 File Offset: 0x00040C97
		public CharacterObject Armorer { get; private set; }

		// Token: 0x17000296 RID: 662
		// (get) Token: 0x06000C21 RID: 3105 RVA: 0x00042AA0 File Offset: 0x00040CA0
		// (set) Token: 0x06000C22 RID: 3106 RVA: 0x00042AA8 File Offset: 0x00040CA8
		public CharacterObject HorseMerchant { get; private set; }

		// Token: 0x17000297 RID: 663
		// (get) Token: 0x06000C23 RID: 3107 RVA: 0x00042AB1 File Offset: 0x00040CB1
		// (set) Token: 0x06000C24 RID: 3108 RVA: 0x00042AB9 File Offset: 0x00040CB9
		public CharacterObject Barber { get; private set; }

		// Token: 0x17000298 RID: 664
		// (get) Token: 0x06000C25 RID: 3109 RVA: 0x00042AC2 File Offset: 0x00040CC2
		// (set) Token: 0x06000C26 RID: 3110 RVA: 0x00042ACA File Offset: 0x00040CCA
		public CharacterObject Merchant { get; private set; }

		// Token: 0x17000299 RID: 665
		// (get) Token: 0x06000C27 RID: 3111 RVA: 0x00042AD3 File Offset: 0x00040CD3
		// (set) Token: 0x06000C28 RID: 3112 RVA: 0x00042ADB File Offset: 0x00040CDB
		public CharacterObject Beggar { get; private set; }

		// Token: 0x1700029A RID: 666
		// (get) Token: 0x06000C29 RID: 3113 RVA: 0x00042AE4 File Offset: 0x00040CE4
		// (set) Token: 0x06000C2A RID: 3114 RVA: 0x00042AEC File Offset: 0x00040CEC
		public CharacterObject FemaleBeggar { get; private set; }

		// Token: 0x1700029B RID: 667
		// (get) Token: 0x06000C2B RID: 3115 RVA: 0x00042AF5 File Offset: 0x00040CF5
		// (set) Token: 0x06000C2C RID: 3116 RVA: 0x00042AFD File Offset: 0x00040CFD
		public CharacterObject FemaleDancer { get; private set; }

		// Token: 0x1700029C RID: 668
		// (get) Token: 0x06000C2D RID: 3117 RVA: 0x00042B06 File Offset: 0x00040D06
		// (set) Token: 0x06000C2E RID: 3118 RVA: 0x00042B0E File Offset: 0x00040D0E
		public CharacterObject Shipwright { get; private set; }

		// Token: 0x1700029D RID: 669
		// (get) Token: 0x06000C2F RID: 3119 RVA: 0x00042B17 File Offset: 0x00040D17
		// (set) Token: 0x06000C30 RID: 3120 RVA: 0x00042B1F File Offset: 0x00040D1F
		public CharacterObject ShipyardWorker { get; private set; }

		// Token: 0x1700029E RID: 670
		// (get) Token: 0x06000C31 RID: 3121 RVA: 0x00042B28 File Offset: 0x00040D28
		// (set) Token: 0x06000C32 RID: 3122 RVA: 0x00042B30 File Offset: 0x00040D30
		public CharacterObject MilitiaVeteranArcher { get; private set; }

		// Token: 0x1700029F RID: 671
		// (get) Token: 0x06000C33 RID: 3123 RVA: 0x00042B39 File Offset: 0x00040D39
		// (set) Token: 0x06000C34 RID: 3124 RVA: 0x00042B41 File Offset: 0x00040D41
		public CharacterObject GearDummy { get; private set; }

		// Token: 0x170002A0 RID: 672
		// (get) Token: 0x06000C35 RID: 3125 RVA: 0x00042B4A File Offset: 0x00040D4A
		// (set) Token: 0x06000C36 RID: 3126 RVA: 0x00042B52 File Offset: 0x00040D52
		public MBEquipmentRoster DefaultBattleEquipmentRoster { get; private set; }

		// Token: 0x170002A1 RID: 673
		// (get) Token: 0x06000C37 RID: 3127 RVA: 0x00042B5B File Offset: 0x00040D5B
		// (set) Token: 0x06000C38 RID: 3128 RVA: 0x00042B63 File Offset: 0x00040D63
		public MBEquipmentRoster DefaultCivilianEquipmentRoster { get; private set; }

		// Token: 0x170002A2 RID: 674
		// (get) Token: 0x06000C39 RID: 3129 RVA: 0x00042B6C File Offset: 0x00040D6C
		// (set) Token: 0x06000C3A RID: 3130 RVA: 0x00042B74 File Offset: 0x00040D74
		public MBEquipmentRoster DefaultStealthEquipmentRoster { get; private set; }

		// Token: 0x170002A3 RID: 675
		// (get) Token: 0x06000C3B RID: 3131 RVA: 0x00042B7D File Offset: 0x00040D7D
		// (set) Token: 0x06000C3C RID: 3132 RVA: 0x00042B85 File Offset: 0x00040D85
		public MBEquipmentRoster DuelPresetEquipmentRoster { get; private set; }

		// Token: 0x170002A4 RID: 676
		// (get) Token: 0x06000C3D RID: 3133 RVA: 0x00042B8E File Offset: 0x00040D8E
		// (set) Token: 0x06000C3E RID: 3134 RVA: 0x00042B96 File Offset: 0x00040D96
		public MBEquipmentRoster MarriageBrideEquipmentRoster { get; private set; }

		// Token: 0x170002A5 RID: 677
		// (get) Token: 0x06000C3F RID: 3135 RVA: 0x00042B9F File Offset: 0x00040D9F
		// (set) Token: 0x06000C40 RID: 3136 RVA: 0x00042BA7 File Offset: 0x00040DA7
		public CharacterObject BanditChief { get; private set; }

		// Token: 0x170002A6 RID: 678
		// (get) Token: 0x06000C41 RID: 3137 RVA: 0x00042BB0 File Offset: 0x00040DB0
		// (set) Token: 0x06000C42 RID: 3138 RVA: 0x00042BB8 File Offset: 0x00040DB8
		public CharacterObject BanditRaider { get; private set; }

		// Token: 0x170002A7 RID: 679
		// (get) Token: 0x06000C43 RID: 3139 RVA: 0x00042BC1 File Offset: 0x00040DC1
		// (set) Token: 0x06000C44 RID: 3140 RVA: 0x00042BC9 File Offset: 0x00040DC9
		public CharacterObject BanditBandit { get; private set; }

		// Token: 0x170002A8 RID: 680
		// (get) Token: 0x06000C45 RID: 3141 RVA: 0x00042BD2 File Offset: 0x00040DD2
		// (set) Token: 0x06000C46 RID: 3142 RVA: 0x00042BDA File Offset: 0x00040DDA
		public CharacterObject BanditBoss { get; private set; }

		// Token: 0x170002A9 RID: 681
		// (get) Token: 0x06000C47 RID: 3143 RVA: 0x00042BE3 File Offset: 0x00040DE3
		// (set) Token: 0x06000C48 RID: 3144 RVA: 0x00042BEB File Offset: 0x00040DEB
		public MBBodyProperty DefaultCharacterCreationBodyProperty { get; private set; }

		// Token: 0x170002AA RID: 682
		// (get) Token: 0x06000C49 RID: 3145 RVA: 0x00042BF4 File Offset: 0x00040DF4
		// (set) Token: 0x06000C4A RID: 3146 RVA: 0x00042BFC File Offset: 0x00040DFC
		public TextObject EncyclopediaText { get; private set; }

		// Token: 0x170002AB RID: 683
		// (get) Token: 0x06000C4B RID: 3147 RVA: 0x00042C05 File Offset: 0x00040E05
		// (set) Token: 0x06000C4C RID: 3148 RVA: 0x00042C0D File Offset: 0x00040E0D
		public CampaignVec2 StartingPoint { get; private set; }

		// Token: 0x170002AC RID: 684
		// (get) Token: 0x06000C4D RID: 3149 RVA: 0x00042C16 File Offset: 0x00040E16
		// (set) Token: 0x06000C4E RID: 3150 RVA: 0x00042C1E File Offset: 0x00040E1E
		public PartyTemplateObject DefaultPartyTemplate { get; private set; }

		// Token: 0x170002AD RID: 685
		// (get) Token: 0x06000C4F RID: 3151 RVA: 0x00042C27 File Offset: 0x00040E27
		// (set) Token: 0x06000C50 RID: 3152 RVA: 0x00042C2F File Offset: 0x00040E2F
		public PartyTemplateObject VillagerPartyTemplate { get; private set; }

		// Token: 0x170002AE RID: 686
		// (get) Token: 0x06000C51 RID: 3153 RVA: 0x00042C38 File Offset: 0x00040E38
		// (set) Token: 0x06000C52 RID: 3154 RVA: 0x00042C40 File Offset: 0x00040E40
		public PartyTemplateObject FishingPartyTemplate { get; private set; }

		// Token: 0x170002AF RID: 687
		// (get) Token: 0x06000C53 RID: 3155 RVA: 0x00042C49 File Offset: 0x00040E49
		// (set) Token: 0x06000C54 RID: 3156 RVA: 0x00042C51 File Offset: 0x00040E51
		public PartyTemplateObject MilitiaPartyTemplate { get; private set; }

		// Token: 0x170002B0 RID: 688
		// (get) Token: 0x06000C55 RID: 3157 RVA: 0x00042C5A File Offset: 0x00040E5A
		// (set) Token: 0x06000C56 RID: 3158 RVA: 0x00042C62 File Offset: 0x00040E62
		public PartyTemplateObject RebelsPartyTemplate { get; private set; }

		// Token: 0x170002B1 RID: 689
		// (get) Token: 0x06000C57 RID: 3159 RVA: 0x00042C6B File Offset: 0x00040E6B
		// (set) Token: 0x06000C58 RID: 3160 RVA: 0x00042C73 File Offset: 0x00040E73
		public MBList<PartyTemplateObject> CaravanPartyTemplates { get; private set; }

		// Token: 0x170002B2 RID: 690
		// (get) Token: 0x06000C59 RID: 3161 RVA: 0x00042C7C File Offset: 0x00040E7C
		// (set) Token: 0x06000C5A RID: 3162 RVA: 0x00042C84 File Offset: 0x00040E84
		public MBList<PartyTemplateObject> EliteCaravanPartyTemplates { get; private set; }

		// Token: 0x170002B3 RID: 691
		// (get) Token: 0x06000C5B RID: 3163 RVA: 0x00042C8D File Offset: 0x00040E8D
		// (set) Token: 0x06000C5C RID: 3164 RVA: 0x00042C95 File Offset: 0x00040E95
		public MBList<ShipHull> AvailableShipHulls { get; private set; }

		// Token: 0x170002B4 RID: 692
		// (get) Token: 0x06000C5D RID: 3165 RVA: 0x00042C9E File Offset: 0x00040E9E
		// (set) Token: 0x06000C5E RID: 3166 RVA: 0x00042CA6 File Offset: 0x00040EA6
		public PartyTemplateObject BanditBossPartyTemplate { get; private set; }

		// Token: 0x170002B5 RID: 693
		// (get) Token: 0x06000C5F RID: 3167 RVA: 0x00042CAF File Offset: 0x00040EAF
		// (set) Token: 0x06000C60 RID: 3168 RVA: 0x00042CB7 File Offset: 0x00040EB7
		public PartyTemplateObject VassalRewardTroopsPartyTemplate { get; private set; }

		// Token: 0x170002B6 RID: 694
		// (get) Token: 0x06000C61 RID: 3169 RVA: 0x00042CC0 File Offset: 0x00040EC0
		// (set) Token: 0x06000C62 RID: 3170 RVA: 0x00042CC8 File Offset: 0x00040EC8
		public PartyTemplateObject SettlementPatrolPartyTemplateWeak { get; private set; }

		// Token: 0x170002B7 RID: 695
		// (get) Token: 0x06000C63 RID: 3171 RVA: 0x00042CD1 File Offset: 0x00040ED1
		// (set) Token: 0x06000C64 RID: 3172 RVA: 0x00042CD9 File Offset: 0x00040ED9
		public PartyTemplateObject SettlementPatrolPartyTemplateModerate { get; private set; }

		// Token: 0x170002B8 RID: 696
		// (get) Token: 0x06000C65 RID: 3173 RVA: 0x00042CE2 File Offset: 0x00040EE2
		// (set) Token: 0x06000C66 RID: 3174 RVA: 0x00042CEA File Offset: 0x00040EEA
		public PartyTemplateObject SettlementPatrolPartyTemplateStrong { get; private set; }

		// Token: 0x170002B9 RID: 697
		// (get) Token: 0x06000C67 RID: 3175 RVA: 0x00042CF3 File Offset: 0x00040EF3
		// (set) Token: 0x06000C68 RID: 3176 RVA: 0x00042CFB File Offset: 0x00040EFB
		public PartyTemplateObject SettlementPatrolPartyTemplateNaval { get; private set; }

		// Token: 0x170002BA RID: 698
		// (get) Token: 0x06000C69 RID: 3177 RVA: 0x00042D04 File Offset: 0x00040F04
		// (set) Token: 0x06000C6A RID: 3178 RVA: 0x00042D0C File Offset: 0x00040F0C
		public MBReadOnlyList<ItemObject> VassalRewardItems { get; private set; }

		// Token: 0x170002BB RID: 699
		// (get) Token: 0x06000C6B RID: 3179 RVA: 0x00042D15 File Offset: 0x00040F15
		// (set) Token: 0x06000C6C RID: 3180 RVA: 0x00042D1D File Offset: 0x00040F1D
		public MBReadOnlyList<ItemObject> BannerBearerReplacementWeapons { get; private set; }

		// Token: 0x170002BC RID: 700
		// (get) Token: 0x06000C6D RID: 3181 RVA: 0x00042D26 File Offset: 0x00040F26
		public MBReadOnlyList<TextObject> MaleNameList
		{
			get
			{
				return this._maleNameList;
			}
		}

		// Token: 0x170002BD RID: 701
		// (get) Token: 0x06000C6E RID: 3182 RVA: 0x00042D2E File Offset: 0x00040F2E
		public MBReadOnlyList<TextObject> FemaleNameList
		{
			get
			{
				return this._femaleNameList;
			}
		}

		// Token: 0x170002BE RID: 702
		// (get) Token: 0x06000C6F RID: 3183 RVA: 0x00042D36 File Offset: 0x00040F36
		public MBReadOnlyList<TextObject> ClanNameList
		{
			get
			{
				return this._clanNameList;
			}
		}

		// Token: 0x170002BF RID: 703
		// (get) Token: 0x06000C70 RID: 3184 RVA: 0x00042D3E File Offset: 0x00040F3E
		public MBReadOnlyList<FeatObject> CultureFeats
		{
			get
			{
				return this._cultureFeats;
			}
		}

		// Token: 0x170002C0 RID: 704
		// (get) Token: 0x06000C71 RID: 3185 RVA: 0x00042D46 File Offset: 0x00040F46
		public MBReadOnlyList<PolicyObject> DefaultPolicyList
		{
			get
			{
				return this._defaultPolicyList;
			}
		}

		// Token: 0x170002C1 RID: 705
		// (get) Token: 0x06000C72 RID: 3186 RVA: 0x00042D4E File Offset: 0x00040F4E
		// (set) Token: 0x06000C73 RID: 3187 RVA: 0x00042D56 File Offset: 0x00040F56
		public MBReadOnlyList<int> PossibleClanBannerIconsIDs { get; private set; }

		// Token: 0x170002C2 RID: 706
		// (get) Token: 0x06000C74 RID: 3188 RVA: 0x00042D5F File Offset: 0x00040F5F
		// (set) Token: 0x06000C75 RID: 3189 RVA: 0x00042D67 File Offset: 0x00040F67
		public MBReadOnlyList<CharacterObject> NotableTemplates { get; private set; }

		// Token: 0x170002C3 RID: 707
		// (get) Token: 0x06000C76 RID: 3190 RVA: 0x00042D70 File Offset: 0x00040F70
		// (set) Token: 0x06000C77 RID: 3191 RVA: 0x00042D78 File Offset: 0x00040F78
		public MBReadOnlyList<CharacterObject> RebelliousHeroTemplates { get; private set; }

		// Token: 0x170002C4 RID: 708
		// (get) Token: 0x06000C78 RID: 3192 RVA: 0x00042D81 File Offset: 0x00040F81
		// (set) Token: 0x06000C79 RID: 3193 RVA: 0x00042D89 File Offset: 0x00040F89
		public MBReadOnlyList<CharacterObject> LordTemplates { get; private set; }

		// Token: 0x170002C5 RID: 709
		// (get) Token: 0x06000C7A RID: 3194 RVA: 0x00042D92 File Offset: 0x00040F92
		// (set) Token: 0x06000C7B RID: 3195 RVA: 0x00042D9A File Offset: 0x00040F9A
		public MBReadOnlyList<CharacterObject> TournamentTeamTemplatesForOneParticipant { get; private set; }

		// Token: 0x170002C6 RID: 710
		// (get) Token: 0x06000C7C RID: 3196 RVA: 0x00042DA3 File Offset: 0x00040FA3
		// (set) Token: 0x06000C7D RID: 3197 RVA: 0x00042DAB File Offset: 0x00040FAB
		public MBReadOnlyList<CharacterObject> TournamentTeamTemplatesForTwoParticipant { get; private set; }

		// Token: 0x170002C7 RID: 711
		// (get) Token: 0x06000C7E RID: 3198 RVA: 0x00042DB4 File Offset: 0x00040FB4
		// (set) Token: 0x06000C7F RID: 3199 RVA: 0x00042DBC File Offset: 0x00040FBC
		public MBReadOnlyList<CharacterObject> TournamentTeamTemplatesForFourParticipant { get; private set; }

		// Token: 0x170002C8 RID: 712
		// (get) Token: 0x06000C80 RID: 3200 RVA: 0x00042DC5 File Offset: 0x00040FC5
		// (set) Token: 0x06000C81 RID: 3201 RVA: 0x00042DCD File Offset: 0x00040FCD
		public MBReadOnlyList<CharacterObject> BasicMercenaryTroops { get; private set; }

		// Token: 0x170002C9 RID: 713
		// (get) Token: 0x06000C82 RID: 3202 RVA: 0x00042DD6 File Offset: 0x00040FD6
		// (set) Token: 0x06000C83 RID: 3203 RVA: 0x00042DDE File Offset: 0x00040FDE
		public int MilitiaBonus { get; set; }

		// Token: 0x170002CA RID: 714
		// (get) Token: 0x06000C84 RID: 3204 RVA: 0x00042DE7 File Offset: 0x00040FE7
		// (set) Token: 0x06000C85 RID: 3205 RVA: 0x00042DEF File Offset: 0x00040FEF
		public int ProsperityBonus { get; set; }

		// Token: 0x170002CB RID: 715
		// (get) Token: 0x06000C86 RID: 3206 RVA: 0x00042DF8 File Offset: 0x00040FF8
		// (set) Token: 0x06000C87 RID: 3207 RVA: 0x00042E00 File Offset: 0x00041000
		public CultureObject.BoardGameType BoardGame { get; private set; }

		// Token: 0x170002CC RID: 716
		// (get) Token: 0x06000C88 RID: 3208 RVA: 0x00042E09 File Offset: 0x00041009
		// (set) Token: 0x06000C89 RID: 3209 RVA: 0x00042E11 File Offset: 0x00041011
		public float NavalFactor { get; private set; }

		// Token: 0x06000C8A RID: 3210 RVA: 0x00042E1A File Offset: 0x0004101A
		public override string ToString()
		{
			return base.Name.ToString();
		}

		// Token: 0x06000C8B RID: 3211 RVA: 0x00042E28 File Offset: 0x00041028
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			this.MilitiaBonus = ((node.Attributes["militia_bonus"] == null) ? 0 : Convert.ToInt32(node.Attributes["militia_bonus"].Value));
			this.ProsperityBonus = ((node.Attributes["prosperity_bonus"] == null) ? 0 : Convert.ToInt32(node.Attributes["prosperity_bonus"].Value));
			this.NavalFactor = ((node.Attributes["naval_factor"] == null) ? 0f : Convert.ToSingle(node.Attributes["naval_factor"].Value));
			this.DefaultPartyTemplate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("default_party_template", node);
			this.VillagerPartyTemplate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("villager_party_template", node);
			this.FishingPartyTemplate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("fishing_party_template", node);
			this.MilitiaPartyTemplate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("militia_party_template", node);
			this.RebelsPartyTemplate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("rebels_party_template", node);
			this.BanditBossPartyTemplate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("bandit_boss_party_template", node);
			this.VassalRewardTroopsPartyTemplate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("vassal_reward_party_template", node);
			this.SettlementPatrolPartyTemplateWeak = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("settlement_patrol_template_level_1", node);
			this.SettlementPatrolPartyTemplateModerate = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("settlement_patrol_template_level_2", node);
			this.SettlementPatrolPartyTemplateStrong = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("settlement_patrol_template_level_3", node);
			this.SettlementPatrolPartyTemplateNaval = objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("settlement_patrol_template_coastal", node);
			this.EliteBasicTroop = objectManager.ReadObjectReferenceFromXml<CharacterObject>("elite_basic_troop", node);
			this.MeleeEliteMilitiaTroop = objectManager.ReadObjectReferenceFromXml<CharacterObject>("melee_elite_militia_troop", node);
			this.RangedEliteMilitiaTroop = objectManager.ReadObjectReferenceFromXml<CharacterObject>("ranged_elite_militia_troop", node);
			this.MeleeMilitiaTroop = objectManager.ReadObjectReferenceFromXml<CharacterObject>("melee_militia_troop", node);
			this.RangedMilitiaTroop = objectManager.ReadObjectReferenceFromXml<CharacterObject>("ranged_militia_troop", node);
			this.BasicTroop = objectManager.ReadObjectReferenceFromXml<CharacterObject>("basic_troop", node);
			this.DefaultBattleEquipmentRoster = objectManager.ReadObjectReferenceFromXml<MBEquipmentRoster>("default_battle_equipment_roster", node);
			this.DefaultCivilianEquipmentRoster = objectManager.ReadObjectReferenceFromXml<MBEquipmentRoster>("default_civilian_equipment_roster", node);
			this.DefaultStealthEquipmentRoster = objectManager.ReadObjectReferenceFromXml<MBEquipmentRoster>("default_stealth_equipment_roster", node);
			this.DuelPresetEquipmentRoster = objectManager.ReadObjectReferenceFromXml<MBEquipmentRoster>("duel_preset_equipment_roster", node);
			this.MarriageBrideEquipmentRoster = objectManager.ReadObjectReferenceFromXml<MBEquipmentRoster>("marriage_bride_equipment_roster", node);
			this.TournamentMaster = objectManager.ReadObjectReferenceFromXml<CharacterObject>("tournament_master", node);
			this.Villager = objectManager.ReadObjectReferenceFromXml<CharacterObject>("villager", node);
			this.CaravanMaster = objectManager.ReadObjectReferenceFromXml<CharacterObject>("caravan_master", node);
			this.CaravanGuard = objectManager.ReadObjectReferenceFromXml<CharacterObject>("caravan_guard", node);
			this.PrisonGuard = objectManager.ReadObjectReferenceFromXml<CharacterObject>("prison_guard", node);
			this.Guard = objectManager.ReadObjectReferenceFromXml<CharacterObject>("guard", node);
			this.Blacksmith = objectManager.ReadObjectReferenceFromXml<CharacterObject>("blacksmith", node);
			this.Weaponsmith = objectManager.ReadObjectReferenceFromXml<CharacterObject>("weaponsmith", node);
			this.Townswoman = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townswoman", node);
			this.TownswomanInfant = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townswoman_infant", node);
			this.TownswomanChild = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townswoman_child", node);
			this.TownswomanTeenager = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townswoman_teenager", node);
			this.Townsman = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townsman", node);
			this.TownsmanInfant = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townsman_infant", node);
			this.TownsmanChild = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townsman_child", node);
			this.TownsmanTeenager = objectManager.ReadObjectReferenceFromXml<CharacterObject>("townsman_teenager", node);
			this.VillageWoman = objectManager.ReadObjectReferenceFromXml<CharacterObject>("village_woman", node);
			this.VillagerMaleChild = objectManager.ReadObjectReferenceFromXml<CharacterObject>("villager_male_child", node);
			this.VillagerMaleTeenager = objectManager.ReadObjectReferenceFromXml<CharacterObject>("villager_male_teenager", node);
			this.VillagerFemaleChild = objectManager.ReadObjectReferenceFromXml<CharacterObject>("villager_female_child", node);
			this.VillagerFemaleTeenager = objectManager.ReadObjectReferenceFromXml<CharacterObject>("villager_female_teenager", node);
			this.RansomBroker = objectManager.ReadObjectReferenceFromXml<CharacterObject>("ransom_broker", node);
			this.GangleaderBodyguard = objectManager.ReadObjectReferenceFromXml<CharacterObject>("gangleader_bodyguard", node);
			this.MerchantNotary = objectManager.ReadObjectReferenceFromXml<CharacterObject>("merchant_notary", node);
			this.ArtisanNotary = objectManager.ReadObjectReferenceFromXml<CharacterObject>("artisan_notary", node);
			this.PreacherNotary = objectManager.ReadObjectReferenceFromXml<CharacterObject>("preacher_notary", node);
			this.RuralNotableNotary = objectManager.ReadObjectReferenceFromXml<CharacterObject>("rural_notable_notary", node);
			this.ShopWorker = objectManager.ReadObjectReferenceFromXml<CharacterObject>("shop_worker", node);
			this.Tavernkeeper = objectManager.ReadObjectReferenceFromXml<CharacterObject>("tavernkeeper", node);
			this.TavernGamehost = objectManager.ReadObjectReferenceFromXml<CharacterObject>("taverngamehost", node);
			this.Musician = objectManager.ReadObjectReferenceFromXml<CharacterObject>("musician", node);
			this.TavernWench = objectManager.ReadObjectReferenceFromXml<CharacterObject>("tavern_wench", node);
			this.Armorer = objectManager.ReadObjectReferenceFromXml<CharacterObject>("armorer", node);
			this.HorseMerchant = objectManager.ReadObjectReferenceFromXml<CharacterObject>("horseMerchant", node);
			this.Barber = objectManager.ReadObjectReferenceFromXml<CharacterObject>("barber", node);
			this.Merchant = objectManager.ReadObjectReferenceFromXml<CharacterObject>("merchant", node);
			this.Beggar = objectManager.ReadObjectReferenceFromXml<CharacterObject>("beggar", node);
			this.FemaleBeggar = objectManager.ReadObjectReferenceFromXml<CharacterObject>("female_beggar", node);
			this.FemaleDancer = objectManager.ReadObjectReferenceFromXml<CharacterObject>("female_dancer", node);
			this.Shipwright = objectManager.ReadObjectReferenceFromXml<CharacterObject>("shipwright", node);
			this.ShipyardWorker = objectManager.ReadObjectReferenceFromXml<CharacterObject>("shipyard_worker", node);
			this.MilitiaVeteranArcher = objectManager.ReadObjectReferenceFromXml<CharacterObject>("militia_veteran_archer", node);
			this.GearDummy = objectManager.ReadObjectReferenceFromXml<CharacterObject>("gear_dummy", node);
			this.BanditBandit = objectManager.ReadObjectReferenceFromXml<CharacterObject>("bandit_bandit", node);
			this.BanditRaider = objectManager.ReadObjectReferenceFromXml<CharacterObject>("bandit_raider", node);
			this.BanditChief = objectManager.ReadObjectReferenceFromXml<CharacterObject>("bandit_chief", node);
			this.BanditBoss = objectManager.ReadObjectReferenceFromXml<CharacterObject>("bandit_boss", node);
			this.DefaultCharacterCreationBodyProperty = ((node.Attributes["default_character_creation_body_property"] != null) ? objectManager.ReadObjectReferenceFromXml<MBBodyProperty>("default_character_creation_body_property", node) : null);
			this.EncyclopediaText = ((node.Attributes["text"] != null) ? new TextObject(node.Attributes["text"].Value, null) : TextObject.GetEmpty());
			float num = ((node.Attributes["start_point_position_x"] == null) ? 0f : Convert.ToSingle(node.Attributes["start_point_position_x"].Value));
			float num2 = ((node.Attributes["start_point_position_y"] == null) ? 0f : Convert.ToSingle(node.Attributes["start_point_position_y"].Value));
			this.StartingPoint = new CampaignVec2(new Vec2(num, num2), true);
			CultureObject.BoardGameType boardGameType;
			if (node.Attributes["board_game_type"] != null && Enum.TryParse<CultureObject.BoardGameType>(node.Attributes["board_game_type"].Value, out boardGameType))
			{
				this.BoardGame = boardGameType;
			}
			XmlNodeList childNodes = node.ChildNodes;
			this._defaultPolicyList = new MBList<PolicyObject>();
			this._maleNameList = new MBList<TextObject>();
			this._femaleNameList = new MBList<TextObject>();
			this._clanNameList = new MBList<TextObject>();
			this._cultureFeats = new MBList<FeatObject>();
			MBList<int> mblist = new MBList<int>();
			MBList<CharacterObject> mblist2 = new MBList<CharacterObject>();
			MBList<CharacterObject> mblist3 = new MBList<CharacterObject>();
			MBList<CharacterObject> mblist4 = new MBList<CharacterObject>();
			MBList<CharacterObject> mblist5 = new MBList<CharacterObject>();
			MBList<CharacterObject> mblist6 = new MBList<CharacterObject>();
			MBList<CharacterObject> mblist7 = new MBList<CharacterObject>();
			MBList<ItemObject> mblist8 = new MBList<ItemObject>();
			MBList<ItemObject> mblist9 = new MBList<ItemObject>();
			MBList<PartyTemplateObject> mblist10 = new MBList<PartyTemplateObject>();
			MBList<PartyTemplateObject> mblist11 = new MBList<PartyTemplateObject>();
			MBList<ShipHull> mblist12 = new MBList<ShipHull>();
			MBList<CharacterObject> mblist13 = new MBList<CharacterObject>();
			foreach (object obj in childNodes)
			{
				XmlNode xmlNode = (XmlNode)obj;
				if (xmlNode.Name == "default_policies")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj2 = enumerator2.Current;
							XmlNode xmlNode2 = (XmlNode)obj2;
							PolicyObject @object = objectManager.GetObject<PolicyObject>(xmlNode2.Attributes["id"].Value);
							this._defaultPolicyList.Add(@object);
						}
						continue;
					}
				}
				if (xmlNode.Name == "male_names")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj3 = enumerator2.Current;
							XmlNode xmlNode3 = (XmlNode)obj3;
							this._maleNameList.Add(new TextObject(xmlNode3.Attributes["name"].Value, null));
						}
						continue;
					}
				}
				if (xmlNode.Name == "female_names")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj4 = enumerator2.Current;
							XmlNode xmlNode4 = (XmlNode)obj4;
							this._femaleNameList.Add(new TextObject(xmlNode4.Attributes["name"].Value, null));
						}
						continue;
					}
				}
				if (xmlNode.Name == "clan_names")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj5 = enumerator2.Current;
							XmlNode xmlNode5 = (XmlNode)obj5;
							this._clanNameList.Add(new TextObject(xmlNode5.Attributes["name"].Value, null));
						}
						continue;
					}
				}
				if (xmlNode.Name == "cultural_feats")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj6 = enumerator2.Current;
							XmlNode xmlNode6 = (XmlNode)obj6;
							string value = xmlNode6.Attributes["id"].Value;
							FeatObject featObject = (FeatObject)MBObjectManager.Instance.CreateObjectFromXmlNode(xmlNode6);
							Debug.Print("Reading feat with id " + value + ",  in Culture  " + base.StringId, 0, Debug.DebugColor.White, 17592186044416UL);
							if (featObject != null)
							{
								this._cultureFeats.Add(featObject);
							}
						}
						continue;
					}
				}
				if (xmlNode.Name == "possible_clan_banner_icon_ids")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj7 = enumerator2.Current;
							int num3;
							int.TryParse(((XmlNode)obj7).Attributes["id"].Value, out num3);
							mblist.Add(num3);
						}
						continue;
					}
				}
				if (xmlNode.Name == "notable_templates")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj8 = enumerator2.Current;
							XmlNode xmlNode7 = (XmlNode)obj8;
							CharacterObject characterObject = objectManager.ReadObjectReferenceFromXml<CharacterObject>("name", xmlNode7);
							mblist2.Add(characterObject);
						}
						continue;
					}
				}
				if (xmlNode.Name == "lord_templates")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj9 = enumerator2.Current;
							XmlNode xmlNode8 = (XmlNode)obj9;
							CharacterObject characterObject2 = objectManager.ReadObjectReferenceFromXml<CharacterObject>("name", xmlNode8);
							mblist4.Add(characterObject2);
						}
						continue;
					}
				}
				if (xmlNode.Name == "rebellion_hero_templates")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj10 = enumerator2.Current;
							XmlNode xmlNode9 = (XmlNode)obj10;
							CharacterObject characterObject3 = objectManager.ReadObjectReferenceFromXml<CharacterObject>("name", xmlNode9);
							mblist3.Add(characterObject3);
						}
						continue;
					}
				}
				if (xmlNode.Name == "tournament_team_templates_one_participant")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj11 = enumerator2.Current;
							XmlNode xmlNode10 = (XmlNode)obj11;
							mblist5.Add(objectManager.ReadObjectReferenceFromXml<CharacterObject>("name", xmlNode10));
						}
						continue;
					}
				}
				if (xmlNode.Name == "tournament_team_templates_two_participant")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj12 = enumerator2.Current;
							XmlNode xmlNode11 = (XmlNode)obj12;
							mblist6.Add(objectManager.ReadObjectReferenceFromXml<CharacterObject>("name", xmlNode11));
						}
						continue;
					}
				}
				if (xmlNode.Name == "tournament_team_templates_four_participant")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj13 = enumerator2.Current;
							XmlNode xmlNode12 = (XmlNode)obj13;
							mblist7.Add(objectManager.ReadObjectReferenceFromXml<CharacterObject>("name", xmlNode12));
						}
						continue;
					}
				}
				if (xmlNode.Name == "vassal_reward_items")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj14 = enumerator2.Current;
							XmlNode xmlNode13 = (XmlNode)obj14;
							mblist8.Add(objectManager.ReadObjectReferenceFromXml<ItemObject>("id", xmlNode13));
						}
						continue;
					}
				}
				if (xmlNode.Name == "basic_mercenary_troops")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj15 = enumerator2.Current;
							XmlNode xmlNode14 = (XmlNode)obj15;
							mblist13.Add(objectManager.ReadObjectReferenceFromXml<CharacterObject>("name", xmlNode14));
						}
						continue;
					}
				}
				if (xmlNode.Name == "banner_bearer_replacement_weapons")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj16 = enumerator2.Current;
							XmlNode xmlNode15 = (XmlNode)obj16;
							mblist9.Add(objectManager.ReadObjectReferenceFromXml<ItemObject>("id", xmlNode15));
						}
						continue;
					}
				}
				if (xmlNode.Name == "caravan_party_templates")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj17 = enumerator2.Current;
							XmlNode xmlNode16 = (XmlNode)obj17;
							mblist10.Add(objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("id", xmlNode16));
						}
						continue;
					}
				}
				if (xmlNode.Name == "elite_caravan_party_templates")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj18 = enumerator2.Current;
							XmlNode xmlNode17 = (XmlNode)obj18;
							mblist11.Add(objectManager.ReadObjectReferenceFromXml<PartyTemplateObject>("id", xmlNode17));
						}
						continue;
					}
				}
				if (xmlNode.Name == "available_ship_hulls")
				{
					foreach (object obj19 in xmlNode.ChildNodes)
					{
						XmlNode xmlNode18 = (XmlNode)obj19;
						mblist12.Add(objectManager.ReadObjectReferenceFromXml<ShipHull>("id", xmlNode18));
					}
				}
			}
			this.PossibleClanBannerIconsIDs = mblist;
			if (this.PossibleClanBannerIconsIDs == null)
			{
				this.PossibleClanBannerIconsIDs = new MBList<int>();
			}
			this.NotableTemplates = mblist2;
			this.RebelliousHeroTemplates = mblist3;
			this.LordTemplates = mblist4;
			this.TournamentTeamTemplatesForOneParticipant = mblist5;
			this.TournamentTeamTemplatesForTwoParticipant = mblist6;
			this.TournamentTeamTemplatesForFourParticipant = mblist7;
			mblist8.RemoveAll((ItemObject x) => !x.IsReady);
			this.VassalRewardItems = mblist8;
			this.BasicMercenaryTroops = mblist13;
			mblist9.RemoveAll((ItemObject x) => !x.IsReady);
			this.BannerBearerReplacementWeapons = mblist9;
			this.CaravanPartyTemplates = mblist10;
			this.EliteCaravanPartyTemplates = mblist11;
			this.AvailableShipHulls = mblist12;
		}

		// Token: 0x06000C8C RID: 3212 RVA: 0x0004403C File Offset: 0x0004223C
		public override TextObject GetName()
		{
			return base.Name;
		}

		// Token: 0x0400038A RID: 906
		private MBList<TextObject> _maleNameList;

		// Token: 0x0400038B RID: 907
		private MBList<TextObject> _femaleNameList;

		// Token: 0x0400038C RID: 908
		private MBList<TextObject> _clanNameList;

		// Token: 0x0400038D RID: 909
		private MBList<FeatObject> _cultureFeats;

		// Token: 0x0400038E RID: 910
		private MBList<PolicyObject> _defaultPolicyList;

		// Token: 0x02000524 RID: 1316
		public enum BoardGameType
		{
			// Token: 0x04001608 RID: 5640
			None = -1,
			// Token: 0x04001609 RID: 5641
			Seega,
			// Token: 0x0400160A RID: 5642
			Puluc,
			// Token: 0x0400160B RID: 5643
			Konane,
			// Token: 0x0400160C RID: 5644
			MuTorere,
			// Token: 0x0400160D RID: 5645
			Tablut,
			// Token: 0x0400160E RID: 5646
			BaghChal,
			// Token: 0x0400160F RID: 5647
			Total
		}
	}
}
