using System;
using System.Collections.Generic;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem
{
	// Token: 0x0200006C RID: 108
	public sealed class PolicyObject : PropertyObject
	{
		// Token: 0x06000E8A RID: 3722 RVA: 0x0004A57B File Offset: 0x0004877B
		internal static void AutoGeneratedStaticCollectObjectsPolicyObject(object o, List<object> collectedObjects)
		{
			((PolicyObject)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06000E8B RID: 3723 RVA: 0x0004A589 File Offset: 0x00048789
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x17000379 RID: 889
		// (get) Token: 0x06000E8C RID: 3724 RVA: 0x0004A592 File Offset: 0x00048792
		public static MBReadOnlyList<PolicyObject> All
		{
			get
			{
				return Campaign.Current.AllPolicies;
			}
		}

		// Token: 0x1700037A RID: 890
		// (get) Token: 0x06000E8D RID: 3725 RVA: 0x0004A59E File Offset: 0x0004879E
		// (set) Token: 0x06000E8E RID: 3726 RVA: 0x0004A5A6 File Offset: 0x000487A6
		public TextObject SecondaryEffects { get; private set; }

		// Token: 0x1700037B RID: 891
		// (get) Token: 0x06000E8F RID: 3727 RVA: 0x0004A5AF File Offset: 0x000487AF
		// (set) Token: 0x06000E90 RID: 3728 RVA: 0x0004A5B7 File Offset: 0x000487B7
		public float AuthoritarianWeight { get; private set; }

		// Token: 0x1700037C RID: 892
		// (get) Token: 0x06000E91 RID: 3729 RVA: 0x0004A5C0 File Offset: 0x000487C0
		// (set) Token: 0x06000E92 RID: 3730 RVA: 0x0004A5C8 File Offset: 0x000487C8
		public float OligarchicWeight { get; private set; }

		// Token: 0x1700037D RID: 893
		// (get) Token: 0x06000E93 RID: 3731 RVA: 0x0004A5D1 File Offset: 0x000487D1
		// (set) Token: 0x06000E94 RID: 3732 RVA: 0x0004A5D9 File Offset: 0x000487D9
		public float EgalitarianWeight { get; private set; }

		// Token: 0x1700037E RID: 894
		// (get) Token: 0x06000E95 RID: 3733 RVA: 0x0004A5E2 File Offset: 0x000487E2
		// (set) Token: 0x06000E96 RID: 3734 RVA: 0x0004A5EA File Offset: 0x000487EA
		public TextObject LogEntryDescription { get; private set; }

		// Token: 0x06000E97 RID: 3735 RVA: 0x0004A5F3 File Offset: 0x000487F3
		public PolicyObject(string stringId)
			: base(stringId)
		{
		}

		// Token: 0x06000E98 RID: 3736 RVA: 0x0004A5FC File Offset: 0x000487FC
		public void Initialize(TextObject name, TextObject description, TextObject logEntryDescription, TextObject secondaryEffects, float authoritarianWeight, float oligarchyWeight, float egalitarianWeight)
		{
			base.Initialize(name, description);
			this.LogEntryDescription = logEntryDescription;
			this.SecondaryEffects = secondaryEffects;
			this.AuthoritarianWeight = authoritarianWeight;
			this.OligarchicWeight = oligarchyWeight;
			this.EgalitarianWeight = egalitarianWeight;
			base.AfterInitialized();
		}

		// Token: 0x06000E99 RID: 3737 RVA: 0x0004A633 File Offset: 0x00048833
		public override string ToString()
		{
			return base.Name.ToString();
		}
	}
}
