using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x0200032D RID: 813
	public class CommonAreaFightLogEntry : LogEntry, IEncyclopediaLog
	{
		// Token: 0x060030AA RID: 12458 RVA: 0x000CC106 File Offset: 0x000CA306
		internal static void AutoGeneratedStaticCollectObjectsCommonAreaFightLogEntry(object o, List<object> collectedObjects)
		{
			((CommonAreaFightLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060030AB RID: 12459 RVA: 0x000CC114 File Offset: 0x000CA314
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._attackerName);
			collectedObjects.Add(this._defenderName);
			collectedObjects.Add(this._settlement);
		}

		// Token: 0x060030AC RID: 12460 RVA: 0x000CC141 File Offset: 0x000CA341
		internal static object AutoGeneratedGetMemberValue_attackerName(object o)
		{
			return ((CommonAreaFightLogEntry)o)._attackerName;
		}

		// Token: 0x060030AD RID: 12461 RVA: 0x000CC14E File Offset: 0x000CA34E
		internal static object AutoGeneratedGetMemberValue_defenderName(object o)
		{
			return ((CommonAreaFightLogEntry)o)._defenderName;
		}

		// Token: 0x060030AE RID: 12462 RVA: 0x000CC15B File Offset: 0x000CA35B
		internal static object AutoGeneratedGetMemberValue_settlement(object o)
		{
			return ((CommonAreaFightLogEntry)o)._settlement;
		}

		// Token: 0x060030AF RID: 12463 RVA: 0x000CC168 File Offset: 0x000CA368
		public CommonAreaFightLogEntry(MobileParty attackerParty, MobileParty defenderParty, Hero attackerHero, Settlement settlement)
		{
			this._attackerName = ((attackerParty != null) ? attackerParty.Name : attackerHero.Name);
			this._defenderName = defenderParty.Name;
			this._settlement = settlement;
		}

		// Token: 0x060030B0 RID: 12464 RVA: 0x000CC19B File Offset: 0x000CA39B
		public override string ToString()
		{
			return this.GetEncyclopediaText().ToString();
		}

		// Token: 0x060030B1 RID: 12465 RVA: 0x000CC1A8 File Offset: 0x000CA3A8
		public bool IsVisibleInEncyclopediaPageOf<T>(T obj) where T : MBObjectBase
		{
			return obj == this._settlement;
		}

		// Token: 0x060030B2 RID: 12466 RVA: 0x000CC1B8 File Offset: 0x000CA3B8
		public TextObject GetEncyclopediaText()
		{
			TextObject textObject = new TextObject("{=A3ql1SUy}{PARTY_1} attacked a common area belonging to {PARTY_2} in {SETTLEMENT}.", null);
			textObject.SetTextVariable("PARTY_1", this._attackerName);
			textObject.SetTextVariable("PARTY_2", this._defenderName);
			textObject.SetTextVariable("SETTLEMENT", this._settlement.EncyclopediaLinkWithName);
			return textObject;
		}

		// Token: 0x04000DF8 RID: 3576
		[SaveableField(170)]
		private readonly TextObject _attackerName;

		// Token: 0x04000DF9 RID: 3577
		[SaveableField(171)]
		private readonly TextObject _defenderName;

		// Token: 0x04000DFA RID: 3578
		[SaveableField(172)]
		private readonly Settlement _settlement;
	}
}
