using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x0200032F RID: 815
	public class DefeatCharacterLogEntry : LogEntry
	{
		// Token: 0x060030C2 RID: 12482 RVA: 0x000CC498 File Offset: 0x000CA698
		internal static void AutoGeneratedStaticCollectObjectsDefeatCharacterLogEntry(object o, List<object> collectedObjects)
		{
			((DefeatCharacterLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060030C3 RID: 12483 RVA: 0x000CC4A6 File Offset: 0x000CA6A6
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.WinnerHero);
			collectedObjects.Add(this.LoserHero);
		}

		// Token: 0x060030C4 RID: 12484 RVA: 0x000CC4C7 File Offset: 0x000CA6C7
		internal static object AutoGeneratedGetMemberValueWinnerHero(object o)
		{
			return ((DefeatCharacterLogEntry)o).WinnerHero;
		}

		// Token: 0x060030C5 RID: 12485 RVA: 0x000CC4D4 File Offset: 0x000CA6D4
		internal static object AutoGeneratedGetMemberValueLoserHero(object o)
		{
			return ((DefeatCharacterLogEntry)o).LoserHero;
		}

		// Token: 0x060030C6 RID: 12486 RVA: 0x000CC4E1 File Offset: 0x000CA6E1
		public DefeatCharacterLogEntry(Hero winner, Hero loser)
		{
			this.WinnerHero = winner;
			this.LoserHero = loser;
		}

		// Token: 0x060030C7 RID: 12487 RVA: 0x000CC4F7 File Offset: 0x000CA6F7
		public override ImportanceEnum GetImportanceForClan(Clan clan)
		{
			if (this.WinnerHero.Clan == clan || this.LoserHero.Clan == clan)
			{
				return ImportanceEnum.SlightlyImportant;
			}
			return ImportanceEnum.Zero;
		}

		// Token: 0x060030C8 RID: 12488 RVA: 0x000CC518 File Offset: 0x000CA718
		public override void GetConversationScoreAndComment(Hero talkTroop, bool findString, out string comment, out ImportanceEnum score)
		{
			score = ImportanceEnum.Zero;
			comment = "";
			if (this.WinnerHero == Hero.MainHero)
			{
				if (this.LoserHero == talkTroop)
				{
					score = ImportanceEnum.SlightlyImportant;
					if (findString)
					{
						comment = "str_comment_you_defeated_me_in_single_combat";
						return;
					}
				}
			}
			else if (this.LoserHero == Hero.MainHero && this.WinnerHero == talkTroop)
			{
				score = ImportanceEnum.SlightlyImportant;
				if (findString)
				{
					comment = "str_comment_i_defeated_you_in_single_combat";
				}
			}
		}

		// Token: 0x060030C9 RID: 12489 RVA: 0x000CC57C File Offset: 0x000CA77C
		public override string ToString()
		{
			TextObject textObject = new TextObject("{=!}{LOSER.NAME} defeated by {WINNER.NAME}.", null);
			StringHelpers.SetCharacterProperties("WINNER", this.WinnerHero.CharacterObject, textObject, false);
			StringHelpers.SetCharacterProperties("LOSER", this.LoserHero.CharacterObject, textObject, false);
			return textObject.ToString();
		}

		// Token: 0x04000DFE RID: 3582
		[SaveableField(200)]
		public readonly Hero WinnerHero;

		// Token: 0x04000DFF RID: 3583
		[SaveableField(201)]
		public readonly Hero LoserHero;
	}
}
