using System;
using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x0200031D RID: 797
	public class LogEntryHistory
	{
		// Token: 0x06002FD3 RID: 12243 RVA: 0x000C9922 File Offset: 0x000C7B22
		internal static void AutoGeneratedStaticCollectObjectsLogEntryHistory(object o, List<object> collectedObjects)
		{
			((LogEntryHistory)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002FD4 RID: 12244 RVA: 0x000C9930 File Offset: 0x000C7B30
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._logs);
		}

		// Token: 0x06002FD5 RID: 12245 RVA: 0x000C993E File Offset: 0x000C7B3E
		internal static object AutoGeneratedGetMemberValueLastAddedIndex(object o)
		{
			return ((LogEntryHistory)o).LastAddedIndex;
		}

		// Token: 0x06002FD6 RID: 12246 RVA: 0x000C9950 File Offset: 0x000C7B50
		internal static object AutoGeneratedGetMemberValue_logs(object o)
		{
			return ((LogEntryHistory)o)._logs;
		}

		// Token: 0x06002FD7 RID: 12247 RVA: 0x000C9960 File Offset: 0x000C7B60
		internal void AddActionLog(LogEntry actionLog, bool checkSequenceAndInsert = false)
		{
			if (this._logs.Count > 0 && this._logs[this._logs.Count - 1].Id > actionLog.Id)
			{
				Debug.FailedAssert("Log ids should always get bigger", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\LogEntries\\LogEntry.cs", "AddActionLog", 215);
				int num = this._logs.FindIndex((LogEntry l) => l.Id > actionLog.Id);
				if (num >= 0)
				{
					this._logs.Insert(num, actionLog);
				}
			}
			else
			{
				this._logs.Add(actionLog);
			}
			Campaign.Current.CampaignInformationManager.NewLogEntryAdded(actionLog);
		}

		// Token: 0x06002FD8 RID: 12248 RVA: 0x000C9A21 File Offset: 0x000C7C21
		internal void DeleteLogAtIndex(int i)
		{
			this._logs.RemoveAt(i);
		}

		// Token: 0x06002FD9 RID: 12249 RVA: 0x000C9A30 File Offset: 0x000C7C30
		public void DeleteOutdatedLogs()
		{
			int num = -1;
			for (int i = 0; i < this._logs.Count; i++)
			{
				LogEntry logEntry = this._logs[i];
				CampaignTime campaignTime = logEntry.KeepInHistoryTime + logEntry.GameTime;
				if (logEntry.IsValid() && !campaignTime.IsPast)
				{
					num++;
					if (i != num)
					{
						this._logs[num] = logEntry;
					}
				}
			}
			if (num < this._logs.Count)
			{
				this._logs.RemoveRange(num + 1, this._logs.Count - num - 1);
			}
		}

		// Token: 0x17000BB9 RID: 3001
		// (get) Token: 0x06002FDA RID: 12250 RVA: 0x000C9AC5 File Offset: 0x000C7CC5
		public MBReadOnlyList<LogEntry> GameActionLogs
		{
			get
			{
				return this._logs;
			}
		}

		// Token: 0x06002FDB RID: 12251 RVA: 0x000C9ACD File Offset: 0x000C7CCD
		public IEnumerable<T> GetGameActionLogs<T>(Func<T, bool> predicate) where T : LogEntry
		{
			using (List<LogEntry>.Enumerator enumerator = this._logs.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					T t;
					if ((t = enumerator.Current as T) != null && predicate(t))
					{
						yield return t;
					}
				}
			}
			List<LogEntry>.Enumerator enumerator = default(List<LogEntry>.Enumerator);
			yield break;
			yield break;
		}

		// Token: 0x06002FDC RID: 12252 RVA: 0x000C9AE4 File Offset: 0x000C7CE4
		public T FindLastGameActionLog<T>(Func<T, bool> predicate) where T : LogEntry
		{
			for (int i = this._logs.Count - 1; i >= 0; i--)
			{
				T t;
				if ((t = this._logs[i] as T) != null && predicate(t))
				{
					return t;
				}
			}
			return default(T);
		}

		// Token: 0x06002FDD RID: 12253 RVA: 0x000C9B3C File Offset: 0x000C7D3C
		private int BinarySearchFirst(long target)
		{
			int i = 0;
			int num = this._logs.Count - 1;
			while (i < num)
			{
				int num2 = (i + num + 1) / 2;
				if (this._logs[num2].Id > target)
				{
					num = num2 - 1;
				}
				else
				{
					i = num2;
				}
			}
			return num;
		}

		// Token: 0x06002FDE RID: 12254 RVA: 0x000C9B84 File Offset: 0x000C7D84
		private int BinarySearchFirst(CampaignTime target)
		{
			int i = 0;
			int num = this._logs.Count - 1;
			while (i < num)
			{
				int num2 = (i + num + 1) / 2;
				if (this._logs[num2].GameTime > target)
				{
					num = num2 - 1;
				}
				else
				{
					i = num2;
				}
			}
			return num;
		}

		// Token: 0x06002FDF RID: 12255 RVA: 0x000C9BD4 File Offset: 0x000C7DD4
		public int GetStartIndexForComments()
		{
			for (int i = MathF.Max(0, this._logs.Count - 10000); i < this._logs.Count; i++)
			{
				if (this._logs[i].Id > Hero.OneToOneConversationHero.LastExaminedLogEntryID)
				{
					return i;
				}
			}
			return this._logs.Count;
		}

		// Token: 0x06002FE0 RID: 12256 RVA: 0x000C9C38 File Offset: 0x000C7E38
		public LogEntry GetRelevantComment(Hero conversationHero, out int bestScore, out string bestRelatedLogEntryTag)
		{
			int num = -1;
			bestRelatedLogEntryTag = "";
			int startIndexForComments = this.GetStartIndexForComments();
			bestScore = 0;
			if (startIndexForComments < this._logs.Count)
			{
				for (int i = startIndexForComments; i < this._logs.Count; i++)
				{
					string text;
					ImportanceEnum importanceEnum;
					this._logs[i].GetConversationScoreAndComment(conversationHero, false, out text, out importanceEnum);
					int num2 = (int)importanceEnum;
					if (num2 > bestScore)
					{
						bestScore = num2;
						num = i;
					}
				}
				Hero.OneToOneConversationHero.LastExaminedLogEntryID = this._logs[this._logs.Count - 1].Id;
			}
			if (num > -1)
			{
				string text2;
				ImportanceEnum importanceEnum2;
				this._logs[num].GetConversationScoreAndComment(conversationHero, true, out text2, out importanceEnum2);
				bestRelatedLogEntryTag = text2;
				return this._logs[num];
			}
			return null;
		}

		// Token: 0x06002FE1 RID: 12257 RVA: 0x000C9CF8 File Offset: 0x000C7EF8
		internal void OnAfterLoad()
		{
			for (int i = this._logs.Count - 1; i >= 0; i--)
			{
				if (this._logs[i] == null || !this._logs[i].IsValid())
				{
					this._logs.RemoveAt(i);
				}
			}
		}

		// Token: 0x04000DC2 RID: 3522
		[SaveableField(0)]
		internal long LastAddedIndex = -1L;

		// Token: 0x04000DC3 RID: 3523
		[SaveableField(1)]
		private readonly MBList<LogEntry> _logs = new MBList<LogEntry>();
	}
}
