using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x0200031C RID: 796
	public abstract class LogEntry
	{
		// Token: 0x06002FB9 RID: 12217 RVA: 0x000C9650 File Offset: 0x000C7850
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.GameTime, collectedObjects);
		}

		// Token: 0x06002FBA RID: 12218 RVA: 0x000C9663 File Offset: 0x000C7863
		internal static object AutoGeneratedGetMemberValueId(object o)
		{
			return ((LogEntry)o).Id;
		}

		// Token: 0x06002FBB RID: 12219 RVA: 0x000C9675 File Offset: 0x000C7875
		internal static object AutoGeneratedGetMemberValueGameTime(object o)
		{
			return ((LogEntry)o).GameTime;
		}

		// Token: 0x17000BB5 RID: 2997
		// (get) Token: 0x06002FBC RID: 12220 RVA: 0x000C9687 File Offset: 0x000C7887
		// (set) Token: 0x06002FBD RID: 12221 RVA: 0x000C968F File Offset: 0x000C788F
		[SaveableProperty(0)]
		public long Id { get; private set; }

		// Token: 0x17000BB6 RID: 2998
		// (get) Token: 0x06002FBE RID: 12222 RVA: 0x000C9698 File Offset: 0x000C7898
		// (set) Token: 0x06002FBF RID: 12223 RVA: 0x000C96A0 File Offset: 0x000C78A0
		[SaveableProperty(1)]
		public CampaignTime GameTime { get; private set; }

		// Token: 0x17000BB7 RID: 2999
		// (get) Token: 0x06002FC0 RID: 12224 RVA: 0x000C96A9 File Offset: 0x000C78A9
		public virtual CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Days(7f);
			}
		}

		// Token: 0x17000BB8 RID: 3000
		// (get) Token: 0x06002FC1 RID: 12225 RVA: 0x000C96B5 File Offset: 0x000C78B5
		public virtual ChatNotificationType NotificationType
		{
			get
			{
				return ChatNotificationType.Default;
			}
		}

		// Token: 0x06002FC2 RID: 12226 RVA: 0x000C96B8 File Offset: 0x000C78B8
		protected ChatNotificationType MilitaryNotification(IFaction benefiter, IFaction affected)
		{
			if (benefiter == Clan.PlayerClan)
			{
				return ChatNotificationType.PlayerClanPositive;
			}
			if (affected == Clan.PlayerClan)
			{
				return ChatNotificationType.PlayerClanNegative;
			}
			if (((benefiter != null) ? benefiter.MapFaction : null) == Clan.PlayerClan.MapFaction)
			{
				return ChatNotificationType.PlayerFactionPositive;
			}
			if (((affected != null) ? affected.MapFaction : null) == Clan.PlayerClan.MapFaction)
			{
				return ChatNotificationType.PlayerFactionNegative;
			}
			if (affected != null && affected.IsAtWarWith(Clan.PlayerClan.MapFaction))
			{
				return ChatNotificationType.PlayerFactionIndirectPositive;
			}
			if (benefiter != null && benefiter.IsAtWarWith(Clan.PlayerClan.MapFaction))
			{
				return ChatNotificationType.PlayerFactionIndirectNegative;
			}
			return ChatNotificationType.Neutral;
		}

		// Token: 0x06002FC3 RID: 12227 RVA: 0x000C9740 File Offset: 0x000C7940
		protected ChatNotificationType DiplomaticNotification(IFaction faction1, IFaction faction2)
		{
			if (faction1 == Clan.PlayerClan || faction2 == Clan.PlayerClan)
			{
				return ChatNotificationType.PlayerClanPositive;
			}
			if (faction1 == Clan.PlayerClan.MapFaction || faction2 == Clan.PlayerClan.MapFaction)
			{
				return ChatNotificationType.PlayerFactionPositive;
			}
			if (faction1 != null && Clan.PlayerClan.MapFaction.IsAtWarWith(faction1))
			{
				return ChatNotificationType.PlayerFactionIndirectNegative;
			}
			if (faction2 != null && Clan.PlayerClan.MapFaction.IsAtWarWith(faction2))
			{
				return ChatNotificationType.PlayerFactionIndirectNegative;
			}
			return ChatNotificationType.PlayerFactionIndirectPositive;
		}

		// Token: 0x06002FC4 RID: 12228 RVA: 0x000C97B0 File Offset: 0x000C79B0
		protected ChatNotificationType AdversityNotification(IFaction faction1, IFaction faction2)
		{
			if (faction1 == Clan.PlayerClan)
			{
				return ChatNotificationType.PlayerClanNegative;
			}
			if (faction2 == Clan.PlayerClan)
			{
				return ChatNotificationType.PlayerClanNegative;
			}
			if (((faction1 != null) ? faction1.MapFaction : null) == Clan.PlayerClan.MapFaction)
			{
				return ChatNotificationType.PlayerFactionNegative;
			}
			if (((faction2 != null) ? faction2.MapFaction : null) == Clan.PlayerClan.MapFaction)
			{
				return ChatNotificationType.PlayerFactionNegative;
			}
			return ChatNotificationType.Neutral;
		}

		// Token: 0x06002FC5 RID: 12229 RVA: 0x000C9806 File Offset: 0x000C7A06
		protected ChatNotificationType PoliticalNotification(IFaction faction)
		{
			if (faction == Clan.PlayerClan)
			{
				return ChatNotificationType.PlayerClanPolitical;
			}
			if (((faction != null) ? faction.MapFaction : null) == Clan.PlayerClan.MapFaction)
			{
				return ChatNotificationType.PlayerFactionPolitical;
			}
			return ChatNotificationType.Political;
		}

		// Token: 0x06002FC6 RID: 12230 RVA: 0x000C9830 File Offset: 0x000C7A30
		protected ChatNotificationType CivilianNotification(IFaction faction)
		{
			if (faction == Clan.PlayerClan)
			{
				return ChatNotificationType.PlayerClanCivilian;
			}
			if (((faction != null) ? faction.MapFaction : null) == Clan.PlayerClan.MapFaction)
			{
				return ChatNotificationType.PlayerFactionCivilian;
			}
			return ChatNotificationType.Civilian;
		}

		// Token: 0x06002FC7 RID: 12231 RVA: 0x000C9858 File Offset: 0x000C7A58
		public static void AddLogEntry(LogEntry logEntry)
		{
			logEntry.GameTime = CampaignTime.Now;
			LogEntryHistory logEntryHistory = Campaign.Current.LogEntryHistory;
			long num = logEntryHistory.LastAddedIndex + 1L;
			logEntryHistory.LastAddedIndex = num;
			logEntry.Id = num;
			Campaign.Current.LogEntryHistory.AddActionLog(logEntry, false);
		}

		// Token: 0x06002FC8 RID: 12232 RVA: 0x000C98A4 File Offset: 0x000C7AA4
		public static void AddLogEntry(LogEntry logEntry, CampaignTime gameTime)
		{
			logEntry.GameTime = gameTime;
			LogEntryHistory logEntryHistory = Campaign.Current.LogEntryHistory;
			long num = logEntryHistory.LastAddedIndex + 1L;
			logEntryHistory.LastAddedIndex = num;
			logEntry.Id = num;
			Campaign.Current.LogEntryHistory.AddActionLog(logEntry, true);
		}

		// Token: 0x06002FC9 RID: 12233 RVA: 0x000C98EA File Offset: 0x000C7AEA
		public virtual ImportanceEnum GetImportanceForClan(Clan clan)
		{
			return ImportanceEnum.Zero;
		}

		// Token: 0x06002FCA RID: 12234 RVA: 0x000C98ED File Offset: 0x000C7AED
		public virtual void GetConversationScoreAndComment(Hero talkTroop, bool findString, out string comment, out ImportanceEnum score)
		{
			comment = "";
			score = ImportanceEnum.Zero;
		}

		// Token: 0x06002FCB RID: 12235 RVA: 0x000C98FA File Offset: 0x000C7AFA
		public virtual int GetAsRumor(Settlement settlement, out TextObject comment)
		{
			comment = TextObject.GetEmpty();
			return 0;
		}

		// Token: 0x06002FCC RID: 12236 RVA: 0x000C9904 File Offset: 0x000C7B04
		public virtual TextObject GetHistoricComment(Hero talkTroop)
		{
			return TextObject.GetEmpty();
		}

		// Token: 0x06002FCD RID: 12237 RVA: 0x000C990B File Offset: 0x000C7B0B
		public virtual int AsReasonForEnmity(Hero referenceHero1, Hero referenceHero2)
		{
			return 0;
		}

		// Token: 0x06002FCE RID: 12238 RVA: 0x000C990E File Offset: 0x000C7B0E
		public virtual int GetValueAsPoliticsAbuseOfPower(Hero referenceTroop, Hero liege)
		{
			return 0;
		}

		// Token: 0x06002FCF RID: 12239 RVA: 0x000C9911 File Offset: 0x000C7B11
		public virtual int GetValueAsPoliticsSlightedClan(Hero referenceTroop, Hero liege)
		{
			return 0;
		}

		// Token: 0x06002FD0 RID: 12240 RVA: 0x000C9914 File Offset: 0x000C7B14
		public virtual int GetValueAsPoliticsShowedWeakness(Hero referenceTroop, Hero liege)
		{
			return 0;
		}

		// Token: 0x06002FD1 RID: 12241 RVA: 0x000C9917 File Offset: 0x000C7B17
		public virtual bool IsValid()
		{
			return true;
		}

		// Token: 0x04000DBF RID: 3519
		protected const uint NotificationDefaultTextColor = 0U;
	}
}
