using System;
using System.Collections.Generic;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x02000335 RID: 821
	public class OverruleInfluenceLogEntry : LogEntry
	{
		// Token: 0x06003101 RID: 12545 RVA: 0x000CCDC8 File Offset: 0x000CAFC8
		internal static void AutoGeneratedStaticCollectObjectsOverruleInfluenceLogEntry(object o, List<object> collectedObjects)
		{
			((OverruleInfluenceLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003102 RID: 12546 RVA: 0x000CCDD6 File Offset: 0x000CAFD6
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._liege);
		}

		// Token: 0x06003103 RID: 12547 RVA: 0x000CCDEB File Offset: 0x000CAFEB
		internal static object AutoGeneratedGetMemberValue_liege(object o)
		{
			return ((OverruleInfluenceLogEntry)o)._liege;
		}

		// Token: 0x17000BE4 RID: 3044
		// (get) Token: 0x06003104 RID: 12548 RVA: 0x000CCDF8 File Offset: 0x000CAFF8
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Days(1680f);
			}
		}

		// Token: 0x06003105 RID: 12549 RVA: 0x000CCE04 File Offset: 0x000CB004
		public OverruleInfluenceLogEntry(Hero liege, Hero wrongedLord)
		{
			this._liege = liege;
		}

		// Token: 0x06003106 RID: 12550 RVA: 0x000CCE13 File Offset: 0x000CB013
		public override TextObject GetHistoricComment(Hero talkTroop)
		{
			TextObject textObject = GameTexts.FindText("str_overrule_influence_historic_comment", null);
			textObject.SetTextVariable("HERO", this._liege.Name);
			textObject.SetTextVariable("FACTION", this._liege.Clan.Name);
			return textObject;
		}

		// Token: 0x06003107 RID: 12551 RVA: 0x000CCE53 File Offset: 0x000CB053
		public override int GetValueAsPoliticsAbuseOfPower(Hero referenceTroop, Hero liege)
		{
			if (liege == this._liege)
			{
				return 3;
			}
			return 0;
		}

		// Token: 0x06003108 RID: 12552 RVA: 0x000CCE61 File Offset: 0x000CB061
		public override string ToString()
		{
			return "OverruleInfluenceLogEntry";
		}

		// Token: 0x04000E10 RID: 3600
		[SaveableField(260)]
		private readonly Hero _liege;
	}
}
