using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x02000341 RID: 833
	public class PlayerReputationChangesLogEntry : LogEntry
	{
		// Token: 0x060031B1 RID: 12721 RVA: 0x000CF196 File Offset: 0x000CD396
		internal static void AutoGeneratedStaticCollectObjectsPlayerReputationChangesLogEntry(object o, List<object> collectedObjects)
		{
			((PlayerReputationChangesLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060031B2 RID: 12722 RVA: 0x000CF1A4 File Offset: 0x000CD3A4
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._trait);
			collectedObjects.Add(this._companionsInParty);
			collectedObjects.Add(this._referenceHero);
		}

		// Token: 0x060031B3 RID: 12723 RVA: 0x000CF1D1 File Offset: 0x000CD3D1
		internal static object AutoGeneratedGetMemberValue_trait(object o)
		{
			return ((PlayerReputationChangesLogEntry)o)._trait;
		}

		// Token: 0x060031B4 RID: 12724 RVA: 0x000CF1DE File Offset: 0x000CD3DE
		internal static object AutoGeneratedGetMemberValue_companionsInParty(object o)
		{
			return ((PlayerReputationChangesLogEntry)o)._companionsInParty;
		}

		// Token: 0x060031B5 RID: 12725 RVA: 0x000CF1EB File Offset: 0x000CD3EB
		internal static object AutoGeneratedGetMemberValue_note(object o)
		{
			return ((PlayerReputationChangesLogEntry)o)._note;
		}

		// Token: 0x060031B6 RID: 12726 RVA: 0x000CF1FD File Offset: 0x000CD3FD
		internal static object AutoGeneratedGetMemberValue_referenceHero(object o)
		{
			return ((PlayerReputationChangesLogEntry)o)._referenceHero;
		}

		// Token: 0x060031B7 RID: 12727 RVA: 0x000CF20A File Offset: 0x000CD40A
		public PlayerReputationChangesLogEntry(TraitObject trait, Hero referenceHero, ActionNotes note)
		{
			this._trait = trait;
			this._referenceHero = referenceHero;
			this._companionsInParty = Hero.MainHero.CompanionsInParty.ToList<Hero>();
			this._note = note;
		}

		// Token: 0x060031B8 RID: 12728 RVA: 0x000CF23C File Offset: 0x000CD43C
		public override void GetConversationScoreAndComment(Hero talkTroop, bool findString, out string comment, out ImportanceEnum score)
		{
			score = ImportanceEnum.Zero;
			comment = "";
			if (this._companionsInParty.Contains(talkTroop))
			{
				if (talkTroop.GetTraitLevel(DefaultTraits.Honor) > 0 && this._trait == DefaultTraits.Honor)
				{
					if (this._note == ActionNotes.QuestSuccess)
					{
						MBTextManager.SetTextVariable("COMMENT_REFERENCE_HERO", this._referenceHero.Name, false);
						comment = "str_comment_companion_on_honor_for_quest_success";
						score = ImportanceEnum.SomewhatImportant;
					}
					else if (this._note == ActionNotes.QuestBetrayal)
					{
						MBTextManager.SetTextVariable("COMMENT_REFERENCE_HERO", this._referenceHero.Name, false);
						comment = "str_comment_companion_on_honor_for_quest_betrayal";
						score = ImportanceEnum.SomewhatImportant;
					}
				}
				if (talkTroop.GetTraitLevel(DefaultTraits.Generosity) > 0 && this._trait == DefaultTraits.Generosity && this._note == ActionNotes.PartyTakenCareOf)
				{
					comment = "str_comment_companion_on_generosity_for_party_morale";
					score = ImportanceEnum.SomewhatImportant;
				}
			}
		}

		// Token: 0x060031B9 RID: 12729 RVA: 0x000CF308 File Offset: 0x000CD508
		public override string ToString()
		{
			return "PlayerReputationChangesLogEntry";
		}

		// Token: 0x04000E47 RID: 3655
		[SaveableField(410)]
		private readonly TraitObject _trait;

		// Token: 0x04000E48 RID: 3656
		[SaveableField(411)]
		private readonly List<Hero> _companionsInParty;

		// Token: 0x04000E49 RID: 3657
		[SaveableField(412)]
		private readonly ActionNotes _note;

		// Token: 0x04000E4A RID: 3658
		[SaveableField(413)]
		private readonly Hero _referenceHero;
	}
}
