using System;
using System.Collections.Generic;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x0200034B RID: 843
	public class StartAllianceLogEntry : LogEntry, IEncyclopediaLog, IChatNotification
	{
		// Token: 0x06003201 RID: 12801 RVA: 0x000CF9B9 File Offset: 0x000CDBB9
		internal static void AutoGeneratedStaticCollectObjectsStartAllianceLogEntry(object o, List<object> collectedObjects)
		{
			((StartAllianceLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003202 RID: 12802 RVA: 0x000CF9C7 File Offset: 0x000CDBC7
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._kingdom1);
			collectedObjects.Add(this._kingdom2);
		}

		// Token: 0x06003203 RID: 12803 RVA: 0x000CF9E8 File Offset: 0x000CDBE8
		internal static object AutoGeneratedGetMemberValue_kingdom1(object o)
		{
			return ((StartAllianceLogEntry)o)._kingdom1;
		}

		// Token: 0x06003204 RID: 12804 RVA: 0x000CF9F5 File Offset: 0x000CDBF5
		internal static object AutoGeneratedGetMemberValue_kingdom2(object o)
		{
			return ((StartAllianceLogEntry)o)._kingdom2;
		}

		// Token: 0x17000C08 RID: 3080
		// (get) Token: 0x06003205 RID: 12805 RVA: 0x000CFA02 File Offset: 0x000CDC02
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Years(4f);
			}
		}

		// Token: 0x17000C09 RID: 3081
		// (get) Token: 0x06003206 RID: 12806 RVA: 0x000CFA0E File Offset: 0x000CDC0E
		public bool IsVisibleNotification
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000C0A RID: 3082
		// (get) Token: 0x06003207 RID: 12807 RVA: 0x000CFA11 File Offset: 0x000CDC11
		public override ChatNotificationType NotificationType
		{
			get
			{
				return base.DiplomaticNotification(this._kingdom1, this._kingdom2);
			}
		}

		// Token: 0x06003208 RID: 12808 RVA: 0x000CFA25 File Offset: 0x000CDC25
		public StartAllianceLogEntry(Kingdom kingdom1, Kingdom kingdom2)
		{
			this._kingdom1 = kingdom1;
			this._kingdom2 = kingdom2;
		}

		// Token: 0x06003209 RID: 12809 RVA: 0x000CFA3B File Offset: 0x000CDC3B
		public override string ToString()
		{
			return this.GetEncyclopediaText().ToString();
		}

		// Token: 0x0600320A RID: 12810 RVA: 0x000CFA48 File Offset: 0x000CDC48
		public TextObject GetNotificationText()
		{
			TextObject textObject = new TextObject("{=0cdXddA9}The {KINGDOM1_LINK} have formed an alliance with the {KINGDOM2_LINK}.", null);
			textObject.SetTextVariable("KINGDOM1_LINK", this._kingdom1.EncyclopediaLinkWithName);
			textObject.SetTextVariable("KINGDOM2_LINK", this._kingdom2.EncyclopediaLinkWithName);
			return textObject;
		}

		// Token: 0x0600320B RID: 12811 RVA: 0x000CFA83 File Offset: 0x000CDC83
		public bool IsVisibleInEncyclopediaPageOf<T>(T obj) where T : MBObjectBase
		{
			return obj == this._kingdom1 || obj == this._kingdom2;
		}

		// Token: 0x0600320C RID: 12812 RVA: 0x000CFAA3 File Offset: 0x000CDCA3
		public TextObject GetEncyclopediaText()
		{
			TextObject textObject = new TextObject("{=0cdXddA9}The {KINGDOM1_LINK} have formed an alliance with the {KINGDOM2_LINK}.", null);
			textObject.SetTextVariable("KINGDOM1_LINK", this._kingdom1.EncyclopediaLinkWithName);
			textObject.SetTextVariable("KINGDOM2_LINK", this._kingdom2.EncyclopediaLinkWithName);
			return textObject;
		}

		// Token: 0x04000E5A RID: 3674
		[SaveableField(10)]
		private readonly Kingdom _kingdom1;

		// Token: 0x04000E5B RID: 3675
		[SaveableField(20)]
		private readonly Kingdom _kingdom2;
	}
}
