using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x02000481 RID: 1153
	public class FiefBarterable : Barterable
	{
		// Token: 0x17000E7B RID: 3707
		// (get) Token: 0x06004932 RID: 18738 RVA: 0x0017357F File Offset: 0x0017177F
		public override string StringID
		{
			get
			{
				return "fief_barterable";
			}
		}

		// Token: 0x17000E7C RID: 3708
		// (get) Token: 0x06004933 RID: 18739 RVA: 0x00173586 File Offset: 0x00171786
		public Settlement TargetSettlement
		{
			get
			{
				return this._settlement;
			}
		}

		// Token: 0x17000E7D RID: 3709
		// (get) Token: 0x06004934 RID: 18740 RVA: 0x0017358E File Offset: 0x0017178E
		public override TextObject Name
		{
			get
			{
				return this._settlement.Name;
			}
		}

		// Token: 0x06004935 RID: 18741 RVA: 0x0017359B File Offset: 0x0017179B
		public FiefBarterable(Settlement settlement, Hero owner, Hero heroOfferedTo)
			: base(owner, null)
		{
			this._settlement = settlement;
			this._heroOfferedTo = heroOfferedTo;
		}

		// Token: 0x06004936 RID: 18742 RVA: 0x001735B4 File Offset: 0x001717B4
		public override int GetUnitValueForFaction(IFaction faction)
		{
			float num = 1f;
			if (faction == this._heroOfferedTo.Clan)
			{
				num = 1f;
			}
			else if (faction == base.OriginalOwner.Clan)
			{
				num = -1f;
			}
			else if (faction.MapFaction == this._heroOfferedTo.MapFaction)
			{
				num = 1f;
			}
			else if (faction.MapFaction == base.OriginalOwner.MapFaction)
			{
				num = -1f;
			}
			float num2 = Campaign.Current.Models.SettlementValueModel.CalculateSettlementValueForFaction(this._settlement, faction);
			return (int)(num * num2);
		}

		// Token: 0x06004937 RID: 18743 RVA: 0x00173647 File Offset: 0x00171847
		public override ImageIdentifier GetVisualIdentifier()
		{
			return null;
		}

		// Token: 0x06004938 RID: 18744 RVA: 0x0017364A File Offset: 0x0017184A
		public override string GetEncyclopediaLink()
		{
			return this.TargetSettlement.EncyclopediaLink;
		}

		// Token: 0x06004939 RID: 18745 RVA: 0x00173657 File Offset: 0x00171857
		public override void Apply()
		{
			ChangeOwnerOfSettlementAction.ApplyByBarter(this._heroOfferedTo, this._settlement);
		}

		// Token: 0x0600493A RID: 18746 RVA: 0x0017366A File Offset: 0x0017186A
		internal static void AutoGeneratedStaticCollectObjectsFiefBarterable(object o, List<object> collectedObjects)
		{
			((FiefBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600493B RID: 18747 RVA: 0x00173678 File Offset: 0x00171878
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._settlement);
			collectedObjects.Add(this._heroOfferedTo);
		}

		// Token: 0x0600493C RID: 18748 RVA: 0x00173699 File Offset: 0x00171899
		internal static object AutoGeneratedGetMemberValue_settlement(object o)
		{
			return ((FiefBarterable)o)._settlement;
		}

		// Token: 0x0600493D RID: 18749 RVA: 0x001736A6 File Offset: 0x001718A6
		internal static object AutoGeneratedGetMemberValue_heroOfferedTo(object o)
		{
			return ((FiefBarterable)o)._heroOfferedTo;
		}

		// Token: 0x0400143A RID: 5178
		[SaveableField(100)]
		private readonly Settlement _settlement;

		// Token: 0x0400143B RID: 5179
		[SaveableField(101)]
		private readonly Hero _heroOfferedTo;
	}
}
