using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x02000482 RID: 1154
	public class GoldBarterable : Barterable
	{
		// Token: 0x17000E7E RID: 3710
		// (get) Token: 0x0600493E RID: 18750 RVA: 0x001736B3 File Offset: 0x001718B3
		public override string StringID
		{
			get
			{
				return "gold_barterable";
			}
		}

		// Token: 0x17000E7F RID: 3711
		// (get) Token: 0x0600493F RID: 18751 RVA: 0x001736BA File Offset: 0x001718BA
		public override int MaxAmount
		{
			get
			{
				return this._maxGold;
			}
		}

		// Token: 0x17000E80 RID: 3712
		// (get) Token: 0x06004940 RID: 18752 RVA: 0x001736C2 File Offset: 0x001718C2
		public override TextObject Name
		{
			get
			{
				return GameTexts.FindText("str_char_denar_tooltip", null);
			}
		}

		// Token: 0x06004941 RID: 18753 RVA: 0x001736CF File Offset: 0x001718CF
		public GoldBarterable(Hero owner, Hero other, PartyBase ownerParty, PartyBase otherParty, int val)
			: base(owner, ownerParty)
		{
			this._ownerHero = owner;
			this._otherHero = other;
			this._otherParty = otherParty;
			this._maxGold = val;
			base.CurrentAmount = 0;
		}

		// Token: 0x06004942 RID: 18754 RVA: 0x00173700 File Offset: 0x00171900
		public override int GetUnitValueForFaction(IFaction faction)
		{
			Hero originalOwner = base.OriginalOwner;
			if (faction != ((originalOwner != null) ? originalOwner.Clan : null))
			{
				Hero originalOwner2 = base.OriginalOwner;
				if (faction != ((originalOwner2 != null) ? originalOwner2.MapFaction : null))
				{
					PartyBase originalParty = base.OriginalParty;
					if (faction != ((originalParty != null) ? originalParty.MapFaction : null))
					{
						Hero otherHero = this._otherHero;
						if (faction != ((otherHero != null) ? otherHero.Clan : null))
						{
							Hero otherHero2 = this._otherHero;
							if (faction != ((otherHero2 != null) ? otherHero2.MapFaction : null))
							{
								PartyBase otherParty = this._otherParty;
								if (faction != ((otherParty != null) ? otherParty.MapFaction : null))
								{
									return 0;
								}
							}
						}
						return 1;
					}
				}
			}
			return -1;
		}

		// Token: 0x06004943 RID: 18755 RVA: 0x00173790 File Offset: 0x00171990
		public override ImageIdentifier GetVisualIdentifier()
		{
			return null;
		}

		// Token: 0x06004944 RID: 18756 RVA: 0x00173793 File Offset: 0x00171993
		public override string GetEncyclopediaLink()
		{
			return "";
		}

		// Token: 0x06004945 RID: 18757 RVA: 0x0017379C File Offset: 0x0017199C
		public override void Apply()
		{
			if (this._ownerHero != null && this._otherHero != null)
			{
				GiveGoldAction.ApplyBetweenCharacters(this._ownerHero, this._otherHero, base.CurrentAmount, false);
				return;
			}
			if (base.OriginalParty == PartyBase.MainParty)
			{
				GiveGoldAction.ApplyForCharacterToParty(Hero.MainHero, this._otherParty, base.CurrentAmount, false);
				return;
			}
			if (this._otherParty != PartyBase.MainParty)
			{
				GiveGoldAction.ApplyForPartyToParty(base.OriginalParty, this._otherParty, base.CurrentAmount, false);
				return;
			}
			GiveGoldAction.ApplyForPartyToCharacter(base.OriginalParty, Hero.MainHero, base.CurrentAmount, false);
		}

		// Token: 0x06004946 RID: 18758 RVA: 0x00173834 File Offset: 0x00171A34
		internal static void AutoGeneratedStaticCollectObjectsGoldBarterable(object o, List<object> collectedObjects)
		{
			((GoldBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06004947 RID: 18759 RVA: 0x00173842 File Offset: 0x00171A42
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._ownerHero);
			collectedObjects.Add(this._otherHero);
			collectedObjects.Add(this._otherParty);
		}

		// Token: 0x06004948 RID: 18760 RVA: 0x0017386F File Offset: 0x00171A6F
		internal static object AutoGeneratedGetMemberValue_maxGold(object o)
		{
			return ((GoldBarterable)o)._maxGold;
		}

		// Token: 0x06004949 RID: 18761 RVA: 0x00173881 File Offset: 0x00171A81
		internal static object AutoGeneratedGetMemberValue_ownerHero(object o)
		{
			return ((GoldBarterable)o)._ownerHero;
		}

		// Token: 0x0600494A RID: 18762 RVA: 0x0017388E File Offset: 0x00171A8E
		internal static object AutoGeneratedGetMemberValue_otherHero(object o)
		{
			return ((GoldBarterable)o)._otherHero;
		}

		// Token: 0x0600494B RID: 18763 RVA: 0x0017389B File Offset: 0x00171A9B
		internal static object AutoGeneratedGetMemberValue_otherParty(object o)
		{
			return ((GoldBarterable)o)._otherParty;
		}

		// Token: 0x0400143C RID: 5180
		[SaveableField(200)]
		private readonly int _maxGold;

		// Token: 0x0400143D RID: 5181
		[SaveableField(201)]
		private readonly Hero _ownerHero;

		// Token: 0x0400143E RID: 5182
		[SaveableField(202)]
		private readonly Hero _otherHero;

		// Token: 0x0400143F RID: 5183
		[SaveableField(203)]
		private readonly PartyBase _otherParty;
	}
}
