using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x02000483 RID: 1155
	public class ItemBarterable : Barterable
	{
		// Token: 0x17000E81 RID: 3713
		// (get) Token: 0x0600494C RID: 18764 RVA: 0x001738A8 File Offset: 0x00171AA8
		public override string StringID
		{
			get
			{
				return "item_barterable";
			}
		}

		// Token: 0x0600494D RID: 18765 RVA: 0x001738AF File Offset: 0x00171AAF
		public ItemBarterable(Hero ownerHero, Hero otherHero, PartyBase ownerParty, PartyBase otherParty, ItemRosterElement itemRosterElement, int averageValueOfItemInNearbySettlements)
			: base(ownerHero, ownerParty)
		{
			this._itemElement = itemRosterElement;
			this._averageValueOfItemInNearbySettlements = averageValueOfItemInNearbySettlements;
			this._otherParty = otherParty;
			this._otherHero = otherHero;
		}

		// Token: 0x17000E82 RID: 3714
		// (get) Token: 0x0600494E RID: 18766 RVA: 0x001738D8 File Offset: 0x00171AD8
		public ItemRosterElement ItemRosterElement
		{
			get
			{
				return this._itemElement;
			}
		}

		// Token: 0x17000E83 RID: 3715
		// (get) Token: 0x0600494F RID: 18767 RVA: 0x001738E0 File Offset: 0x00171AE0
		public override int MaxAmount
		{
			get
			{
				return this._itemElement.Amount;
			}
		}

		// Token: 0x17000E84 RID: 3716
		// (get) Token: 0x06004950 RID: 18768 RVA: 0x001738FC File Offset: 0x00171AFC
		public override TextObject Name
		{
			get
			{
				return this._itemElement.EquipmentElement.Item.Name;
			}
		}

		// Token: 0x17000E85 RID: 3717
		// (get) Token: 0x06004951 RID: 18769 RVA: 0x00173924 File Offset: 0x00171B24
		public int ItemValue
		{
			get
			{
				return this._averageValueOfItemInNearbySettlements;
			}
		}

		// Token: 0x06004952 RID: 18770 RVA: 0x0017392C File Offset: 0x00171B2C
		public override int GetUnitValueForFaction(IFaction faction)
		{
			return MathF.Round(Campaign.Current.Models.BarterModel.GetBarterPenalty(faction, this, this._otherHero, this._otherParty).ResultNumber * (float)this.ItemValue);
		}

		// Token: 0x06004953 RID: 18771 RVA: 0x00173970 File Offset: 0x00171B70
		public override void CheckBarterLink(Barterable parentLinkedBarterable)
		{
		}

		// Token: 0x06004954 RID: 18772 RVA: 0x00173974 File Offset: 0x00171B74
		public override ImageIdentifier GetVisualIdentifier()
		{
			return new ItemImageIdentifier(this._itemElement.EquipmentElement.Item, "");
		}

		// Token: 0x06004955 RID: 18773 RVA: 0x001739A1 File Offset: 0x00171BA1
		public override string GetEncyclopediaLink()
		{
			return "";
		}

		// Token: 0x06004956 RID: 18774 RVA: 0x001739A8 File Offset: 0x00171BA8
		public override void Apply()
		{
			if (this._otherParty != null)
			{
				base.OriginalParty.ItemRoster.AddToCounts(this._itemElement.EquipmentElement, -base.CurrentAmount);
				this._otherParty.ItemRoster.AddToCounts(this._itemElement.EquipmentElement, base.CurrentAmount);
				return;
			}
			ItemRosterElement itemRosterElement = new ItemRosterElement(this._itemElement.EquipmentElement, base.CurrentAmount);
			GiveItemAction.ApplyForHeroes(base.OriginalOwner, this._otherHero, in itemRosterElement);
		}

		// Token: 0x06004957 RID: 18775 RVA: 0x00173A37 File Offset: 0x00171C37
		internal static void AutoGeneratedStaticCollectObjectsItemBarterable(object o, List<object> collectedObjects)
		{
			((ItemBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06004958 RID: 18776 RVA: 0x00173A45 File Offset: 0x00171C45
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x04001440 RID: 5184
		private readonly ItemRosterElement _itemElement;

		// Token: 0x04001441 RID: 5185
		private readonly Hero _otherHero;

		// Token: 0x04001442 RID: 5186
		private readonly PartyBase _otherParty;

		// Token: 0x04001443 RID: 5187
		private readonly int _averageValueOfItemInNearbySettlements;
	}
}
