using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x02000485 RID: 1157
	public class LeaveKingdomAsClanBarterable : Barterable
	{
		// Token: 0x17000E88 RID: 3720
		// (get) Token: 0x06004964 RID: 18788 RVA: 0x00173E89 File Offset: 0x00172089
		public override string StringID
		{
			get
			{
				return "leave_faction_barterable";
			}
		}

		// Token: 0x17000E89 RID: 3721
		// (get) Token: 0x06004965 RID: 18789 RVA: 0x00173E90 File Offset: 0x00172090
		public override TextObject Name
		{
			get
			{
				TextObject textObject = new TextObject("{=x5POJVWw}Stop serving {FACTION}", null);
				textObject.SetTextVariable("FACTION", base.OriginalOwner.MapFaction.Name);
				return textObject;
			}
		}

		// Token: 0x06004966 RID: 18790 RVA: 0x00173EB9 File Offset: 0x001720B9
		public LeaveKingdomAsClanBarterable(Hero owner, PartyBase ownerParty)
			: base(owner, ownerParty)
		{
		}

		// Token: 0x06004967 RID: 18791 RVA: 0x00173EC4 File Offset: 0x001720C4
		public override int GetUnitValueForFaction(IFaction faction)
		{
			Hero leader = base.OriginalOwner.Clan.Leader;
			IFaction mapFaction = base.OriginalOwner.MapFaction;
			if (faction != base.OriginalOwner.Clan)
			{
				float num;
				if (faction == base.OriginalOwner.MapFaction)
				{
					if (base.OriginalOwner.Clan.IsUnderMercenaryService)
					{
						num = Campaign.Current.Models.DiplomacyModel.GetScoreOfMercenaryToLeaveKingdom(base.OriginalOwner.Clan, base.OriginalOwner.Clan.Kingdom);
					}
					else
					{
						num = Campaign.Current.Models.DiplomacyModel.GetScoreOfClanToLeaveKingdom(base.OriginalOwner.Clan, base.OriginalOwner.Clan.Kingdom);
					}
					num *= (float)((faction == base.OriginalOwner.Clan || faction == base.OriginalOwner.Clan.Kingdom) ? (-1) : 1);
				}
				else
				{
					float num2 = 0.5f;
					float num3 = 0.01f;
					float num4 = -0.5f;
					float clanStrength = Campaign.Current.Models.DiplomacyModel.GetClanStrength(base.OriginalOwner.Clan);
					if (faction.IsClan && FactionManager.IsAtWarAgainstFaction(faction, base.OriginalOwner.Clan.Kingdom))
					{
						num = clanStrength * num2;
					}
					else if (DiplomacyHelper.IsSameFactionAndNotEliminated(faction, base.OriginalOwner.Clan.Kingdom))
					{
						num = clanStrength * num4;
					}
					else
					{
						num = clanStrength * num3;
					}
				}
				return (int)num;
			}
			if (base.OriginalOwner.Clan.IsMinorFaction)
			{
				return (int)Campaign.Current.Models.DiplomacyModel.GetScoreOfMercenaryToLeaveKingdom(base.OriginalOwner.Clan, base.OriginalOwner.Clan.Kingdom);
			}
			return (int)Campaign.Current.Models.DiplomacyModel.GetScoreOfClanToLeaveKingdom(base.OriginalOwner.Clan, base.OriginalOwner.Clan.Kingdom);
		}

		// Token: 0x06004968 RID: 18792 RVA: 0x001740A6 File Offset: 0x001722A6
		public override void CheckBarterLink(Barterable linkedBarterable)
		{
		}

		// Token: 0x06004969 RID: 18793 RVA: 0x001740A8 File Offset: 0x001722A8
		public override bool IsCompatible(Barterable barterable)
		{
			JoinKingdomAsClanBarterable joinKingdomAsClanBarterable = barterable as JoinKingdomAsClanBarterable;
			return joinKingdomAsClanBarterable == null || joinKingdomAsClanBarterable.OriginalOwner != base.OriginalOwner || joinKingdomAsClanBarterable.TargetKingdom != base.OriginalOwner.MapFaction;
		}

		// Token: 0x0600496A RID: 18794 RVA: 0x001740E5 File Offset: 0x001722E5
		public override ImageIdentifier GetVisualIdentifier()
		{
			return new BannerImageIdentifier(base.OriginalOwner.Clan.Banner, false);
		}

		// Token: 0x0600496B RID: 18795 RVA: 0x001740FD File Offset: 0x001722FD
		public override string GetEncyclopediaLink()
		{
			return base.OriginalOwner.MapFaction.EncyclopediaLink;
		}

		// Token: 0x0600496C RID: 18796 RVA: 0x0017410F File Offset: 0x0017230F
		public override void Apply()
		{
			if (base.OriginalOwner.Clan.IsUnderMercenaryService)
			{
				ChangeKingdomAction.ApplyByLeaveKingdomAsMercenary(base.OriginalOwner.Clan, true);
				return;
			}
			ChangeKingdomAction.ApplyByLeaveKingdom(base.OriginalOwner.Clan, true);
		}

		// Token: 0x0600496D RID: 18797 RVA: 0x00174146 File Offset: 0x00172346
		internal static void AutoGeneratedStaticCollectObjectsLeaveKingdomAsClanBarterable(object o, List<object> collectedObjects)
		{
			((LeaveKingdomAsClanBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600496E RID: 18798 RVA: 0x00174154 File Offset: 0x00172354
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}
	}
}
