using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x02000487 RID: 1159
	public class MercenaryJoinKingdomBarterable : Barterable
	{
		// Token: 0x17000E8C RID: 3724
		// (get) Token: 0x0600497C RID: 18812 RVA: 0x00174781 File Offset: 0x00172981
		public override string StringID
		{
			get
			{
				return "mercenary_join_faction_barterable";
			}
		}

		// Token: 0x0600497D RID: 18813 RVA: 0x00174788 File Offset: 0x00172988
		public MercenaryJoinKingdomBarterable(Hero owner, PartyBase ownerParty, Kingdom targetKingdom)
			: base(owner, ownerParty)
		{
			this._targetKingdom = targetKingdom;
		}

		// Token: 0x17000E8D RID: 3725
		// (get) Token: 0x0600497E RID: 18814 RVA: 0x00174799 File Offset: 0x00172999
		public override TextObject Name
		{
			get
			{
				TextObject textObject = new TextObject("{=PaG0Blui}Become a mercenary for {TARGET_FACTION}", null);
				textObject.SetTextVariable("TARGET_FACTION", this._targetKingdom.Name);
				return textObject;
			}
		}

		// Token: 0x0600497F RID: 18815 RVA: 0x001747C0 File Offset: 0x001729C0
		public override int GetUnitValueForFaction(IFaction faction)
		{
			float num = 0f;
			if (this._targetKingdom == faction.MapFaction)
			{
				num += Campaign.Current.Models.DiplomacyModel.GetScoreOfKingdomToHireMercenary(this._targetKingdom, base.OriginalOwner.Clan);
			}
			else if (faction == base.OriginalOwner.Clan)
			{
				if (base.OriginalOwner.Clan.Kingdom != null)
				{
					num += Campaign.Current.Models.DiplomacyModel.GetScoreOfMercenaryToLeaveKingdom(base.OriginalOwner.Clan, base.OriginalOwner.Clan.Kingdom);
				}
				num += Campaign.Current.Models.DiplomacyModel.GetScoreOfMercenaryToJoinKingdom(base.OriginalOwner.Clan, this._targetKingdom);
			}
			return (int)num;
		}

		// Token: 0x06004980 RID: 18816 RVA: 0x00174887 File Offset: 0x00172A87
		public override void CheckBarterLink(Barterable linkedBarterable)
		{
		}

		// Token: 0x06004981 RID: 18817 RVA: 0x00174889 File Offset: 0x00172A89
		public override ImageIdentifier GetVisualIdentifier()
		{
			return null;
		}

		// Token: 0x06004982 RID: 18818 RVA: 0x0017488C File Offset: 0x00172A8C
		public override string GetEncyclopediaLink()
		{
			return this._targetKingdom.EncyclopediaLink;
		}

		// Token: 0x06004983 RID: 18819 RVA: 0x0017489C File Offset: 0x00172A9C
		public override void Apply()
		{
			ChangeKingdomAction.ApplyByJoinFactionAsMercenary(base.OriginalOwner.Clan, this._targetKingdom, default(CampaignTime), Campaign.Current.Models.MinorFactionsModel.GetMercenaryAwardFactorToJoinKingdom(base.OriginalOwner.Clan, this._targetKingdom, false), true);
		}

		// Token: 0x06004984 RID: 18820 RVA: 0x001748EF File Offset: 0x00172AEF
		internal static void AutoGeneratedStaticCollectObjectsMercenaryJoinKingdomBarterable(object o, List<object> collectedObjects)
		{
			((MercenaryJoinKingdomBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06004985 RID: 18821 RVA: 0x001748FD File Offset: 0x00172AFD
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._targetKingdom);
		}

		// Token: 0x06004986 RID: 18822 RVA: 0x00174912 File Offset: 0x00172B12
		internal static object AutoGeneratedGetMemberValue_targetKingdom(object o)
		{
			return ((MercenaryJoinKingdomBarterable)o)._targetKingdom;
		}

		// Token: 0x04001448 RID: 5192
		[SaveableField(700)]
		private readonly Kingdom _targetKingdom;
	}
}
