using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x0200048B RID: 1163
	public class SetPrisonerFreeBarterable : Barterable
	{
		// Token: 0x17000E95 RID: 3733
		// (get) Token: 0x060049A3 RID: 18851 RVA: 0x001755D3 File Offset: 0x001737D3
		public override string StringID
		{
			get
			{
				return "set_prisoner_free_barterable";
			}
		}

		// Token: 0x060049A4 RID: 18852 RVA: 0x001755DA File Offset: 0x001737DA
		public SetPrisonerFreeBarterable(Hero prisonerCharacter, Hero captor, PartyBase ownerParty, Hero ransompayer)
			: base(captor, ownerParty)
		{
			this._prisonerCharacter = prisonerCharacter;
			this._ransompayer = ransompayer;
		}

		// Token: 0x17000E96 RID: 3734
		// (get) Token: 0x060049A5 RID: 18853 RVA: 0x001755F3 File Offset: 0x001737F3
		public override TextObject Name
		{
			get
			{
				StringHelpers.SetCharacterProperties("PRISONER", this._prisonerCharacter.CharacterObject, null, false);
				return new TextObject("{=RwOzeGc3}Release {PRISONER.NAME}", null);
			}
		}

		// Token: 0x060049A6 RID: 18854 RVA: 0x00175618 File Offset: 0x00173818
		public override int GetUnitValueForFaction(IFaction faction)
		{
			float num = (float)Campaign.Current.Models.RansomValueCalculationModel.PrisonerRansomValue(this._prisonerCharacter.CharacterObject, null) * 0.9f;
			if (faction == this._prisonerCharacter.MapFaction || faction == this._prisonerCharacter.Clan)
			{
				num *= 1f + (float)((int)MBMath.ClampFloat(this._prisonerCharacter.CaptivityStartTime.ElapsedWeeksUntilNow * MBRandom.RandomFloatRanged(0.875f, 1.75f), 0f, 8f)) * 0.3f;
				return (int)num;
			}
			if (faction.MapFaction == this._prisonerCharacter.PartyBelongedToAsPrisoner.MapFaction)
			{
				return (int)(-(int)num);
			}
			return 0;
		}

		// Token: 0x060049A7 RID: 18855 RVA: 0x001756CC File Offset: 0x001738CC
		public override ImageIdentifier GetVisualIdentifier()
		{
			return new CharacterImageIdentifier(CharacterCode.CreateFrom(this._prisonerCharacter.CharacterObject));
		}

		// Token: 0x060049A8 RID: 18856 RVA: 0x001756E3 File Offset: 0x001738E3
		public override string GetEncyclopediaLink()
		{
			return this._prisonerCharacter.EncyclopediaLink;
		}

		// Token: 0x060049A9 RID: 18857 RVA: 0x001756F0 File Offset: 0x001738F0
		public override void Apply()
		{
			if (this._prisonerCharacter.IsPrisoner)
			{
				EndCaptivityAction.ApplyByRansom(this._prisonerCharacter, this._ransompayer);
			}
		}

		// Token: 0x060049AA RID: 18858 RVA: 0x00175710 File Offset: 0x00173910
		internal static void AutoGeneratedStaticCollectObjectsSetPrisonerFreeBarterable(object o, List<object> collectedObjects)
		{
			((SetPrisonerFreeBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060049AB RID: 18859 RVA: 0x0017571E File Offset: 0x0017391E
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._prisonerCharacter);
			collectedObjects.Add(this._ransompayer);
		}

		// Token: 0x060049AC RID: 18860 RVA: 0x0017573F File Offset: 0x0017393F
		internal static object AutoGeneratedGetMemberValue_prisonerCharacter(object o)
		{
			return ((SetPrisonerFreeBarterable)o)._prisonerCharacter;
		}

		// Token: 0x060049AD RID: 18861 RVA: 0x0017574C File Offset: 0x0017394C
		internal static object AutoGeneratedGetMemberValue_ransompayer(object o)
		{
			return ((SetPrisonerFreeBarterable)o)._ransompayer;
		}

		// Token: 0x04001452 RID: 5202
		[SaveableField(900)]
		private readonly Hero _prisonerCharacter;

		// Token: 0x04001453 RID: 5203
		[SaveableField(901)]
		private readonly Hero _ransompayer;
	}
}
