using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.MapNotificationTypes
{
	// Token: 0x020002BA RID: 698
	public class AlleyLeaderDiedMapNotification : InformationData
	{
		// Token: 0x06002531 RID: 9521 RVA: 0x0009D414 File Offset: 0x0009B614
		internal static void AutoGeneratedStaticCollectObjectsAlleyLeaderDiedMapNotification(object o, List<object> collectedObjects)
		{
			((AlleyLeaderDiedMapNotification)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002532 RID: 9522 RVA: 0x0009D422 File Offset: 0x0009B622
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Alley);
		}

		// Token: 0x06002533 RID: 9523 RVA: 0x0009D437 File Offset: 0x0009B637
		internal static object AutoGeneratedGetMemberValueAlley(object o)
		{
			return ((AlleyLeaderDiedMapNotification)o).Alley;
		}

		// Token: 0x17000953 RID: 2387
		// (get) Token: 0x06002534 RID: 9524 RVA: 0x0009D444 File Offset: 0x0009B644
		// (set) Token: 0x06002535 RID: 9525 RVA: 0x0009D44C File Offset: 0x0009B64C
		[SaveableProperty(10)]
		public Alley Alley { get; private set; }

		// Token: 0x06002536 RID: 9526 RVA: 0x0009D455 File Offset: 0x0009B655
		public AlleyLeaderDiedMapNotification(Alley alley, TextObject description)
			: base(description)
		{
			this.Alley = alley;
		}

		// Token: 0x17000954 RID: 2388
		// (get) Token: 0x06002537 RID: 9527 RVA: 0x0009D465 File Offset: 0x0009B665
		public override TextObject TitleText
		{
			get
			{
				return new TextObject("{=6QoSHiWC}An alley without a leader", null);
			}
		}

		// Token: 0x17000955 RID: 2389
		// (get) Token: 0x06002538 RID: 9528 RVA: 0x0009D472 File Offset: 0x0009B672
		public override string SoundEventPath
		{
			get
			{
				return "event:/ui/notification/death";
			}
		}
	}
}
