using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.MapNotificationTypes
{
	// Token: 0x020002AF RID: 687
	public class SettlementOwnerChangedMapNotification : InformationData
	{
		// Token: 0x060024AF RID: 9391 RVA: 0x0009CC5A File Offset: 0x0009AE5A
		internal static void AutoGeneratedStaticCollectObjectsSettlementOwnerChangedMapNotification(object o, List<object> collectedObjects)
		{
			((SettlementOwnerChangedMapNotification)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060024B0 RID: 9392 RVA: 0x0009CC68 File Offset: 0x0009AE68
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.PreviousOwner);
			collectedObjects.Add(this.NewOwner);
			collectedObjects.Add(this.Settlement);
		}

		// Token: 0x060024B1 RID: 9393 RVA: 0x0009CC95 File Offset: 0x0009AE95
		internal static object AutoGeneratedGetMemberValuePreviousOwner(object o)
		{
			return ((SettlementOwnerChangedMapNotification)o).PreviousOwner;
		}

		// Token: 0x060024B2 RID: 9394 RVA: 0x0009CCA2 File Offset: 0x0009AEA2
		internal static object AutoGeneratedGetMemberValueNewOwner(object o)
		{
			return ((SettlementOwnerChangedMapNotification)o).NewOwner;
		}

		// Token: 0x060024B3 RID: 9395 RVA: 0x0009CCAF File Offset: 0x0009AEAF
		internal static object AutoGeneratedGetMemberValueSettlement(object o)
		{
			return ((SettlementOwnerChangedMapNotification)o).Settlement;
		}

		// Token: 0x17000926 RID: 2342
		// (get) Token: 0x060024B4 RID: 9396 RVA: 0x0009CCBC File Offset: 0x0009AEBC
		public override TextObject TitleText
		{
			get
			{
				return new TextObject("{=b6BunI6y}Settlement Owner Changed", null);
			}
		}

		// Token: 0x17000927 RID: 2343
		// (get) Token: 0x060024B5 RID: 9397 RVA: 0x0009CCC9 File Offset: 0x0009AEC9
		public override string SoundEventPath
		{
			get
			{
				return "event:/ui/notification/settlement_owner_change";
			}
		}

		// Token: 0x17000928 RID: 2344
		// (get) Token: 0x060024B6 RID: 9398 RVA: 0x0009CCD0 File Offset: 0x0009AED0
		// (set) Token: 0x060024B7 RID: 9399 RVA: 0x0009CCD8 File Offset: 0x0009AED8
		[SaveableProperty(10)]
		public Hero PreviousOwner { get; private set; }

		// Token: 0x17000929 RID: 2345
		// (get) Token: 0x060024B8 RID: 9400 RVA: 0x0009CCE1 File Offset: 0x0009AEE1
		// (set) Token: 0x060024B9 RID: 9401 RVA: 0x0009CCE9 File Offset: 0x0009AEE9
		[SaveableProperty(20)]
		public Hero NewOwner { get; private set; }

		// Token: 0x1700092A RID: 2346
		// (get) Token: 0x060024BA RID: 9402 RVA: 0x0009CCF2 File Offset: 0x0009AEF2
		// (set) Token: 0x060024BB RID: 9403 RVA: 0x0009CCFA File Offset: 0x0009AEFA
		[SaveableProperty(30)]
		public Settlement Settlement { get; private set; }

		// Token: 0x060024BC RID: 9404 RVA: 0x0009CD03 File Offset: 0x0009AF03
		public SettlementOwnerChangedMapNotification(Settlement settlement, Hero newOwner, Hero previousOwner, TextObject descriptionText)
			: base(descriptionText)
		{
			this.PreviousOwner = previousOwner;
			this.NewOwner = newOwner;
			this.Settlement = settlement;
		}
	}
}
