using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues.IssueQuestTasks
{
	// Token: 0x02000381 RID: 897
	public class ChangeSettlementOwnerTask : QuestTaskBase
	{
		// Token: 0x06003484 RID: 13444 RVA: 0x000D8C6E File Offset: 0x000D6E6E
		internal static void AutoGeneratedStaticCollectObjectsChangeSettlementOwnerTask(object o, List<object> collectedObjects)
		{
			((ChangeSettlementOwnerTask)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003485 RID: 13445 RVA: 0x000D8C7C File Offset: 0x000D6E7C
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._settlement);
			collectedObjects.Add(this._newOwner);
		}

		// Token: 0x06003486 RID: 13446 RVA: 0x000D8C9D File Offset: 0x000D6E9D
		internal static object AutoGeneratedGetMemberValue_settlement(object o)
		{
			return ((ChangeSettlementOwnerTask)o)._settlement;
		}

		// Token: 0x06003487 RID: 13447 RVA: 0x000D8CAA File Offset: 0x000D6EAA
		internal static object AutoGeneratedGetMemberValue_newOwner(object o)
		{
			return ((ChangeSettlementOwnerTask)o)._newOwner;
		}

		// Token: 0x06003488 RID: 13448 RVA: 0x000D8CB7 File Offset: 0x000D6EB7
		public ChangeSettlementOwnerTask(Settlement settlement, Hero newOwner, Action onSucceededAction, Action onFailedAction, Action onCanceledAction, DialogFlow dialogFlow = null)
			: base(dialogFlow, onSucceededAction, onFailedAction, onCanceledAction)
		{
			this._settlement = settlement;
			this._newOwner = newOwner;
		}

		// Token: 0x06003489 RID: 13449 RVA: 0x000D8CD4 File Offset: 0x000D6ED4
		public void OnSettlementOwnerChanged(Settlement settlement, bool openToClaim, Hero newOwner, Hero oldOwner, Hero capturerHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail)
		{
			if (this._settlement == settlement && this._newOwner == newOwner)
			{
				base.Finish(QuestTaskBase.FinishStates.Success);
			}
		}

		// Token: 0x0600348A RID: 13450 RVA: 0x000D8CEF File Offset: 0x000D6EEF
		public override void SetReferences()
		{
			CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener(this, new Action<Settlement, bool, Hero, Hero, Hero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail>(this.OnSettlementOwnerChanged));
		}

		// Token: 0x04000F05 RID: 3845
		[SaveableField(30)]
		private readonly Settlement _settlement;

		// Token: 0x04000F06 RID: 3846
		[SaveableField(31)]
		private readonly Hero _newOwner;
	}
}
