using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000359 RID: 857
	public class ArmyNeedsSuppliesIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x0600331D RID: 13085 RVA: 0x000D2ED5 File Offset: 0x000D10D5
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
			CampaignEvents.ArmyDispersed.AddNonSerializedListener(this, new Action<Army, Army.ArmyDispersionReason, bool>(this.OnArmyDispersed));
		}

		// Token: 0x0600331E RID: 13086 RVA: 0x000D2F05 File Offset: 0x000D1105
		private void OnArmyDispersed(Army army, Army.ArmyDispersionReason reason, bool arg3)
		{
			Hero armyOwner = army.ArmyOwner;
			if (((armyOwner != null) ? armyOwner.Issue : null) is ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue)
			{
				army.ArmyOwner.Issue.CompleteIssueWithStayAliveConditionsFailed();
			}
		}

		// Token: 0x0600331F RID: 13087 RVA: 0x000D2F30 File Offset: 0x000D1130
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x06003320 RID: 13088 RVA: 0x000D2F94 File Offset: 0x000D1194
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.IsLord && issueGiver.MapFaction.IsKingdomFaction && issueGiver.PartyBelongedTo != null && issueGiver.PartyBelongedTo.Army != null && issueGiver.PartyBelongedTo.Army.ArmyOwner == issueGiver && issueGiver.PartyBelongedTo.Army.Cohesion > 80f;
		}

		// Token: 0x06003321 RID: 13089 RVA: 0x000D2FF7 File Offset: 0x000D11F7
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			return new ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue(issueOwner);
		}

		// Token: 0x06003322 RID: 13090 RVA: 0x000D2FFF File Offset: 0x000D11FF
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EAA RID: 3754
		private const IssueBase.IssueFrequency ArmyNeedsSuppliesIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x04000EAB RID: 3755
		private const float QuestDurationInDays = 15f;

		// Token: 0x020006E4 RID: 1764
		public class ArmyNeedsSuppliesIssue : IssueBase
		{
			// Token: 0x06005422 RID: 21538 RVA: 0x0018EB53 File Offset: 0x0018CD53
			internal static void AutoGeneratedStaticCollectObjectsArmyNeedsSuppliesIssue(object o, List<object> collectedObjects)
			{
				((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005423 RID: 21539 RVA: 0x0018EB61 File Offset: 0x0018CD61
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005424 RID: 21540 RVA: 0x0018EB6A File Offset: 0x0018CD6A
			internal static object AutoGeneratedGetMemberValueNumberOfManInArmy(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue)o).NumberOfManInArmy;
			}

			// Token: 0x17000F97 RID: 3991
			// (get) Token: 0x06005425 RID: 21541 RVA: 0x0018EB7C File Offset: 0x0018CD7C
			private int GrainAmount
			{
				get
				{
					return MathF.Ceiling((float)(this.NumberOfManInArmy / 20) * 5f);
				}
			}

			// Token: 0x17000F98 RID: 3992
			// (get) Token: 0x06005426 RID: 21542 RVA: 0x0018EB93 File Offset: 0x0018CD93
			private int LiveStockAmount
			{
				get
				{
					return MathF.Ceiling((float)(this.NumberOfManInArmy / 20) * 0.5f);
				}
			}

			// Token: 0x17000F99 RID: 3993
			// (get) Token: 0x06005427 RID: 21543 RVA: 0x0018EBAA File Offset: 0x0018CDAA
			private int WineAmount
			{
				get
				{
					return MathF.Ceiling((float)(this.NumberOfManInArmy / 20) * 0.5f);
				}
			}

			// Token: 0x17000F9A RID: 3994
			// (get) Token: 0x06005428 RID: 21544 RVA: 0x0018EBC1 File Offset: 0x0018CDC1
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17000F9B RID: 3995
			// (get) Token: 0x06005429 RID: 21545 RVA: 0x0018EBC4 File Offset: 0x0018CDC4
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17000F9C RID: 3996
			// (get) Token: 0x0600542A RID: 21546 RVA: 0x0018EBC7 File Offset: 0x0018CDC7
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=BW7v0g6q}We are about to go on campaign but my quartermaster reports that our food supplies will not be enough to keep us in the field for very long. I can't spare any of my lords, so I need someone else to bring us a large amount of supplies as soon as possible. Can you do this?[if:convo_grave][ib:closed]", null);
				}
			}

			// Token: 0x17000F9D RID: 3997
			// (get) Token: 0x0600542B RID: 21547 RVA: 0x0018EBD4 File Offset: 0x0018CDD4
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=YaZc08oa}I can bring supplies, your {?QUEST_GIVER.GENDER}ladyship{?}lordship{\\?}. Just tell me what you need.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000F9E RID: 3998
			// (get) Token: 0x0600542C RID: 21548 RVA: 0x0018EC08 File Offset: 0x0018CE08
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=444rcko0}We need {GRAIN_AMOUNT} sacks of grain to meet our basic needs. And if you can find {LIVESTOCK_AMOUNT} live stocks and {WINE_AMOUNT} barrels of wine that would be a great favor. Men fight better after a good meal.", null);
					textObject.SetTextVariable("GRAIN_AMOUNT", this.GrainAmount);
					textObject.SetTextVariable("LIVESTOCK_AMOUNT", this.LiveStockAmount);
					textObject.SetTextVariable("WINE_AMOUNT", this.WineAmount);
					return textObject;
				}
			}

			// Token: 0x17000F9F RID: 3999
			// (get) Token: 0x0600542D RID: 21549 RVA: 0x0018EC58 File Offset: 0x0018CE58
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=ppO0hoT6}I'll deliver {GRAIN_AMOUNT} sacks of grain as soon as possible {?QUEST_GIVER.GENDER}lady{?}sir{\\?}, and try to find some livestock and wine as you requested.", null);
					textObject.SetTextVariable("GRAIN_AMOUNT", this.GrainAmount);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000FA0 RID: 4000
			// (get) Token: 0x0600542E RID: 21550 RVA: 0x0018EC9C File Offset: 0x0018CE9C
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=wVyqTlpS}Army Needs Supply", null);
				}
			}

			// Token: 0x17000FA1 RID: 4001
			// (get) Token: 0x0600542F RID: 21551 RVA: 0x0018ECA9 File Offset: 0x0018CEA9
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=iMq7M0bo}{QUEST_GIVER.LINK} asks you to provide them supplies for their military campaign.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, null, false);
					return textObject;
				}
			}

			// Token: 0x06005430 RID: 21552 RVA: 0x0018ECCE File Offset: 0x0018CECE
			public ArmyNeedsSuppliesIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(15f))
			{
				this.NumberOfManInArmy = base.IssueOwner.PartyBelongedTo.Army.TotalRegularCount;
			}

			// Token: 0x06005431 RID: 21553 RVA: 0x0018ECFC File Offset: 0x0018CEFC
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005432 RID: 21554 RVA: 0x0018ECFE File Offset: 0x0018CEFE
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005433 RID: 21555 RVA: 0x0018ED00 File Offset: 0x0018CF00
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(15f), this.RewardGold, this.GrainAmount, this.LiveStockAmount, this.WineAmount);
			}

			// Token: 0x06005434 RID: 21556 RVA: 0x0018ED30 File Offset: 0x0018CF30
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005435 RID: 21557 RVA: 0x0018ED34 File Offset: 0x0018CF34
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				relationHero = null;
				skill = null;
				requiredGold = 0;
				flags = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (Hero.MainHero.IsKingdomLeader)
				{
					flags |= IssueBase.PreconditionFlags.MainHeroIsKingdomLeader;
				}
				if (issueGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				if (Clan.PlayerClan.Tier < 1)
				{
					flags |= IssueBase.PreconditionFlags.ClanTier;
				}
				if (Clan.PlayerClan.Kingdom != issueGiver.MapFaction)
				{
					flags |= IssueBase.PreconditionFlags.NotInSameFaction;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005436 RID: 21558 RVA: 0x0018EDD1 File Offset: 0x0018CFD1
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.ClanInfluence)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005437 RID: 21559 RVA: 0x0018EDE8 File Offset: 0x0018CFE8
			public override bool IssueStayAliveConditions()
			{
				if (base.IssueOwner.PartyBelongedTo != null && base.IssueOwner.PartyBelongedTo.Army != null && base.IssueOwner.PartyBelongedTo.Army.ArmyOwner == base.IssueOwner && base.IssueOwner.PartyBelongedTo.Army.Cohesion > 40f && base.IssueOwner.Clan != Clan.PlayerClan && base.IssueOwner.MapFaction.IsKingdomFaction)
				{
					this.NumberOfManInArmy = base.IssueOwner.PartyBelongedTo.Army.TotalRegularCount;
					return true;
				}
				return false;
			}

			// Token: 0x06005438 RID: 21560 RVA: 0x0018EE92 File Offset: 0x0018D092
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001BDF RID: 7135
			[SaveableField(70)]
			private int NumberOfManInArmy;
		}

		// Token: 0x020006E5 RID: 1765
		public class ArmyNeedsSuppliesIssueQuest : QuestBase
		{
			// Token: 0x06005439 RID: 21561 RVA: 0x0018EE94 File Offset: 0x0018D094
			internal static void AutoGeneratedStaticCollectObjectsArmyNeedsSuppliesIssueQuest(object o, List<object> collectedObjects)
			{
				((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600543A RID: 21562 RVA: 0x0018EEA2 File Offset: 0x0018D0A2
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._grainLog);
				collectedObjects.Add(this._liveStockLog);
				collectedObjects.Add(this._wineLog);
			}

			// Token: 0x0600543B RID: 21563 RVA: 0x0018EECF File Offset: 0x0018D0CF
			internal static object AutoGeneratedGetMemberValue_requestedGrainAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._requestedGrainAmount;
			}

			// Token: 0x0600543C RID: 21564 RVA: 0x0018EEE1 File Offset: 0x0018D0E1
			internal static object AutoGeneratedGetMemberValue_requestedLiveStockAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._requestedLiveStockAmount;
			}

			// Token: 0x0600543D RID: 21565 RVA: 0x0018EEF3 File Offset: 0x0018D0F3
			internal static object AutoGeneratedGetMemberValue_requestedWineAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._requestedWineAmount;
			}

			// Token: 0x0600543E RID: 21566 RVA: 0x0018EF05 File Offset: 0x0018D105
			internal static object AutoGeneratedGetMemberValue_currentGrainAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._currentGrainAmount;
			}

			// Token: 0x0600543F RID: 21567 RVA: 0x0018EF17 File Offset: 0x0018D117
			internal static object AutoGeneratedGetMemberValue_currentLiveStockAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._currentLiveStockAmount;
			}

			// Token: 0x06005440 RID: 21568 RVA: 0x0018EF29 File Offset: 0x0018D129
			internal static object AutoGeneratedGetMemberValue_currentWineAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._currentWineAmount;
			}

			// Token: 0x06005441 RID: 21569 RVA: 0x0018EF3B File Offset: 0x0018D13B
			internal static object AutoGeneratedGetMemberValue_grainLog(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._grainLog;
			}

			// Token: 0x06005442 RID: 21570 RVA: 0x0018EF48 File Offset: 0x0018D148
			internal static object AutoGeneratedGetMemberValue_liveStockLog(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._liveStockLog;
			}

			// Token: 0x06005443 RID: 21571 RVA: 0x0018EF55 File Offset: 0x0018D155
			internal static object AutoGeneratedGetMemberValue_wineLog(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._wineLog;
			}

			// Token: 0x17000FA2 RID: 4002
			// (get) Token: 0x06005444 RID: 21572 RVA: 0x0018EF62 File Offset: 0x0018D162
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17000FA3 RID: 4003
			// (get) Token: 0x06005445 RID: 21573 RVA: 0x0018EF65 File Offset: 0x0018D165
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=wVyqTlpS}Army Needs Supply", null);
				}
			}

			// Token: 0x17000FA4 RID: 4004
			// (get) Token: 0x06005446 RID: 21574 RVA: 0x0018EF74 File Offset: 0x0018D174
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=GiaTh92Q}{QUEST_GIVER.LINK}, commanding an army of the {QUEST_GIVER_FACTION}, has told you that they need food supplies for their upcoming military campaign. {?QUEST_GIVER.GENDER}She{?}He{\\?} wanted you to deliver {GRAIN_AMOUNT} sacks of grain and although it's not necessary, to provide {LIVESTOCK_AMOUNT} live stocks and {WINE_AMOUNT} barrels of wine {?QUEST_GIVER.GENDER}she{?}he{\\?} would appreciate it.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_FACTION", base.QuestGiver.MapFaction.EncyclopediaLinkWithName);
					textObject.SetTextVariable("GRAIN_AMOUNT", this._requestedGrainAmount);
					textObject.SetTextVariable("LIVESTOCK_AMOUNT", this._requestedLiveStockAmount);
					textObject.SetTextVariable("WINE_AMOUNT", this._requestedWineAmount);
					return textObject;
				}
			}

			// Token: 0x17000FA5 RID: 4005
			// (get) Token: 0x06005447 RID: 21575 RVA: 0x0018EFF8 File Offset: 0x0018D1F8
			private TextObject SuccessQuestLogText
			{
				get
				{
					return new TextObject("{=z9pbB0K5}You have successfully delivered the supplies as requested.", null);
				}
			}

			// Token: 0x17000FA6 RID: 4006
			// (get) Token: 0x06005448 RID: 21576 RVA: 0x0018F005 File Offset: 0x0018D205
			private TextObject FailQuestLogText
			{
				get
				{
					return new TextObject("{=k5HJ3Ld6}You have failed to deliver the supplies in time.", null);
				}
			}

			// Token: 0x17000FA7 RID: 4007
			// (get) Token: 0x06005449 RID: 21577 RVA: 0x0018F014 File Offset: 0x0018D214
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17000FA8 RID: 4008
			// (get) Token: 0x0600544A RID: 21578 RVA: 0x0018F048 File Offset: 0x0018D248
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x0600544B RID: 21579 RVA: 0x0018F07A File Offset: 0x0018D27A
			public ArmyNeedsSuppliesIssueQuest(string questId, Hero questGiver, CampaignTime duration, int rewardGold, int grainAmount, int liveStockAmount, int wineAmount)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._requestedGrainAmount = grainAmount;
				this._requestedLiveStockAmount = liveStockAmount;
				this._requestedWineAmount = wineAmount;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x0600544C RID: 21580 RVA: 0x0018F0AB File Offset: 0x0018D2AB
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x0600544D RID: 21581 RVA: 0x0018F0B3 File Offset: 0x0018D2B3
			protected override void HourlyTick()
			{
			}

			// Token: 0x0600544E RID: 21582 RVA: 0x0018F0B8 File Offset: 0x0018D2B8
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=64RFlBFr}Very well. Don't worry, all your expenses will be covered.[if:convo_approving][ib:hip] ", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=bGbSbqTG}Have you brought our supplies?", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(delegate
					{
						this.CalculateAndUpdateRequestedItemsCountInPlayer(false);
					})
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=FmjZfigu}Yes. I have brought your grain, livestock and wine as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedEverything))
					.NpcLine(new TextObject("{=UjS8JnH5}Splendid. I will never forget your service, my friend.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedEverythingConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=ISOHhXxW}Yes. I have brought your grain and wine as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedGrainWine))
					.NpcLine(new TextObject("{=1atg831t}Thank you. Your service will be remembered.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedGrainAndWineConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=YbsVaZkb}Yes. I have brought your grain and livestock as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedGrainLiveStock))
					.NpcLine(new TextObject("{=1atg831t}Thank you. Your service will be remembered.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedGrainAndLiveStockConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=m9a3ZalO}Yes. I have brought your grain as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedGrain))
					.NpcLine(new TextObject("{=1atg831t}Thank you. Your service will be remembered.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedGrainConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=PAbVhuKi}Not yet. I'm still working on it.", null), null, null, null)
					.NpcLine(new TextObject("{=AV5xVGM5}Good. We need them as soon as possible.[if:convo_undecided_open][ib:closed2]", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(MapEventHelper.OnConversationEnd))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x0600544F RID: 21583 RVA: 0x0018F2E0 File Offset: 0x0018D4E0
			private void CollectedGrainConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 5f);
				this.RelationshipChangeWithQuestGiver = 2;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005450 RID: 21584 RVA: 0x0018F380 File Offset: 0x0018D580
			private void CollectedGrainAndLiveStockConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 5f);
				this.RelationshipChangeWithQuestGiver = 3;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("sheep").Value * this._requestedLiveStockAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				this.RemoveLiveStocksFromPlayer();
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005451 RID: 21585 RVA: 0x0018F444 File Offset: 0x0018D644
			private void CollectedGrainAndWineConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 5f);
				this.RelationshipChangeWithQuestGiver = 4;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("wine").Value * this._requestedLiveStockAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>("wine");
				MobileParty.MainParty.ItemRoster.AddToCounts(@object, -this._requestedWineAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(@object, this._requestedWineAmount);
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005452 RID: 21586 RVA: 0x0018F548 File Offset: 0x0018D748
			private void CollectedEverythingConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 8f);
				this.RelationshipChangeWithQuestGiver = 6;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("wine").Value * this._requestedLiveStockAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("sheep").Value * this._requestedLiveStockAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>("wine");
				MobileParty.MainParty.ItemRoster.AddToCounts(@object, -this._requestedWineAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(@object, this._requestedWineAmount);
				this.RemoveLiveStocksFromPlayer();
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005453 RID: 21587 RVA: 0x0018F670 File Offset: 0x0018D870
			private void RemoveLiveStocksFromPlayer()
			{
				int i = this._requestedLiveStockAmount;
				while (i > 0)
				{
					for (int j = 0; j < MobileParty.MainParty.ItemRoster.Count; j++)
					{
						ItemRosterElement itemRosterElement = MobileParty.MainParty.ItemRoster[j];
						if (!itemRosterElement.IsEmpty)
						{
							ItemObject item = itemRosterElement.EquipmentElement.Item;
							if (item.HasHorseComponent && item.HorseComponent.IsLiveStock)
							{
								if (i < itemRosterElement.Amount)
								{
									MobileParty.MainParty.ItemRoster.AddToCounts(item, -i);
									i = 0;
									break;
								}
								MobileParty.MainParty.ItemRoster.AddToCounts(item, -itemRosterElement.Amount);
								i -= itemRosterElement.Amount;
							}
						}
					}
				}
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(MBObjectManager.Instance.GetObject<ItemObject>("meat"), this._requestedLiveStockAmount * 2);
			}

			// Token: 0x06005454 RID: 21588 RVA: 0x0018F763 File Offset: 0x0018D963
			private bool CheckIfPlayerCollectedGrain()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount;
			}

			// Token: 0x06005455 RID: 21589 RVA: 0x0018F776 File Offset: 0x0018D976
			private bool CheckIfPlayerCollectedGrainLiveStock()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount && this._currentLiveStockAmount >= this._requestedLiveStockAmount;
			}

			// Token: 0x06005456 RID: 21590 RVA: 0x0018F799 File Offset: 0x0018D999
			private bool CheckIfPlayerCollectedGrainWine()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount && this._currentWineAmount >= this._requestedWineAmount;
			}

			// Token: 0x06005457 RID: 21591 RVA: 0x0018F7BC File Offset: 0x0018D9BC
			private bool CheckIfPlayerCollectedEverything()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount && this._currentWineAmount >= this._requestedWineAmount && this._currentLiveStockAmount >= this._requestedLiveStockAmount;
			}

			// Token: 0x06005458 RID: 21592 RVA: 0x0018F7F0 File Offset: 0x0018D9F0
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddLog(this.PlayerStartsQuestLogText, false);
				this.CalculateAndUpdateRequestedItemsCountInPlayer(true);
				this._grainLog = base.AddDiscreteLog(TextObject.GetEmpty(), new TextObject("{=yGxjOnYb}Collected Grain Amount", null), this._currentGrainAmount, this._requestedGrainAmount, null, false);
				this._liveStockLog = base.AddDiscreteLog(TextObject.GetEmpty(), new TextObject("{=aIxX2s8n}Collected Livestock Amount (Optional)", null), this._currentLiveStockAmount, this._requestedLiveStockAmount, null, false);
				this._wineLog = base.AddDiscreteLog(TextObject.GetEmpty(), new TextObject("{=ENS8Ig1o}Collected Wine Amount (Optional)", null), this._currentWineAmount, this._requestedWineAmount, null, false);
			}

			// Token: 0x06005459 RID: 21593 RVA: 0x0018F898 File Offset: 0x0018DA98
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnInventoryExchange));
				CampaignEvents.ArmyDispersed.AddNonSerializedListener(this, new Action<Army, Army.ArmyDispersionReason, bool>(this.OnArmyDispersed));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
			}

			// Token: 0x0600545A RID: 21594 RVA: 0x0018F904 File Offset: 0x0018DB04
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (clan == Clan.PlayerClan && oldKingdom == base.QuestGiver.MapFaction)
				{
					TextObject textObject = new TextObject("{=aQVdW6aC}You have left {QUEST_GIVER_FACTION}. Your agreement with {QUEST_GIVER.LINK} is terminated.", null);
					textObject.SetTextVariable("QUEST_GIVER_FACTION", base.QuestGiver.MapFaction.EncyclopediaLinkWithName);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					base.CompleteQuestWithCancel(textObject);
					return;
				}
				if (base.QuestGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x0600545B RID: 21595 RVA: 0x0018F997 File Offset: 0x0018DB97
			private void OnArmyDispersed(Army army, Army.ArmyDispersionReason reason, bool isPlayersArmy)
			{
				if (army.ArmyOwner == base.QuestGiver)
				{
					base.AddLog(new TextObject("{=K2gsZOMb}Army is disbanded and your mission was canceled.", null), false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x0600545C RID: 21596 RVA: 0x0018F9C1 File Offset: 0x0018DBC1
			private void OnInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				this.CalculateAndUpdateRequestedItemsCountInPlayer(true);
			}

			// Token: 0x0600545D RID: 21597 RVA: 0x0018F9CC File Offset: 0x0018DBCC
			private void CalculateAndUpdateRequestedItemsCountInPlayer(bool notifyPlayer = true)
			{
				ItemObject grain = DefaultItems.Grain;
				ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>("wine");
				this._currentGrainAmount = MobileParty.MainParty.ItemRoster.GetItemNumber(grain);
				this._currentLiveStockAmount = MobileParty.MainParty.ItemRoster.NumberOfLivestockAnimals;
				this._currentWineAmount = MobileParty.MainParty.ItemRoster.GetItemNumber(@object);
				if (notifyPlayer)
				{
					if (this._currentGrainAmount >= this._requestedGrainAmount && this._currentLiveStockAmount >= this._requestedLiveStockAmount && this._currentWineAmount >= this._requestedWineAmount)
					{
						MBInformationManager.AddQuickInformation(new TextObject("{=uEV6kKdU}You have collected all the supplies that the army commander requested. Return to army and deliver the supplies", null), 0, null, null, "");
					}
					else if (this._currentGrainAmount >= this._requestedGrainAmount)
					{
						MBInformationManager.AddQuickInformation(new TextObject("{=8XpTvx1i}You have collected enough grains that the army commander requested. Return to army and deliver the supplies", null), 0, null, null, "");
					}
				}
				this._currentGrainAmount = (int)MathF.Clamp((float)this._currentGrainAmount, 0f, (float)this._requestedGrainAmount);
				this._currentLiveStockAmount = (int)MathF.Clamp((float)this._currentLiveStockAmount, 0f, (float)this._requestedLiveStockAmount);
				this._currentWineAmount = (int)MathF.Clamp((float)this._currentWineAmount, 0f, (float)this._requestedWineAmount);
				JournalLog grainLog = this._grainLog;
				if (grainLog != null)
				{
					grainLog.UpdateCurrentProgress(this._currentGrainAmount);
				}
				JournalLog liveStockLog = this._liveStockLog;
				if (liveStockLog != null)
				{
					liveStockLog.UpdateCurrentProgress(this._currentLiveStockAmount);
				}
				JournalLog wineLog = this._wineLog;
				if (wineLog == null)
				{
					return;
				}
				wineLog.UpdateCurrentProgress(this._currentWineAmount);
			}

			// Token: 0x0600545E RID: 21598 RVA: 0x0018FB3E File Offset: 0x0018DD3E
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x0600545F RID: 21599 RVA: 0x0018FB56 File Offset: 0x0018DD56
			public override void OnFailed()
			{
				this.RelationshipChangeWithQuestGiver = -2;
			}

			// Token: 0x06005460 RID: 21600 RVA: 0x0018FB60 File Offset: 0x0018DD60
			protected override void OnCompleteWithSuccess()
			{
				base.AddLog(this.SuccessQuestLogText, false);
			}

			// Token: 0x06005461 RID: 21601 RVA: 0x0018FB70 File Offset: 0x0018DD70
			protected override void OnTimedOut()
			{
				this.OnFailed();
				base.AddLog(this.FailQuestLogText, false);
			}

			// Token: 0x06005462 RID: 21602 RVA: 0x0018FB86 File Offset: 0x0018DD86
			public override void OnCanceled()
			{
			}

			// Token: 0x04001BE0 RID: 7136
			[SaveableField(10)]
			private int _requestedGrainAmount;

			// Token: 0x04001BE1 RID: 7137
			[SaveableField(20)]
			private int _requestedLiveStockAmount;

			// Token: 0x04001BE2 RID: 7138
			[SaveableField(30)]
			private int _requestedWineAmount;

			// Token: 0x04001BE3 RID: 7139
			[SaveableField(40)]
			private int _currentGrainAmount;

			// Token: 0x04001BE4 RID: 7140
			[SaveableField(50)]
			private int _currentLiveStockAmount;

			// Token: 0x04001BE5 RID: 7141
			[SaveableField(60)]
			private int _currentWineAmount;

			// Token: 0x04001BE6 RID: 7142
			[SaveableField(70)]
			private JournalLog _grainLog;

			// Token: 0x04001BE7 RID: 7143
			[SaveableField(80)]
			private JournalLog _liveStockLog;

			// Token: 0x04001BE8 RID: 7144
			[SaveableField(90)]
			private JournalLog _wineLog;
		}

		// Token: 0x020006E6 RID: 1766
		public class ArmyNeedsSuppliesIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005466 RID: 21606 RVA: 0x0018FBAF File Offset: 0x0018DDAF
			public ArmyNeedsSuppliesIssueTypeDefiner()
				: base(585800)
			{
			}

			// Token: 0x06005467 RID: 21607 RVA: 0x0018FBBC File Offset: 0x0018DDBC
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue), 1, null);
				base.AddClassDefinition(typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest), 2, null);
			}
		}
	}
}
