using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x0200035D RID: 861
	public class CapturedByBountyHuntersIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x17000C57 RID: 3159
		// (get) Token: 0x0600333F RID: 13119 RVA: 0x000D3608 File Offset: 0x000D1808
		private float ValidHideoutDistance
		{
			get
			{
				return Campaign.Current.EstimatedAverageBanditPartySpeed * (float)CampaignTime.HoursInDay;
			}
		}

		// Token: 0x06003340 RID: 13120 RVA: 0x000D361B File Offset: 0x000D181B
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003341 RID: 13121 RVA: 0x000D3634 File Offset: 0x000D1834
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x06003342 RID: 13122 RVA: 0x000D3638 File Offset: 0x000D1838
		private bool ConditionsHold(Hero issueGiver, out Settlement selectedHideout)
		{
			selectedHideout = null;
			if (issueGiver.IsLord || (issueGiver.IsNotable && issueGiver.CurrentSettlement == null))
			{
				return false;
			}
			if (issueGiver.IsGangLeader)
			{
				selectedHideout = this.FindSuitableHideout(issueGiver);
				CharacterObject @object = MBObjectManager.Instance.GetObject<CharacterObject>("looter");
				return selectedHideout != null && @object != null;
			}
			return false;
		}

		// Token: 0x06003343 RID: 13123 RVA: 0x000D3690 File Offset: 0x000D1890
		private Settlement FindSuitableHideout(Hero issueGiver)
		{
			Hideout hideout = SettlementHelper.FindNearestHideoutToSettlement(issueGiver.CurrentSettlement, MobileParty.NavigationType.Default, (Settlement s) => s.Hideout.IsInfested && !s.IsSettlementBusy(this) && Campaign.Current.Models.MapDistanceModel.GetDistance(issueGiver.CurrentSettlement, s, false, false, MobileParty.NavigationType.Default) < this.ValidHideoutDistance);
			if (hideout == null)
			{
				return null;
			}
			return hideout.Settlement;
		}

		// Token: 0x06003344 RID: 13124 RVA: 0x000D36DC File Offset: 0x000D18DC
		public void OnCheckForIssue(Hero hero)
		{
			Settlement settlement;
			if (this.ConditionsHold(hero, out settlement))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssue), IssueBase.IssueFrequency.Common, settlement));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssue), IssueBase.IssueFrequency.Common));
		}

		// Token: 0x06003345 RID: 13125 RVA: 0x000D3744 File Offset: 0x000D1944
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			PotentialIssueData potentialIssueData = pid;
			return new CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssue(issueOwner, potentialIssueData.RelatedObject as Settlement);
		}

		// Token: 0x04000EB5 RID: 3765
		private const IssueBase.IssueFrequency CapturedByBountyHuntersIssueFrequency = IssueBase.IssueFrequency.Common;

		// Token: 0x020006F6 RID: 1782
		public class CapturedByBountyHuntersIssue : IssueBase
		{
			// Token: 0x0600559D RID: 21917 RVA: 0x0019401C File Offset: 0x0019221C
			internal static void AutoGeneratedStaticCollectObjectsCapturedByBountyHuntersIssue(object o, List<object> collectedObjects)
			{
				((CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600559E RID: 21918 RVA: 0x0019402A File Offset: 0x0019222A
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._hideout);
			}

			// Token: 0x0600559F RID: 21919 RVA: 0x0019403F File Offset: 0x0019223F
			internal static object AutoGeneratedGetMemberValue_hideout(object o)
			{
				return ((CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssue)o)._hideout;
			}

			// Token: 0x1700100B RID: 4107
			// (get) Token: 0x060055A0 RID: 21920 RVA: 0x0019404C File Offset: 0x0019224C
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 10;
				}
			}

			// Token: 0x1700100C RID: 4108
			// (get) Token: 0x060055A1 RID: 21921 RVA: 0x00194050 File Offset: 0x00192250
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return Math.Max(5, 4 + MathF.Ceiling(6f * base.IssueDifficultyMultiplier));
				}
			}

			// Token: 0x1700100D RID: 4109
			// (get) Token: 0x060055A2 RID: 21922 RVA: 0x0019406B File Offset: 0x0019226B
			protected override int RewardGold
			{
				get
				{
					return 3000;
				}
			}

			// Token: 0x1700100E RID: 4110
			// (get) Token: 0x060055A3 RID: 21923 RVA: 0x00194072 File Offset: 0x00192272
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Casualties | IssueBase.AlternativeSolutionScaleFlag.FailureRisk;
				}
			}

			// Token: 0x1700100F RID: 4111
			// (get) Token: 0x060055A4 RID: 21924 RVA: 0x00194076 File Offset: 0x00192276
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=QtmPWQ5a}Some of my lads have gone missing. I've got a witness who says they'd gotten themselves dead drunk drinking with another band in these parts who turned out to be filthy bounty hunters. Now my boys are all trussed up, and these treacherous animals aim to turn them in for the bounty.[if:convo_annoyed][ib:closed]", null);
				}
			}

			// Token: 0x17001010 RID: 4112
			// (get) Token: 0x060055A5 RID: 21925 RVA: 0x00194083 File Offset: 0x00192283
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=A6iOIurY}How can I help you?", null);
				}
			}

			// Token: 0x17001011 RID: 4113
			// (get) Token: 0x060055A6 RID: 21926 RVA: 0x00194090 File Offset: 0x00192290
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=MiVYmiBc}Raid the bounty hunters' hideout and rescue my associates from them. I will make it worth your while, say {GOLD_AMOUNT} denars.[if:convo_mocking_revenge][ib:closed2]", null);
					textObject.SetTextVariable("GOLD_AMOUNT", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x17001012 RID: 4114
			// (get) Token: 0x060055A7 RID: 21927 RVA: 0x001940AF File Offset: 0x001922AF
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=GIkvhuCC}Maybe one of your men who knows a thing or two about scouting, with {TROOP_AMOUNT} good men can deal with these scum. So what do you say?[if:convo_undecided_open]", null);
					textObject.SetTextVariable("TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					return textObject;
				}
			}

			// Token: 0x17001013 RID: 4115
			// (get) Token: 0x060055A8 RID: 21928 RVA: 0x001940CE File Offset: 0x001922CE
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=cvWxXGo5}I can do the job.", null);
				}
			}

			// Token: 0x17001014 RID: 4116
			// (get) Token: 0x060055A9 RID: 21929 RVA: 0x001940DB File Offset: 0x001922DB
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=AvBNKK5y}Alright, I will have one of my companions go and rescue your associates.", null);
				}
			}

			// Token: 0x17001015 RID: 4117
			// (get) Token: 0x060055AA RID: 21930 RVA: 0x001940E8 File Offset: 0x001922E8
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=9u9OEZ9Y}Splendid. My men will guide your companion to the hideout.", null);
				}
			}

			// Token: 0x17001016 RID: 4118
			// (get) Token: 0x060055AB RID: 21931 RVA: 0x001940F5 File Offset: 0x001922F5
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=zwNjgdbi}My boys are getting ready for the battle. I'm pretty sure your men will tip the balance of that fight in our favor. Thank you.", null);
				}
			}

			// Token: 0x17001017 RID: 4119
			// (get) Token: 0x060055AC RID: 21932 RVA: 0x00194102 File Offset: 0x00192302
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001018 RID: 4120
			// (get) Token: 0x060055AD RID: 21933 RVA: 0x00194105 File Offset: 0x00192305
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001019 RID: 4121
			// (get) Token: 0x060055AE RID: 21934 RVA: 0x00194108 File Offset: 0x00192308
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=TQyB9rAs}{ISSUE_OWNER.NAME}'s Associates Captured by Bounty Hunters", null);
					StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700101A RID: 4122
			// (get) Token: 0x060055AF RID: 21935 RVA: 0x0019413C File Offset: 0x0019233C
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=HhTTzgLj}{ISSUE_OWNER.LINK}, a gang leader in {ISSUE_SETTLEMENT}, wants us to raid some bounty hunters' hideout and rescue {?ISSUE_OWNER.GENDER}her{?}his{\\?} associates.", null);
					StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.IssueOwner.CharacterObject, textObject, false);
					textObject.SetTextVariable("ISSUE_SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x060055B0 RID: 21936 RVA: 0x0019418A File Offset: 0x0019238A
			public CapturedByBountyHuntersIssue(Hero issueOwner, Settlement hideout)
				: base(issueOwner, CampaignTime.DaysFromNow(15f))
			{
				this._hideout = hideout;
			}

			// Token: 0x060055B1 RID: 21937 RVA: 0x001941A4 File Offset: 0x001923A4
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementSecurity)
				{
					return 1f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.2f;
				}
				return 0f;
			}

			// Token: 0x060055B2 RID: 21938 RVA: 0x001941C7 File Offset: 0x001923C7
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Scouting) >= hero.GetSkillValue(DefaultSkills.Riding)) ? DefaultSkills.Scouting : DefaultSkills.Riding, 120);
			}

			// Token: 0x060055B3 RID: 21939 RVA: 0x001941F4 File Offset: 0x001923F4
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x060055B4 RID: 21940 RVA: 0x00194205 File Offset: 0x00192405
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x060055B5 RID: 21941 RVA: 0x0019421F File Offset: 0x0019241F
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x1700101B RID: 4123
			// (get) Token: 0x060055B6 RID: 21942 RVA: 0x0019422D File Offset: 0x0019242D
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(750f + 1000f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x060055B7 RID: 21943 RVA: 0x00194242 File Offset: 0x00192442
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.RelationshipChangeWithIssueOwner = 5;
				base.IssueOwner.AddPower(10f);
				base.IssueOwner.CurrentSettlement.Town.Security -= 5f;
			}

			// Token: 0x060055B8 RID: 21944 RVA: 0x0019427C File Offset: 0x0019247C
			protected override void AlternativeSolutionEndWithFailureConsequence()
			{
				TraitLevelingHelper.OnIssueFailed(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -10)
				});
				this.RelationshipChangeWithIssueOwner = -5;
				base.IssueOwner.AddPower(-10f);
				base.IssueOwner.CurrentSettlement.Town.Security += 5f;
			}

			// Token: 0x1700101C RID: 4124
			// (get) Token: 0x060055B9 RID: 21945 RVA: 0x001942E4 File Offset: 0x001924E4
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=U7sTASN4}{ISSUE_OWNER.LINK}, a gang leader from {QUEST_SETTLEMENT}, has told you that some bounty hunters captured some of {?ISSUE_OWNER.GENDER}her{?}his{\\?} gang members and are holding them in their hideout. {?ISSUE_OWNER.GENDER}She{?}He{\\?} wants them found and rescued. You agreed to send {TROOP_COUNT} of your men along with a {COMPANION.LINK} to find these bounty hunters and rescue {?ISSUE_OWNER.GENDER}her{?}his{\\?} associates. They should be back in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					textObject.SetTextVariable("TROOP_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					return textObject;
				}
			}

			// Token: 0x060055BA RID: 21946 RVA: 0x00194375 File Offset: 0x00192575
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Common;
			}

			// Token: 0x060055BB RID: 21947 RVA: 0x00194378 File Offset: 0x00192578
			public override bool IssueStayAliveConditions()
			{
				return this._hideout.Hideout.IsInfested;
			}

			// Token: 0x060055BC RID: 21948 RVA: 0x0019438C File Offset: 0x0019258C
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				skill = null;
				relationHero = null;
				requiredGold = 0;
				flag = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (MobileParty.MainParty.MemberRoster.TotalHealthyCount - 1 < 25)
				{
					flag |= IssueBase.PreconditionFlags.NotEnoughTroops;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x060055BD RID: 21949 RVA: 0x001943E1 File Offset: 0x001925E1
			protected override void OnGameLoad()
			{
			}

			// Token: 0x060055BE RID: 21950 RVA: 0x001943E3 File Offset: 0x001925E3
			protected override void HourlyTick()
			{
			}

			// Token: 0x060055BF RID: 21951 RVA: 0x001943E5 File Offset: 0x001925E5
			public override void IsSettlementBusy(Settlement settlement, object asker, ref int priority)
			{
				if (asker != this && settlement == this._hideout)
				{
					priority = Math.Max(priority, 100);
				}
			}

			// Token: 0x060055C0 RID: 21952 RVA: 0x001943FF File Offset: 0x001925FF
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this.RewardGold, this._hideout);
			}

			// Token: 0x060055C1 RID: 21953 RVA: 0x00194423 File Offset: 0x00192623
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x060055C2 RID: 21954 RVA: 0x00194425 File Offset: 0x00192625
			protected override void OnIssueFinalized()
			{
			}

			// Token: 0x04001C30 RID: 7216
			private const int QuestSolutionNeededMinimumHealthyMenCount = 25;

			// Token: 0x04001C31 RID: 7217
			private const int CompanionRequiredSkillLevel = 120;

			// Token: 0x04001C32 RID: 7218
			private const int IssueDuration = 15;

			// Token: 0x04001C33 RID: 7219
			private const int QuestTimeLimit = 30;

			// Token: 0x04001C34 RID: 7220
			private const int AlternativeSolutionMinimumTroopTier = 2;

			// Token: 0x04001C35 RID: 7221
			[SaveableField(100)]
			private Settlement _hideout;
		}

		// Token: 0x020006F7 RID: 1783
		public class CapturedByBountyHuntersIssueQuest : QuestBase
		{
			// Token: 0x060055C3 RID: 21955 RVA: 0x00194427 File Offset: 0x00192627
			internal static void AutoGeneratedStaticCollectObjectsCapturedByBountyHuntersIssueQuest(object o, List<object> collectedObjects)
			{
				((CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x060055C4 RID: 21956 RVA: 0x00194435 File Offset: 0x00192635
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._questHideout);
			}

			// Token: 0x060055C5 RID: 21957 RVA: 0x0019444A File Offset: 0x0019264A
			internal static object AutoGeneratedGetMemberValue_questHideout(object o)
			{
				return ((CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssueQuest)o)._questHideout;
			}

			// Token: 0x1700101D RID: 4125
			// (get) Token: 0x060055C6 RID: 21958 RVA: 0x00194458 File Offset: 0x00192658
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=TQyB9rAs}{ISSUE_OWNER.NAME}'s Associates Captured by Bounty Hunters", null);
					StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700101E RID: 4126
			// (get) Token: 0x060055C7 RID: 21959 RVA: 0x0019448A File Offset: 0x0019268A
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700101F RID: 4127
			// (get) Token: 0x060055C8 RID: 21960 RVA: 0x00194490 File Offset: 0x00192690
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=P7MZ0hZb}{QUEST_GIVER.LINK}, a gang leader from {QUEST_SETTLEMENT}, has told you that some bounty hunters captured some of {?QUEST_GIVER.GENDER}her{?}his{\\?} gang members and are holding them in their hideout. You told {?QUEST_GIVER.GENDER}her{?}him{\\?} you would find them yourself.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", Settlement.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17001020 RID: 4128
			// (get) Token: 0x060055C9 RID: 21961 RVA: 0x001944D8 File Offset: 0x001926D8
			private TextObject SuccessQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=rNDRyFP4}You cleared the hideout and rescued the {QUEST_GIVER.LINK}'s associates. {?QUEST_GIVER.GENDER}She{?}He{\\?} sends you the following letter. \"Thank you for rescuing my men. I'll remember this.\"", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001021 RID: 4129
			// (get) Token: 0x060055CA RID: 21962 RVA: 0x0019450C File Offset: 0x0019270C
			private TextObject PlayerLostTheFightLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=nq0qLQ1x}You lost the fight against bounty hunters and failed to rescue the {QUEST_GIVER.LINK}'s men. {?QUEST_GIVER.GENDER}She{?}He{\\?} sends you the following letter. \"I appreciate your effort but it wasn't good enough...\"", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001022 RID: 4130
			// (get) Token: 0x060055CB RID: 21963 RVA: 0x00194540 File Offset: 0x00192740
			private TextObject HideoutClearedBySomeoneElseLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=4Bub0GY6}Hideout was cleared by someone else. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001023 RID: 4131
			// (get) Token: 0x060055CC RID: 21964 RVA: 0x00194574 File Offset: 0x00192774
			private TextObject TimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=JPAGzEhe}You failed to rescue the {QUEST_GIVER.LINK}'s men in time. {?QUEST_GIVER.GENDER}She{?}He{\\?} sends you the following letter. \"You sat on your heels doing nothing and my men will pay the price. I won't forget this...\"", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x060055CD RID: 21965 RVA: 0x001945A6 File Offset: 0x001927A6
			public CapturedByBountyHuntersIssueQuest(string questId, Hero giverHero, CampaignTime duration, int rewardGold, Settlement hideout)
				: base(questId, giverHero, duration, rewardGold)
			{
				this._questHideout = hideout;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x060055CE RID: 21966 RVA: 0x001945C7 File Offset: 0x001927C7
			private bool DialogCondition()
			{
				return Hero.OneToOneConversationHero == base.QuestGiver;
			}

			// Token: 0x060055CF RID: 21967 RVA: 0x001945D8 File Offset: 0x001927D8
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=BUM63VJq}That's the spirit. My men will tell you how to find the hideout. Rescue those poor captives, and a large sack of silver will be on your way![if:convo_approving][ib:hip]", null), null, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.DialogCondition))
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=vYCY931w}Any news about my men?", null), null, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.DialogCondition))
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=DJcMau0U}Not yet. We are still looking for them.", null), null, null, null)
					.NpcLine(new TextObject("{=VZhs6rpG}Well, try to speed it up. Once the bounty hunters turn them in, it'll be too late.", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=LvNTjCtQ}We need more time.", null), null, null, null)
					.NpcLine(new TextObject("{=15wCjIBY}Take too much time, and my men will swing from the gallows. Speed it along, will you?", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions();
			}

			// Token: 0x060055D0 RID: 21968 RVA: 0x001946CD File Offset: 0x001928CD
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddLog(this.PlayerStartsQuestLogText, false);
			}

			// Token: 0x060055D1 RID: 21969 RVA: 0x001946E3 File Offset: 0x001928E3
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x060055D2 RID: 21970 RVA: 0x001946EB File Offset: 0x001928EB
			protected override void HourlyTick()
			{
			}

			// Token: 0x060055D3 RID: 21971 RVA: 0x001946ED File Offset: 0x001928ED
			protected override void OnFinalize()
			{
			}

			// Token: 0x060055D4 RID: 21972 RVA: 0x001946F0 File Offset: 0x001928F0
			protected override void RegisterEvents()
			{
				CampaignEvents.OnSessionLaunchedEvent.AddNonSerializedListener(this, new Action<CampaignGameStarter>(this.OnSessionLaunched));
				CampaignEvents.MapEventEnded.AddNonSerializedListener(this, new Action<MapEvent>(this.OnMapEventEnded));
				CampaignEvents.OnSettlementLeftEvent.AddNonSerializedListener(this, new Action<MobileParty, Settlement>(this.OnSettlementLeft));
				CampaignEvents.IsSettlementBusyEvent.AddNonSerializedListener(this, new ReferenceAction<Settlement, object, int>(this.IsSettlementBusy));
			}

			// Token: 0x060055D5 RID: 21973 RVA: 0x00194759 File Offset: 0x00192959
			private void IsSettlementBusy(Settlement settlement, object asker, ref int priority)
			{
				if (asker != this && settlement == this._questHideout)
				{
					priority = Math.Max(priority, 200);
				}
			}

			// Token: 0x060055D6 RID: 21974 RVA: 0x00194776 File Offset: 0x00192976
			private void OnSessionLaunched(CampaignGameStarter campaignGameStarter)
			{
				if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.9", 0) && this._questHideout.IsSettlementBusy(this))
				{
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x060055D7 RID: 21975 RVA: 0x001947AC File Offset: 0x001929AC
			private void OnSettlementLeft(MobileParty party, Settlement settlement)
			{
				if (party == MobileParty.MainParty && settlement == base.QuestGiver.CurrentSettlement)
				{
					this._questHideout.Hideout.IsSpotted = true;
					this._questHideout.IsVisible = true;
					base.AddTrackedObject(this._questHideout);
					TextObject textObject = new TextObject("{=R9R6imnU}Scouts working for {QUEST_GIVER.NAME} marked the hideout on your map", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				}
			}

			// Token: 0x060055D8 RID: 21976 RVA: 0x0019482C File Offset: 0x00192A2C
			private void OnMapEventEnded(MapEvent mapEvent)
			{
				if (mapEvent.IsPlayerMapEvent)
				{
					if (mapEvent.MapEventSettlement == this._questHideout)
					{
						if (mapEvent.DefeatedSide == mapEvent.PlayerSide || mapEvent.DefeatedSide == BattleSideEnum.None)
						{
							base.AddLog(this.PlayerLostTheFightLogText, false);
							this.FailConsequences(false);
							return;
						}
						base.AddLog(this.SuccessQuestLogText, false);
						this.SuccessConsequences();
						return;
					}
				}
				else if (this._questHideout.Parties.Count == 0)
				{
					base.AddLog(this.HideoutClearedBySomeoneElseLogText, false);
					base.CompleteQuestWithFail(null);
				}
			}

			// Token: 0x060055D9 RID: 21977 RVA: 0x001948B8 File Offset: 0x00192AB8
			private void SuccessConsequences()
			{
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				base.QuestGiver.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = 5;
				if (base.QuestGiver.CurrentSettlement != null && base.QuestGiver.CurrentSettlement.Town != null)
				{
					base.QuestGiver.CurrentSettlement.Town.Security -= 5f;
				}
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 100)
				});
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x060055DA RID: 21978 RVA: 0x00194954 File Offset: 0x00192B54
			private void FailConsequences(bool isTimedOut)
			{
				TraitLevelingHelper.OnIssueFailed(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -10)
				});
				this.RelationshipChangeWithQuestGiver = -5;
				base.QuestGiver.AddPower(-10f);
				if (base.QuestGiver.CurrentSettlement != null && base.QuestGiver.CurrentSettlement.Town != null)
				{
					base.QuestGiver.CurrentSettlement.Town.Security += 5f;
				}
				if (!isTimedOut)
				{
					base.CompleteQuestWithFail(null);
				}
			}

			// Token: 0x060055DB RID: 21979 RVA: 0x001949E3 File Offset: 0x00192BE3
			protected override void OnTimedOut()
			{
				base.AddLog(this.TimeOutLogText, false);
				this.FailConsequences(true);
			}

			// Token: 0x04001C36 RID: 7222
			[SaveableField(102)]
			private Settlement _questHideout;
		}

		// Token: 0x020006F8 RID: 1784
		public class CapturedByBountyHuntersIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x060055DC RID: 21980 RVA: 0x001949FA File Offset: 0x00192BFA
			public CapturedByBountyHuntersIssueTypeDefiner()
				: base(580000)
			{
			}

			// Token: 0x060055DD RID: 21981 RVA: 0x00194A07 File Offset: 0x00192C07
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssue), 1, null);
				base.AddClassDefinition(typeof(CapturedByBountyHuntersIssueBehavior.CapturedByBountyHuntersIssueQuest), 2, null);
			}
		}
	}
}
