using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.CraftingSystem;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000362 RID: 866
	public class GangLeaderNeedsSpecialWeaponsIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x06003366 RID: 13158 RVA: 0x000D3E77 File Offset: 0x000D2077
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003367 RID: 13159 RVA: 0x000D3E90 File Offset: 0x000D2090
		private void OnCheckForIssue(Hero hero)
		{
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, this.ConditionsHold(hero) ? new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssue), IssueBase.IssueFrequency.VeryCommon, null) : new PotentialIssueData(typeof(GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x06003368 RID: 13160 RVA: 0x000D3EE5 File Offset: 0x000D20E5
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.CurrentSettlement != null && issueGiver.IsGangLeader && issueGiver.CurrentSettlement.IsTown && Campaign.Current.GetCampaignBehavior<ICraftingCampaignBehavior>() != null;
		}

		// Token: 0x06003369 RID: 13161 RVA: 0x000D3F13 File Offset: 0x000D2113
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			return new GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssue(issueOwner);
		}

		// Token: 0x0600336A RID: 13162 RVA: 0x000D3F1B File Offset: 0x000D211B
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EBB RID: 3771
		private const IssueBase.IssueFrequency SpecialWeaponOrderIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000708 RID: 1800
		public class GangLeaderNeedsSpecialWeaponsIssue : IssueBase
		{
			// Token: 0x0600576F RID: 22383 RVA: 0x0019B68E File Offset: 0x0019988E
			internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsSpecialWeaponsIssue(object o, List<object> collectedObjects)
			{
				((GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005770 RID: 22384 RVA: 0x0019B69C File Offset: 0x0019989C
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x170010B6 RID: 4278
			// (get) Token: 0x06005771 RID: 22385 RVA: 0x0019B6A5 File Offset: 0x001998A5
			public int NumberOfDaggersRequested
			{
				get
				{
					return 2 + MathF.Ceiling(4f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170010B7 RID: 4279
			// (get) Token: 0x06005772 RID: 22386 RVA: 0x0019B6BA File Offset: 0x001998BA
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170010B8 RID: 4280
			// (get) Token: 0x06005773 RID: 22387 RVA: 0x0019B6BD File Offset: 0x001998BD
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170010B9 RID: 4281
			// (get) Token: 0x06005774 RID: 22388 RVA: 0x0019B6C0 File Offset: 0x001998C0
			protected override bool IssueQuestCanBeDuplicated
			{
				get
				{
					return false;
				}
			}

			// Token: 0x06005775 RID: 22389 RVA: 0x0019B6C3 File Offset: 0x001998C3
			public GangLeaderNeedsSpecialWeaponsIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
			}

			// Token: 0x170010BA RID: 4282
			// (get) Token: 0x06005776 RID: 22390 RVA: 0x0019B6D6 File Offset: 0x001998D6
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=fmjWsUB6}Yeah... I've heard about your skills as a crafter of weapons. Now, nothing inspires my lads to shed my enemies' blood more than the feel of a really well-made blade in their hands. Could you make me some? I'll pay well.", null);
				}
			}

			// Token: 0x170010BB RID: 4283
			// (get) Token: 0x06005777 RID: 22391 RVA: 0x0019B6E3 File Offset: 0x001998E3
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=UdnXHLSh}What do you want exactly?", null);
				}
			}

			// Token: 0x170010BC RID: 4284
			// (get) Token: 0x06005778 RID: 22392 RVA: 0x0019B6F0 File Offset: 0x001998F0
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=xmETCOam}Daggers. Good, sharp, light daggers that they can hide under their clothes, so the guards won't stop them. We want to order {REQUESTED_AMOUNT} daggers. I can arrange things with the smith of {QUEST_SETTLEMENT} for you to work in his workshop.", null);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this.NumberOfDaggersRequested);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.IssueOwner.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x170010BD RID: 4285
			// (get) Token: 0x06005779 RID: 22393 RVA: 0x0019B72B File Offset: 0x0019992B
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=goLdeLsT}Alright I will forge your daggers.", null);
				}
			}

			// Token: 0x170010BE RID: 4286
			// (get) Token: 0x0600577A RID: 22394 RVA: 0x0019B738 File Offset: 0x00199938
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=tm9PiOMA}Special Weapon Order", null);
				}
			}

			// Token: 0x170010BF RID: 4287
			// (get) Token: 0x0600577B RID: 22395 RVA: 0x0019B745 File Offset: 0x00199945
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=auIV2JoK}{ISSUE_GIVER.LINK} is looking for someone to craft special weapons for {?ISSUE_GIVER.GENDER}her{?}his{\\?} men.", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x0600577C RID: 22396 RVA: 0x0019B769 File Offset: 0x00199969
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x0600577D RID: 22397 RVA: 0x0019B76C File Offset: 0x0019996C
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flag = IssueBase.PreconditionFlags.None;
				relationHero = issueGiver;
				requiredGold = 0;
				skill = DefaultSkills.Crafting;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				if (Hero.MainHero.GetSkillValue(skill) < 30)
				{
					flag |= IssueBase.PreconditionFlags.Skill;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x0600577E RID: 22398 RVA: 0x0019B7D8 File Offset: 0x001999D8
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				if (issueEffect == DefaultIssueEffects.SettlementSecurity)
				{
					return 0.5f;
				}
				return 0f;
			}

			// Token: 0x0600577F RID: 22399 RVA: 0x0019B7FB File Offset: 0x001999FB
			public override bool IssueStayAliveConditions()
			{
				return true;
			}

			// Token: 0x06005780 RID: 22400 RVA: 0x0019B7FE File Offset: 0x001999FE
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x06005781 RID: 22401 RVA: 0x0019B800 File Offset: 0x00199A00
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005782 RID: 22402 RVA: 0x0019B802 File Offset: 0x00199A02
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest(questId, base.IssueOwner, this.NumberOfDaggersRequested, CampaignTime.DaysFromNow(30f), this.RewardGold);
			}

			// Token: 0x06005783 RID: 22403 RVA: 0x0019B826 File Offset: 0x00199A26
			protected override void HourlyTick()
			{
			}

			// Token: 0x04001C9E RID: 7326
			private const int IssueAndQuestDuration = 30;
		}

		// Token: 0x02000709 RID: 1801
		public class GangLeaderNeedsSpecialWeaponsIssueQuest : QuestBase
		{
			// Token: 0x06005784 RID: 22404 RVA: 0x0019B828 File Offset: 0x00199A28
			internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsSpecialWeaponsIssueQuest(object o, List<object> collectedObjects)
			{
				((GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005785 RID: 22405 RVA: 0x0019B836 File Offset: 0x00199A36
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._currentCraftingOrder);
				collectedObjects.Add(this._playerAcceptedQuestLog);
				collectedObjects.Add(this._playerHasNeededItemsLog);
			}

			// Token: 0x06005786 RID: 22406 RVA: 0x0019B863 File Offset: 0x00199A63
			internal static object AutoGeneratedGetMemberValue_numberOfDaggersRequested(object o)
			{
				return ((GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest)o)._numberOfDaggersRequested;
			}

			// Token: 0x06005787 RID: 22407 RVA: 0x0019B875 File Offset: 0x00199A75
			internal static object AutoGeneratedGetMemberValue_currentCraftingOrder(object o)
			{
				return ((GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest)o)._currentCraftingOrder;
			}

			// Token: 0x06005788 RID: 22408 RVA: 0x0019B882 File Offset: 0x00199A82
			internal static object AutoGeneratedGetMemberValue_completedCraftingOrders(object o)
			{
				return ((GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest)o)._completedCraftingOrders;
			}

			// Token: 0x06005789 RID: 22409 RVA: 0x0019B894 File Offset: 0x00199A94
			internal static object AutoGeneratedGetMemberValue_playerAcceptedQuestLog(object o)
			{
				return ((GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest)o)._playerAcceptedQuestLog;
			}

			// Token: 0x0600578A RID: 22410 RVA: 0x0019B8A1 File Offset: 0x00199AA1
			internal static object AutoGeneratedGetMemberValue_playerHasNeededItemsLog(object o)
			{
				return ((GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest)o)._playerHasNeededItemsLog;
			}

			// Token: 0x170010C0 RID: 4288
			// (get) Token: 0x0600578B RID: 22411 RVA: 0x0019B8AE File Offset: 0x00199AAE
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170010C1 RID: 4289
			// (get) Token: 0x0600578C RID: 22412 RVA: 0x0019B8B4 File Offset: 0x00199AB4
			private TextObject QuestStartedLog
			{
				get
				{
					TextObject textObject = new TextObject("{=zo1shYCL}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}her{?}his{\\?} men need a special dagger that should be light and small enough to hide from the city guards. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to forge {REQUESTED_AMOUNT} daggers at the smith of {QUEST_SETTLEMENT}.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this._numberOfDaggersRequested);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x170010C2 RID: 4290
			// (get) Token: 0x0600578D RID: 22413 RVA: 0x0019B911 File Offset: 0x00199B11
			private TextObject QuestSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=3uvbVxfx}You have delivered the weapons to {QUEST_GIVER.LINK} as promised.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x170010C3 RID: 4291
			// (get) Token: 0x0600578E RID: 22414 RVA: 0x0019B938 File Offset: 0x00199B38
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170010C4 RID: 4292
			// (get) Token: 0x0600578F RID: 22415 RVA: 0x0019B96C File Offset: 0x00199B6C
			private TextObject QuestFailedLog
			{
				get
				{
					TextObject textObject = new TextObject("{=iTgVn26a}You have failed to bring the weapons to {QUEST_GIVER.LINK} in time.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170010C5 RID: 4293
			// (get) Token: 0x06005790 RID: 22416 RVA: 0x0019B99E File Offset: 0x00199B9E
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=tm9PiOMA}Special Weapon Order", null);
				}
			}

			// Token: 0x170010C6 RID: 4294
			// (get) Token: 0x06005791 RID: 22417 RVA: 0x0019B9AB File Offset: 0x00199BAB
			private TextObject PlayerHasNeededItemsLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=kHio2hlU}You now have enough daggers to complete the quest. Return to {QUEST_GIVER.LINK} to hand them over.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x06005792 RID: 22418 RVA: 0x0019B9CF File Offset: 0x00199BCF
			public GangLeaderNeedsSpecialWeaponsIssueQuest(string questId, Hero questGiver, int numberOfDaggersRequested, CampaignTime duration, int rewardGold)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._numberOfDaggersRequested = numberOfDaggersRequested;
				this._craftingBehavior = Campaign.Current.GetCampaignBehavior<ICraftingCampaignBehavior>();
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005793 RID: 22419 RVA: 0x0019BA00 File Offset: 0x00199C00
			protected override void SetDialogs()
			{
				TextObject textObject = new TextObject("{=siofh72D}Thank you, my friend. I'm looking forward to giving my boys their new toys.", null);
				TextObject textObject2 = new TextObject("{=cJOGUpSS}Any news about my orders?", null);
				TextObject textObject3 = new TextObject("{=R9NDaOhb}The daggers are almost ready. They just need a little more work...", null);
				TextObject textObject4 = new TextObject("{=CDXUehf0}Good, good.", null);
				TextObject textObject5 = new TextObject("{=wErSpkjy}I'm still working on it.", null);
				TextObject textObject6 = new TextObject("{=r2g61BjX}Well, my lads are anxiously waiting...", null);
				TextObject textObject7 = new TextObject("{=TBuyyh2S}There you go, that should be enough daggers for your men.", null);
				TextObject textObject8 = new TextObject("{=QCzB8DDX}Ah excellent, these will come in handy.", null);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(textObject, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject2, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject3, null, null, null)
					.NpcLine(textObject4, null, null, null, null)
					.CloseDialog()
					.PlayerOption(textObject5, null, null, null)
					.NpcLine(textObject6, null, null, null, null)
					.CloseDialog()
					.PlayerOption(textObject7, null, null, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.CheckPlayerHasCompletedEnoughOrdersClickableCondition))
					.NpcLine(textObject8, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.SucceedQuest))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005794 RID: 22420 RVA: 0x0019BB60 File Offset: 0x00199D60
			private bool CheckPlayerHasCompletedEnoughOrdersClickableCondition(out TextObject explanation)
			{
				if (this._completedCraftingOrders >= this._numberOfDaggersRequested)
				{
					explanation = null;
					return true;
				}
				explanation = new TextObject("{=mAvJcyY1}You haven't completed enough crafting orders yet.", null);
				return false;
			}

			// Token: 0x06005795 RID: 22421 RVA: 0x0019BB83 File Offset: 0x00199D83
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				this._currentCraftingOrder = this.GetDaggerCraftingOrder();
				this._playerAcceptedQuestLog = base.AddDiscreteLog(this.QuestStartedLog, new TextObject("{=scjHmuyF}Complete Crafting Orders", null), this._completedCraftingOrders, this._numberOfDaggersRequested, null, false);
			}

			// Token: 0x06005796 RID: 22422 RVA: 0x0019BBC4 File Offset: 0x00199DC4
			private void CheckIfPlayerReadyToReturnItems()
			{
				if (this._playerHasNeededItemsLog == null && this._playerAcceptedQuestLog.CurrentProgress >= this._numberOfDaggersRequested)
				{
					this._playerHasNeededItemsLog = base.AddLog(this.PlayerHasNeededItemsLogText, false);
					return;
				}
				if (this._playerHasNeededItemsLog != null && this._playerAcceptedQuestLog.CurrentProgress < this._numberOfDaggersRequested)
				{
					base.RemoveLog(this._playerHasNeededItemsLog);
					this._playerHasNeededItemsLog = null;
				}
			}

			// Token: 0x06005797 RID: 22423 RVA: 0x0019BC2E File Offset: 0x00199E2E
			protected override void OnTimedOut()
			{
				if (this._playerHasNeededItemsLog != null && this._playerHasNeededItemsLog.CurrentProgress >= this._numberOfDaggersRequested)
				{
					this.SucceedQuest();
					return;
				}
				this.FailQuest();
			}

			// Token: 0x06005798 RID: 22424 RVA: 0x0019BC58 File Offset: 0x00199E58
			private void SucceedQuest()
			{
				base.AddLog(this.QuestSuccessLog, false);
				this.RelationshipChangeWithQuestGiver = 8;
				base.QuestGiver.AddPower(15f);
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005799 RID: 22425 RVA: 0x0019BC85 File Offset: 0x00199E85
			private void FailQuest()
			{
				this.RelationshipChangeWithQuestGiver = -5;
				base.QuestGiver.AddPower(-10f);
				base.CompleteQuestWithFail(this.QuestFailedLog);
			}

			// Token: 0x0600579A RID: 22426 RVA: 0x0019BCAB File Offset: 0x00199EAB
			protected override void OnCompleteWithSuccess()
			{
				base.OnCompleteWithSuccess();
				if (this._currentCraftingOrder != null)
				{
					this._craftingBehavior.CancelCustomOrder(base.QuestGiver.CurrentSettlement.Town, this._currentCraftingOrder);
				}
			}

			// Token: 0x0600579B RID: 22427 RVA: 0x0019BCDC File Offset: 0x00199EDC
			public override void OnFailed()
			{
				base.OnFailed();
				if (this._currentCraftingOrder != null)
				{
					this._craftingBehavior.CancelCustomOrder(base.QuestGiver.CurrentSettlement.Town, this._currentCraftingOrder);
				}
			}

			// Token: 0x0600579C RID: 22428 RVA: 0x0019BD0D File Offset: 0x00199F0D
			public override void OnCanceled()
			{
				base.OnCanceled();
				if (this._currentCraftingOrder != null)
				{
					this._craftingBehavior.CancelCustomOrder(base.QuestGiver.CurrentSettlement.Town, this._currentCraftingOrder);
				}
			}

			// Token: 0x0600579D RID: 22429 RVA: 0x0019BD40 File Offset: 0x00199F40
			protected override void RegisterEvents()
			{
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnCraftingOrderCompletedEvent.AddNonSerializedListener(this, new Action<Town, CraftingOrder, ItemObject, Hero>(this.OnCraftingOrderCompleted));
				CampaignEvents.OnGameLoadFinishedEvent.AddNonSerializedListener(this, new Action(this.OnGameLoadFinished));
			}

			// Token: 0x0600579E RID: 22430 RVA: 0x0019BDAC File Offset: 0x00199FAC
			private void OnGameLoadFinished()
			{
				if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.3.2", 0))
				{
					foreach (KeyValuePair<ITrackableCampaignObject, List<QuestBase>> keyValuePair in Campaign.Current.QuestManager.TrackedObjects.ToMBList<KeyValuePair<ITrackableCampaignObject, List<QuestBase>>>())
					{
						if (keyValuePair.Key is CraftingOrder)
						{
							base.RemoveTrackedObject(keyValuePair.Key);
						}
					}
					if (this._currentCraftingOrder != null)
					{
						base.AddTrackedObject(this._currentCraftingOrder);
					}
				}
			}

			// Token: 0x0600579F RID: 22431 RVA: 0x0019BE58 File Offset: 0x0019A058
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (clan == Clan.PlayerClan && newKingdom != null && newKingdom.IsAtWarWith(base.QuestGiver.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x060057A0 RID: 22432 RVA: 0x0019BE84 File Offset: 0x0019A084
			private void OnCraftingOrderCompleted(Town town, CraftingOrder craftingOrder, ItemObject craftedItem, Hero completerHero)
			{
				if (craftingOrder == this._currentCraftingOrder)
				{
					this._completedCraftingOrders++;
					if (this._completedCraftingOrders <= this._numberOfDaggersRequested)
					{
						this._playerAcceptedQuestLog.UpdateCurrentProgress(this._completedCraftingOrders);
						this.CheckIfPlayerReadyToReturnItems();
						if (this._completedCraftingOrders == this._numberOfDaggersRequested)
						{
							TextObject textObject = new TextObject("{=T4q1DkfF}You have completed {QUEST_GIVER.NAME}'s request. You can go back to {QUEST_GIVER.NAME} and return the daggers.", null);
							textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
							MBInformationManager.AddQuickInformation(textObject, 3000, null, null, "");
							base.RemoveTrackedObject(this._currentCraftingOrder);
							this._currentCraftingOrder = null;
							return;
						}
						base.RemoveTrackedObject(this._currentCraftingOrder);
						this._currentCraftingOrder = this.GetDaggerCraftingOrder();
					}
				}
			}

			// Token: 0x060057A1 RID: 22433 RVA: 0x0019BF40 File Offset: 0x0019A140
			private CraftingOrder GetDaggerCraftingOrder()
			{
				CraftingTemplate templateFromId = CraftingTemplate.GetTemplateFromId("Dagger");
				CraftingOrder craftingOrder = this._craftingBehavior.CreateCustomOrderForHero(base.QuestGiver, this.GetCraftingDifficulty(), null, templateFromId);
				base.AddTrackedObject(craftingOrder);
				return craftingOrder;
			}

			// Token: 0x060057A2 RID: 22434 RVA: 0x0019BF7A File Offset: 0x0019A17A
			private float GetCraftingDifficulty()
			{
				return MathF.Clamp((float)MathF.Min(Hero.MainHero.GetSkillValue(DefaultSkills.Crafting), 100), 10f, 100f) + (float)MBRandom.RandomInt(-10, 10);
			}

			// Token: 0x060057A3 RID: 22435 RVA: 0x0019BFAD File Offset: 0x0019A1AD
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail declareWarDetail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, declareWarDetail, this.QuestCanceledWarDeclaredLog, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x060057A4 RID: 22436 RVA: 0x0019BFC5 File Offset: 0x0019A1C5
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				this._craftingBehavior = Campaign.Current.GetCampaignBehavior<ICraftingCampaignBehavior>();
				if (this._craftingBehavior != null)
				{
					CraftingOrder currentCraftingOrder = this._currentCraftingOrder;
					if (currentCraftingOrder == null || currentCraftingOrder.IsReady)
					{
						return;
					}
				}
				base.CompleteQuestWithCancel(null);
			}

			// Token: 0x060057A5 RID: 22437 RVA: 0x0019C003 File Offset: 0x0019A203
			protected override void HourlyTick()
			{
			}

			// Token: 0x04001C9F RID: 7327
			[SaveableField(1)]
			private readonly int _numberOfDaggersRequested;

			// Token: 0x04001CA0 RID: 7328
			[SaveableField(3)]
			private CraftingOrder _currentCraftingOrder;

			// Token: 0x04001CA1 RID: 7329
			[SaveableField(4)]
			private int _completedCraftingOrders;

			// Token: 0x04001CA2 RID: 7330
			[SaveableField(5)]
			private JournalLog _playerAcceptedQuestLog;

			// Token: 0x04001CA3 RID: 7331
			[SaveableField(6)]
			private JournalLog _playerHasNeededItemsLog;

			// Token: 0x04001CA4 RID: 7332
			private const int SuccessRelationBonus = 8;

			// Token: 0x04001CA5 RID: 7333
			private const int SuccessPowerBonus = 15;

			// Token: 0x04001CA6 RID: 7334
			private const int FailRelationPenalty = -5;

			// Token: 0x04001CA7 RID: 7335
			private const int FailPowerPenalty = -10;

			// Token: 0x04001CA8 RID: 7336
			private const int MaxCraftingOrderDifficulty = 100;

			// Token: 0x04001CA9 RID: 7337
			private const int CraftingOrderDifficultyVariance = 10;

			// Token: 0x04001CAA RID: 7338
			private const string DaggerCraftingTemplateId = "Dagger";

			// Token: 0x04001CAB RID: 7339
			private ICraftingCampaignBehavior _craftingBehavior;
		}

		// Token: 0x0200070A RID: 1802
		public class GangLeaderNeedsSpecialWeaponsIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x060057A8 RID: 22440 RVA: 0x0019C023 File Offset: 0x0019A223
			public GangLeaderNeedsSpecialWeaponsIssueTypeDefiner()
				: base(596061)
			{
			}

			// Token: 0x060057A9 RID: 22441 RVA: 0x0019C030 File Offset: 0x0019A230
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssue), 1, null);
				base.AddClassDefinition(typeof(GangLeaderNeedsSpecialWeaponsIssueBehavior.GangLeaderNeedsSpecialWeaponsIssueQuest), 2, null);
			}
		}
	}
}
