using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000366 RID: 870
	public class HeadmanNeedsToDeliverAHerdIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x06003388 RID: 13192 RVA: 0x000D4437 File Offset: 0x000D2637
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003389 RID: 13193 RVA: 0x000D4450 File Offset: 0x000D2650
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x0600338A RID: 13194 RVA: 0x000D4454 File Offset: 0x000D2654
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x0600338B RID: 13195 RVA: 0x000D44B8 File Offset: 0x000D26B8
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.CurrentSettlement != null && issueGiver.CurrentSettlement.IsVillage && HeadmanNeedsToDeliverAHerdIssueBehavior.IsVillageSuitableForIssue(issueGiver.CurrentSettlement.Village) && (issueGiver.IsHeadman || issueGiver.IsRuralNotable) && issueGiver.CurrentSettlement.Village.Bound.Notables.Count > 0 && issueGiver.CurrentSettlement.Village.Bound.Town.Security <= 60f;
		}

		// Token: 0x0600338C RID: 13196 RVA: 0x000D4540 File Offset: 0x000D2740
		private static bool IsVillageSuitableForIssue(Village village)
		{
			return !village.Bound.IsCastle && (village.VillageType == DefaultVillageTypes.BattanianHorseRanch || village.VillageType == DefaultVillageTypes.DesertHorseRanch || village.VillageType == DefaultVillageTypes.EuropeHorseRanch || village.VillageType == DefaultVillageTypes.SteppeHorseRanch || village.VillageType == DefaultVillageTypes.SturgianHorseRanch || village.VillageType == DefaultVillageTypes.VlandianHorseRanch || village.VillageType == DefaultVillageTypes.CattleRange || village.VillageType == DefaultVillageTypes.SheepFarm || village.VillageType == DefaultVillageTypes.HogFarm);
		}

		// Token: 0x0600338D RID: 13197 RVA: 0x000D45D3 File Offset: 0x000D27D3
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			this._headmanNeedsToDeliverAHerdIssue = new HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue(issueOwner);
			return this._headmanNeedsToDeliverAHerdIssue;
		}

		// Token: 0x04000EC4 RID: 3780
		private const IssueBase.IssueFrequency HeadmanNeedsToDeliverAHerdIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x04000EC5 RID: 3781
		[SaveableField(216)]
		private HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue _headmanNeedsToDeliverAHerdIssue;

		// Token: 0x02000716 RID: 1814
		public class HeadmanNeedsToDeliverAHerdIssue : IssueBase
		{
			// Token: 0x060058F5 RID: 22773 RVA: 0x001A0FEE File Offset: 0x0019F1EE
			internal static void AutoGeneratedStaticCollectObjectsHeadmanNeedsToDeliverAHerdIssue(object o, List<object> collectedObjects)
			{
				((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x060058F6 RID: 22774 RVA: 0x001A0FFC File Offset: 0x0019F1FC
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
				collectedObjects.Add(this._targetHero);
				collectedObjects.Add(this._herdTypeToDeliver);
			}

			// Token: 0x060058F7 RID: 22775 RVA: 0x001A1029 File Offset: 0x0019F229
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o)._targetSettlement;
			}

			// Token: 0x060058F8 RID: 22776 RVA: 0x001A1036 File Offset: 0x0019F236
			internal static object AutoGeneratedGetMemberValue_targetHero(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o)._targetHero;
			}

			// Token: 0x060058F9 RID: 22777 RVA: 0x001A1043 File Offset: 0x0019F243
			internal static object AutoGeneratedGetMemberValue_herdTypeToDeliver(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue)o)._herdTypeToDeliver;
			}

			// Token: 0x17001126 RID: 4390
			// (get) Token: 0x060058FA RID: 22778 RVA: 0x001A1050 File Offset: 0x0019F250
			private float MaxDistanceForSettlementSelection
			{
				get
				{
					return Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.Default) * 3.75f;
				}
			}

			// Token: 0x17001127 RID: 4391
			// (get) Token: 0x060058FB RID: 22779 RVA: 0x001A1063 File Offset: 0x0019F263
			private float MinDistanceForSettlementSelection
			{
				get
				{
					return Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.Default) * 1.5f;
				}
			}

			// Token: 0x17001128 RID: 4392
			// (get) Token: 0x060058FC RID: 22780 RVA: 0x001A1076 File Offset: 0x0019F276
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x17001129 RID: 4393
			// (get) Token: 0x060058FD RID: 22781 RVA: 0x001A1079 File Offset: 0x0019F279
			private int AnimalCountToDeliver
			{
				get
				{
					return (int)MathF.Clamp((float)MathF.Round(5000f * base.IssueDifficultyMultiplier / (float)this._herdTypeToDeliver.Value), 10f, 75f);
				}
			}

			// Token: 0x1700112A RID: 4394
			// (get) Token: 0x060058FE RID: 22782 RVA: 0x001A10AA File Offset: 0x0019F2AA
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 6 + MathF.Ceiling(14f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700112B RID: 4395
			// (get) Token: 0x060058FF RID: 22783 RVA: 0x001A10BF File Offset: 0x0019F2BF
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 5 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700112C RID: 4396
			// (get) Token: 0x06005900 RID: 22784 RVA: 0x001A10D4 File Offset: 0x0019F2D4
			protected override int RewardGold
			{
				get
				{
					return 300 + (int)((float)this._herdTypeToDeliver.Value * 0.75f * (float)this.AnimalCountToDeliver);
				}
			}

			// Token: 0x1700112D RID: 4397
			// (get) Token: 0x06005901 RID: 22785 RVA: 0x001A10F7 File Offset: 0x0019F2F7
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=kDIi3bLN}The village needs someone to take a herd to {TARGET_SETTLEMENT}.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x1700112E RID: 4398
			// (get) Token: 0x06005902 RID: 22786 RVA: 0x001A111C File Offset: 0x0019F31C
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=7H4HQNvF}Yes. Some of the families in this village need to raise a bit of money. [if:convo_calm_friendly][ib:normal2]They've put together a herd of {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} to sell in {TARGET_SETTLEMENT}, but with all the banditry on the roads, they can't drive it there on their own. We're not merchants or landowners. We can't afford any losses.", null);
					if (base.IssueOwner.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						textObject = new TextObject("{=6kJ31qut}Yeah, well, some people here are a bit short of money these days. [if:convo_calm_friendly][ib:normal]They've put together a herd of {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} to sell in {TARGET_SETTLEMENT}. But they're poor folks. Not really fighters, and they can't afford to hire guards. If they go there by themselves they'd be sitting ducks for any bandits.", null);
					}
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this.AnimalCountToDeliver);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					return textObject;
				}
			}

			// Token: 0x1700112F RID: 4399
			// (get) Token: 0x06005903 RID: 22787 RVA: 0x001A1199 File Offset: 0x0019F399
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=lmJYF6pQ}Tell me how I can help.", null);
				}
			}

			// Token: 0x17001130 RID: 4400
			// (get) Token: 0x06005904 RID: 22788 RVA: 0x001A11A8 File Offset: 0x0019F3A8
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=VbRyXBsv}If you're going in the direction of {TARGET_SETTLEMENT}, you can perhaps take our herd there to {TARGET_HERO.LINK}. I am willing to pay {REWARD_AMOUNT}{GOLD_ICON} if you deliver them safe and sound.[if:convo_calm_friendly][ib:normal]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("REWARD_AMOUNT", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001131 RID: 4401
			// (get) Token: 0x06005905 RID: 22789 RVA: 0x001A1214 File Offset: 0x0019F414
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=CqmoyrHH}You can assign a companion with {REQUIRED_SOLDIERS} men, they will be enough too. Both ways works fine for us. I promise if you or your men manage to deliver the herd safely, I will pay you {REWARD}{GOLD_ICON}. So what do you say?[if:convo_nonchalant]", null);
					textObject.SetTextVariable("REQUIRED_SOLDIERS", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001132 RID: 4402
			// (get) Token: 0x06005906 RID: 22790 RVA: 0x001A1264 File Offset: 0x0019F464
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=MJdVfS4z}Don't worry. I will deliver your {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} personally to {TARGET_HERO.LINK} in {TARGET_SETTLEMENT}.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this.AnimalCountToDeliver);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001133 RID: 4403
			// (get) Token: 0x06005907 RID: 22791 RVA: 0x001A12D8 File Offset: 0x0019F4D8
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=k8W02aj9}I will assign a companion with {NEEDED_MEN_COUNT} of my men to deliver {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} safely.", null);
					textObject.SetTextVariable("NEEDED_MEN_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this.AnimalCountToDeliver);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					return textObject;
				}
			}

			// Token: 0x17001134 RID: 4404
			// (get) Token: 0x06005908 RID: 22792 RVA: 0x001A132B File Offset: 0x0019F52B
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					TextObject textObject = new TextObject("{=mwpY5Ylb}I am still waiting for news from {TARGET_SETTLEMENT}. Once again, I appreciate that you could spare the men to do this.[if:convo_calm_friendly]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001135 RID: 4405
			// (get) Token: 0x06005909 RID: 22793 RVA: 0x001A1350 File Offset: 0x0019F550
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=BJxJwCc5}Thank you, {?PLAYER.GENDER}madam{?}sir{\\?}. Any brigands would be most unwise to tangle with you.", null);
					if (base.IssueOwner.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						textObject = new TextObject("{=muE5fcOf}Good. Anyone gives you trouble... Well, you look like you could handle them.", null);
					}
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001136 RID: 4406
			// (get) Token: 0x0600590A RID: 22794 RVA: 0x001A13A0 File Offset: 0x0019F5A0
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=m2h6zMp7}{ISSUE_GIVER.LINK}, the headman from {SETTLEMENT}, has asked you to deliver some of the village's livestock to {SETTLEMENT_TARGET}. The villagers can't afford their own guards and also can't afford any losses. {ISSUE_GIVER.LINK} offers {REWARD_AMOUNT}{GOLD_ICON} for the herd's delivery. You sent {COMPANION.LINK} with {NEEDED_MEN_COUNT} of your men to protect the herd. They should return to you with news of their success in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("SETTLEMENT_TARGET", this._targetSettlement.Name);
					textObject.SetTextVariable("NEEDED_MEN_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("REWARD_AMOUNT", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x17001137 RID: 4407
			// (get) Token: 0x0600590B RID: 22795 RVA: 0x001A146B File Offset: 0x0019F66B
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001138 RID: 4408
			// (get) Token: 0x0600590C RID: 22796 RVA: 0x001A146E File Offset: 0x0019F66E
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001139 RID: 4409
			// (get) Token: 0x0600590D RID: 22797 RVA: 0x001A1474 File Offset: 0x0019F674
			public override TextObject IssueAsRumorInSettlement
			{
				get
				{
					TextObject textObject = new TextObject("{=cvZH3cI1}I hope {QUEST_GIVER.NAME} has a plan to get that herd to market.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700113A RID: 4410
			// (get) Token: 0x0600590E RID: 22798 RVA: 0x001A14A6 File Offset: 0x0019F6A6
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700113B RID: 4411
			// (get) Token: 0x0600590F RID: 22799 RVA: 0x001A14BB File Offset: 0x0019F6BB
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=KhUkmIrH}Deliver the Herd to {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x06005910 RID: 22800 RVA: 0x001A14E0 File Offset: 0x0019F6E0
			public HeadmanNeedsToDeliverAHerdIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue <>4__this = this;
				Settlement settlement = SettlementHelper.FindRandomSettlement(delegate(Settlement x)
				{
					if (x.IsTown)
					{
						if (x.Notables.Any<Hero>((Hero y) => y.CanHaveCampaignIssues()) && !x.MapFaction.IsAtWarWith(issueOwner.MapFaction) && Campaign.Current.Models.MapDistanceModel.GetDistance(x, <>4__this.IssueSettlement, false, false, MobileParty.MainParty.NavigationCapability) > <>4__this.MinDistanceForSettlementSelection)
						{
							return Campaign.Current.Models.MapDistanceModel.GetDistance(x, <>4__this.IssueSettlement, false, false, MobileParty.MainParty.NavigationCapability) < <>4__this.MaxDistanceForSettlementSelection;
						}
					}
					return false;
				});
				this._targetSettlement = settlement ?? base.IssueSettlement.Village.Bound;
				this._herdTypeToDeliver = Campaign.Current.ObjectManager.GetObject<ItemObject>(this._possibleHerdTypes.GetRandomElement<string>());
				if (this._targetSettlement != null)
				{
					this._targetHero = this._targetSettlement.Notables.GetRandomElementWithPredicate<Hero>((Hero x) => x.CanHaveCampaignIssues()) ?? this._targetSettlement.Notables.GetRandomElement<Hero>();
				}
			}

			// Token: 0x06005911 RID: 22801 RVA: 0x001A15E1 File Offset: 0x0019F7E1
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementProsperity)
				{
					return -0.2f;
				}
				return 0f;
			}

			// Token: 0x06005912 RID: 22802 RVA: 0x001A15F6 File Offset: 0x0019F7F6
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Riding) >= hero.GetSkillValue(DefaultSkills.Scouting)) ? DefaultSkills.Riding : DefaultSkills.Scouting, 120);
			}

			// Token: 0x06005913 RID: 22803 RVA: 0x001A1623 File Offset: 0x0019F823
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005914 RID: 22804 RVA: 0x001A1634 File Offset: 0x0019F834
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x06005915 RID: 22805 RVA: 0x001A1644 File Offset: 0x0019F844
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid && this._targetHero.IsActive && base.IssueOwner.CurrentSettlement.Village.Bound.Town.Security <= 70f;
			}

			// Token: 0x06005916 RID: 22806 RVA: 0x001A16AD File Offset: 0x0019F8AD
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x06005917 RID: 22807 RVA: 0x001A16AF File Offset: 0x0019F8AF
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005918 RID: 22808 RVA: 0x001A16C9 File Offset: 0x0019F8C9
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.ApplySuccessRewards(base.IssueOwner);
			}

			// Token: 0x06005919 RID: 22809 RVA: 0x001A16D7 File Offset: 0x0019F8D7
			private void ApplySuccessRewards(Hero issueGiver)
			{
				issueGiver.AddPower(5f);
				this.RelationshipChangeWithIssueOwner = 5;
				issueGiver.CurrentSettlement.Village.Hearth += 50f;
			}

			// Token: 0x0600591A RID: 22810 RVA: 0x001A1707 File Offset: 0x0019F907
			protected override void OnGameLoad()
			{
			}

			// Token: 0x0600591B RID: 22811 RVA: 0x001A1709 File Offset: 0x0019F909
			protected override void HourlyTick()
			{
			}

			// Token: 0x0600591C RID: 22812 RVA: 0x001A170B File Offset: 0x0019F90B
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this.AnimalCountToDeliver, this._herdTypeToDeliver, this._targetSettlement, this.RewardGold, this._targetHero);
			}

			// Token: 0x0600591D RID: 22813 RVA: 0x001A1741 File Offset: 0x0019F941
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x0600591E RID: 22814 RVA: 0x001A1744 File Offset: 0x0019F944
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flag = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (issueGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x04001CFE RID: 7422
			private const int IssueDuration = 30;

			// Token: 0x04001CFF RID: 7423
			private const int QuestTimeLimit = 30;

			// Token: 0x04001D00 RID: 7424
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x04001D01 RID: 7425
			private const int RequiredSkillForSendingCompanion = 120;

			// Token: 0x04001D02 RID: 7426
			[CachedData]
			private readonly MBList<string> _possibleHerdTypes = new MBList<string> { "sheep", "cow", "hog" };

			// Token: 0x04001D03 RID: 7427
			[SaveableField(10)]
			private Settlement _targetSettlement;

			// Token: 0x04001D04 RID: 7428
			[SaveableField(20)]
			private Hero _targetHero;

			// Token: 0x04001D05 RID: 7429
			[SaveableField(30)]
			private ItemObject _herdTypeToDeliver;
		}

		// Token: 0x02000717 RID: 1815
		public class HeadmanNeedsToDeliverAHerdIssueQuest : QuestBase
		{
			// Token: 0x0600591F RID: 22815 RVA: 0x001A179D File Offset: 0x0019F99D
			internal static void AutoGeneratedStaticCollectObjectsHeadmanNeedsToDeliverAHerdIssueQuest(object o, List<object> collectedObjects)
			{
				((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005920 RID: 22816 RVA: 0x001A17AB File Offset: 0x0019F9AB
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
				collectedObjects.Add(this._targetHero);
				collectedObjects.Add(this._herdTypeToDeliver);
				collectedObjects.Add(this._playerStartsQuestLog);
			}

			// Token: 0x06005921 RID: 22817 RVA: 0x001A17E4 File Offset: 0x0019F9E4
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._targetSettlement;
			}

			// Token: 0x06005922 RID: 22818 RVA: 0x001A17F1 File Offset: 0x0019F9F1
			internal static object AutoGeneratedGetMemberValue_targetHero(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._targetHero;
			}

			// Token: 0x06005923 RID: 22819 RVA: 0x001A17FE File Offset: 0x0019F9FE
			internal static object AutoGeneratedGetMemberValue_herdTypeToDeliver(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._herdTypeToDeliver;
			}

			// Token: 0x06005924 RID: 22820 RVA: 0x001A180B File Offset: 0x0019FA0B
			internal static object AutoGeneratedGetMemberValue_animalCountToDeliver(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._animalCountToDeliver;
			}

			// Token: 0x06005925 RID: 22821 RVA: 0x001A181D File Offset: 0x0019FA1D
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._rewardGold;
			}

			// Token: 0x06005926 RID: 22822 RVA: 0x001A182F File Offset: 0x0019FA2F
			internal static object AutoGeneratedGetMemberValue_playerStartsQuestLog(object o)
			{
				return ((HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest)o)._playerStartsQuestLog;
			}

			// Token: 0x1700113C RID: 4412
			// (get) Token: 0x06005927 RID: 22823 RVA: 0x001A183C File Offset: 0x0019FA3C
			public sealed override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=KhUkmIrH}Deliver the Herd to {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700113D RID: 4413
			// (get) Token: 0x06005928 RID: 22824 RVA: 0x001A1860 File Offset: 0x0019FA60
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700113E RID: 4414
			// (get) Token: 0x06005929 RID: 22825 RVA: 0x001A1864 File Offset: 0x0019FA64
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=wsGDDXPN}{QUEST_GIVER.LINK}, the headman from {QUEST_GIVER_SETTLEMENT} has asked you to deliver {ANIMAL_COUNT_TO_DELIVER} {.%}{?ANIMAL_COUNT_TO_DELIVER > 1}{PLURAL(HERD_TYPE_TO_DELIVER)}{?}{HERD_TYPE_TO_DELIVER}{\\?}{.%} to {TARGET_HERO.LINK} in {TARGET_SETTLEMENT}. {?QUEST_GIVER.GENDER}She{?}He{\\?} fears such a large herd will attract attention from the brigands on the way. {QUEST_GIVER.LINK} offers {REWARD_AMOUNT}{GOLD_ICON} for the herd's delivery.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("TARGET_HERO", this._targetHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("ANIMAL_COUNT_TO_DELIVER", this._animalCountToDeliver);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("HERD_TYPE_TO_DELIVER", this._herdTypeToDeliver.Name);
					textObject.SetTextVariable("REWARD_AMOUNT", this._rewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x1700113F RID: 4415
			// (get) Token: 0x0600592A RID: 22826 RVA: 0x001A1930 File Offset: 0x0019FB30
			private TextObject SuccessQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=6IKKFH3A}You have received a message and a large purse from {QUEST_GIVER.LINK}. The missive reads: ”The herd is safe. Thank you, and please accept these {REWARD}{GOLD_ICON} with our gratitude.”.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REWARD", this._rewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001140 RID: 4416
			// (get) Token: 0x0600592B RID: 22827 RVA: 0x001A1988 File Offset: 0x0019FB88
			private TextObject FailByTimeOutQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=hhrRnSvr}You failed to deliver the herd in time, as {QUEST_GIVER.LINK} has asked of you. The shepherds and the herd left you.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001141 RID: 4417
			// (get) Token: 0x0600592C RID: 22828 RVA: 0x001A19CC File Offset: 0x0019FBCC
			private TextObject FailByRejectQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=MjwNHtQd}You rejected to deliver the herd, as {QUEST_GIVER.LINK} has asked of you. The shepherds have left you.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001142 RID: 4418
			// (get) Token: 0x0600592D RID: 22829 RVA: 0x001A1A10 File Offset: 0x0019FC10
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001143 RID: 4419
			// (get) Token: 0x0600592E RID: 22830 RVA: 0x001A1A44 File Offset: 0x0019FC44
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x0600592F RID: 22831 RVA: 0x001A1A78 File Offset: 0x0019FC78
			public HeadmanNeedsToDeliverAHerdIssueQuest(string questId, Hero questGiver, CampaignTime duration, int animalCountToDeliver, ItemObject herdTypeToDeliver, Settlement targetSettlement, int rewardGold, Hero targetHero)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._animalCountToDeliver = animalCountToDeliver;
				this._herdTypeToDeliver = herdTypeToDeliver;
				this._targetSettlement = targetSettlement;
				this._rewardGold = rewardGold;
				this._targetHero = targetHero;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005930 RID: 22832 RVA: 0x001A1AC4 File Offset: 0x0019FCC4
			protected override void SetDialogs()
			{
				TextObject textObject = new TextObject("{=iUQuwAZY}Thank you, {?PLAYER.GENDER}madam{?}sir{\\?}. The village will be grateful to you. Good luck.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(textObject, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=zB6elkn1}The herd is ready to depart.", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=8tBET7S5}Good. We will be heading out soon.", null), null, null, null)
					.NpcLine(new TextObject("{=iAGx49nO}Good to hear that! Safe journeys.[if:convo_approving]", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=EOaOlh39}In due time. Let's not be too hasty.", null), null, null, null)
					.NpcLine(new TextObject("{=79Te4duG}As you wish.[if:convo_normal][ib:demure]", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005931 RID: 22833 RVA: 0x001A1BD4 File Offset: 0x0019FDD4
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				this._playerStartsQuestLog = base.AddLog(this.PlayerStartsQuestLogText, false);
				this.AddHerdAndShepherdsToMainParty();
				base.AddTrackedObject(this._targetSettlement);
				base.AddTrackedObject(this._targetHero);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetDeliveryDialogFlow(), this);
			}

			// Token: 0x06005932 RID: 22834 RVA: 0x001A1C30 File Offset: 0x0019FE30
			protected override void OnCompleteWithSuccess()
			{
				base.QuestGiver.AddPower(5f);
				this.RelationshipChangeWithQuestGiver = 5;
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.QuestGiver.CurrentSettlement.Village.Hearth += 50f;
				this._targetSettlement.Town.Prosperity += 50f;
				int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._herdTypeToDeliver);
				int num = ((availableRequestedItemCountOnPlayer > this._animalCountToDeliver) ? this._animalCountToDeliver : availableRequestedItemCountOnPlayer);
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._herdTypeToDeliver)
					{
						int amount = itemRosterElement.Amount;
						if (amount >= num)
						{
							PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -num);
							this._targetSettlement.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, num);
							break;
						}
						num -= amount;
						PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -amount);
						this._targetSettlement.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, amount);
					}
				}
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
				base.AddLog(this.SuccessQuestLogText, false);
			}

			// Token: 0x06005933 RID: 22835 RVA: 0x001A1DCC File Offset: 0x0019FFCC
			protected override void OnFinalize()
			{
				base.RemoveTrackedObject(this._targetSettlement);
				base.RemoveTrackedObject(this._targetHero);
			}

			// Token: 0x06005934 RID: 22836 RVA: 0x001A1DE8 File Offset: 0x0019FFE8
			private DialogFlow GetDeliveryDialogFlow()
			{
				TextObject textObject = new TextObject("{=8nwZXNTk}About the task {QUEST_GIVER.LINK} gave me...", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				TextObject textObject2 = new TextObject("{=kwJBLl00}Yes {?PLAYER.GENDER}madam{?}sir{\\?}. Our mutual friend {QUEST_GIVER.LINK} sent word to us. {?QUEST_GIVER.GENDER}She{?}He{\\?} told us to expect you with {?QUEST_GIVER.GENDER}her{?}his{\\?} {HERD_AMOUNT} {.%}{?HERD_AMOUNT > 1}{PLURAL(HERD_TYPE)}{?}{HERD_TYPE}{\\?}{.%}.", null);
				TextObject textObject3 = new TextObject("{=vXCg3OYx}So, have you brought them?[if:convo_undecided_open]", null);
				textObject2.SetTextVariable("HERD_AMOUNT", this._animalCountToDeliver);
				textObject2.SetTextVariable("HERD_TYPE", this._herdTypeToDeliver.Name);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject2, false);
				TextObject textObject4 = new TextObject("{=wmZYHGb9}I brought {HERD_AMOUNT} {.%}{?HERD_AMOUNT > 1}{PLURAL(HERD_TYPE)}{?}{HERD_TYPE}{\\?}{.%} as we agreed.", null);
				textObject4.SetTextVariable("HERD_AMOUNT", this._animalCountToDeliver);
				textObject4.SetTextVariable("HERD_TYPE", this._herdTypeToDeliver.Name);
				TextObject textObject5 = new TextObject("{=VkUMPAfR}Thank you for your help. {QUEST_GIVER.LINK} will send your reward as soon as possible.[if:convo_calm_friendly][ib:demure]", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject5, false);
				TextObject textObject6 = new TextObject("{=1s54uxsA}Sorry. I don't have any animals for you this time.", null);
				TextObject textObject7 = new TextObject("{=1dUVrgQ8}I just hope you can deliver the herd soon.", null);
				TextObject textObject8 = new TextObject("{=HFZisEnI}I'm going to keep that herd for myself.", null);
				TextObject textObject9 = new TextObject("{=LpfQYLQo}What? That's straight-up theft. I guarantee you {QUEST_GIVER.LINK} will hear about this![if:convo_annoyed][ib:aggressive]", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject9, false);
				return DialogFlow.CreateDialogFlow("hero_main_options", 125).PlayerLine(textObject, null, null, null).Condition(() => Settlement.CurrentSettlement == this._targetSettlement && CharacterObject.OneToOneConversationCharacter.IsHero && CharacterObject.OneToOneConversationCharacter.HeroObject == this._targetHero)
					.NpcLine(textObject2, null, null, null, null)
					.NpcLine(textObject3, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject4, null, null, null)
					.Condition(delegate
					{
						int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._herdTypeToDeliver);
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("HERD_AMOUNT", this._animalCountToDeliver);
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("HERD_TYPE", this._herdTypeToDeliver.Name);
						return availableRequestedItemCountOnPlayer >= this._animalCountToDeliver;
					})
					.NpcLine(textObject5, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverHerdOnConsequence))
					.CloseDialog()
					.PlayerOption(textObject8, null, null, null)
					.NpcLine(textObject9, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverHerdRejectOnConsequence))
					.CloseDialog()
					.PlayerOption(textObject6, null, null, null)
					.NpcLine(textObject7, null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005935 RID: 22837 RVA: 0x001A1FF7 File Offset: 0x001A01F7
			private void DeliverHerdRejectOnConsequence()
			{
				base.CompleteQuestWithFail(null);
				ChangeCrimeRatingAction.Apply(base.QuestGiver.CurrentSettlement.MapFaction, 20f, true);
			}

			// Token: 0x06005936 RID: 22838 RVA: 0x001A201B File Offset: 0x001A021B
			private void DeliverHerdOnConsequence()
			{
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005937 RID: 22839 RVA: 0x001A2024 File Offset: 0x001A0224
			private int GetAvailableRequestedItemCountOnPlayer(ItemObject item)
			{
				int num = 0;
				foreach (ItemRosterElement itemRosterElement in PartyBase.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == item)
					{
						num += itemRosterElement.Amount;
					}
				}
				return num;
			}

			// Token: 0x06005938 RID: 22840 RVA: 0x001A2090 File Offset: 0x001A0290
			public override void OnCanceled()
			{
				int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer(this._herdTypeToDeliver);
				PartyBase.MainParty.ItemRoster.AddToCounts(this._herdTypeToDeliver, (availableRequestedItemCountOnPlayer > this._animalCountToDeliver) ? (-this._animalCountToDeliver) : (-availableRequestedItemCountOnPlayer));
			}

			// Token: 0x06005939 RID: 22841 RVA: 0x001A20D4 File Offset: 0x001A02D4
			protected override void OnTimedOut()
			{
				this.ApplyFailureEffects(true);
				base.AddLog(this.FailByTimeOutQuestLogText, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -10)
				});
				this.RemoveRemainingHorses();
			}

			// Token: 0x0600593A RID: 22842 RVA: 0x001A2111 File Offset: 0x001A0311
			public override void OnFailed()
			{
				this.ApplyFailureEffects(false);
				base.AddLog(this.FailByRejectQuestLogText, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -30)
				});
			}

			// Token: 0x0600593B RID: 22843 RVA: 0x001A2148 File Offset: 0x001A0348
			private void ApplyFailureEffects(bool isTimedOut = false)
			{
				base.QuestGiver.AddPower(-5f);
				this._targetSettlement.Town.Prosperity -= 10f;
				this.RelationshipChangeWithQuestGiver = (isTimedOut ? (-5) : (-10));
			}

			// Token: 0x0600593C RID: 22844 RVA: 0x001A2188 File Offset: 0x001A0388
			private void RemoveRemainingHorses()
			{
				int num = this._animalCountToDeliver;
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._herdTypeToDeliver)
					{
						int amount = itemRosterElement.Amount;
						if (amount >= num)
						{
							PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -num);
							break;
						}
						num -= amount;
						PartyBase.MainParty.ItemRoster.AddToCounts(itemRosterElement.EquipmentElement, -amount);
					}
				}
			}

			// Token: 0x0600593D RID: 22845 RVA: 0x001A223C File Offset: 0x001A043C
			private void AddHerdAndShepherdsToMainParty()
			{
				MobileParty.MainParty.ItemRoster.AddToCounts(this._herdTypeToDeliver, this._animalCountToDeliver);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, 5);
				TextObject textObject = new TextObject("{=GgBtpOEm}{.%}{ANIMAL_COUNT} {?ANIMAL_COUNT > 1}{PLURAL(ANIMAL_TYPE)}{?}{ANIMAL_TYPE}{\\?}{.%} added to your party.", null);
				textObject.SetTextVariable("ANIMAL_COUNT", this._animalCountToDeliver);
				textObject.SetTextVariable("ANIMAL_TYPE", this._herdTypeToDeliver.Name);
				MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
			}

			// Token: 0x0600593E RID: 22846 RVA: 0x001A22BC File Offset: 0x001A04BC
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetDeliveryDialogFlow(), this);
			}

			// Token: 0x0600593F RID: 22847 RVA: 0x001A22DA File Offset: 0x001A04DA
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005940 RID: 22848 RVA: 0x001A22DC File Offset: 0x001A04DC
			protected override void RegisterEvents()
			{
				CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, new Action<Hero, Hero, KillCharacterAction.KillCharacterActionDetail, bool>(this.OnHeroKilled));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			// Token: 0x06005941 RID: 22849 RVA: 0x001A2345 File Offset: 0x001A0545
			public override void OnHeroCanHaveCampaignIssuesInfoIsRequested(Hero hero, ref bool result)
			{
				if (hero == this._targetHero)
				{
					result = false;
				}
			}

			// Token: 0x06005942 RID: 22850 RVA: 0x001A2353 File Offset: 0x001A0553
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x17001144 RID: 4420
			// (get) Token: 0x06005943 RID: 22851 RVA: 0x001A2366 File Offset: 0x001A0566
			protected override TextObject TargetHeroDiedLogText
			{
				get
				{
					return new TextObject("{=m41vdhSR}{QUEST_TARGET.LINK} is no longer alive. It might not be your fault that you didn't get the herd to {?QUEST_TARGET.GENDER}her{?}him{\\?} in time, but many people will consider this breach of trust.", null);
				}
			}

			// Token: 0x06005944 RID: 22852 RVA: 0x001A2374 File Offset: 0x001A0574
			private void OnHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification)
			{
				if (victim == this._targetHero)
				{
					TextObject textObject = ((detail == KillCharacterAction.KillCharacterActionDetail.Lost) ? this.TargetHeroDisappearedLogText : this.TargetHeroDiedLogText);
					StringHelpers.SetCharacterProperties("QUEST_TARGET", this._targetHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					base.AddLog(textObject, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005945 RID: 22853 RVA: 0x001A23DD File Offset: 0x001A05DD
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x06005946 RID: 22854 RVA: 0x001A240C File Offset: 0x001A060C
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x04001D06 RID: 7430
			[SaveableField(10)]
			private readonly Settlement _targetSettlement;

			// Token: 0x04001D07 RID: 7431
			[SaveableField(20)]
			private readonly Hero _targetHero;

			// Token: 0x04001D08 RID: 7432
			[SaveableField(30)]
			private readonly ItemObject _herdTypeToDeliver;

			// Token: 0x04001D09 RID: 7433
			[SaveableField(40)]
			private readonly int _animalCountToDeliver;

			// Token: 0x04001D0A RID: 7434
			[SaveableField(70)]
			private int _rewardGold;

			// Token: 0x04001D0B RID: 7435
			[SaveableField(215)]
			private JournalLog _playerStartsQuestLog;
		}

		// Token: 0x02000718 RID: 1816
		public class HeadmanNeedsToDeliverAHerdIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x0600594B RID: 22859 RVA: 0x001A24DD File Offset: 0x001A06DD
			public HeadmanNeedsToDeliverAHerdIssueTypeDefiner()
				: base(430000)
			{
			}

			// Token: 0x0600594C RID: 22860 RVA: 0x001A24EA File Offset: 0x001A06EA
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssue), 1, null);
				base.AddClassDefinition(typeof(HeadmanNeedsToDeliverAHerdIssueBehavior.HeadmanNeedsToDeliverAHerdIssueQuest), 2, null);
			}
		}
	}
}
