using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000367 RID: 871
	public class HeadmanVillageNeedsDraughtAnimalsIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x0600338F RID: 13199 RVA: 0x000D45EF File Offset: 0x000D27EF
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003390 RID: 13200 RVA: 0x000D4608 File Offset: 0x000D2808
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x06003391 RID: 13201 RVA: 0x000D460C File Offset: 0x000D280C
		private bool ConditionsHold(Hero issueGiver)
		{
			if (issueGiver.CurrentSettlement != null && issueGiver.IsHeadman)
			{
				Village village = issueGiver.CurrentSettlement.Village;
				return (village.GetProsperityLevel() == SettlementComponent.ProsperityLevel.Low || village.GetProsperityLevel() == SettlementComponent.ProsperityLevel.Mid) && (village.VillageType == DefaultVillageTypes.IronMine || village.VillageType == DefaultVillageTypes.ClayMine || village.VillageType == DefaultVillageTypes.SaltMine || village.VillageType == DefaultVillageTypes.SilverMine || village.VillageType == DefaultVillageTypes.Lumberjack);
			}
			return false;
		}

		// Token: 0x06003392 RID: 13202 RVA: 0x000D4690 File Offset: 0x000D2890
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x06003393 RID: 13203 RVA: 0x000D46F4 File Offset: 0x000D28F4
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue(issueOwner);
		}

		// Token: 0x04000EC6 RID: 3782
		private const IssueBase.IssueFrequency HeadmanVillageNeedsDraughtAnimalsIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000719 RID: 1817
		public class HeadmanVillageNeedsDraughtAnimalsIssue : IssueBase
		{
			// Token: 0x0600594D RID: 22861 RVA: 0x001A2510 File Offset: 0x001A0710
			internal static void AutoGeneratedStaticCollectObjectsHeadmanVillageNeedsDraughtAnimalsIssue(object o, List<object> collectedObjects)
			{
				((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600594E RID: 22862 RVA: 0x001A251E File Offset: 0x001A071E
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._selectedAnimal);
			}

			// Token: 0x0600594F RID: 22863 RVA: 0x001A2533 File Offset: 0x001A0733
			internal static object AutoGeneratedGetMemberValue_selectedAnimal(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue)o)._selectedAnimal;
			}

			// Token: 0x06005950 RID: 22864 RVA: 0x001A2540 File Offset: 0x001A0740
			internal static object AutoGeneratedGetMemberValue_isQuestWithMeatOffer(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue)o)._isQuestWithMeatOffer;
			}

			// Token: 0x06005951 RID: 22865 RVA: 0x001A2552 File Offset: 0x001A0752
			internal static object AutoGeneratedGetMemberValue_requestedAnimalAmount(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue)o)._requestedAnimalAmount;
			}

			// Token: 0x17001145 RID: 4421
			// (get) Token: 0x06005952 RID: 22866 RVA: 0x001A2564 File Offset: 0x001A0764
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x17001146 RID: 4422
			// (get) Token: 0x06005953 RID: 22867 RVA: 0x001A2567 File Offset: 0x001A0767
			private ItemObject _meatItem
			{
				get
				{
					return Game.Current.ObjectManager.GetObject<ItemObject>("meat");
				}
			}

			// Token: 0x17001147 RID: 4423
			// (get) Token: 0x06005954 RID: 22868 RVA: 0x001A257D File Offset: 0x001A077D
			private int OfferedMeatAmount
			{
				get
				{
					return (300 + this._selectedAnimal.Value * this._requestedAnimalAmount) / this._meatItem.Value * 2;
				}
			}

			// Token: 0x17001148 RID: 4424
			// (get) Token: 0x06005955 RID: 22869 RVA: 0x001A25A5 File Offset: 0x001A07A5
			private int GoldRequiredForAlternativeSolution
			{
				get
				{
					return (int)((float)(this._selectedAnimal.Value * this._requestedAnimalAmount) * 0.7f);
				}
			}

			// Token: 0x17001149 RID: 4425
			// (get) Token: 0x06005956 RID: 22870 RVA: 0x001A25C1 File Offset: 0x001A07C1
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 3 + MathF.Ceiling(3f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700114A RID: 4426
			// (get) Token: 0x06005957 RID: 22871 RVA: 0x001A25D6 File Offset: 0x001A07D6
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 3 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700114B RID: 4427
			// (get) Token: 0x06005958 RID: 22872 RVA: 0x001A25EB File Offset: 0x001A07EB
			protected override int RewardGold
			{
				get
				{
					if (this._isQuestWithMeatOffer)
					{
						return 0;
					}
					return 500 + this._selectedAnimal.Value * this._requestedAnimalAmount;
				}
			}

			// Token: 0x1700114C RID: 4428
			// (get) Token: 0x06005959 RID: 22873 RVA: 0x001A260F File Offset: 0x001A080F
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=9nxTUZkO}We do have a problem. Last winter was hard on our animals. A number died from disease, and others were taken by wolves. We'd go to town to buy more, but, well, herds make a tempting target for bandits and we're not really suited to fight them. We can't afford to slaughter even the oldest and weakest of our animals because we need them to pull the plough. Maybe you can help us?[if:convo_grave][ib:demure2]", null);
				}
			}

			// Token: 0x1700114D RID: 4429
			// (get) Token: 0x0600595A RID: 22874 RVA: 0x001A261C File Offset: 0x001A081C
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=nvaLVB5f}Tell me your needs.", null);
				}
			}

			// Token: 0x1700114E RID: 4430
			// (get) Token: 0x0600595B RID: 22875 RVA: 0x001A262C File Offset: 0x001A082C
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject;
					if (this._isQuestWithMeatOffer)
					{
						textObject = new TextObject("{=aExKdXmx}We need {REQUESTED_ANIMAL_AMOUNT} {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}{.%}.[if:convo_normal][ib:demure] To be honest our village is poor and our coffers are empty. We can make payment only as meat - the meat of the old animals that we'll slaughter as soon as you bring us the new ones. We can offer {MEAT_AMOUNT} loads of meat, will you accept that, {?PLAYER.GENDER}madam{?}sir{\\?}?", null);
						textObject.SetTextVariable("MEAT_AMOUNT", this.OfferedMeatAmount);
					}
					else
					{
						textObject = new TextObject("{=TEhwK74M}We are willing to pay {REWARD}{GOLD_ICON} denars for {REQUESTED_ANIMAL_AMOUNT} healthy and strong [if:convo_normal][ib:demure]{.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}{.%}. Unlike us, I'm sure you can travel distant villages easily and find the finest and cheapest ones there.", null);
						textObject.SetTextVariable("REWARD", this.RewardGold);
					}
					textObject.SetTextVariable("REQUESTED_ANIMAL_AMOUNT", this._requestedAnimalAmount);
					textObject.SetTextVariable("SELECTED_ANIMAL", this._selectedAnimal.Name);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x1700114F RID: 4431
			// (get) Token: 0x0600595C RID: 22876 RVA: 0x001A26BA File Offset: 0x001A08BA
			public override TextObject IssuePlayerResponseAfterAlternativeExplanation
			{
				get
				{
					return new TextObject("{=qYSrlr4q}Maybe I should send one of my men to find the animals you need.", null);
				}
			}

			// Token: 0x17001150 RID: 4432
			// (get) Token: 0x0600595D RID: 22877 RVA: 0x001A26C8 File Offset: 0x001A08C8
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=bvEOmHWd}I think a man who knows how to trade alongside {ALTERNATIVE_TROOP_AMOUNT} [if:convo_undecided_open]fighters can get the job done without trouble. they will need {GOLD_REQUIRED_FOR_ALTERNATIVE_SOLUTION}{GOLD_ICON} denars to buy the animals. You or one of your companions, {?PLAYER.GENDER}madam{?}sir{\\?} - it doesn't matter for us as long as you find the animals we need...", null);
					textObject.SetTextVariable("ALTERNATIVE_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("GOLD_REQUIRED_FOR_ALTERNATIVE_SOLUTION", this.GoldRequiredForAlternativeSolution);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001151 RID: 4433
			// (get) Token: 0x0600595E RID: 22878 RVA: 0x001A2715 File Offset: 0x001A0915
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=iq3yEuO9}All right. I will bring your animals by myself.", null);
				}
			}

			// Token: 0x17001152 RID: 4434
			// (get) Token: 0x0600595F RID: 22879 RVA: 0x001A2722 File Offset: 0x001A0922
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=BMQQSeTp}I'm sure my men will find what you need and bring them to you in time.", null);
				}
			}

			// Token: 0x17001153 RID: 4435
			// (get) Token: 0x06005960 RID: 22880 RVA: 0x001A272F File Offset: 0x001A092F
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=D9LxQxNa}Thank you for your help {?PLAYER.GENDER}madam{?}sir{\\?}.[if:convo_bemused][ib:demure2] We will be waiting for your men. Good luck to you all.", null);
				}
			}

			// Token: 0x17001154 RID: 4436
			// (get) Token: 0x06005961 RID: 22881 RVA: 0x001A273C File Offset: 0x001A093C
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=jol73R8f}We are still waiting for your men to arrive, {?PLAYER.GENDER}ma'am{?}sir{\\?}. The village needs the animals they are bringing.", null);
				}
			}

			// Token: 0x17001155 RID: 4437
			// (get) Token: 0x06005962 RID: 22882 RVA: 0x001A2749 File Offset: 0x001A0949
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001156 RID: 4438
			// (get) Token: 0x06005963 RID: 22883 RVA: 0x001A274C File Offset: 0x001A094C
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001157 RID: 4439
			// (get) Token: 0x06005964 RID: 22884 RVA: 0x001A2750 File Offset: 0x001A0950
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=QJn8pbzh}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}{.%} for {?QUEST_GIVER.GENDER}her{?}his{\\?} village. {?QUEST_GIVER.GENDER}She{?}He{\\?} will pay you {REWARD} when the animals are delivered. You asked your {COMPANION.LINK} and {ALTERNATIVE_TROOP_AMOUNT} of your men to deliver {REQUESTED_ANIMAL_AMOUNT} {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}{.%} to {QUEST_GIVER.LINK}. They will rejoin your party in {RETURN_DAYS} days.", null);
					textObject.SetTextVariable("ALTERNATIVE_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("REQUESTED_ANIMAL_AMOUNT", this._requestedAnimalAmount);
					textObject.SetTextVariable("SELECTED_ANIMAL", this._selectedAnimal.Name);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					TextObject textObject2 = TextObject.GetEmpty();
					if (!this._isQuestWithMeatOffer)
					{
						textObject2 = new TextObject("{=OyOn7N84}{REWARD_GOLD}{GOLD_ICON} denars", null);
						textObject2.SetTextVariable("REWARD_GOLD", this.RewardGold);
						textObject2.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					}
					else
					{
						textObject2 = new TextObject("{=3bh1q4ZV}{MEAT_AMOUNT} meat", null);
						textObject2.SetTextVariable("MEAT_AMOUNT", this.OfferedMeatAmount);
					}
					textObject.SetTextVariable("REWARD", textObject2);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001158 RID: 4440
			// (get) Token: 0x06005965 RID: 22885 RVA: 0x001A2851 File Offset: 0x001A0A51
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=MXLcZPaO}Village Needs Draught Animals", null);
				}
			}

			// Token: 0x17001159 RID: 4441
			// (get) Token: 0x06005966 RID: 22886 RVA: 0x001A285E File Offset: 0x001A0A5E
			public override TextObject Description
			{
				get
				{
					return new TextObject("{=Ntv5KPFe}Headman in the village requested draught animals to replace them with old ones.", null);
				}
			}

			// Token: 0x06005967 RID: 22887 RVA: 0x001A286C File Offset: 0x001A0A6C
			public HeadmanVillageNeedsDraughtAnimalsIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				this._selectedAnimal = this._possibleAnimals.GetRandomElement<ItemObject>();
				this._isQuestWithMeatOffer = issueOwner.CurrentSettlement.Village.Hearth <= 300f;
				this._requestedAnimalAmount = MathF.Round((float)((int)(5000f / (float)this._selectedAnimal.Value)) * base.IssueDifficultyMultiplier);
			}

			// Token: 0x06005968 RID: 22888 RVA: 0x001A293A File Offset: 0x001A0B3A
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.VillageHearth)
				{
					return -0.2f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005969 RID: 22889 RVA: 0x001A295D File Offset: 0x001A0B5D
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x0600596A RID: 22890 RVA: 0x001A296E File Offset: 0x001A0B6E
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x0600596B RID: 22891 RVA: 0x001A297C File Offset: 0x001A0B7C
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Riding) >= hero.GetSkillValue(DefaultSkills.Trade)) ? DefaultSkills.Riding : DefaultSkills.Trade, 120);
			}

			// Token: 0x0600596C RID: 22892 RVA: 0x001A29A9 File Offset: 0x001A0BA9
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false) && QuestHelper.CheckGoldForAlternativeSolution(this.GoldRequiredForAlternativeSolution, out explanation);
			}

			// Token: 0x0600596D RID: 22893 RVA: 0x001A29D3 File Offset: 0x001A0BD3
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x0600596E RID: 22894 RVA: 0x001A29D6 File Offset: 0x001A0BD6
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid;
			}

			// Token: 0x0600596F RID: 22895 RVA: 0x001A29FF File Offset: 0x001A0BFF
			public override void AlternativeSolutionStartConsequence()
			{
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, null, this.GoldRequiredForAlternativeSolution, false);
			}

			// Token: 0x06005970 RID: 22896 RVA: 0x001A2A14 File Offset: 0x001A0C14
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005971 RID: 22897 RVA: 0x001A2A68 File Offset: 0x001A0C68
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005972 RID: 22898 RVA: 0x001A2A6A File Offset: 0x001A0C6A
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005973 RID: 22899 RVA: 0x001A2A6C File Offset: 0x001A0C6C
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this._selectedAnimal, this._requestedAnimalAmount, this._isQuestWithMeatOffer, this.OfferedMeatAmount, this.RewardGold);
			}

			// Token: 0x06005974 RID: 22900 RVA: 0x001A2AA2 File Offset: 0x001A0CA2
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x1700115A RID: 4442
			// (get) Token: 0x06005975 RID: 22901 RVA: 0x001A2AA4 File Offset: 0x001A0CA4
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06005976 RID: 22902 RVA: 0x001A2ABC File Offset: 0x001A0CBC
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				base.IssueOwner.AddPower(10f);
				ChangeRelationAction.ApplyPlayerRelation(base.IssueOwner, 5, true, true);
				base.IssueOwner.CurrentSettlement.Village.Hearth += 30f;
				if (this._isQuestWithMeatOffer)
				{
					ItemObject @object = Game.Current.ObjectManager.GetObject<ItemObject>("meat");
					MobileParty.MainParty.ItemRoster.AddToCounts(@object, this.OfferedMeatAmount);
				}
			}

			// Token: 0x04001D0C RID: 7436
			private const int IssueActiveTime = 30;

			// Token: 0x04001D0D RID: 7437
			private const int QuestDuration = 30;

			// Token: 0x04001D0E RID: 7438
			private const int VillageHearthConstant = 300;

			// Token: 0x04001D0F RID: 7439
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x04001D10 RID: 7440
			private const int CompanionRequiredSkillLevel = 120;

			// Token: 0x04001D11 RID: 7441
			[CachedData]
			private readonly MBList<ItemObject> _possibleAnimals = new MBList<ItemObject>
			{
				Game.Current.ObjectManager.GetObject<ItemObject>("cow"),
				Game.Current.ObjectManager.GetObject<ItemObject>("mule"),
				Game.Current.ObjectManager.GetObject<ItemObject>("sumpter_horse")
			};

			// Token: 0x04001D12 RID: 7442
			[SaveableField(1)]
			private ItemObject _selectedAnimal;

			// Token: 0x04001D13 RID: 7443
			[SaveableField(2)]
			private bool _isQuestWithMeatOffer;

			// Token: 0x04001D14 RID: 7444
			[SaveableField(3)]
			private int _requestedAnimalAmount;
		}

		// Token: 0x0200071A RID: 1818
		public class HeadmanVillageNeedsDraughtAnimalsIssueQuest : QuestBase
		{
			// Token: 0x06005977 RID: 22903 RVA: 0x001A2B3C File Offset: 0x001A0D3C
			internal static void AutoGeneratedStaticCollectObjectsHeadmanVillageNeedsDraughtAnimalsIssueQuest(object o, List<object> collectedObjects)
			{
				((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005978 RID: 22904 RVA: 0x001A2B4A File Offset: 0x001A0D4A
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._requestedAnimal);
				collectedObjects.Add(this._questProgressLogTest);
			}

			// Token: 0x06005979 RID: 22905 RVA: 0x001A2B6B File Offset: 0x001A0D6B
			internal static object AutoGeneratedGetMemberValue_requestedAnimal(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest)o)._requestedAnimal;
			}

			// Token: 0x0600597A RID: 22906 RVA: 0x001A2B78 File Offset: 0x001A0D78
			internal static object AutoGeneratedGetMemberValue_requestedAnimalAmount(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest)o)._requestedAnimalAmount;
			}

			// Token: 0x0600597B RID: 22907 RVA: 0x001A2B8A File Offset: 0x001A0D8A
			internal static object AutoGeneratedGetMemberValue_isQuestWithMeatOffer(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest)o)._isQuestWithMeatOffer;
			}

			// Token: 0x0600597C RID: 22908 RVA: 0x001A2B9C File Offset: 0x001A0D9C
			internal static object AutoGeneratedGetMemberValue_discountValue(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest)o)._discountValue;
			}

			// Token: 0x0600597D RID: 22909 RVA: 0x001A2BAE File Offset: 0x001A0DAE
			internal static object AutoGeneratedGetMemberValue_offeredMeatAmount(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest)o)._offeredMeatAmount;
			}

			// Token: 0x0600597E RID: 22910 RVA: 0x001A2BC0 File Offset: 0x001A0DC0
			internal static object AutoGeneratedGetMemberValue_questProgressLogTest(object o)
			{
				return ((HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest)o)._questProgressLogTest;
			}

			// Token: 0x1700115B RID: 4443
			// (get) Token: 0x0600597F RID: 22911 RVA: 0x001A2BCD File Offset: 0x001A0DCD
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=MXLcZPaO}Village Needs Draught Animals", null);
				}
			}

			// Token: 0x1700115C RID: 4444
			// (get) Token: 0x06005980 RID: 22912 RVA: 0x001A2BDA File Offset: 0x001A0DDA
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700115D RID: 4445
			// (get) Token: 0x06005981 RID: 22913 RVA: 0x001A2BE0 File Offset: 0x001A0DE0
			private TextObject QuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=V7YG3nKb}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}{.%} for {?QUEST_GIVER.GENDER}her{?}his{\\?} village. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to bring {REQUESTED_ANIMAL_AMOUNT} {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}{.%} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("REQUESTED_ANIMAL_AMOUNT", this._requestedAnimalAmount);
					textObject.SetTextVariable("SELECTED_ANIMAL", this._requestedAnimal.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700115E RID: 4446
			// (get) Token: 0x06005982 RID: 22914 RVA: 0x001A2C3C File Offset: 0x001A0E3C
			private TextObject QuestStartedLogTextWithMeat
			{
				get
				{
					TextObject textObject = new TextObject("{=7VUNi3zy}{QUEST_GIVER.LINK} will make payment as {MEAT_AMOUNT} meat when the task is done.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("MEAT_AMOUNT", this._offeredMeatAmount);
					return textObject;
				}
			}

			// Token: 0x1700115F RID: 4447
			// (get) Token: 0x06005983 RID: 22915 RVA: 0x001A2C80 File Offset: 0x001A0E80
			private TextObject QuestSuccessLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=uubL3Uck}You brought {REQUESTED_ANIMAL_AMOUNT} {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}{.%} to {?QUEST_GIVER.GENDER}her{?}him{\\?} as promised.", null);
					textObject.SetTextVariable("REQUESTED_ANIMAL_AMOUNT", this._requestedAnimalAmount);
					textObject.SetTextVariable("SELECTED_ANIMAL", this._requestedAnimal.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001160 RID: 4448
			// (get) Token: 0x06005984 RID: 22916 RVA: 0x001A2CDC File Offset: 0x001A0EDC
			private TextObject QuestStartedLogTextWithDenars
			{
				get
				{
					TextObject textObject = new TextObject("{=7LjTNs1k}{QUEST_GIVER.LINK} will pay you {REWARD_GOLD}{GOLD_ICON} denars when the task is done.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REWARD_GOLD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001161 RID: 4449
			// (get) Token: 0x06005985 RID: 22917 RVA: 0x001A2D34 File Offset: 0x001A0F34
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001162 RID: 4450
			// (get) Token: 0x06005986 RID: 22918 RVA: 0x001A2D68 File Offset: 0x001A0F68
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001163 RID: 4451
			// (get) Token: 0x06005987 RID: 22919 RVA: 0x001A2D9C File Offset: 0x001A0F9C
			private TextObject QuestGiverVillageRaided
			{
				get
				{
					TextObject textObject = new TextObject("{=gJG0xmAq}{QUEST_GIVER.LINK}'s village {QUEST_SETTLEMENT} was raided. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17001164 RID: 4452
			// (get) Token: 0x06005988 RID: 22920 RVA: 0x001A2DEC File Offset: 0x001A0FEC
			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=xvCzjcjU}You failed to deliver {REQUESTED_ANIMAL_AMOUNT} {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{REQUESTED_ANIMAL}{.s}{?}{REQUESTED_ANIMAL}{\\?}{.%} to {QUEST_GIVER.LINK} in time.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_ANIMAL_AMOUNT", this._requestedAnimalAmount);
					textObject.SetTextVariable("REQUESTED_ANIMAL", this._requestedAnimal.Name);
					return textObject;
				}
			}

			// Token: 0x06005989 RID: 22921 RVA: 0x001A2E48 File Offset: 0x001A1048
			public HeadmanVillageNeedsDraughtAnimalsIssueQuest(string questId, Hero giverHero, CampaignTime duration, ItemObject requestedAnimal, int requestedAnimalAmount, bool isQuestWithMeatOffer, int offeredMeatAmount, int rewardGold)
				: base(questId, giverHero, duration, rewardGold)
			{
				this._isQuestWithMeatOffer = isQuestWithMeatOffer;
				this._requestedAnimal = requestedAnimal;
				this._requestedAnimalAmount = requestedAnimalAmount;
				this._offeredMeatAmount = offeredMeatAmount;
				this.CalculateRequestedAnimalCountOnPlayer();
				this.SetDialogs();
				base.InitializeQuestOnCreation();
				if (!isQuestWithMeatOffer && MBRandom.RandomFloat <= 0.7f)
				{
					this._discountValue = (int)((float)this.RewardGold * 0.3f);
				}
			}

			// Token: 0x0600598A RID: 22922 RVA: 0x001A2EB8 File Offset: 0x001A10B8
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddTrackedObject(base.QuestGiver.CurrentSettlement);
				TextObject textObject = new TextObject("{=yc9rGlzb}Ready to deliver {.%}{?(REQUESTED_ANIMAL_AMOUNT > 1)}{PLURAL(SELECTED_ANIMAL)}{?}{SELECTED_ANIMAL}{\\?}:{.%}", null);
				textObject.SetTextVariable("SELECTED_ANIMAL", this._requestedAnimal.Name);
				textObject.SetTextVariable("REQUESTED_ANIMAL_AMOUNT", this._requestedAnimalAmount);
				this._questProgressLogTest = base.AddDiscreteLog(this.QuestStartedLogText, textObject, this._currentAnimalAmount, this._requestedAnimalAmount, null, false);
				base.AddLog(this._isQuestWithMeatOffer ? this.QuestStartedLogTextWithMeat : this.QuestStartedLogTextWithDenars, false);
			}

			// Token: 0x0600598B RID: 22923 RVA: 0x001A2F50 File Offset: 0x001A1150
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=msDCQIY7}Thank you, {?PLAYER.GENDER}madam{?}sir{\\?}. [if:convo_grateful][ib:confident]In these hard times, people like you are a gift from Heaven… The village will never forget that you were willing to help. Good luck.", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == this.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				TextObject textObject = new TextObject("{=rRGbn0Sm}Thank you {?PLAYER.GENDER}madam{?}sir{\\?}. [if:convo_focused_happy][ib:normal]You did a great favor to people of {ISSUE_VILLAGE}.", null);
				textObject.SetTextVariable("ISSUE_VILLAGE", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
				TextObject npcDiscountLine = new TextObject("{=p9rzYV4T}Things have gotten worse for the village, [if:convo_dismayed][ib:nervous2]since we last met {?PLAYER.GENDER}madam{?}sir{\\?}. Is it possible that we could pay you a bit less, what about {DISCOUNTED_REWARD}{GOLD_ICON} denars?", null);
				TextObject textObject2 = new TextObject("{=4kealpZK}Have you brought the animals {?PLAYER.GENDER}madam{?}sir{\\?}?", null);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject2, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == this.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=CjuVoxaC}Yes, Here are your animals.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerHasEnoughAnimals))
					.BeginNpcOptions(null, false)
					.NpcOption(npcDiscountLine, delegate
					{
						if (this._discountValue > 0)
						{
							npcDiscountLine.SetTextVariable("DISCOUNTED_REWARD", this.RewardGold - this._discountValue);
							npcDiscountLine.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
							return true;
						}
						return false;
					}, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=KBmAqg54}No problem, you can pay what you can afford.", null), null, null, null)
					.NpcLine(textObject, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestSuccessPlayerDeliveredAnimalsWithAcceptingDiscount))
					.CloseDialog()
					.PlayerOption(new TextObject("{=kYc90hEl}Sorry, but the price is what we agreed on. I can't lower it.", null), null, null, null)
					.NpcLine(new TextObject("{=r4pLtP5V}You're right. We agreed on this price. Thank you for your efforts.[if:convo_nervous][ib:normal]", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestSuccessPlayerDeliveredAnimalsWithoutAcceptingDiscount))
					.CloseDialog()
					.EndPlayerOptions()
					.NpcOption(new TextObject("{=l8ezl95j}Thank you {?PLAYER.GENDER}madam{?}sir{\\?}.[if:convo_calm_friendly] Here is what we promised.", null), null, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestSuccessPlayerDeliveredAnimalsNormal))
					.CloseDialog()
					.EndNpcOptions()
					.PlayerOption(new TextObject("{=PI6ikMsc}I'm working on it.", null), null, null, null)
					.NpcLine(new TextObject("{=4MQQf3wp}We are waiting for your arrival. ", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions();
			}

			// Token: 0x0600598C RID: 22924 RVA: 0x001A3154 File Offset: 0x001A1354
			private void CalculateRequestedAnimalCountOnPlayer()
			{
				int num = 0;
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._requestedAnimal)
					{
						num += itemRosterElement.Amount;
					}
				}
				this._currentAnimalAmount = num;
			}

			// Token: 0x0600598D RID: 22925 RVA: 0x001A31C8 File Offset: 0x001A13C8
			private bool CheckIfPlayerHasEnoughAnimals()
			{
				this.CalculateRequestedAnimalCountOnPlayer();
				return this._currentAnimalAmount >= this._requestedAnimalAmount;
			}

			// Token: 0x0600598E RID: 22926 RVA: 0x001A31E1 File Offset: 0x001A13E1
			private void QuestSuccessPlayerDeliveredAnimalsNormal()
			{
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, 5, true, true);
				base.QuestGiver.CurrentSettlement.Village.Hearth += 30f;
				this.ApplyRewards(false);
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x0600598F RID: 22927 RVA: 0x001A3220 File Offset: 0x001A1420
			private void QuestSuccessPlayerDeliveredAnimalsWithAcceptingDiscount()
			{
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, 8, true, true);
				TraitLevelingHelper.OnIssueSolvedThroughBetrayal(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Mercy, 30)
				});
				base.QuestGiver.CurrentSettlement.Village.Hearth += 80f;
				this.ApplyRewards(true);
				foreach (Hero hero in base.QuestGiver.CurrentSettlement.Notables)
				{
					if (hero != base.QuestGiver)
					{
						ChangeRelationAction.ApplyPlayerRelation(hero, 3, true, true);
					}
				}
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005990 RID: 22928 RVA: 0x001A32E4 File Offset: 0x001A14E4
			private void QuestSuccessPlayerDeliveredAnimalsWithoutAcceptingDiscount()
			{
				TraitLevelingHelper.OnIssueSolvedThroughBetrayal(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Mercy, -20)
				});
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, 5, true, true);
				base.QuestGiver.CurrentSettlement.Village.Hearth += 50f;
				this.ApplyRewards(false);
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005991 RID: 22929 RVA: 0x001A3350 File Offset: 0x001A1550
			private void ApplyRewards(bool applyDiscount)
			{
				if (this._isQuestWithMeatOffer)
				{
					ItemObject @object = Game.Current.ObjectManager.GetObject<ItemObject>("meat");
					MobileParty.MainParty.ItemRoster.AddToCounts(@object, this._offeredMeatAmount);
					using (List<Hero>.Enumerator enumerator = base.QuestGiver.CurrentSettlement.Notables.GetEnumerator())
					{
						while (enumerator.MoveNext())
						{
							Hero hero = enumerator.Current;
							if (hero != base.QuestGiver)
							{
								ChangeRelationAction.ApplyPlayerRelation(hero, 3, true, true);
							}
						}
						return;
					}
				}
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, applyDiscount ? (this.RewardGold - this._discountValue) : this.RewardGold, false);
			}

			// Token: 0x06005992 RID: 22930 RVA: 0x001A3410 File Offset: 0x001A1610
			protected override void OnCompleteWithSuccess()
			{
				base.AddLog(this.QuestSuccessLogText, false);
				MobileParty.MainParty.ItemRoster.FindIndexOfItem(this._requestedAnimal);
				int num = 0;
				for (int i = MobileParty.MainParty.ItemRoster.Count - 1; i >= 0; i--)
				{
					ItemRosterElement itemRosterElement = MobileParty.MainParty.ItemRoster[i];
					if (itemRosterElement.EquipmentElement.Item == this._requestedAnimal)
					{
						int num2 = ((itemRosterElement.Amount >= this._requestedAnimalAmount) ? (this._requestedAnimalAmount - num) : itemRosterElement.Amount);
						EquipmentElement equipmentElement = new EquipmentElement(itemRosterElement.EquipmentElement.Item, itemRosterElement.EquipmentElement.ItemModifier, null, false);
						MobileParty.MainParty.ItemRoster.AddToCounts(equipmentElement, -num2);
						num += itemRosterElement.Amount;
						if (num >= this._requestedAnimalAmount)
						{
							break;
						}
					}
				}
				TraitLevelingHelper.OnIssueSolvedThroughBetrayal(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.QuestGiver.AddPower(10f);
			}

			// Token: 0x06005993 RID: 22931 RVA: 0x001A3530 File Offset: 0x001A1730
			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				base.QuestGiver.AddPower(-10f);
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, -5, true, true);
				base.QuestGiver.CurrentSettlement.Village.Hearth -= 30f;
			}

			// Token: 0x06005994 RID: 22932 RVA: 0x001A358B File Offset: 0x001A178B
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005995 RID: 22933 RVA: 0x001A3590 File Offset: 0x001A1790
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.VillageBeingRaided.AddNonSerializedListener(this, new Action<Village>(this.OnVillageRaided));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnPlayerInventoryExchange));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			// Token: 0x06005996 RID: 22934 RVA: 0x001A3610 File Offset: 0x001A1810
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005997 RID: 22935 RVA: 0x001A3624 File Offset: 0x001A1824
			private void OnPlayerInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				int num = 0;
				foreach (ValueTuple<ItemRosterElement, int> valueTuple in purchasedItems)
				{
					ItemRosterElement itemRosterElement = valueTuple.Item1;
					if (itemRosterElement.EquipmentElement.Item == this._requestedAnimal)
					{
						int num2 = num;
						itemRosterElement = valueTuple.Item1;
						num = num2 + itemRosterElement.Amount;
					}
				}
				foreach (ValueTuple<ItemRosterElement, int> valueTuple2 in soldItems)
				{
					ItemRosterElement itemRosterElement = valueTuple2.Item1;
					if (itemRosterElement.EquipmentElement.Item == this._requestedAnimal)
					{
						int num3 = num;
						itemRosterElement = valueTuple2.Item1;
						num = num3 - itemRosterElement.Amount;
					}
				}
				this._currentAnimalAmount += num;
				this._currentAnimalAmount = (int)MathF.Clamp((float)this._currentAnimalAmount, 0f, (float)this._requestedAnimalAmount);
				this._questProgressLogTest.UpdateCurrentProgress(this._currentAnimalAmount);
			}

			// Token: 0x06005998 RID: 22936 RVA: 0x001A3744 File Offset: 0x001A1944
			private void OnVillageRaided(Village village)
			{
				if (village == base.QuestGiver.CurrentSettlement.Village)
				{
					base.AddLog(this.QuestGiverVillageRaided, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005999 RID: 22937 RVA: 0x001A376E File Offset: 0x001A196E
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x0600599A RID: 22938 RVA: 0x001A379D File Offset: 0x001A199D
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x0600599B RID: 22939 RVA: 0x001A37B5 File Offset: 0x001A19B5
			protected override void OnFinalize()
			{
			}

			// Token: 0x0600599C RID: 22940 RVA: 0x001A37B7 File Offset: 0x001A19B7
			protected override void InitializeQuestOnGameLoad()
			{
				this.CalculateRequestedAnimalCountOnPlayer();
				this.SetDialogs();
			}

			// Token: 0x04001D15 RID: 7445
			[SaveableField(1)]
			private ItemObject _requestedAnimal;

			// Token: 0x04001D16 RID: 7446
			[SaveableField(2)]
			private int _requestedAnimalAmount;

			// Token: 0x04001D17 RID: 7447
			private int _currentAnimalAmount;

			// Token: 0x04001D18 RID: 7448
			[SaveableField(3)]
			private bool _isQuestWithMeatOffer;

			// Token: 0x04001D19 RID: 7449
			[SaveableField(4)]
			private int _discountValue;

			// Token: 0x04001D1A RID: 7450
			[SaveableField(5)]
			private int _offeredMeatAmount;

			// Token: 0x04001D1B RID: 7451
			[SaveableField(6)]
			private JournalLog _questProgressLogTest;
		}

		// Token: 0x0200071B RID: 1819
		public class HeadmanVillageNeedsDraughtAnimalsIssueBehaviorTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x0600599D RID: 22941 RVA: 0x001A37C5 File Offset: 0x001A19C5
			public HeadmanVillageNeedsDraughtAnimalsIssueBehaviorTypeDefiner()
				: base(812000)
			{
			}

			// Token: 0x0600599E RID: 22942 RVA: 0x001A37D2 File Offset: 0x001A19D2
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssue), 1, null);
				base.AddClassDefinition(typeof(HeadmanVillageNeedsDraughtAnimalsIssueBehavior.HeadmanVillageNeedsDraughtAnimalsIssueQuest), 2, null);
			}
		}
	}
}
