using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x0200036A RID: 874
	public class LandlordNeedsAccessToVillageCommonsIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060033A4 RID: 13220 RVA: 0x000D4B58 File Offset: 0x000D2D58
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060033A5 RID: 13221 RVA: 0x000D4B71 File Offset: 0x000D2D71
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x060033A6 RID: 13222 RVA: 0x000D4B74 File Offset: 0x000D2D74
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssue), IssueBase.IssueFrequency.Common, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssue), IssueBase.IssueFrequency.Common));
		}

		// Token: 0x060033A7 RID: 13223 RVA: 0x000D4BD8 File Offset: 0x000D2DD8
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.CurrentSettlement != null && issueGiver.CurrentSettlement.IsVillage && !issueGiver.CurrentSettlement.IsUnderRaid && issueGiver.CurrentSettlement.Village.VillageType == DefaultVillageTypes.WheatFarm && issueGiver.IsRuralNotable && !Clan.BanditFactions.IsEmpty<Clan>() && issueGiver.GetTraitLevel(DefaultTraits.Mercy) <= 0 && issueGiver.GetTraitLevel(DefaultTraits.Generosity) <= 0 && issueGiver.CurrentSettlement.Village.Bound.Town.Security <= 70f && issueGiver.CurrentSettlement.Village.Bound.BoundVillages.Any<Village>(delegate(Village x)
			{
				if (x.Settlement != issueGiver.CurrentSettlement && !x.Settlement.IsUnderRaid)
				{
					return x.Settlement.Notables.Any<Hero>((Hero notable) => notable.IsHeadman && notable.CanHaveCampaignIssues());
				}
				return false;
			});
		}

		// Token: 0x060033A8 RID: 13224 RVA: 0x000D4CE0 File Offset: 0x000D2EE0
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssue(issueOwner);
		}

		// Token: 0x04000ECB RID: 3787
		private const IssueBase.IssueFrequency LandlordNeedsAccessToVillageCommonsIssueFrequency = IssueBase.IssueFrequency.Common;

		// Token: 0x02000722 RID: 1826
		public class LandlordNeedsAccessToVillageCommonsIssue : IssueBase
		{
			// Token: 0x06005A46 RID: 23110 RVA: 0x001A5E33 File Offset: 0x001A4033
			internal static void AutoGeneratedStaticCollectObjectsLandlordNeedsAccessToVillageCommonsIssue(object o, List<object> collectedObjects)
			{
				((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005A47 RID: 23111 RVA: 0x001A5E41 File Offset: 0x001A4041
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
			}

			// Token: 0x06005A48 RID: 23112 RVA: 0x001A5E56 File Offset: 0x001A4056
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssue)o)._targetSettlement;
			}

			// Token: 0x17001194 RID: 4500
			// (get) Token: 0x06005A49 RID: 23113 RVA: 0x001A5E63 File Offset: 0x001A4063
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Casualties | IssueBase.AlternativeSolutionScaleFlag.FailureRisk;
				}
			}

			// Token: 0x17001195 RID: 4501
			// (get) Token: 0x06005A4A RID: 23114 RVA: 0x001A5E67 File Offset: 0x001A4067
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 3 + MathF.Ceiling(4f + base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001196 RID: 4502
			// (get) Token: 0x06005A4B RID: 23115 RVA: 0x001A5E7C File Offset: 0x001A407C
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 2 + MathF.Ceiling(4f + base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001197 RID: 4503
			// (get) Token: 0x06005A4C RID: 23116 RVA: 0x001A5E91 File Offset: 0x001A4091
			protected override int RewardGold
			{
				get
				{
					return (int)(250f + 1000f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001198 RID: 4504
			// (get) Token: 0x06005A4D RID: 23117 RVA: 0x001A5EA8 File Offset: 0x001A40A8
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=6OKW8Ba3}{ISSUE_GIVER.LINK}, a landowner from {ISSUE_GIVER_SETTLEMENT}, has told you about {?ISSUE_GIVER.GENDER}her{?}his{\\?} problems with the herders of {TARGET_SETTLEMENT}. Apparently {?ISSUE_GIVER.GENDER}she{?}he{\\?} purchased the right to use a pasture near the village. But some local herders refuse to clear out and are causing problems for {?ISSUE_GIVER.GENDER}her{?}his{\\?} herdsmen. You have agreed to send {COMPANION.LINK} along with {NEEDED_MEN_COUNT} of your men to take care of the situation. You expect them to return in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					textObject.SetTextVariable("ISSUE_GIVER_SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("NEEDED_MEN_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x17001199 RID: 4505
			// (get) Token: 0x06005A4E RID: 23118 RVA: 0x001A5F50 File Offset: 0x001A4150
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=jYHKGhnc}Landlord Needs Access to the {TARGET_SETTLEMENT} Commons", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700119A RID: 4506
			// (get) Token: 0x06005A4F RID: 23119 RVA: 0x001A5F74 File Offset: 0x001A4174
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=XXac5fMa}A landowner needs your help in a dispute with herders from nearby {TARGET_SETTLEMENT}. They won't let {?ISSUE_GIVER.GENDER}her{?}his{\\?} herdsmen use pastures {?ISSUE_GIVER.GENDER}she{?}he{\\?} bought.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700119B RID: 4507
			// (get) Token: 0x06005A50 RID: 23120 RVA: 0x001A5F98 File Offset: 0x001A4198
			public override TextObject IssueAsRumorInSettlement
			{
				get
				{
					TextObject textObject = new TextObject("{=nxyXKy2z}Old {QUEST_GIVER.NAME} has got some problems with those herders over in {TARGET_SETTLEMENT}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700119C RID: 4508
			// (get) Token: 0x06005A51 RID: 23121 RVA: 0x001A5FE4 File Offset: 0x001A41E4
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=DUB6zfSe}I have a bit of a dispute with {TARGET_SETTLEMENT}. I recently purchased the right to graze cattle in the nearby pastures from a landowner there. But now some of the herders are making problems.[if:convo_thinking][ib:closed]", null);
					if (base.IssueOwner.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						textObject = new TextObject("{=0TyPBryV}I recently bought the right to graze cattle near the village of {TARGET_SETTLEMENT}. Good pastureland is hard to find. But now the locals are giving my herdsmen trouble.[if:convo_thinking][ib:closed]", null);
					}
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700119D RID: 4509
			// (get) Token: 0x06005A52 RID: 23122 RVA: 0x001A6038 File Offset: 0x001A4238
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=TXDjKUNf}What's the problem?", null);
				}
			}

			// Token: 0x1700119E RID: 4510
			// (get) Token: 0x06005A53 RID: 23123 RVA: 0x001A6048 File Offset: 0x001A4248
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=Je7SWXK3}They claim that I don't have the right to graze there, that village land can't be bought and sold like that. But look, I spent my silver. I won't get it back. Meanwhile, I can't afford to wait. I need someone to ride along with my herdsmen and my cattle can graze, one way or the other, even if it means violence. I can't let my herd just starve.[if:convo_bored][ib:hip]", null);
					if (base.IssueOwner.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						textObject = new TextObject("{=5ehlbXm6}They don't want to share the pastures. But I spent my silver, and I hold the title deed. I need someone to ride along with my herdsmen and clear off anyone who gets in their way.[if:convo_stern][ib:hip]", null);
					}
					return textObject;
				}
			}

			// Token: 0x1700119F RID: 4511
			// (get) Token: 0x06005A54 RID: 23124 RVA: 0x001A6088 File Offset: 0x001A4288
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=wodLHjnh}You or one of your companions with some {ALTERNATIVE_TROOP_AMOUNT} men should do the job. Either way I am willing to pay you {REWARD}{GOLD_ICON}. I doubt they'd stand up long to real warriors.[if:convo_mocking_teasing][ib:closed2]", null);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("ALTERNATIVE_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170011A0 RID: 4512
			// (get) Token: 0x06005A55 RID: 23125 RVA: 0x001A60D5 File Offset: 0x001A42D5
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x170011A1 RID: 4513
			// (get) Token: 0x06005A56 RID: 23126 RVA: 0x001A60D8 File Offset: 0x001A42D8
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170011A2 RID: 4514
			// (get) Token: 0x06005A57 RID: 23127 RVA: 0x001A60DB File Offset: 0x001A42DB
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=GOkjJwZr}I can get your herdsmen to the pastures.", null);
				}
			}

			// Token: 0x170011A3 RID: 4515
			// (get) Token: 0x06005A58 RID: 23128 RVA: 0x001A60E8 File Offset: 0x001A42E8
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=QO0EX2O3}Sure. I can order one of my companions and {TROOP_AMOUNT} men to escort your herds to pasture in {TARGET_SETTLEMENT}.", null);
					textObject.SetTextVariable("TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x170011A4 RID: 4516
			// (get) Token: 0x06005A59 RID: 23129 RVA: 0x001A611E File Offset: 0x001A431E
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					TextObject textObject = new TextObject("{=BH17ZNSe}I don't think we'll have any more problems at {TARGET_SETTLEMENT}, thanks to your men. Please give them our thanks, {?PLAYER.GENDER}madam{?}sir{\\?}.[if:convo_mocking_teasing][ib:hip]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x170011A5 RID: 4517
			// (get) Token: 0x06005A5A RID: 23130 RVA: 0x001A6144 File Offset: 0x001A4344
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=8INOZiew}Thank you, [if:convo_normal][ib:confident]both for looking out for my interests and upholding the law.", null);
					if (base.IssueOwner.CharacterObject.GetPersona() == DefaultTraits.PersonaCurt)
					{
						textObject = new TextObject("{=UsuOXc25}Thanks. [if:convo_stern][ib:closed]Show those troublemakers that the law is the law.", null);
					}
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011A6 RID: 4518
			// (get) Token: 0x06005A5B RID: 23131 RVA: 0x001A6193 File Offset: 0x001A4393
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(700f + 900f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06005A5C RID: 23132 RVA: 0x001A61A8 File Offset: 0x001A43A8
			public LandlordNeedsAccessToVillageCommonsIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(15f))
			{
			}

			// Token: 0x06005A5D RID: 23133 RVA: 0x001A61BB File Offset: 0x001A43BB
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementSecurity)
				{
					return -1f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005A5E RID: 23134 RVA: 0x001A61E0 File Offset: 0x001A43E0
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				int skillValue = hero.GetSkillValue(DefaultSkills.OneHanded);
				int skillValue2 = hero.GetSkillValue(DefaultSkills.TwoHanded);
				int skillValue3 = hero.GetSkillValue(DefaultSkills.Polearm);
				if (skillValue >= skillValue2 && skillValue >= skillValue3)
				{
					return new ValueTuple<SkillObject, int>(DefaultSkills.OneHanded, 150);
				}
				return new ValueTuple<SkillObject, int>((skillValue2 >= skillValue3) ? DefaultSkills.TwoHanded : DefaultSkills.Polearm, 150);
			}

			// Token: 0x06005A5F RID: 23135 RVA: 0x001A6243 File Offset: 0x001A4443
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005A60 RID: 23136 RVA: 0x001A625D File Offset: 0x001A445D
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.ApplySuccessRewards();
			}

			// Token: 0x06005A61 RID: 23137 RVA: 0x001A6265 File Offset: 0x001A4465
			protected override void AlternativeSolutionEndWithFailureConsequence()
			{
				this.ApplyFailRewards();
			}

			// Token: 0x06005A62 RID: 23138 RVA: 0x001A6270 File Offset: 0x001A4470
			private void ApplySuccessRewards()
			{
				base.IssueOwner.AddPower(10f);
				ChangeRelationAction.ApplyPlayerRelation(base.IssueOwner, 5, true, true);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30),
					new Tuple<TraitObject, int>(DefaultTraits.Mercy, -20)
				});
				foreach (Hero hero in this._targetSettlement.Notables)
				{
					if (hero.IsHeadman)
					{
						ChangeRelationAction.ApplyPlayerRelation(hero, -3, true, true);
						hero.AddPower(-10f);
					}
				}
			}

			// Token: 0x06005A63 RID: 23139 RVA: 0x001A632C File Offset: 0x001A452C
			private void ApplyFailRewards()
			{
				base.IssueOwner.AddPower(-10f);
				ChangeRelationAction.ApplyPlayerRelation(base.IssueOwner, -5, true, true);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -20)
				});
				foreach (Hero hero in this._targetSettlement.Notables)
				{
					if (hero.IsHeadman)
					{
						ChangeRelationAction.ApplyPlayerRelation(hero, 3, true, true);
						hero.AddPower(10f);
					}
				}
			}

			// Token: 0x06005A64 RID: 23140 RVA: 0x001A63D8 File Offset: 0x001A45D8
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005A65 RID: 23141 RVA: 0x001A63E9 File Offset: 0x001A45E9
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x06005A66 RID: 23142 RVA: 0x001A63F7 File Offset: 0x001A45F7
			protected override void AfterIssueCreation()
			{
				Village village = base.IssueOwner.CurrentSettlement.Village.Bound.BoundVillages.FirstOrDefault<Village>(delegate(Village x)
				{
					if (x.Settlement != base.IssueOwner.CurrentSettlement && !x.Settlement.IsUnderRaid)
					{
						return x.Settlement.Notables.Any<Hero>((Hero notable) => notable.IsHeadman);
					}
					return false;
				});
				this._targetSettlement = ((village != null) ? village.Settlement : null);
			}

			// Token: 0x06005A67 RID: 23143 RVA: 0x001A6436 File Offset: 0x001A4636
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005A68 RID: 23144 RVA: 0x001A6438 File Offset: 0x001A4638
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005A69 RID: 23145 RVA: 0x001A643A File Offset: 0x001A463A
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(6f), this._targetSettlement, this.RewardGold, base.IssueDifficultyMultiplier);
			}

			// Token: 0x06005A6A RID: 23146 RVA: 0x001A6464 File Offset: 0x001A4664
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Common;
			}

			// Token: 0x06005A6B RID: 23147 RVA: 0x001A6468 File Offset: 0x001A4668
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				skill = null;
				relationHero = null;
				requiredGold = 0;
				flag = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (base.IssueOwner.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				if (MobileParty.MainParty.MemberRoster.TotalHealthyCount < 10)
				{
					flag |= IssueBase.PreconditionFlags.NotEnoughTroops;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005A6C RID: 23148 RVA: 0x001A64E0 File Offset: 0x001A46E0
			public override bool IssueStayAliveConditions()
			{
				if (!base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid && base.IssueOwner.CurrentSettlement.Village.Bound.Town.Security <= 90f)
				{
					if (this._targetSettlement.Notables.Any<Hero>((Hero x) => x.IsHeadman))
					{
						return !Clan.BanditFactions.IsEmpty<Clan>();
					}
				}
				return false;
			}

			// Token: 0x06005A6D RID: 23149 RVA: 0x001A6577 File Offset: 0x001A4777
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001D30 RID: 7472
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x04001D31 RID: 7473
			private const int MinimumRequiredMenCount = 10;

			// Token: 0x04001D32 RID: 7474
			private const int NeededCompanionSkill = 150;

			// Token: 0x04001D33 RID: 7475
			private const int IssueDuration = 15;

			// Token: 0x04001D34 RID: 7476
			private const int QuestTimeLimit = 6;

			// Token: 0x04001D35 RID: 7477
			[SaveableField(100)]
			private Settlement _targetSettlement;
		}

		// Token: 0x02000723 RID: 1827
		public class LandlordNeedsAccessToVillageCommonsIssueQuest : QuestBase
		{
			// Token: 0x06005A6F RID: 23151 RVA: 0x001A65DA File Offset: 0x001A47DA
			internal static void AutoGeneratedStaticCollectObjectsLandlordNeedsAccessToVillageCommonsIssueQuest(object o, List<object> collectedObjects)
			{
				((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005A70 RID: 23152 RVA: 0x001A65E8 File Offset: 0x001A47E8
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._rivalMobileParty);
				collectedObjects.Add(this._targetSettlement);
				collectedObjects.Add(this._herdersMobileParty);
				collectedObjects.Add(this._headmanNotable);
			}

			// Token: 0x06005A71 RID: 23153 RVA: 0x001A6621 File Offset: 0x001A4821
			internal static object AutoGeneratedGetMemberValue_rivalMobileParty(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._rivalMobileParty;
			}

			// Token: 0x06005A72 RID: 23154 RVA: 0x001A662E File Offset: 0x001A482E
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._targetSettlement;
			}

			// Token: 0x06005A73 RID: 23155 RVA: 0x001A663B File Offset: 0x001A483B
			internal static object AutoGeneratedGetMemberValue_herdersMobileParty(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._herdersMobileParty;
			}

			// Token: 0x06005A74 RID: 23156 RVA: 0x001A6648 File Offset: 0x001A4848
			internal static object AutoGeneratedGetMemberValue_issueDifficultyMultiplier(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._issueDifficultyMultiplier;
			}

			// Token: 0x06005A75 RID: 23157 RVA: 0x001A665A File Offset: 0x001A485A
			internal static object AutoGeneratedGetMemberValue_headmanNotable(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._headmanNotable;
			}

			// Token: 0x06005A76 RID: 23158 RVA: 0x001A6667 File Offset: 0x001A4867
			internal static object AutoGeneratedGetMemberValue_questId(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._questId;
			}

			// Token: 0x06005A77 RID: 23159 RVA: 0x001A6674 File Offset: 0x001A4874
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._rewardGold;
			}

			// Token: 0x06005A78 RID: 23160 RVA: 0x001A6686 File Offset: 0x001A4886
			internal static object AutoGeneratedGetMemberValue_rivalPartySpawnDeltaTime(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._rivalPartySpawnDeltaTime;
			}

			// Token: 0x06005A79 RID: 23161 RVA: 0x001A6698 File Offset: 0x001A4898
			internal static object AutoGeneratedGetMemberValue_battleStarted(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._battleStarted;
			}

			// Token: 0x06005A7A RID: 23162 RVA: 0x001A66AA File Offset: 0x001A48AA
			internal static object AutoGeneratedGetMemberValue_spawnRivalPartyAfterHours(object o)
			{
				return ((LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest)o)._spawnRivalPartyAfterHours;
			}

			// Token: 0x170011A7 RID: 4519
			// (get) Token: 0x06005A7B RID: 23163 RVA: 0x001A66BC File Offset: 0x001A48BC
			private float PastureRadius
			{
				get
				{
					return Campaign.Current.Models.EncounterModel.GetEncounterJoiningRadius * 2.5f;
				}
			}

			// Token: 0x170011A8 RID: 4520
			// (get) Token: 0x06005A7C RID: 23164 RVA: 0x001A66D8 File Offset: 0x001A48D8
			public sealed override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=oT8DUcHf}Landowner Needs {TARGET_SETTLEMENT}'s Pasture", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x170011A9 RID: 4521
			// (get) Token: 0x06005A7D RID: 23165 RVA: 0x001A66FC File Offset: 0x001A48FC
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170011AA RID: 4522
			// (get) Token: 0x06005A7E RID: 23166 RVA: 0x001A6700 File Offset: 0x001A4900
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=GyZHauax}{QUEST_GIVER.LINK}, a rural landowner, has told you about {?QUEST_GIVER.GENDER}her{?}his{\\?} problems with the local herders of {TARGET_SETTLEMENT}. Apparently {?QUEST_GIVER.GENDER}she{?}he{\\?} purchased the right to use a nearby pasture. But the local herders of {TARGET_SETTLEMENT} refuse to clear out and are causing problems for {?QUEST_GIVER.GENDER}her{?}his{\\?} herdsmen. You agreed to do the job yourself, and escort herders to pasture.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x170011AB RID: 4523
			// (get) Token: 0x06005A7F RID: 23167 RVA: 0x001A6768 File Offset: 0x001A4968
			private TextObject SuccessWitHVillagerSurrenderQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=avMQKUoJ}You were able to drive the herders from the disputed pasture. The landowner {QUEST_GIVER.LINK}. {?QUEST_GIVER.GENDER}She{?}he{\\?} is grateful and sends {REWARD}{GOLD_ICON} with {?QUEST_GIVER.GENDER}her{?}his{\\?} regards.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("REWARD", this._rewardGold);
					return textObject;
				}
			}

			// Token: 0x170011AC RID: 4524
			// (get) Token: 0x06005A80 RID: 23168 RVA: 0x001A67C0 File Offset: 0x001A49C0
			private TextObject SuccessWitHWinningTheFightQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=YbBObxLH}You were able to drive the herders from the disputed pasture. The landowner, {QUEST_GIVER.LINK}, is grateful and sends {REWARD}{GOLD_ICON} with {?QUEST_GIVER.GENDER}her{?}his{\\?} regards.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("REWARD", this._rewardGold);
					return textObject;
				}
			}

			// Token: 0x170011AD RID: 4525
			// (get) Token: 0x06005A81 RID: 23169 RVA: 0x001A6834 File Offset: 0x001A4A34
			private TextObject FailWithLosingTheFightQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=117W31dZ}You were unable to drive the herders from the disputed pasture. The landowner, {QUEST_GIVER.LINK}, probably feels that you let {?QUEST_GIVER.GENDER}her{?}him{\\?} down.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x170011AE RID: 4526
			// (get) Token: 0x06005A82 RID: 23170 RVA: 0x001A6884 File Offset: 0x001A4A84
			private TextObject FailWithCounterOfferLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=zJujFbXU}You decided that the herders had more right to the disputed pasture than the landowner, {QUEST_GIVER.LINK}. {?QUEST_GIVER.GENDER}She{?}He{\\?} probably feels betrayed.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x170011AF RID: 4527
			// (get) Token: 0x06005A83 RID: 23171 RVA: 0x001A68D4 File Offset: 0x001A4AD4
			private TextObject FailByTimeoutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=ja74aAEI}You ignored the herders and did not solve the dispute. {?QUEST_GIVER.GENDER}She{?}he{\\?} probably feels betrayed.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011B0 RID: 4528
			// (get) Token: 0x06005A84 RID: 23172 RVA: 0x001A6908 File Offset: 0x001A4B08
			private TextObject TargetVillageRaided
			{
				get
				{
					TextObject textObject = new TextObject("{=aN85Kfnq}{SETTLEMENT} was raided. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", this._targetSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x170011B1 RID: 4529
			// (get) Token: 0x06005A85 RID: 23173 RVA: 0x001A6954 File Offset: 0x001A4B54
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011B2 RID: 4530
			// (get) Token: 0x06005A86 RID: 23174 RVA: 0x001A6986 File Offset: 0x001A4B86
			private TextObject WarDeclaredCancelLog
			{
				get
				{
					return new TextObject("{=wQH1N109}War broke out between your clan and the quest giver's realm. Quest canceled.", null);
				}
			}

			// Token: 0x06005A87 RID: 23175 RVA: 0x001A6994 File Offset: 0x001A4B94
			public LandlordNeedsAccessToVillageCommonsIssueQuest(string questId, Hero questGiver, CampaignTime duration, Settlement targetSettlement, int rewardGold, float issueDifficultyMultiplier)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._targetSettlement = targetSettlement;
				this._headmanNotable = targetSettlement.Notables.First<Hero>((Hero x) => x.IsHeadman);
				this._questId = questId;
				this._rewardGold = rewardGold;
				this._issueDifficultyMultiplier = issueDifficultyMultiplier;
				this._rivalPartySpawnDeltaTime = 0;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005A88 RID: 23176 RVA: 0x001A6A10 File Offset: 0x001A4C10
			protected override void SetDialogs()
			{
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetRivalPartyDialogues(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetHerderPartyNearVillageDialogues(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetHerderPartyDialogues(), this);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=qkYCWjTA}I appreciate it. I wait for the good news.", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=FogJnYH9}Any news about the pastures?[if:convo_undecided_open][ib:closed]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=wErSpkjy}I'm still working on it.", null), null, null, null)
					.NpcLine(new TextObject("{=xolucdbr}I am glad to hear that.[if:convo_undecided_open]", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=7o68QryW}Not yet. I have some other business to attend to.", null), null, null, null)
					.NpcLine(new TextObject("{=bEab8stb}Okay. I'm waiting for your good news.[if:convo_undecided_open]", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005A89 RID: 23177 RVA: 0x001A6B4C File Offset: 0x001A4D4C
			private DialogFlow GetRivalPartyDialogues()
			{
				TextObject textObject = new TextObject("{=Rt2w61N8}Don't get involved in this. [if:convo_confused_normal][ib:hip]We've grazed our herds on these hillsides since our fathers' fathers' time. We don't care if one rich bastard gave a couple of bags of silver to another rich bastard. We don't care about title deeds or courts of law or any of that. Custom is custom, and we're not going anywhere!", null);
				TextObject textObject2 = new TextObject("{=YPTZ2et7}Calm down. You're right. No one has the right to sell your ancestral lands. These herdsmen can take their cattle elsewhere.", null);
				TextObject textObject3 = new TextObject("{=R1W5Il2d}You can take your grievances to your lord, or to whoever sold the land. The law says a buyer has rights, and you need to clear out.", null);
				TextObject textObject4 = new TextObject("{=l3ALRD7c}You're just a rich bastard's lackey.[if:convo_confused_annoyed][ib:closed]", null);
				TextObject textObject5 = new TextObject("{=YLjksPbk}You're a kind {?PLAYER.GENDER}woman, [if:convo_happy]madam{?}man, sir{\\?}. You understand what poor folk like us are up against.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject4, false);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject5, false);
				TextObject textObject6 = new TextObject("{=ybb0ToHE}We will protect our lands![if:convo_thinking]", null);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject, null, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.RivalPartyTalkOnCondition))
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject2, null, null, null)
					.NpcLine(textObject5, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.FailWithAcceptingCounterOffer))
					.CloseDialog()
					.PlayerOption(textObject3, null, null, null)
					.EndPlayerOptions()
					.BeginNpcOptions(null, false)
					.NpcOption(textObject4, new ConversationSentence.OnConditionDelegate(this.RivalPartySurrenderOnCondition), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.SuccessWithVillagersSurrender))
					.CloseDialog()
					.NpcOption(textObject6, new ConversationSentence.OnConditionDelegate(this.RivalPartyFightOnCondition), null, null, null, null)
					.Consequence(delegate
					{
						PlayerEncounter.LeaveEncounter = false;
					})
					.CloseDialog()
					.EndNpcOptions()
					.CloseDialog();
			}

			// Token: 0x06005A8A RID: 23178 RVA: 0x001A6CAC File Offset: 0x001A4EAC
			private DialogFlow GetHerderPartyDialogues()
			{
				TextObject textObject = new TextObject("{=He6DW2Xb}Thank you for protecting us {?PLAYER.GENDER}madam{?}sir{\\?}. Keep following, we are almost there.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject, null, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.HerdersTalkOnCondition))
					.Consequence(delegate
					{
						PlayerEncounter.LeaveEncounter = true;
					})
					.CloseDialog();
			}

			// Token: 0x06005A8B RID: 23179 RVA: 0x001A6D27 File Offset: 0x001A4F27
			private bool RivalPartySurrenderOnCondition()
			{
				return MobileParty.MainParty.MemberRoster.TotalManCount - MobileParty.MainParty.MemberRoster.TotalWounded > 14;
			}

			// Token: 0x06005A8C RID: 23180 RVA: 0x001A6D4C File Offset: 0x001A4F4C
			private DialogFlow GetHerderPartyNearVillageDialogues()
			{
				TextObject textObject = new TextObject("{=crg2DrbZ}We are worried that the herders of {TARGET_SETTLEMENT} will harm our animals. Fortunately we have you on our side {?PLAYER.GENDER}madam{?}sir{\\?}.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
				textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject, null, null, null, null).Condition(() => this.HerdersTalkOnCondition() && DistanceHelper.FindClosestDistanceFromMobilePartyToSettlement(MobileParty.ConversationParty, this._targetSettlement, MobileParty.NavigationType.Default) < this.PastureRadius + 2f)
					.Consequence(delegate
					{
						PlayerEncounter.LeaveEncounter = true;
					})
					.CloseDialog();
			}

			// Token: 0x06005A8D RID: 23181 RVA: 0x001A6DE0 File Offset: 0x001A4FE0
			private bool RivalPartyTalkOnCondition()
			{
				return base.IsOngoing && this._rivalMobileParty != null && CharacterObject.OneToOneConversationCharacter != null && this._rivalMobileParty.MemberRoster.Contains(CharacterObject.OneToOneConversationCharacter) && MobileParty.ConversationParty != null && !CharacterObject.OneToOneConversationCharacter.IsHero && MobileParty.ConversationParty.HomeSettlement == this._targetSettlement;
			}

			// Token: 0x06005A8E RID: 23182 RVA: 0x001A6E42 File Offset: 0x001A5042
			private bool RivalPartyFightOnCondition()
			{
				return MobileParty.MainParty.MemberRoster.TotalManCount - MobileParty.MainParty.MemberRoster.TotalWounded <= 14;
			}

			// Token: 0x06005A8F RID: 23183 RVA: 0x001A6E6C File Offset: 0x001A506C
			private bool HerdersTalkOnCondition()
			{
				return base.IsOngoing && this._herdersMobileParty != null && CharacterObject.OneToOneConversationCharacter != null && this._herdersMobileParty.MemberRoster.Contains(CharacterObject.OneToOneConversationCharacter) && MobileParty.ConversationParty != null && !CharacterObject.OneToOneConversationCharacter.IsHero && MobileParty.ConversationParty.Party.Owner != Hero.MainHero && MobileParty.ConversationParty.HomeSettlement == base.QuestGiver.CurrentSettlement;
			}

			// Token: 0x06005A90 RID: 23184 RVA: 0x001A6EEC File Offset: 0x001A50EC
			private void FailWithAcceptingCounterOffer()
			{
				ChangeRelationAction.ApplyPlayerRelation(this._headmanNotable, 3, true, true);
				TraitLevelingHelper.OnIssueSolvedThroughBetrayal(this._headmanNotable, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -30),
					new Tuple<TraitObject, int>(DefaultTraits.Mercy, 20)
				});
				base.CompleteQuestWithFail(null);
				base.AddLog(this.FailWithCounterOfferLogText, false);
				PlayerEncounter.LeaveEncounter = true;
			}

			// Token: 0x06005A91 RID: 23185 RVA: 0x001A6F54 File Offset: 0x001A5154
			private void SpawnRivalParty()
			{
				Clan clan = Clan.BanditFactions.FirstOrDefault<Clan>((Clan x) => !x.Culture.CanHaveSettlement);
				if (clan == null)
				{
					Hideout hideout = SettlementHelper.FindNearestHideoutToSettlement(this._targetSettlement, MobileParty.NavigationType.Default, null);
					if (hideout != null)
					{
						CultureObject banditCulture = hideout.Settlement.Culture;
						clan = Clan.BanditFactions.FirstOrDefault<Clan>((Clan x) => x.Culture == banditCulture);
					}
					if (clan == null)
					{
						clan = Clan.BanditFactions.GetRandomElementInefficiently<Clan>();
					}
				}
				this._rivalMobileParty = BanditPartyComponent.CreateLooterParty("villagers_of_landlord_needs_access_to_village_common_quest" + this._questId, clan, this._targetSettlement, false, null, this._targetSettlement.GatePosition);
				this._rivalMobileParty.MemberRoster.AddToCounts(base.QuestGiver.Culture.Villager, MathF.Ceiling(10f + 20f * this._issueDifficultyMultiplier), false, 0, 0, true, -1);
				TextObject textObject = new TextObject("{=QLLeHRWw}Herders of {QUEST_SETTLEMENT}", null);
				textObject.SetTextVariable("QUEST_SETTLEMENT", this._targetSettlement.Name);
				this._rivalMobileParty.InitializePartyTrade(200);
				this._rivalMobileParty.SetPartyUsedByQuest(true);
				this._rivalMobileParty.Party.SetCustomName(textObject);
				this._rivalMobileParty.IgnoreForHours((float)(CampaignTime.HoursInDay * 30));
				this._rivalMobileParty.Ai.SetDoNotMakeNewDecisions(true);
				SetPartyAiAction.GetActionForEngagingParty(this._rivalMobileParty, this._herdersMobileParty, MobileParty.NavigationType.Default, false);
				this._rivalMobileParty.TargetPosition = this._herdersMobileParty.Position;
				this._rivalMobileParty.Party.SetVisualAsDirty();
				base.AddTrackedObject(this._rivalMobileParty);
				this._rivalMobileParty.Aggressiveness = 0f;
			}

			// Token: 0x06005A92 RID: 23186 RVA: 0x001A7111 File Offset: 0x001A5311
			private void SuccessWithVillagersSurrender()
			{
				base.CompleteQuestWithSuccess();
				base.AddLog(this.SuccessWitHVillagerSurrenderQuestLogText, false);
				PlayerEncounter.LeaveEncounter = true;
			}

			// Token: 0x06005A93 RID: 23187 RVA: 0x001A7130 File Offset: 0x001A5330
			private void SpawnHerdersParty()
			{
				TextObject textObject = new TextObject("{=tLakpr0a}Herdsmen of {QUEST_GIVER}", null);
				textObject.SetTextVariable("QUEST_GIVER", base.QuestGiver.Name);
				this._herdersMobileParty = CustomPartyComponent.CreateCustomPartyWithTroopRoster(base.QuestGiver.CurrentSettlement.GatePosition, 1f, base.QuestGiver.CurrentSettlement, textObject, null, TroopRoster.CreateDummyTroopRoster(), TroopRoster.CreateDummyTroopRoster(), null, "", "", 0f, false);
				this._herdersMobileParty.MemberRoster.AddToCounts(base.QuestGiver.Culture.Villager, MathF.Ceiling(2f + 5f * this._issueDifficultyMultiplier), false, 0, 0, true, -1);
				this._herdersMobileParty.InitializePartyTrade(200);
				this._herdersMobileParty.SetPartyUsedByQuest(true);
				this._herdersMobileParty.ItemRoster.AddToCounts(MBObjectManager.Instance.GetObject<ItemObject>("sumpter_horse"), MathF.Ceiling(2f + 5f * this._issueDifficultyMultiplier));
				this._herdersMobileParty.IgnoreForHours((float)(CampaignTime.HoursInDay * 30));
				this._herdersMobileParty.Ai.SetDoNotMakeNewDecisions(true);
				this._herdersMobileParty.Party.SetVisualAsDirty();
				base.AddTrackedObject(this._herdersMobileParty);
				this._herdersMobileParty.Aggressiveness = 0f;
				CampaignVec2 campaignVec = this._targetSettlement.GatePosition;
				int[] invalidTerrainTypesForNavigationType = Campaign.Current.Models.PartyNavigationModel.GetInvalidTerrainTypesForNavigationType(MobileParty.NavigationType.Default);
				for (int i = 0; i < 15; i++)
				{
					campaignVec = NavigationHelper.FindReachablePointAroundPosition(this._targetSettlement.GatePosition, MobileParty.NavigationType.Default, this.PastureRadius - 2f, this.PastureRadius - 3f, false);
					float num;
					if (Campaign.Current.MapSceneWrapper.GetPathDistanceBetweenAIFaces(this._targetSettlement.GatePosition.Face, campaignVec.Face, this._targetSettlement.GatePosition.ToVec2(), campaignVec.ToVec2(), 0.3f, this.PastureRadius, out num, invalidTerrainTypesForNavigationType, Campaign.Current.Models.MapDistanceModel.RegionSwitchCostFromLandToSea, Campaign.Current.Models.MapDistanceModel.RegionSwitchCostFromSeaToLand))
					{
						break;
					}
				}
				this._herdersMobileParty.SetMoveGoToPoint(campaignVec, MobileParty.NavigationType.Default);
				float num2;
				Campaign.Current.MapSceneWrapper.GetPathDistanceBetweenAIFaces(this._herdersMobileParty.CurrentNavigationFace, campaignVec.Face, this._herdersMobileParty.GetPosition2D, campaignVec.ToVec2(), 0.3f, float.MaxValue, out num2, invalidTerrainTypesForNavigationType, Campaign.Current.Models.MapDistanceModel.RegionSwitchCostFromLandToSea, Campaign.Current.Models.MapDistanceModel.RegionSwitchCostFromSeaToLand);
				this._spawnRivalPartyAfterHours = (int)(num2 / this._herdersMobileParty.Speed) + 3;
			}

			// Token: 0x06005A94 RID: 23188 RVA: 0x001A73F6 File Offset: 0x001A55F6
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddLog(this.PlayerStartsQuestLogText, false);
				base.AddTrackedObject(this._targetSettlement);
				this.SpawnHerdersParty();
			}

			// Token: 0x06005A95 RID: 23189 RVA: 0x001A7420 File Offset: 0x001A5620
			protected override void OnCompleteWithSuccess()
			{
				base.QuestGiver.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = 5;
				this._headmanNotable.AddPower(-10f);
				ChangeRelationAction.ApplyPlayerRelation(this._headmanNotable, -3, true, true);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30),
					new Tuple<TraitObject, int>(DefaultTraits.Mercy, -20)
				});
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
			}

			// Token: 0x06005A96 RID: 23190 RVA: 0x001A74A4 File Offset: 0x001A56A4
			public override void OnFailed()
			{
				base.QuestGiver.AddPower(-10f);
				this._headmanNotable.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = -5;
				TraitLevelingHelper.OnIssueFailed(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -20)
				});
			}

			// Token: 0x06005A97 RID: 23191 RVA: 0x001A74FC File Offset: 0x001A56FC
			protected override void OnTimedOut()
			{
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
				TraitLevelingHelper.OnIssueFailed(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -20)
				});
				base.AddLog(this.FailByTimeoutLogText, false);
			}

			// Token: 0x06005A98 RID: 23192 RVA: 0x001A7550 File Offset: 0x001A5750
			protected override void OnFinalize()
			{
				if (this._herdersMobileParty != null && this._herdersMobileParty.IsActive)
				{
					DestroyPartyAction.Apply(null, this._herdersMobileParty);
					this._herdersMobileParty = null;
				}
				if (this._rivalMobileParty != null && this._rivalMobileParty.IsActive)
				{
					DestroyPartyAction.Apply(null, this._rivalMobileParty);
					this._rivalMobileParty = null;
				}
			}

			// Token: 0x06005A99 RID: 23193 RVA: 0x001A75B0 File Offset: 0x001A57B0
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (this._rivalMobileParty != null && mapEvent.InvolvedParties.Contains(PartyBase.MainParty) && mapEvent.InvolvedParties.Contains(this._rivalMobileParty.Party) && !mapEvent.InvolvedParties.Contains(this._herdersMobileParty.Party))
				{
					this._herdersMobileParty.Party.MapEventSide = PartyBase.MainParty.MapEventSide;
				}
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005A9A RID: 23194 RVA: 0x001A7634 File Offset: 0x001A5834
			private void OnMapEventEnded(MapEvent mapEvent)
			{
				if (this._rivalMobileParty != null && ((mapEvent.InvolvedParties.Contains(PartyBase.MainParty) && mapEvent.InvolvedParties.Contains(this._rivalMobileParty.Party)) || (mapEvent.InvolvedParties.Contains(PartyBase.MainParty) && mapEvent.InvolvedParties.Contains(this._rivalMobileParty.Party) && mapEvent.InvolvedParties.Contains(this._herdersMobileParty.Party))))
				{
					if (mapEvent.WinningSide == mapEvent.PlayerSide)
					{
						base.CompleteQuestWithSuccess();
						base.AddLog(this.SuccessWitHWinningTheFightQuestLogText, false);
						return;
					}
					base.CompleteQuestWithFail(null);
					base.AddLog(this.FailWithLosingTheFightQuestLogText, false);
				}
			}

			// Token: 0x06005A9B RID: 23195 RVA: 0x001A76F0 File Offset: 0x001A58F0
			protected override void HourlyTick()
			{
				if (base.IsOngoing)
				{
					this.CheckAnSpawnRivalParty();
					if (this._rivalMobileParty != null && this._rivalMobileParty.IsActive)
					{
						MobileParty herdersMobileParty = this._herdersMobileParty;
						if (((herdersMobileParty != null) ? herdersMobileParty.MapEvent : null) == null)
						{
							MobileParty rivalMobileParty = this._rivalMobileParty;
							if (((rivalMobileParty != null) ? rivalMobileParty.MapEvent : null) == null && !this._battleStarted && DistanceHelper.FindClosestDistanceFromMobilePartyToMobileParty(this._rivalMobileParty, this._herdersMobileParty, MobileParty.NavigationType.Default) < Campaign.Current.Models.EncounterModel.GetEncounterJoiningRadius / 6f)
							{
								EncounterManager.StartPartyEncounter(this._rivalMobileParty.Party, this._herdersMobileParty.Party);
								this._rivalMobileParty.MapEvent.IsInvulnerable = true;
								this._battleStarted = true;
							}
						}
						if (this._battleStarted && this._rivalMobileParty.MapEvent.BattleStartTime.ElapsedHoursUntilNow > 5f)
						{
							this._rivalMobileParty.MapEvent.FinalizeEvent();
							DestroyPartyAction.Apply(this._rivalMobileParty.Party, this._herdersMobileParty);
						}
					}
				}
			}

			// Token: 0x06005A9C RID: 23196 RVA: 0x001A7807 File Offset: 0x001A5A07
			private void CheckAnSpawnRivalParty()
			{
				if (this._rivalMobileParty == null && this._rivalPartySpawnDeltaTime <= this._spawnRivalPartyAfterHours)
				{
					this._rivalPartySpawnDeltaTime++;
					if (this._rivalPartySpawnDeltaTime > this._spawnRivalPartyAfterHours)
					{
						this.SpawnRivalParty();
					}
				}
			}

			// Token: 0x06005A9D RID: 23197 RVA: 0x001A7844 File Offset: 0x001A5A44
			private void OnMobilePartyDestroyed(MobileParty mobileParty, PartyBase destroyerParty)
			{
				if (base.IsOngoing)
				{
					if (mobileParty == this._rivalMobileParty && (destroyerParty == PartyBase.MainParty || destroyerParty == this._herdersMobileParty.Party))
					{
						this._rivalMobileParty = null;
						base.AddLog(this.SuccessWitHWinningTheFightQuestLogText, false);
						base.CompleteQuestWithSuccess();
					}
					if (mobileParty == this._herdersMobileParty)
					{
						this._herdersMobileParty = null;
						base.AddLog(this.FailWithLosingTheFightQuestLogText, false);
						base.CompleteQuestWithFail(null);
					}
				}
			}

			// Token: 0x06005A9E RID: 23198 RVA: 0x001A78B8 File Offset: 0x001A5AB8
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.WarDeclaredCancelLog);
				}
			}

			// Token: 0x06005A9F RID: 23199 RVA: 0x001A78E7 File Offset: 0x001A5AE7
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.WarDeclaredCancelLog, false);
			}

			// Token: 0x06005AA0 RID: 23200 RVA: 0x001A78FF File Offset: 0x001A5AFF
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06005AA1 RID: 23201 RVA: 0x001A7907 File Offset: 0x001A5B07
			private void OnVillageRaided(Village village)
			{
				if (village == this._targetSettlement.Village || village == base.QuestGiver.CurrentSettlement.Village)
				{
					base.AddLog(this.TargetVillageRaided, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005AA2 RID: 23202 RVA: 0x001A7940 File Offset: 0x001A5B40
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.MapEventEnded.AddNonSerializedListener(this, new Action<MapEvent>(this.OnMapEventEnded));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.MobilePartyDestroyed.AddNonSerializedListener(this, new Action<MobileParty, PartyBase>(this.OnMobilePartyDestroyed));
				CampaignEvents.VillageBeingRaided.AddNonSerializedListener(this, new Action<Village>(this.OnVillageRaided));
				CampaignEvents.GameMenuOpened.AddNonSerializedListener(this, new Action<MenuCallbackArgs>(this.OnGameMenuOpened));
				CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, new Action<Hero, Hero, KillCharacterAction.KillCharacterActionDetail, bool>(this.OnHeroKilled));
			}

			// Token: 0x06005AA3 RID: 23203 RVA: 0x001A7A05 File Offset: 0x001A5C05
			public override void OnHeroCanHaveCampaignIssuesInfoIsRequested(Hero hero, ref bool result)
			{
				if (hero == this._headmanNotable)
				{
					result = false;
				}
			}

			// Token: 0x06005AA4 RID: 23204 RVA: 0x001A7A14 File Offset: 0x001A5C14
			private void OnHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification = true)
			{
				if (victim == this._headmanNotable)
				{
					TextObject textObject = ((detail == KillCharacterAction.KillCharacterActionDetail.Lost) ? this.TargetHeroDisappearedLogText : this.TargetHeroDiedLogText);
					StringHelpers.SetCharacterProperties("QUEST_TARGET", this._headmanNotable.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					base.AddLog(textObject, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005AA5 RID: 23205 RVA: 0x001A7A80 File Offset: 0x001A5C80
			private void OnGameMenuOpened(MenuCallbackArgs args)
			{
				if (args.MenuContext.GameMenu.StringId == "join_encounter" && this._battleStarted && PlayerEncounter.EncounteredBattle != null && PlayerEncounter.EncounteredBattle.InvolvedParties.Contains(this._rivalMobileParty.Party))
				{
					this._rivalMobileParty.MapEvent.IsInvulnerable = false;
				}
			}

			// Token: 0x04001D36 RID: 7478
			private const int BattleFakeSimulationDuration = 5;

			// Token: 0x04001D37 RID: 7479
			[SaveableField(11)]
			private MobileParty _rivalMobileParty;

			// Token: 0x04001D38 RID: 7480
			[SaveableField(30)]
			private readonly Settlement _targetSettlement;

			// Token: 0x04001D39 RID: 7481
			[SaveableField(21)]
			private MobileParty _herdersMobileParty;

			// Token: 0x04001D3A RID: 7482
			[SaveableField(31)]
			private float _issueDifficultyMultiplier;

			// Token: 0x04001D3B RID: 7483
			[SaveableField(50)]
			private readonly Hero _headmanNotable;

			// Token: 0x04001D3C RID: 7484
			[SaveableField(80)]
			private string _questId;

			// Token: 0x04001D3D RID: 7485
			[SaveableField(90)]
			private int _rewardGold;

			// Token: 0x04001D3E RID: 7486
			[SaveableField(100)]
			private int _rivalPartySpawnDeltaTime;

			// Token: 0x04001D3F RID: 7487
			[SaveableField(110)]
			private bool _battleStarted;

			// Token: 0x04001D40 RID: 7488
			[SaveableField(120)]
			private int _spawnRivalPartyAfterHours;
		}

		// Token: 0x02000724 RID: 1828
		public class LandlordNeedsAccessToVillageCommonsIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005AA9 RID: 23209 RVA: 0x001A7B2E File Offset: 0x001A5D2E
			public LandlordNeedsAccessToVillageCommonsIssueTypeDefiner()
				: base(420000)
			{
			}

			// Token: 0x06005AAA RID: 23210 RVA: 0x001A7B3B File Offset: 0x001A5D3B
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssue), 1, null);
				base.AddClassDefinition(typeof(LandlordNeedsAccessToVillageCommonsIssueBehavior.LandlordNeedsAccessToVillageCommonsIssueQuest), 2, null);
			}
		}
	}
}
