using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x0200036C RID: 876
	public class LandLordTheArtOfTheTradeIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060033B0 RID: 13232 RVA: 0x000D4DF4 File Offset: 0x000D2FF4
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060033B1 RID: 13233 RVA: 0x000D4E0D File Offset: 0x000D300D
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x060033B2 RID: 13234 RVA: 0x000D4E10 File Offset: 0x000D3010
		private bool ConditionsHold(Hero issueGiver)
		{
			if (issueGiver.IsRuralNotable)
			{
				Settlement currentSettlement = issueGiver.CurrentSettlement;
				Village village = ((currentSettlement != null) ? currentSettlement.Village : null);
				return village != null && village.Bound.Town.GetItemPrice(village.VillageType.PrimaryProduction, null, false) < village.VillageType.PrimaryProduction.Value;
			}
			return false;
		}

		// Token: 0x060033B3 RID: 13235 RVA: 0x000D4E70 File Offset: 0x000D3070
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x060033B4 RID: 13236 RVA: 0x000D4ED4 File Offset: 0x000D30D4
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue(issueOwner, issueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction);
		}

		// Token: 0x04000ECD RID: 3789
		private const IssueBase.IssueFrequency LandLordTheArtOfTheTradeIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x04000ECE RID: 3790
		private const float TargetDenarsConstant = 0.55f;

		// Token: 0x0200072A RID: 1834
		public class LandLordTheArtOfTheTradeIssue : IssueBase
		{
			// Token: 0x06005B06 RID: 23302 RVA: 0x001A8F0D File Offset: 0x001A710D
			internal static void AutoGeneratedStaticCollectObjectsLandLordTheArtOfTheTradeIssue(object o, List<object> collectedObjects)
			{
				((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005B07 RID: 23303 RVA: 0x001A8F1B File Offset: 0x001A711B
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x170011D3 RID: 4563
			// (get) Token: 0x06005B08 RID: 23304 RVA: 0x001A8F24 File Offset: 0x001A7124
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x170011D4 RID: 4564
			// (get) Token: 0x06005B09 RID: 23305 RVA: 0x001A8F27 File Offset: 0x001A7127
			private int SelectedItemObjectCount
			{
				get
				{
					return MathF.Max(1, MathF.Round((float)((int)(5000f / (float)this._selectedItemObject.Value)) * base.IssueDifficultyMultiplier));
				}
			}

			// Token: 0x170011D5 RID: 4565
			// (get) Token: 0x06005B0A RID: 23306 RVA: 0x001A8F4F File Offset: 0x001A714F
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 2 + MathF.Ceiling(4f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170011D6 RID: 4566
			// (get) Token: 0x06005B0B RID: 23307 RVA: 0x001A8F64 File Offset: 0x001A7164
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 3 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170011D7 RID: 4567
			// (get) Token: 0x06005B0C RID: 23308 RVA: 0x001A8F79 File Offset: 0x001A7179
			protected override int RewardGold
			{
				get
				{
					return (int)((float)(this._selectedItemObject.Value * this.SelectedItemObjectCount) * this.RewardGoldDeterministicRandomContribution);
				}
			}

			// Token: 0x170011D8 RID: 4568
			// (get) Token: 0x06005B0D RID: 23309 RVA: 0x001A8F96 File Offset: 0x001A7196
			private float RewardGoldDeterministicRandomContribution
			{
				get
				{
					return base.IssueOwner.RandomFloatWithSeed((uint)this.IssueCreationTime.ElapsedDaysUntilNow, 0.2f, 0.5f);
				}
			}

			// Token: 0x170011D9 RID: 4569
			// (get) Token: 0x06005B0E RID: 23310 RVA: 0x001A8FBC File Offset: 0x001A71BC
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=AKdDSZoM}Yes. It's a good problem to have, though. As you know, I deal in {.%}{SELECTED_ITEM}{.%}. Production this year has been very good, and we can no longer make a profit on the local market. I cannot however, put together a caravan to sell it elsewhere. So, I propose a very simple deal.[if:convo_innocent_smile][ib:confident]", null);
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject = new TextObject("{=llVFTH6n}Yes. It's a good problem to have, though. As you may know, I deal in {PLURAL(SELECTED_ITEM)}. Our herds have increased this year, and we can no longer make a profit on the local market. I cannot however organize a drive to a new market. So, I propose a very simple deal.[if:convo_innocent_smile][ib:confident]", null);
					}
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					return textObject;
				}
			}

			// Token: 0x170011DA RID: 4570
			// (get) Token: 0x06005B0F RID: 23311 RVA: 0x001A9013 File Offset: 0x001A7213
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=8jyUn6mb}You sell me the goods at a discount?", null);
				}
			}

			// Token: 0x170011DB RID: 4571
			// (get) Token: 0x06005B10 RID: 23312 RVA: 0x001A9020 File Offset: 0x001A7220
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=rWnvnufw}That could work, if you have the money. But if you don't, I'm willing to take a chance on you. I reckon for {SELECTED_ITEM_COUNT} {.%}{?SELECTED_ITEM_COUNT > 1}{PLURAL(SELECTED_ITEM)}{?}{SELECTED_ITEM}{\\?}{.%} you can probably find a market nearby where buyers will pay you a total of {TOTAL_GOLD}{GOLD_ICON}. Here's my offer. I loan you the product. You sell it at whatever price you like, and bring me back {TOTAL_GOLD}{GOLD_ICON} denars. I have little doubt you could find a market where you could get a better price than this, and make a profit.[if:convo_innocent_smile][ib:confident]", null);
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject = new TextObject("{=b19Hlp7h}That could work, if you have the money. But if you don't, I'm willing to take a chance on you. I reckon for {SELECTED_ITEM_COUNT} {?SELECTED_ITEM_COUNT > 1}{PLURAL(SELECTED_ITEM)}{?}{SELECTED_ITEM}{\\?} you can probably find a market nearby where buyers will pay you a total of {TOTAL_GOLD}{GOLD_ICON}. Here's my offer. I loan you the livestock. You sell at whatever price you like, and bring me back {TOTAL_GOLD}{GOLD_ICON} denars. I have little doubt you could find a market where you could get a better price than this, and make a profit.[if:convo_innocent_smile][ib:confident]", null);
					}
					textObject.SetTextVariable("TOTAL_GOLD", (int)((float)(this._selectedItemObject.Value * this.SelectedItemObjectCount) * 0.55f));
					textObject.SetTextVariable("SELECTED_ITEM_COUNT", this.SelectedItemObjectCount);
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170011DC RID: 4572
			// (get) Token: 0x06005B11 RID: 23313 RVA: 0x001A90C0 File Offset: 0x001A72C0
			public override TextObject IssuePlayerResponseAfterAlternativeExplanation
			{
				get
				{
					return new TextObject("{=w1rVTUIs}This seems like a simple errand. Would your offer still stand if I get someone else to do it for me?", null);
				}
			}

			// Token: 0x170011DD RID: 4573
			// (get) Token: 0x06005B12 RID: 23314 RVA: 0x001A90CD File Offset: 0x001A72CD
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=PE97ZWvX}Not just anybody. If you have a companion that has your complete trust, then I'll agree... Just make sure he is well guarded. Goods attract bandits, as I'm sure you know. I suppose {ALTERNATIVE_TROOP_AMOUNT} well-armed men would be enough.[if:convo_innocent_smile][ib:confident]", null);
					textObject.SetTextVariable("ALTERNATIVE_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					return textObject;
				}
			}

			// Token: 0x170011DE RID: 4574
			// (get) Token: 0x06005B13 RID: 23315 RVA: 0x001A90EC File Offset: 0x001A72EC
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=aB0TT6Ur}Fear not. I will find the right market for your {.%}{SELECTED_ITEM}{.%} myself.", null);
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject = new TextObject("{=cBO49V5b}Fear not. I will find the right market for your {PLURAL(SELECTED_ITEM)} myself.", null);
					}
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					return textObject;
				}
			}

			// Token: 0x170011DF RID: 4575
			// (get) Token: 0x06005B14 RID: 23316 RVA: 0x001A9143 File Offset: 0x001A7343
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=IFasMslv}I will assign a companion with {TROOP_COUNT} good men for {RETURN_DAYS} days.", null);
					textObject.SetTextVariable("TROOP_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x170011E0 RID: 4576
			// (get) Token: 0x06005B15 RID: 23317 RVA: 0x001A9174 File Offset: 0x001A7374
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=dLywF1Uz}I have heard your companion has started to sell the goods. This was a good deal, {?PLAYER.GENDER}ma'am{?}sir{\\?}.[if:convo_relaxed_happy][ib:confident]", null);
				}
			}

			// Token: 0x170011E1 RID: 4577
			// (get) Token: 0x06005B16 RID: 23318 RVA: 0x001A9181 File Offset: 0x001A7381
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=aUXAh8cE}Very well, {PLAYER.NAME}. If you're willing to vouch for your companion, I'm sure this will work.[if:convo_innocent_smile][ib:confident]", null);
				}
			}

			// Token: 0x170011E2 RID: 4578
			// (get) Token: 0x06005B17 RID: 23319 RVA: 0x001A918E File Offset: 0x001A738E
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x170011E3 RID: 4579
			// (get) Token: 0x06005B18 RID: 23320 RVA: 0x001A9191 File Offset: 0x001A7391
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170011E4 RID: 4580
			// (get) Token: 0x06005B19 RID: 23321 RVA: 0x001A9194 File Offset: 0x001A7394
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=BK9ww4NU}{QUEST_GIVER.LINK} asked you to sell {?QUEST_GIVER.GENDER}her{?}his{\\?} goods for at least {UNIT_PRICE}{GOLD_ICON} per {UNIT_NAME} and return to {?QUEST_GIVER.GENDER}her{?}him{\\?}. {?QUEST_GIVER.GENDER}She{?}He{\\?} told you that any profit that the deal would make above this price is yours to keep. You asked {COMPANION.LINK} to take {TROOP_COUNT} of your best men to go and take care of it. They should report back to you in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, true);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("UNIT_NAME", "{=g72xNv75}load");
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject.SetTextVariable("UNIT_NAME", "{=T9Tgi9is}animal");
					}
					textObject.SetTextVariable("UNIT_PRICE", this._selectedItemObject.Value);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					textObject.SetTextVariable("TROOP_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170011E5 RID: 4581
			// (get) Token: 0x06005B1A RID: 23322 RVA: 0x001A9268 File Offset: 0x001A7468
			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=BDAmZkJF}You received a message from {ISSUE_GIVER.LINK}. 'It was a pleasure doing business with you and your folks.'", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011E6 RID: 4582
			// (get) Token: 0x06005B1B RID: 23323 RVA: 0x001A929A File Offset: 0x001A749A
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=96m29Eb7}The Art of the Trade", null);
				}
			}

			// Token: 0x170011E7 RID: 4583
			// (get) Token: 0x06005B1C RID: 23324 RVA: 0x001A92A7 File Offset: 0x001A74A7
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=BZwKEIm5}{ISSUE_GIVER.LINK} wants you to sell {?ISSUE_GIVER.GENDER}her{?}his{\\?} goods for a price above the global average.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, null, false);
					return textObject;
				}
			}

			// Token: 0x06005B1D RID: 23325 RVA: 0x001A92CC File Offset: 0x001A74CC
			public LandLordTheArtOfTheTradeIssue(Hero issueOwner, ItemObject villageProduction)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				this._selectedItemObject = villageProduction;
			}

			// Token: 0x06005B1E RID: 23326 RVA: 0x001A92E6 File Offset: 0x001A74E6
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.VillageHearth)
				{
					return -0.1f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005B1F RID: 23327 RVA: 0x001A9309 File Offset: 0x001A7509
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Trade) >= hero.GetSkillValue(DefaultSkills.Riding)) ? DefaultSkills.Trade : DefaultSkills.Riding, 120);
			}

			// Token: 0x06005B20 RID: 23328 RVA: 0x001A9338 File Offset: 0x001A7538
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				int totalAlternativeSolutionNeededMenCount = base.GetTotalAlternativeSolutionNeededMenCount();
				if (this.GetNumberOfTier2Troops(troopRoster) < totalAlternativeSolutionNeededMenCount)
				{
					explanation = new TextObject("{=rJIY7OiR}You have to send {NEEDED_TROOP_COUNT} troops with at least tier 2 to this quest.", null);
					explanation.SetTextVariable("NEEDED_TROOP_COUNT", totalAlternativeSolutionNeededMenCount);
					return false;
				}
				explanation = null;
				return true;
			}

			// Token: 0x06005B21 RID: 23329 RVA: 0x001A9378 File Offset: 0x001A7578
			private int GetNumberOfTier2Troops(TroopRoster troopRoster)
			{
				int num = 0;
				foreach (TroopRosterElement troopRosterElement in troopRoster.GetTroopRoster())
				{
					if (troopRosterElement.Character.Tier >= 2)
					{
						num += troopRoster.GetTroopCount(troopRosterElement.Character) - troopRoster.GetElementWoundedNumber(troopRoster.FindIndexOfTroop(troopRosterElement.Character));
					}
				}
				return num;
			}

			// Token: 0x06005B22 RID: 23330 RVA: 0x001A93F8 File Offset: 0x001A75F8
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005B23 RID: 23331 RVA: 0x001A93FC File Offset: 0x001A75FC
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid && (float)base.IssueOwner.CurrentSettlement.Village.Bound.Town.GetItemPrice(base.IssueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction, null, false) < (float)base.IssueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction.Value * 1.3f;
			}

			// Token: 0x06005B24 RID: 23332 RVA: 0x001A9494 File Offset: 0x001A7694
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005B25 RID: 23333 RVA: 0x001A94E8 File Offset: 0x001A76E8
			protected override void OnGameLoad()
			{
				this._selectedItemObject = base.IssueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction;
			}

			// Token: 0x06005B26 RID: 23334 RVA: 0x001A950A File Offset: 0x001A770A
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005B27 RID: 23335 RVA: 0x001A950C File Offset: 0x001A770C
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this._selectedItemObject, this.SelectedItemObjectCount);
			}

			// Token: 0x06005B28 RID: 23336 RVA: 0x001A9530 File Offset: 0x001A7730
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x170011E8 RID: 4584
			// (get) Token: 0x06005B29 RID: 23337 RVA: 0x001A9532 File Offset: 0x001A7732
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(900f + 800f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06005B2A RID: 23338 RVA: 0x001A9547 File Offset: 0x001A7747
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				this.RelationshipChangeWithIssueOwner = 5;
			}

			// Token: 0x04001D53 RID: 7507
			private const int IssueAndQuestDuration = 30;

			// Token: 0x04001D54 RID: 7508
			private const int CompanionRequiredSkillLevel = 120;

			// Token: 0x04001D55 RID: 7509
			private ItemObject _selectedItemObject;
		}

		// Token: 0x0200072B RID: 1835
		public class LandLordTheArtOfTheTradeIssueQuest : QuestBase
		{
			// Token: 0x06005B2B RID: 23339 RVA: 0x001A9560 File Offset: 0x001A7760
			internal static void AutoGeneratedStaticCollectObjectsLandLordTheArtOfTheTradeIssueQuest(object o, List<object> collectedObjects)
			{
				((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005B2C RID: 23340 RVA: 0x001A956E File Offset: 0x001A776E
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._selectedItemObject);
				collectedObjects.Add(this._soldItemAmountLog);
				collectedObjects.Add(this._gatheredDenarsLog);
			}

			// Token: 0x06005B2D RID: 23341 RVA: 0x001A959B File Offset: 0x001A779B
			internal static object AutoGeneratedGetMemberValue_selectedItemObject(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._selectedItemObject;
			}

			// Token: 0x06005B2E RID: 23342 RVA: 0x001A95A8 File Offset: 0x001A77A8
			internal static object AutoGeneratedGetMemberValue_selectedItemObjectCount(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._selectedItemObjectCount;
			}

			// Token: 0x06005B2F RID: 23343 RVA: 0x001A95BA File Offset: 0x001A77BA
			internal static object AutoGeneratedGetMemberValue_soldCount(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._soldCount;
			}

			// Token: 0x06005B30 RID: 23344 RVA: 0x001A95CC File Offset: 0x001A77CC
			internal static object AutoGeneratedGetMemberValue_gatheredDenars(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._gatheredDenars;
			}

			// Token: 0x06005B31 RID: 23345 RVA: 0x001A95DE File Offset: 0x001A77DE
			internal static object AutoGeneratedGetMemberValue_daysPassed(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._daysPassed;
			}

			// Token: 0x06005B32 RID: 23346 RVA: 0x001A95F0 File Offset: 0x001A77F0
			internal static object AutoGeneratedGetMemberValue_underSoldLogAdded(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._underSoldLogAdded;
			}

			// Token: 0x06005B33 RID: 23347 RVA: 0x001A9602 File Offset: 0x001A7802
			internal static object AutoGeneratedGetMemberValue_soldItemAmountLog(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._soldItemAmountLog;
			}

			// Token: 0x06005B34 RID: 23348 RVA: 0x001A960F File Offset: 0x001A780F
			internal static object AutoGeneratedGetMemberValue_gatheredDenarsLog(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._gatheredDenarsLog;
			}

			// Token: 0x170011E9 RID: 4585
			// (get) Token: 0x06005B35 RID: 23349 RVA: 0x001A961C File Offset: 0x001A781C
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=96m29Eb7}The Art of the Trade", null);
				}
			}

			// Token: 0x170011EA RID: 4586
			// (get) Token: 0x06005B36 RID: 23350 RVA: 0x001A9629 File Offset: 0x001A7829
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170011EB RID: 4587
			// (get) Token: 0x06005B37 RID: 23351 RVA: 0x001A962C File Offset: 0x001A782C
			private bool QuestCanBeFinalized
			{
				get
				{
					return Hero.OneToOneConversationHero != null && Hero.OneToOneConversationHero == base.QuestGiver && (this.ItemCountLeftToSell <= 0 || this._targetDenarsToAchieve <= this._gatheredDenars || (this._daysPassed >= 1 && this.CheckIfPlayerLostItem()));
				}
			}

			// Token: 0x170011EC RID: 4588
			// (get) Token: 0x06005B38 RID: 23352 RVA: 0x001A9679 File Offset: 0x001A7879
			private int ItemCountLeftToSell
			{
				get
				{
					return this._selectedItemObjectCount - this._soldCount;
				}
			}

			// Token: 0x170011ED RID: 4589
			// (get) Token: 0x06005B39 RID: 23353 RVA: 0x001A9688 File Offset: 0x001A7888
			private int RemainingDenars
			{
				get
				{
					return this._targetDenarsToAchieve - this._gatheredDenars;
				}
			}

			// Token: 0x170011EE RID: 4590
			// (get) Token: 0x06005B3A RID: 23354 RVA: 0x001A9698 File Offset: 0x001A7898
			private TextObject QuestStartedLogText1
			{
				get
				{
					TextObject textObject = new TextObject("{=2bcNCnI3}{QUEST_GIVER.LINK} asked you to sell {?QUEST_GIVER.GENDER}her{?}his{\\?} goods for at least {UNIT_PRICE}{GOLD_ICON} per load and return to {?QUEST_GIVER.GENDER}her{?}him{\\?}. {?QUEST_GIVER.GENDER}She{?}He{\\?} told you that any profit would make above this price is yours to keep.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, true);
					textObject.SetTextVariable("UNIT_PRICE", this._targetDenarsToAchieve / this._selectedItemObjectCount);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170011EF RID: 4591
			// (get) Token: 0x06005B3B RID: 23355 RVA: 0x001A96F4 File Offset: 0x001A78F4
			private TextObject QuestStartedLogText2
			{
				get
				{
					TextObject textObject = new TextObject("{=jI251oj9}{?QUEST_GIVER.GENDER}She{?}He{\\?} noted that {?QUEST_GIVER.GENDER}she{?}he{\\?} has {SELECTED_ITEM_COUNT} {.%}{?SELECTED_ITEM_COUNT > 1}{PLURAL(SELECTED_ITEM)}{?}{SELECTED_ITEM}{\\?}{.%}. {?QUEST_GIVER.GENDER}She{?}He{\\?} is expecting to earn {TOTAL_GOLD}{GOLD_ICON} denars from that.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("SELECTED_ITEM_COUNT", this._selectedItemObjectCount);
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					textObject.SetTextVariable("TOTAL_GOLD", this._targetDenarsToAchieve);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170011F0 RID: 4592
			// (get) Token: 0x06005B3C RID: 23356 RVA: 0x001A9774 File Offset: 0x001A7974
			private TextObject QuestStartedLogText3
			{
				get
				{
					TextObject textObject = new TextObject("{=tf04Piaj}You told {?QUEST_GIVER.GENDER}her{?}him{\\?} that you will sell the goods personally.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011F1 RID: 4593
			// (get) Token: 0x06005B3D RID: 23357 RVA: 0x001A97A6 File Offset: 0x001A79A6
			private TextObject QuestSuccessLogText
			{
				get
				{
					return new TextObject("{=EsNDadiR}You have completed your end of your bargain and made some denars simply by using your smarts.", null);
				}
			}

			// Token: 0x170011F2 RID: 4594
			// (get) Token: 0x06005B3E RID: 23358 RVA: 0x001A97B4 File Offset: 0x001A79B4
			private TextObject QuestReadyToBeFinishedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=2GMOnUIM}{QUEST_GIVER.LINK} expects your return to have {?QUEST_GIVER.GENDER}her{?}his{\\?} share of the deal.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011F3 RID: 4595
			// (get) Token: 0x06005B3F RID: 23359 RVA: 0x001A97F8 File Offset: 0x001A79F8
			private TextObject QuestReadyToBeFinishedUnderSoldLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=IfPnl0B6}You have lost some of the wares you were supposed to be selling. You can speak with {QUEST_GIVER.LINK} to pay for a compensation.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011F4 RID: 4596
			// (get) Token: 0x06005B40 RID: 23360 RVA: 0x001A982C File Offset: 0x001A7A2C
			private TextObject QuestSuccessWithPayingGatheredDenarsLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=4bDHBIr1}You have completed your end of the bargain. {QUEST_GIVER.LINK} now considers you as a trustworthy {?PLAYER.GENDER}tradeswoman{?}tradesman{\\?}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011F5 RID: 4597
			// (get) Token: 0x06005B41 RID: 23361 RVA: 0x001A9870 File Offset: 0x001A7A70
			private TextObject QuestSuccessPlayerBoughtItemsLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=rYt43AWk}{QUEST_GIVER.LINK} accepted your offer to buy the products from an average price. You can now sell those for profits without any obligations to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011F6 RID: 4598
			// (get) Token: 0x06005B42 RID: 23362 RVA: 0x001A98A4 File Offset: 0x001A7AA4
			private TextObject QuestFailedPlayerBrokeTheAgreementLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=1q2dxlol}You have failed to pay {TOTAL_DENAR}{GOLD_ICON} denars to {QUEST_GIVER.LINK}. {QUEST_GIVER_VILLAGE} and its locals are aware of your misdemeanor.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_VILLAGE", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("TOTAL_DENAR", this._targetDenarsToAchieve);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170011F7 RID: 4599
			// (get) Token: 0x06005B43 RID: 23363 RVA: 0x001A9918 File Offset: 0x001A7B18
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011F8 RID: 4600
			// (get) Token: 0x06005B44 RID: 23364 RVA: 0x001A994C File Offset: 0x001A7B4C
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011F9 RID: 4601
			// (get) Token: 0x06005B45 RID: 23365 RVA: 0x001A9980 File Offset: 0x001A7B80
			private TextObject QuestGiverVillageRaided
			{
				get
				{
					TextObject textObject = new TextObject("{=w0FD9U98}{QUEST_GIVER.LINK}'s village is raided. Your agreement with {?QUEST_GIVER.GENDER}her{?}him{\\?} is moot.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x170011FA RID: 4602
			// (get) Token: 0x06005B46 RID: 23366 RVA: 0x001A99D0 File Offset: 0x001A7BD0
			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=PQt8lfTX}You have failed to return to the {QUEST_GIVER.LINK} in time. {QUEST_GIVER_VILLAGE} and its locals are aware of your misdemeanor.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_VILLAGE", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x06005B47 RID: 23367 RVA: 0x001A9A20 File Offset: 0x001A7C20
			public LandLordTheArtOfTheTradeIssueQuest(string questId, Hero giverHero, CampaignTime duration, ItemObject selectedItemObject, int selectedItemObjectCount)
				: base(questId, giverHero, duration, 0)
			{
				this._selectedItemObject = selectedItemObject;
				this._selectedItemObjectCount = selectedItemObjectCount;
				this._targetDenarsToAchieve = (int)((float)(selectedItemObject.Value * selectedItemObjectCount) * 0.55f);
				this._daysPassed = 0;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005B48 RID: 23368 RVA: 0x001A9A7C File Offset: 0x001A7C7C
			protected override void SetDialogs()
			{
				TextObject textObject = new TextObject("{=3Sk0BQ4n}I will buy the products from you for {TOTAL_GOLD}{GOLD_ICON}. This way we both will get what we desire.", null);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject = new TextObject("{=7nBOWsg2}I will buy the livestock from you for {TOTAL_GOLD}{GOLD_ICON}. This way we both will get what we desire.", null);
				}
				textObject.SetTextVariable("TOTAL_GOLD", this._targetDenarsToAchieve);
				textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
				TextObject textObject2 = new TextObject("{=iYtzlRSN}I would rather be your middleman on this matter. I need to keep my money. You can have your men load up the {.%}{SELECTED_ITEM}{.%} already.", null);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject2 = new TextObject("{=exmSGWUb}I would rather be your middleman on this matter. I need to keep my money. You can have your men get the herd ready.", null);
				}
				textObject2.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				TextObject textObject3 = new TextObject("{=9d6WxRrj}Do you want to buy the goods yourself? Or will I retain ownership, and you just keep the extra profits? I am expecting to earn {TOTAL_DENARS}{GOLD_ICON} for {SELECTED_COUNT} loads of produce. If would like to buy it right away you can simply sell it yourself or do whatever you wish with it.", null);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject3 = new TextObject("{=GihVcxIB}Do you want to buy the livestock yourself? Or will I retain ownership, and you just keep the extra profits? I am expecting to earn {TOTAL_DENARS}{GOLD_ICON} in total. If would like to buy the livestock right away you can simply sell it yourself or do whatever you wish with it.", null);
				}
				textObject3.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				textObject3.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
				textObject3.SetTextVariable("SELECTED_COUNT", this._selectedItemObjectCount);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=NaoYCmC6}Good. Needless to say, by not taking any money up front, I am trusting in your honesty in your ability to protect those goods. But I am sure that trust will not be misplaced.[if:convo_innocent_smile][ib:closed]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == this.QuestGiver)
					.NpcLine(textObject3, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject, null, null, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.PlayerBuyClickableOptionCondition))
					.NpcLine(new TextObject("{=LmTii9E2}It was a pleasure doing business with you. If only everyone was as honest as you.[if:convo_happy][ib:confident3]", null), null, null, null, null)
					.Consequence(delegate
					{
						this.StartQuest();
						this.QuestFinishedPlayerBoughtTheGoods();
					})
					.CloseDialog()
					.PlayerOption(textObject2, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
				TextObject playerMainOptionOneWithGold = new TextObject("{=1zdkXAwL}The market isn't what we expected. I am afraid I only made {GATHERED_DENARS}{GOLD_ICON} of the {TOTAL_DENARS}{GOLD_ICON} that we agreed upon.", null);
				playerMainOptionOneWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
				playerMainOptionOneWithGold.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				playerMainOptionOneWithGold.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
				TextObject playerMainOptionOneNoGold = new TextObject("{=52lNazA1}I'm afraid that things came up. I was not able to make the sale.", null);
				TextObject textObject4 = new TextObject("{=!}{PLAYER_OPTION}", null);
				TextObject textObject5 = new TextObject("{=THD3C7xc}I have. Here is the {TOTAL_DENARS}{GOLD_ICON} denars just as we agreed.", null);
				textObject5.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				textObject5.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
				TextObject textObject6 = new TextObject("{=z47GjqTZ}Yes, of course. This is the {TOTAL_DENARS}{GOLD_ICON} denars that I owe you.", null);
				textObject6.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
				textObject6.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				TextObject playerFailOptionWithGold = new TextObject("{=dtzKfkrh}We never agreed on this. I am not paying you any more than {GATHERED_DENARS}{GOLD_ICON}, and you cannot force me.", null);
				playerFailOptionWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
				TextObject playerFailOptionNoGold = new TextObject("{=aFDiKxhr}Our deal involved you getting your cut from the sales I made. No sale means no cut. I'm sure you understand.[ib:warrior2]", null);
				TextObject textObject7 = new TextObject("{=!}{PLAYER_FAIL_OPTION}", null);
				TextObject textObject8 = new TextObject("{=41wb8QaV}I know I can not force you to pay you what you owe me. But I think you will find that a good name is worth more than a few loads of {SELECTED_ITEM}...", null);
				textObject8.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject8 = new TextObject("{=pcrdOlE8}I know I can not force you to pay you what you owe me. But I think you will find that a good name is worth more than a bit of livestock...", null);
				}
				TextObject textObject9 = new TextObject("{=OIwtLKN3}I am a {?PLAYER.GENDER}woman{?}man{\\?} of my word. I will raise some money to pay you. Wait for my return {QUEST_GIVER.LINK}.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject9, false);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject9, false);
				TextObject textObject10 = new TextObject("{=bPPXiybO}I just happened to be around. Have no fear {QUEST_GIVER.NAME}, your goods are fine.", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject10, false);
				TextObject textObject11 = new TextObject("{=ekSg8okD}I will be better once you return with the denars you owe me {PLAYER.NAME}.[ib:aggressive2]", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject10, false);
				TextObject textObject12 = new TextObject("{=bbsN6hOo}Have you already sold that {SELECTED_ITEM}? If so, that seems awfully quick.", null);
				textObject12.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).BeginNpcOptions(null, false).NpcOption(textObject12, () => Hero.OneToOneConversationHero != null && Hero.OneToOneConversationHero == this.QuestGiver && !this.QuestCanBeFinalized, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=gVad94Br}I was just checking in with you.", null), null, null, null)
					.Condition(() => !this.QuestCanBeFinalized)
					.NpcLine(textObject11, null, null, null, null)
					.CloseDialog()
					.PlayerOption(textObject10, null, null, null)
					.Condition(() => !this.QuestCanBeFinalized)
					.NpcLine(textObject11, null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.NpcOption(new TextObject("{=1q3FKY1s}Have you made your trip yet? I presume you were able to make a sale?", null), () => Hero.OneToOneConversationHero != null && Hero.OneToOneConversationHero == this.QuestGiver && this.QuestCanBeFinalized, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject4, null, null, null)
					.Condition(delegate
					{
						if (this._gatheredDenars > 0)
						{
							playerMainOptionOneWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_OPTION", playerMainOptionOneWithGold);
						}
						else
						{
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_OPTION", playerMainOptionOneNoGold);
						}
						return this.QuestCanBeFinalized && this._productsUndersold;
					})
					.NpcLine(new TextObject("{=QlYUE00L}Well. We did have an agreement. I do expect you to pay the full amount.", null), null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject6, null, null, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.PlayerPayAgreedDenarsClickableCondition))
					.NpcLine(new TextObject("{=gNHh9bvb}I am sorry that you did not manage to make a profit. But you are keeping your end of the bargain, and that is admirable.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.PlayerPaidAgreedDenarsQuestSuccess;
					})
					.CloseDialog()
					.PlayerOption(textObject7, null, null, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.PlayerFailWithGoldClickableCondition))
					.Condition(delegate
					{
						if (this._gatheredDenars > 0)
						{
							playerFailOptionWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_FAIL_OPTION", playerFailOptionWithGold);
						}
						else
						{
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_FAIL_OPTION", playerFailOptionNoGold);
						}
						return true;
					})
					.NpcLine(textObject8, null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.QuestFailedPlayerBrokeTheAgreement;
					})
					.CloseDialog()
					.PlayerOption(textObject9, null, null, null)
					.NpcLine(new TextObject("{=RxjuaDum}I am glad of that. Don't make me wait too long. Some men say they will pay a debt, and you never see them again.[if:convo_mocking_teasing][ib:confident2]", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.PlayerOption(textObject5, null, null, null)
					.Condition(() => this.QuestCanBeFinalized && !this._productsUndersold)
					.NpcLine(new TextObject("{=9jFqXvHy}Excellent! I knew you were an honest soul. Trust is a fine thing, isn't it? Perhaps we can do more business in the future.[if:convo_innocent_smile][ib:confident]", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestSuccessPlayerSoldTheProducts))
					.CloseDialog()
					.EndPlayerOptions()
					.EndNpcOptions();
			}

			// Token: 0x06005B49 RID: 23369 RVA: 0x001AA060 File Offset: 0x001A8260
			private void QuestSuccessPlayerSoldTheProducts()
			{
				base.AddLog(this.QuestSuccessLogText, false);
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				this.RelationshipChangeWithQuestGiver = 5;
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._targetDenarsToAchieve, false);
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005B4A RID: 23370 RVA: 0x001AA0B0 File Offset: 0x001A82B0
			private void QuestFailedPlayerBrokeTheAgreement()
			{
				base.AddLog(this.QuestFailedPlayerBrokeTheAgreementLogText, false);
				base.QuestGiver.AddPower(-5f);
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._gatheredDenars, false);
				this.RelationshipChangeWithQuestGiver = -10 - this.RemainingDenars / 10;
				base.CompleteQuestWithFail(null);
				ChangeCrimeRatingAction.Apply(base.QuestGiver.MapFaction, 5f, true);
			}

			// Token: 0x06005B4B RID: 23371 RVA: 0x001AA124 File Offset: 0x001A8324
			private void PlayerPaidAgreedDenarsQuestSuccess()
			{
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._targetDenarsToAchieve, false);
				this.RelationshipChangeWithQuestGiver = 5;
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				base.AddLog(this.QuestSuccessWithPayingGatheredDenarsLogText, false);
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005B4C RID: 23372 RVA: 0x001AA173 File Offset: 0x001A8373
			private bool PlayerPayAgreedDenarsClickableCondition(out TextObject explanation)
			{
				if (Hero.MainHero.Gold < this._targetDenarsToAchieve)
				{
					explanation = new TextObject("{=d0kbtGYn}You don't have enough gold.", null);
					return false;
				}
				MBTextManager.SetTextVariable("REMAINING_DENARS", this.RemainingDenars);
				explanation = null;
				return true;
			}

			// Token: 0x06005B4D RID: 23373 RVA: 0x001AA1AA File Offset: 0x001A83AA
			private bool PlayerFailWithGoldClickableCondition(out TextObject explanation)
			{
				if (this._gatheredDenars > 0 && Hero.MainHero.Gold < this._gatheredDenars)
				{
					explanation = new TextObject("{=d0kbtGYn}You don't have enough gold.", null);
					return false;
				}
				explanation = null;
				return true;
			}

			// Token: 0x06005B4E RID: 23374 RVA: 0x001AA1DC File Offset: 0x001A83DC
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddTrackedObject(base.QuestGiver.CurrentSettlement);
				MobileParty.MainParty.ItemRoster.AddToCounts(this._selectedItemObject, this._selectedItemObjectCount);
				TextObject textObject = new TextObject("{=jKHkGzUn}As agreed, {SELECTED_ITEM_COUNT} {?IS_PLURAL}{.%}{PLURAL(SELECTED_ITEM)}{.%} have been{?}{.%}{SELECTED_ITEM}{.%} has been{\\?} added to your inventory.", null);
				textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				textObject.SetTextVariable("SELECTED_ITEM_COUNT", this._selectedItemObjectCount);
				textObject.SetTextVariable("IS_PLURAL", (this._selectedItemObjectCount > 1) ? 1 : 0);
				MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				base.AddLog(this.QuestStartedLogText1, false);
				base.AddLog(this.QuestStartedLogText2, false);
				base.AddLog(this.QuestStartedLogText3, false);
				TextObject textObject2 = new TextObject("{=GaXEmoFy}Sold {.%}{SELECTED_ITEM}{.%} amount:", null);
				textObject2.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				TextObject textObject3 = new TextObject("{=pwnqk0Nj}Gathered denars from {.%}{SELECTED_ITEM}{.%}", null);
				textObject3.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				this._soldItemAmountLog = base.AddDiscreteLog(TextObject.GetEmpty(), textObject2, this._soldCount, this._selectedItemObjectCount, null, false);
				this._gatheredDenarsLog = base.AddDiscreteLog(TextObject.GetEmpty(), textObject3, this._gatheredDenars, this._targetDenarsToAchieve, null, false);
			}

			// Token: 0x06005B4F RID: 23375 RVA: 0x001AA328 File Offset: 0x001A8528
			private void QuestFinishedPlayerBoughtTheGoods()
			{
				base.AddLog(this.QuestSuccessPlayerBoughtItemsLogText, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(this._selectedItemObject, this._selectedItemObjectCount);
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._targetDenarsToAchieve, false);
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				this.RelationshipChangeWithQuestGiver = 1;
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005B50 RID: 23376 RVA: 0x001AA393 File Offset: 0x001A8593
			private bool PlayerBuyClickableOptionCondition(out TextObject explanation)
			{
				if (Hero.MainHero.Gold < this._targetDenarsToAchieve)
				{
					explanation = new TextObject("{=d0kbtGYn}You don't have enough gold.", null);
					return false;
				}
				explanation = null;
				return true;
			}

			// Token: 0x06005B51 RID: 23377 RVA: 0x001AA3BA File Offset: 0x001A85BA
			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				this.RelationshipChangeWithQuestGiver = -10;
				CampaignEvents.WarDeclared.ClearListeners(this);
				ChangeCrimeRatingAction.Apply(base.QuestGiver.MapFaction, 5f, true);
			}

			// Token: 0x06005B52 RID: 23378 RVA: 0x001AA3F4 File Offset: 0x001A85F4
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.VillageBeingRaided.AddNonSerializedListener(this, new Action<Village>(this.OnVillageRaided));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnPlayerInventoryExchange));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			// Token: 0x06005B53 RID: 23379 RVA: 0x001AA474 File Offset: 0x001A8674
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005B54 RID: 23380 RVA: 0x001AA487 File Offset: 0x001A8687
			protected override void HourlyTick()
			{
				if (base.IsOngoing && !this._underSoldLogAdded && this.CheckIfPlayerLostItem())
				{
					base.AddLog(this.QuestReadyToBeFinishedUnderSoldLogText, false);
					this._daysPassed++;
					this._underSoldLogAdded = true;
				}
			}

			// Token: 0x06005B55 RID: 23381 RVA: 0x001AA4C4 File Offset: 0x001A86C4
			private bool CheckIfPlayerLostItem()
			{
				return this._soldCount + MobileParty.MainParty.ItemRoster.GetItemNumber(this._selectedItemObject) < this._selectedItemObjectCount;
			}

			// Token: 0x06005B56 RID: 23382 RVA: 0x001AA4EC File Offset: 0x001A86EC
			private void OnPlayerInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				if (isTrading && this.ItemCountLeftToSell > 0)
				{
					foreach (ValueTuple<ItemRosterElement, int> valueTuple in soldItems)
					{
						ItemRosterElement itemRosterElement = valueTuple.Item1;
						if (itemRosterElement.EquipmentElement.Item == this._selectedItemObject)
						{
							int soldCount = this._soldCount;
							itemRosterElement = valueTuple.Item1;
							this._soldCount = soldCount + itemRosterElement.Amount;
							this._gatheredDenars += valueTuple.Item2;
						}
					}
					if (this.ItemCountLeftToSell <= 0)
					{
						base.AddLog(this.QuestReadyToBeFinishedLogText, false);
					}
					this._productsUndersold = this._gatheredDenars < this._targetDenarsToAchieve;
					this._soldItemAmountLog.UpdateCurrentProgress(this._soldCount);
					this._gatheredDenarsLog.UpdateCurrentProgress(this._gatheredDenars);
				}
			}

			// Token: 0x06005B57 RID: 23383 RVA: 0x001AA5E0 File Offset: 0x001A87E0
			private void OnVillageRaided(Village village)
			{
				if (village == base.QuestGiver.CurrentSettlement.Village)
				{
					base.AddLog(this.QuestGiverVillageRaided, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005B58 RID: 23384 RVA: 0x001AA60A File Offset: 0x001A880A
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x06005B59 RID: 23385 RVA: 0x001AA639 File Offset: 0x001A8839
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x06005B5A RID: 23386 RVA: 0x001AA651 File Offset: 0x001A8851
			protected override void OnFinalize()
			{
			}

			// Token: 0x06005B5B RID: 23387 RVA: 0x001AA653 File Offset: 0x001A8853
			protected override void InitializeQuestOnGameLoad()
			{
				this._targetDenarsToAchieve = (int)((float)(this._selectedItemObject.Value * this._selectedItemObjectCount) * 0.55f);
				this._productsUndersold = this._gatheredDenars < this._targetDenarsToAchieve;
				this.SetDialogs();
			}

			// Token: 0x04001D56 RID: 7510
			[SaveableField(10)]
			private ItemObject _selectedItemObject;

			// Token: 0x04001D57 RID: 7511
			[SaveableField(20)]
			private int _selectedItemObjectCount;

			// Token: 0x04001D58 RID: 7512
			[SaveableField(30)]
			private int _soldCount;

			// Token: 0x04001D59 RID: 7513
			[SaveableField(40)]
			private int _gatheredDenars;

			// Token: 0x04001D5A RID: 7514
			private bool _productsUndersold = true;

			// Token: 0x04001D5B RID: 7515
			[SaveableField(60)]
			private int _daysPassed;

			// Token: 0x04001D5C RID: 7516
			[SaveableField(70)]
			private bool _underSoldLogAdded;

			// Token: 0x04001D5D RID: 7517
			private int _targetDenarsToAchieve;

			// Token: 0x04001D5E RID: 7518
			[SaveableField(80)]
			private JournalLog _soldItemAmountLog;

			// Token: 0x04001D5F RID: 7519
			[SaveableField(90)]
			private JournalLog _gatheredDenarsLog;
		}

		// Token: 0x0200072C RID: 1836
		public class LandLordTheArtOfTheTradeIssueBehaviorTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005B5C RID: 23388 RVA: 0x001AA68F File Offset: 0x001A888F
			public LandLordTheArtOfTheTradeIssueBehaviorTypeDefiner()
				: base(249000)
			{
			}

			// Token: 0x06005B5D RID: 23389 RVA: 0x001AA69C File Offset: 0x001A889C
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue), 1, null);
				base.AddClassDefinition(typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest), 2, null);
			}
		}
	}
}
