using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x0200036B RID: 875
	public class LandLordNeedsManualLaborersIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060033AA RID: 13226 RVA: 0x000D4CF0 File Offset: 0x000D2EF0
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060033AB RID: 13227 RVA: 0x000D4D09 File Offset: 0x000D2F09
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x060033AC RID: 13228 RVA: 0x000D4D0C File Offset: 0x000D2F0C
		private bool ConditionsHold(Hero issueGiver)
		{
			if (issueGiver.CurrentSettlement != null && issueGiver.IsRuralNotable && issueGiver.GetTraitLevel(DefaultTraits.Mercy) <= 0)
			{
				Village village = issueGiver.CurrentSettlement.Village;
				return village != null && (village.VillageType == DefaultVillageTypes.IronMine || village.VillageType == DefaultVillageTypes.ClayMine || village.VillageType == DefaultVillageTypes.SaltMine || village.VillageType == DefaultVillageTypes.SilverMine);
			}
			return false;
		}

		// Token: 0x060033AD RID: 13229 RVA: 0x000D4D80 File Offset: 0x000D2F80
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x060033AE RID: 13230 RVA: 0x000D4DE4 File Offset: 0x000D2FE4
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue(issueOwner);
		}

		// Token: 0x04000ECC RID: 3788
		private const IssueBase.IssueFrequency NeedsLaborersIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000727 RID: 1831
		public class LandLordNeedsManualLaborersIssue : IssueBase
		{
			// Token: 0x06005AB0 RID: 23216 RVA: 0x001A7BF0 File Offset: 0x001A5DF0
			internal static void AutoGeneratedStaticCollectObjectsLandLordNeedsManualLaborersIssue(object o, List<object> collectedObjects)
			{
				((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005AB1 RID: 23217 RVA: 0x001A7BFE File Offset: 0x001A5DFE
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x170011B3 RID: 4531
			// (get) Token: 0x06005AB2 RID: 23218 RVA: 0x001A7C07 File Offset: 0x001A5E07
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.RequiredTroops;
				}
			}

			// Token: 0x170011B4 RID: 4532
			// (get) Token: 0x06005AB3 RID: 23219 RVA: 0x001A7C0A File Offset: 0x001A5E0A
			private int RequestedPrisonerCount
			{
				get
				{
					return 6 + MathF.Ceiling(30f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170011B5 RID: 4533
			// (get) Token: 0x06005AB4 RID: 23220 RVA: 0x001A7C1F File Offset: 0x001A5E1F
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 8 + MathF.Ceiling(12f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170011B6 RID: 4534
			// (get) Token: 0x06005AB5 RID: 23221 RVA: 0x001A7C34 File Offset: 0x001A5E34
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 5 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170011B7 RID: 4535
			// (get) Token: 0x06005AB6 RID: 23222 RVA: 0x001A7C49 File Offset: 0x001A5E49
			protected override int RewardGold
			{
				get
				{
					return this.RequestedPrisonerCount * 50;
				}
			}

			// Token: 0x170011B8 RID: 4536
			// (get) Token: 0x06005AB7 RID: 23223 RVA: 0x001A7C54 File Offset: 0x001A5E54
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject;
					if (base.IssueOwner.CharacterObject.GetTraitLevel(DefaultTraits.Mercy) < 0)
					{
						textObject = new TextObject("{=QEhapwtN}I own a mine near here. Normally I can find willing villagers to work it, but these days they've been demanding higher and higher wages. Fine. They're out of a job, but I still need to work the mine. If you could perhaps find me some prisoners...[if:convo_normal][ib:confident2]", null);
					}
					else
					{
						textObject = new TextObject("{=1LFcSRPw}I have a mine near here. We had an unfortunate accident a week back. Two workers were crushed to death. It's a great shame... but work must go on. Trouble is, no one wants to come back. If perhaps you could find me some prisoners...[if:convo_thinking][ib:hip]", null);
					}
					return textObject;
				}
			}

			// Token: 0x170011B9 RID: 4537
			// (get) Token: 0x06005AB8 RID: 23224 RVA: 0x001A7C94 File Offset: 0x001A5E94
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=DSMMIrz9}Prisoners... You want criminals or war captives?", null);
				}
			}

			// Token: 0x170011BA RID: 4538
			// (get) Token: 0x06005AB9 RID: 23225 RVA: 0x001A7CA1 File Offset: 0x001A5EA1
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=ji5kkqXy}They need to be criminals, bandits, for me to do this legally. I need at least {WANTED_PRISONER_AMOUNT} of them. But if you can bring more I will gladly accept. I'm willing to pay five times more than their market price for each. What do you say?[if:convo_nonchalant]", null);
					textObject.SetTextVariable("WANTED_PRISONER_AMOUNT", this.RequestedPrisonerCount);
					return textObject;
				}
			}

			// Token: 0x170011BB RID: 4539
			// (get) Token: 0x06005ABA RID: 23226 RVA: 0x001A7CC0 File Offset: 0x001A5EC0
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=WpidwcAV}If you have a companion who understands this type of work and {ALTERNATIVE_TROOP_AMOUNT} men, I can tell them where to go to get their hands on some prisoners.", null);
					textObject.SetTextVariable("ALTERNATIVE_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					return textObject;
				}
			}

			// Token: 0x170011BC RID: 4540
			// (get) Token: 0x06005ABB RID: 23227 RVA: 0x001A7CDF File Offset: 0x001A5EDF
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=C06TxxnM}I'll bring you at least {WANTED_PRISONER_AMOUNT} prisoners as soon as possible.", null);
					textObject.SetTextVariable("WANTED_PRISONER_AMOUNT", this.RequestedPrisonerCount);
					return textObject;
				}
			}

			// Token: 0x170011BD RID: 4541
			// (get) Token: 0x06005ABC RID: 23228 RVA: 0x001A7CFE File Offset: 0x001A5EFE
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=QH3shVzb}My people can bring you your laborers.", null);
				}
			}

			// Token: 0x170011BE RID: 4542
			// (get) Token: 0x06005ABD RID: 23229 RVA: 0x001A7D0B File Offset: 0x001A5F0B
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=XXOlu6z0}Thank you for sparing some of your men to save my business. I am looking forward to resuming work.[if:convo_mocking_teasing]", null);
				}
			}

			// Token: 0x170011BF RID: 4543
			// (get) Token: 0x06005ABE RID: 23230 RVA: 0x001A7D18 File Offset: 0x001A5F18
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=PrzguaEq}Thank you. I appreciate your people's help.", null);
				}
			}

			// Token: 0x170011C0 RID: 4544
			// (get) Token: 0x06005ABF RID: 23231 RVA: 0x001A7D25 File Offset: 0x001A5F25
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x170011C1 RID: 4545
			// (get) Token: 0x06005AC0 RID: 23232 RVA: 0x001A7D28 File Offset: 0x001A5F28
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170011C2 RID: 4546
			// (get) Token: 0x06005AC1 RID: 23233 RVA: 0x001A7D2C File Offset: 0x001A5F2C
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=MYeCnHTb}You asked {COMPANION.LINK} to deliver at least {WANTED_PRISONER_AMOUNT} prisoners to {ISSUE_GIVER.LINK} in {SETTLEMENT}. They should rejoin your party in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("WANTED_PRISONER_AMOUNT", this.RequestedPrisonerCount);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x170011C3 RID: 4547
			// (get) Token: 0x06005AC2 RID: 23234 RVA: 0x001A7DB6 File Offset: 0x001A5FB6
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=hVIsGd2y}Landowner Needs Manual Laborers", null);
				}
			}

			// Token: 0x170011C4 RID: 4548
			// (get) Token: 0x06005AC3 RID: 23235 RVA: 0x001A7DC3 File Offset: 0x001A5FC3
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=5of4a1kg}A landowner needs your help to find prisoners to use in {?ISSUE_GIVER.GENDER}her{?}his{\\?} mines as manual laborers.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, null, false);
					return textObject;
				}
			}

			// Token: 0x06005AC4 RID: 23236 RVA: 0x001A7DE8 File Offset: 0x001A5FE8
			public LandLordNeedsManualLaborersIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
			}

			// Token: 0x06005AC5 RID: 23237 RVA: 0x001A7DFB File Offset: 0x001A5FFB
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.VillageHearth)
				{
					return -0.3f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005AC6 RID: 23238 RVA: 0x001A7E1E File Offset: 0x001A601E
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Athletics) >= hero.GetSkillValue(DefaultSkills.Leadership)) ? DefaultSkills.Athletics : DefaultSkills.Leadership, 120);
			}

			// Token: 0x06005AC7 RID: 23239 RVA: 0x001A7E4B File Offset: 0x001A604B
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005AC8 RID: 23240 RVA: 0x001A7E5C File Offset: 0x001A605C
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005AC9 RID: 23241 RVA: 0x001A7E76 File Offset: 0x001A6076
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x06005ACA RID: 23242 RVA: 0x001A7E84 File Offset: 0x001A6084
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005ACB RID: 23243 RVA: 0x001A7E87 File Offset: 0x001A6087
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid;
			}

			// Token: 0x06005ACC RID: 23244 RVA: 0x001A7EB0 File Offset: 0x001A60B0
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005ACD RID: 23245 RVA: 0x001A7F04 File Offset: 0x001A6104
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005ACE RID: 23246 RVA: 0x001A7F06 File Offset: 0x001A6106
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005ACF RID: 23247 RVA: 0x001A7F08 File Offset: 0x001A6108
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(20f), this.RequestedPrisonerCount);
			}

			// Token: 0x06005AD0 RID: 23248 RVA: 0x001A7F26 File Offset: 0x001A6126
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x170011C5 RID: 4549
			// (get) Token: 0x06005AD1 RID: 23249 RVA: 0x001A7F28 File Offset: 0x001A6128
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06005AD2 RID: 23250 RVA: 0x001A7F3D File Offset: 0x001A613D
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.IssueOwner.AddPower(10f);
				this.RelationshipChangeWithIssueOwner = 5;
			}

			// Token: 0x04001D44 RID: 7492
			private const int IssueDuration = 30;

			// Token: 0x04001D45 RID: 7493
			private const int QuestDuration = 20;

			// Token: 0x04001D46 RID: 7494
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x04001D47 RID: 7495
			private const int CompanionRequiredSkillLevel = 120;
		}

		// Token: 0x02000728 RID: 1832
		public class LandLordNeedsManualLaborersIssueQuest : QuestBase
		{
			// Token: 0x06005AD3 RID: 23251 RVA: 0x001A7F76 File Offset: 0x001A6176
			internal static void AutoGeneratedStaticCollectObjectsLandLordNeedsManualLaborersIssueQuest(object o, List<object> collectedObjects)
			{
				((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005AD4 RID: 23252 RVA: 0x001A7F84 File Offset: 0x001A6184
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._questProgressLogTest);
			}

			// Token: 0x06005AD5 RID: 23253 RVA: 0x001A7F99 File Offset: 0x001A6199
			internal static object AutoGeneratedGetMemberValue_requestedPrisonerCount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._requestedPrisonerCount;
			}

			// Token: 0x06005AD6 RID: 23254 RVA: 0x001A7FAB File Offset: 0x001A61AB
			internal static object AutoGeneratedGetMemberValue_shareProfit(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._shareProfit;
			}

			// Token: 0x06005AD7 RID: 23255 RVA: 0x001A7FBD File Offset: 0x001A61BD
			internal static object AutoGeneratedGetMemberValue_counterOfferGiven(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._counterOfferGiven;
			}

			// Token: 0x06005AD8 RID: 23256 RVA: 0x001A7FCF File Offset: 0x001A61CF
			internal static object AutoGeneratedGetMemberValue_deliveredPrisonerCount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._deliveredPrisonerCount;
			}

			// Token: 0x06005AD9 RID: 23257 RVA: 0x001A7FE1 File Offset: 0x001A61E1
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._rewardGold;
			}

			// Token: 0x06005ADA RID: 23258 RVA: 0x001A7FF3 File Offset: 0x001A61F3
			internal static object AutoGeneratedGetMemberValue_maximumPrisonerCount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._maximumPrisonerCount;
			}

			// Token: 0x06005ADB RID: 23259 RVA: 0x001A8005 File Offset: 0x001A6205
			internal static object AutoGeneratedGetMemberValue_playerReachedMaximumAmount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._playerReachedMaximumAmount;
			}

			// Token: 0x06005ADC RID: 23260 RVA: 0x001A8017 File Offset: 0x001A6217
			internal static object AutoGeneratedGetMemberValue_questProgressLogTest(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._questProgressLogTest;
			}

			// Token: 0x170011C6 RID: 4550
			// (get) Token: 0x06005ADD RID: 23261 RVA: 0x001A8024 File Offset: 0x001A6224
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=hVIsGd2y}Landowner Needs Manual Laborers", null);
				}
			}

			// Token: 0x170011C7 RID: 4551
			// (get) Token: 0x06005ADE RID: 23262 RVA: 0x001A8031 File Offset: 0x001A6231
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170011C8 RID: 4552
			// (get) Token: 0x06005ADF RID: 23263 RVA: 0x001A8034 File Offset: 0x001A6234
			private bool IsQuestWithCounterOffer
			{
				get
				{
					if (base.QuestGiver.CharacterObject.GetTraitLevel(DefaultTraits.Mercy) < 0)
					{
						return base.QuestGiver.CurrentSettlement.Notables.FirstOrDefault<Hero>((Hero x) => x.IsHeadman) != null;
					}
					return false;
				}
			}

			// Token: 0x170011C9 RID: 4553
			// (get) Token: 0x06005AE0 RID: 23264 RVA: 0x001A8094 File Offset: 0x001A6294
			private TextObject QuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=7XR4MJci}{QUEST_GIVER.LINK}, a landowner in {SETTLEMENT}, told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs prisoners to use in {?QUEST_GIVER.GENDER}her{?}his{\\?} mines as manual laborers. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to bring at least {NEEDED_PRISONER_AMOUNT} bandit prisoners, but {?QUEST_GIVER.GENDER}she{?}he{\\?} will pay extra if you bring more. You have agreed to bring {?QUEST_GIVER.GENDER}her{?}him{\\?} at least {NEEDED_PRISONER_AMOUNT} bandit prisoner and you will be paid five times more than their market price for each prisoner you bring.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("NEEDED_PRISONER_AMOUNT", this._requestedPrisonerCount);
					return textObject;
				}
			}

			// Token: 0x170011CA RID: 4554
			// (get) Token: 0x06005AE1 RID: 23265 RVA: 0x001A80F4 File Offset: 0x001A62F4
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011CB RID: 4555
			// (get) Token: 0x06005AE2 RID: 23266 RVA: 0x001A8128 File Offset: 0x001A6328
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011CC RID: 4556
			// (get) Token: 0x06005AE3 RID: 23267 RVA: 0x001A815C File Offset: 0x001A635C
			private TextObject QuestGiverVillageRaided
			{
				get
				{
					TextObject textObject = new TextObject("{=gJG0xmAq}{QUEST_GIVER.LINK}'s village {QUEST_SETTLEMENT} was raided. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x170011CD RID: 4557
			// (get) Token: 0x06005AE4 RID: 23268 RVA: 0x001A81AC File Offset: 0x001A63AC
			private TextObject QuestSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=ucu9u1nS}You delivered the prisoners to {QUEST_GIVER.LINK} as promised.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011CE RID: 4558
			// (get) Token: 0x06005AE5 RID: 23269 RVA: 0x001A81DE File Offset: 0x001A63DE
			private TextObject PlayerSharedTheProfitWithHeadManLogText
			{
				get
				{
					return new TextObject("{=ULpP07bg}You promised to share half of the profit with the headman and the villager.", null);
				}
			}

			// Token: 0x170011CF RID: 4559
			// (get) Token: 0x06005AE6 RID: 23270 RVA: 0x001A81EC File Offset: 0x001A63EC
			private TextObject QuestSuccessWithProfitShareLog
			{
				get
				{
					TextObject textObject = new TextObject("{=SyuxD1aY}You delivered the prisoners to {QUEST_GIVER.LINK} as promised and you shared half of the profit with the headman and the villagers.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011D0 RID: 4560
			// (get) Token: 0x06005AE7 RID: 23271 RVA: 0x001A8220 File Offset: 0x001A6420
			private TextObject QuestFailPlayerAcceptedCounterOfferLog
			{
				get
				{
					TextObject textObject = new TextObject("{=u8DJ8a2D}You agreed with the headman to break your agreement with {QUEST_GIVER.LINK}. By doing so you protected the villagers' jobs and now they are grateful to you.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011D1 RID: 4561
			// (get) Token: 0x06005AE8 RID: 23272 RVA: 0x001A8254 File Offset: 0x001A6454
			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=b1lsZNxE}You failed to deliver enough prisoners in time. {QUEST_GIVER.LINK} must be disappointed.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170011D2 RID: 4562
			// (get) Token: 0x06005AE9 RID: 23273 RVA: 0x001A8288 File Offset: 0x001A6488
			private TextObject QuestDeliveredRequestedPrisonersLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=YiPUbIII}You have delivered the requested number of prisoners to {QUEST_GIVER.LINK}. You may settle your accounts with {?QUEST_GIVER.GENDER}her{?}him{\\?} at any point to receive your pay, or continue to bring more captives.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x06005AEA RID: 23274 RVA: 0x001A82BC File Offset: 0x001A64BC
			public LandLordNeedsManualLaborersIssueQuest(string questId, Hero giverHero, CampaignTime duration, int requestedPrisonerCount)
				: base(questId, giverHero, duration, 0)
			{
				this._requestedPrisonerCount = requestedPrisonerCount;
				this._shareProfit = false;
				this._deliveredPrisonerCount = 0;
				this._rewardGold = 0;
				this._counterOfferGiven = false;
				this._maximumPrisonerCount = MBRandom.RandomInt(40, 60);
				this._playerReachedMaximumAmount = false;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005AEB RID: 23275 RVA: 0x001A831C File Offset: 0x001A651C
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddTrackedObject(base.QuestGiver.CurrentSettlement);
				TextObject textObject = new TextObject("{=N4eLGduQ}Delivered Prisoners ({TOTAL_REWARD}{GOLD_ICON})", null);
				textObject.SetTextVariable("TOTAL_REWARD", this._rewardGold);
				textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
				this._questProgressLogTest = base.AddDiscreteLog(this.QuestStartedLogText, textObject, this._deliveredPrisonerCount, this._requestedPrisonerCount, null, false);
			}

			// Token: 0x06005AEC RID: 23276 RVA: 0x001A8390 File Offset: 0x001A6590
			private DialogFlow GetCounterOfferDialogFlow()
			{
				TextObject textObject = new TextObject("{=aJHMafam}{?PLAYER.GENDER}Madam{?}Sir{\\?} - a moment of your time! [if:convo_undecided_open][ib:nervous2]You're on a job for {ISSUE_GIVER.LINK}, am I right? Look - our people are depending on those jobs. {?ISSUE_GIVER.GENDER}She{?}He{\\?} doesn't need to pay us a living wage if {?ISSUE_GIVER.GENDER}she{?}he{\\?} can do the work with prisoners. Please - break your agreement. You don't have to do this.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
				StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				TextObject textObject2 = new TextObject("{=8BdJ2MZj}I don't want to hurt your people. I'll forget my deal with {ISSUE_GIVER.LINK}.", null);
				StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject, null, null, null, null).Condition(delegate
				{
					if (!this._counterOfferGiven && Hero.OneToOneConversationHero != null)
					{
						return Hero.OneToOneConversationHero == base.QuestGiver.CurrentSettlement.Notables.FirstOrDefault<Hero>((Hero x) => x.IsHeadman);
					}
					return false;
				})
					.Consequence(delegate
					{
						this._counterOfferGiven = true;
					})
					.BeginPlayerOptions(null, false)
					.PlayerOption("{=rOWyAHPo}Mind your own business, Headman.", null, null, null)
					.NpcLine("{=tLapkQqg}We won't forget this![if:convo_thinking][ib:aggressive]", null, null, null, null)
					.Consequence(delegate
					{
						ChangeRelationAction.ApplyPlayerRelation(Hero.OneToOneConversationHero, -3, true, true);
					})
					.CloseDialog()
					.PlayerOption("{=I3GUAb9a}I understand your concern, Headman, but I made an agreement. How about I share the profit with you and your people?", null, null, null)
					.NpcLine("{=MmQt0TD3}This is not we want, but it's more than nothing.[if:convo_dismayed][ib:normal]", null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.ShareTheProfit))
					.CloseDialog()
					.PlayerOption(textObject2, null, null, null)
					.NpcLine("{=E5yAFR6y}Good to hear that. Thank you.[if:convo_relaxed_happy][ib:normal]", null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestFailPlayerAcceptedCounterOffer))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005AED RID: 23277 RVA: 0x001A84E2 File Offset: 0x001A66E2
			private void ShareTheProfit()
			{
				base.AddLog(this.PlayerSharedTheProfitWithHeadManLogText, false);
				ChangeRelationAction.ApplyPlayerRelation(Hero.OneToOneConversationHero, 3, true, true);
				this._shareProfit = true;
			}

			// Token: 0x06005AEE RID: 23278 RVA: 0x001A8508 File Offset: 0x001A6708
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=l7dL6arZ}Thank you. Remember - they need to be looters or bandits. Anyone else I can't put to work.[if:convo_mocking_teasing][ib:closed]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == this.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				TextObject npcDiscussLine = new TextObject("{=!}{MANUAL_LABORERS_QUEST_NOTABLE_DISCUSS}", null);
				TextObject npcResponseLine = new TextObject("{=!}{MANUAL_LABORERS_QUEST_NOTABLE_RESPONSE}", null);
				bool changeDialogAfterTransfer = false;
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).BeginNpcOptions(null, false).NpcOption(new TextObject("{=VRLbAaYe}Thank you for saving my business {?PLAYER.GENDER}madam{?}sir{\\?}. Here is your payment.", null), () => Hero.OneToOneConversationHero == this.QuestGiver && this._playerReachedMaximumAmount, null, null, null, null)
					.Consequence(delegate
					{
						this.ApplyQuestSuccessConsequences();
						this.CompleteQuestWithSuccess();
					})
					.CloseDialog()
					.NpcOption(npcDiscussLine, delegate
					{
						if (Hero.OneToOneConversationHero != this.QuestGiver)
						{
							return false;
						}
						if (!changeDialogAfterTransfer)
						{
							npcDiscussLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_DISCUSS", new TextObject("{=B0YOpGsZ}Any news about my prisoners?[if:convo_mocking_teasing][ib:hip]", null));
						}
						else
						{
							npcDiscussLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_DISCUSS", new TextObject("{=ds294zxi}Anything else?", null));
							changeDialogAfterTransfer = false;
						}
						return true;
					}, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=QbaOoilS}Yes, I have brought you a few men.", null), null, null, null)
					.Condition(() => this.CheckIfThereIsSuitablePrisonerInPlayer() && !this._playerReachedMaximumAmount)
					.NpcLine(npcResponseLine, null, null, null, null)
					.Condition(delegate
					{
						if (this._playerReachedMaximumAmount)
						{
							return false;
						}
						if ((float)this._deliveredPrisonerCount < (float)this._maximumPrisonerCount * 0.75f)
						{
							npcResponseLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_RESPONSE", new TextObject("{=0ewaZnfe}Very good. Keep them coming.[if:convo_mocking_aristocratic]", null));
						}
						else
						{
							TextObject textObject = new TextObject("{=CBBPWMZd}Thanks to you, my mines are full {?PLAYER.GENDER}madam{?}sir{\\?}. I will only buy {X} more, then we're done.", null);
							textObject.SetTextVariable("X", this._maximumPrisonerCount - this._deliveredPrisonerCount);
							npcResponseLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_RESPONSE", textObject);
							changeDialogAfterTransfer = false;
						}
						return true;
					})
					.PlayerLine(new TextObject("{=IULW8h03}Sure.", null), null, null, null)
					.Consequence(delegate
					{
						changeDialogAfterTransfer = true;
						this.OpenPrisonerDeliveryScreen();
					})
					.NpcLine(new TextObject("{=!}Party screen goes here.", null), null, null, null, null)
					.GotoDialogState("quest_discuss")
					.PlayerOption(new TextObject("{=UOE7ejgq}Here is all I've got. Let's settle up and finish this business.", null), null, null, null)
					.Condition(() => !this._playerReachedMaximumAmount && this._deliveredPrisonerCount >= this._requestedPrisonerCount)
					.NpcLine(new TextObject("{=YZ6UmX5o}Certainly. Here is your payment as I promised. Thank you.[if:convo_mocking_teasing][ib:confident3]", null), null, null, null, null)
					.Consequence(delegate
					{
						this.ApplyQuestSuccessConsequences();
						this.CompleteQuestWithSuccess();
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=wErSpkjy}I'm still working on it.", null), null, null, null)
					.NpcLine(new TextObject("{=oiLdjqwe}I am glad to hear that.[if:convo_nonchalant]", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions();
				if (this.IsQuestWithCounterOffer)
				{
					this.QuestCharacterDialogFlow = this.GetCounterOfferDialogFlow();
				}
			}

			// Token: 0x06005AEF RID: 23279 RVA: 0x001A8724 File Offset: 0x001A6924
			private void OpenPrisonerDeliveryScreen()
			{
				PartyScreenHelper.OpenScreenWithCondition(new IsTroopTransferableDelegate(this.IsTroopTransferable), new PartyPresentationDoneButtonConditionDelegate(this.DoneButtonCondition), new PartyPresentationDoneButtonDelegate(this.OnDoneClicked), new PartyPresentationCancelButtonDelegate(this.OnCancelClicked), PartyScreenLogic.TransferState.NotTransferable, PartyScreenLogic.TransferState.Transferable, base.QuestGiver.Name, this._maximumPrisonerCount - this._deliveredPrisonerCount, true, false, PartyScreenHelper.PartyScreenMode.PrisonerManage, null, null);
			}

			// Token: 0x06005AF0 RID: 23280 RVA: 0x001A8785 File Offset: 0x001A6985
			private void OnCancelClicked()
			{
				Campaign.Current.ConversationManager.ContinueConversation();
			}

			// Token: 0x06005AF1 RID: 23281 RVA: 0x001A8798 File Offset: 0x001A6998
			private Tuple<bool, TextObject> DoneButtonCondition(TroopRoster leftMemberRoster, TroopRoster leftPrisonRoster, TroopRoster rightMemberRoster, TroopRoster rightPrisonRoster, int leftLimitNum, int rightLimitNum)
			{
				if (this._maximumPrisonerCount - this._deliveredPrisonerCount < leftPrisonRoster.TotalManCount)
				{
					int num = this._maximumPrisonerCount - this._deliveredPrisonerCount;
					TextObject textObject = new TextObject("{=bgXebaRF}You can only transfer {X} prisoner{?IS_PLURAL}s{?}{\\?}.", null);
					textObject.SetTextVariable("IS_PLURAL", (num > 1) ? 1 : 0);
					textObject.SetTextVariable("X", num);
					return new Tuple<bool, TextObject>(false, textObject);
				}
				return new Tuple<bool, TextObject>(true, null);
			}

			// Token: 0x06005AF2 RID: 23282 RVA: 0x001A8804 File Offset: 0x001A6A04
			private bool OnDoneClicked(TroopRoster leftMemberRoster, TroopRoster leftPrisonRoster, TroopRoster rightMemberRoster, TroopRoster rightPrisonRoster, FlattenedTroopRoster takenPrisonerRoster, FlattenedTroopRoster releasedPrisonerRoster, bool isForced, PartyBase leftParty, PartyBase rightParty)
			{
				foreach (TroopRosterElement troopRosterElement in leftPrisonRoster.GetTroopRoster())
				{
					this._rewardGold += (int)((float)(Campaign.Current.Models.RansomValueCalculationModel.PrisonerRansomValue(troopRosterElement.Character, Hero.MainHero) * troopRosterElement.Number) * 5f);
				}
				int deliveredPrisonerCount = this._deliveredPrisonerCount;
				this._deliveredPrisonerCount += releasedPrisonerRoster.Count<FlattenedTroopRosterElement>();
				int deliveredPrisonerCount2 = this._deliveredPrisonerCount;
				bool flag = deliveredPrisonerCount < this._requestedPrisonerCount && deliveredPrisonerCount2 >= this._requestedPrisonerCount;
				if (deliveredPrisonerCount2 != this._maximumPrisonerCount && flag)
				{
					base.AddLog(this.QuestDeliveredRequestedPrisonersLogText, false);
				}
				this._questProgressLogTest.UpdateCurrentProgress(this._deliveredPrisonerCount);
				this._questProgressLogTest.TaskName.SetTextVariable("TOTAL_REWARD", this._rewardGold);
				if (this._deliveredPrisonerCount == this._maximumPrisonerCount)
				{
					this._playerReachedMaximumAmount = true;
				}
				Campaign.Current.ConversationManager.ContinueConversation();
				return true;
			}

			// Token: 0x06005AF3 RID: 23283 RVA: 0x001A8938 File Offset: 0x001A6B38
			private bool IsTroopTransferable(CharacterObject character, PartyScreenLogic.TroopType type, PartyScreenLogic.PartyRosterSide side, PartyBase leftOwnerParty)
			{
				return side == PartyScreenLogic.PartyRosterSide.Left || (this._maximumPrisonerCount - this._deliveredPrisonerCount >= 0 && MobileParty.MainParty.PrisonRoster.Contains(character) && character.Occupation == Occupation.Bandit);
			}

			// Token: 0x06005AF4 RID: 23284 RVA: 0x001A8970 File Offset: 0x001A6B70
			private bool CheckIfThereIsSuitablePrisonerInPlayer()
			{
				bool flag = false;
				using (List<TroopRosterElement>.Enumerator enumerator = MobileParty.MainParty.PrisonRoster.GetTroopRoster().GetEnumerator())
				{
					while (enumerator.MoveNext())
					{
						if (enumerator.Current.Character.Occupation == Occupation.Bandit)
						{
							flag = true;
							break;
						}
					}
				}
				return flag;
			}

			// Token: 0x06005AF5 RID: 23285 RVA: 0x001A89DC File Offset: 0x001A6BDC
			private void ApplyQuestSuccessConsequences()
			{
				if (this._shareProfit)
				{
					base.AddLog(this.QuestSuccessWithProfitShareLog, false);
					TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
					{
						new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
					});
					GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold / 2, false);
					if (this.IsQuestWithCounterOffer)
					{
						base.QuestGiver.CurrentSettlement.Notables.First<Hero>((Hero x) => x.IsHeadman).AddPower(5f);
					}
				}
				else
				{
					base.AddLog(this.QuestSuccessLog, false);
					TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
					{
						new Tuple<TraitObject, int>(DefaultTraits.Honor, 30),
						new Tuple<TraitObject, int>(DefaultTraits.Mercy, -20)
					});
					GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
					if (this.IsQuestWithCounterOffer && this._counterOfferGiven)
					{
						ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver.CurrentSettlement.Notables.First<Hero>((Hero x) => x.IsHeadman), -5, true, true);
						base.QuestGiver.CurrentSettlement.Notables.First<Hero>((Hero x) => x.IsHeadman).AddPower(-10f);
					}
				}
				base.QuestGiver.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = 5;
			}

			// Token: 0x06005AF6 RID: 23286 RVA: 0x001A8B78 File Offset: 0x001A6D78
			private void QuestFailPlayerAcceptedCounterOffer()
			{
				base.AddLog(this.QuestFailPlayerAcceptedCounterOfferLog, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Mercy, 20),
					new Tuple<TraitObject, int>(DefaultTraits.Generosity, 20),
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -10)
				});
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -3;
				Hero hero = base.QuestGiver.CurrentSettlement.Notables.First<Hero>((Hero x) => x.IsHeadman);
				hero.AddPower(10f);
				ChangeRelationAction.ApplyPlayerRelation(hero, 5, true, true);
				base.CompleteQuestWithFail(null);
			}

			// Token: 0x06005AF7 RID: 23287 RVA: 0x001A8C37 File Offset: 0x001A6E37
			protected override void OnBeforeTimedOut(ref bool completeWithSuccess, ref bool doNotResolveTheQuest)
			{
				if (this._deliveredPrisonerCount >= this._requestedPrisonerCount)
				{
					completeWithSuccess = true;
					this.ApplyQuestSuccessConsequences();
				}
			}

			// Token: 0x06005AF8 RID: 23288 RVA: 0x001A8C50 File Offset: 0x001A6E50
			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
			}

			// Token: 0x06005AF9 RID: 23289 RVA: 0x001A8C78 File Offset: 0x001A6E78
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005AFA RID: 23290 RVA: 0x001A8C7C File Offset: 0x001A6E7C
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.VillageBeingRaided.AddNonSerializedListener(this, new Action<Village>(this.OnVillageRaided));
				CampaignEvents.GameMenuOpened.AddNonSerializedListener(this, new Action<MenuCallbackArgs>(this.OnGameMenuOpened));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			// Token: 0x06005AFB RID: 23291 RVA: 0x001A8CFC File Offset: 0x001A6EFC
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005AFC RID: 23292 RVA: 0x001A8D10 File Offset: 0x001A6F10
			private void OnGameMenuOpened(MenuCallbackArgs args)
			{
				if (this.IsQuestWithCounterOffer && !this._counterOfferGiven && args.MenuContext.GameMenu.StringId == "village" && Settlement.CurrentSettlement == base.QuestGiver.CurrentSettlement && Campaign.Current.GameMenuManager.NextLocation == null && GameStateManager.Current.ActiveState is MapState && PlayerEncounter.EncounterSettlement != null && this.CheckIfThereIsSuitablePrisonerInPlayer())
				{
					Hero hero = base.QuestGiver.CurrentSettlement.Notables.First<Hero>((Hero x) => x.IsHeadman);
					CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, PartyBase.MainParty, false, false, false, false, false, false), new ConversationCharacterData(hero.CharacterObject, null, false, false, false, false, false, false));
				}
			}

			// Token: 0x06005AFD RID: 23293 RVA: 0x001A8DFC File Offset: 0x001A6FFC
			private void OnVillageRaided(Village village)
			{
				if (village == base.QuestGiver.CurrentSettlement.Village)
				{
					base.AddLog(this.QuestGiverVillageRaided, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005AFE RID: 23294 RVA: 0x001A8E26 File Offset: 0x001A7026
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x06005AFF RID: 23295 RVA: 0x001A8E55 File Offset: 0x001A7055
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x06005B00 RID: 23296 RVA: 0x001A8E6D File Offset: 0x001A706D
			protected override void OnFinalize()
			{
			}

			// Token: 0x06005B01 RID: 23297 RVA: 0x001A8E6F File Offset: 0x001A706F
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x04001D48 RID: 7496
			private const int MaximumPrisonerLimitMinValue = 40;

			// Token: 0x04001D49 RID: 7497
			private const int MaximumPrisonerLimitMaxValue = 60;

			// Token: 0x04001D4A RID: 7498
			[SaveableField(1)]
			private int _requestedPrisonerCount;

			// Token: 0x04001D4B RID: 7499
			[SaveableField(2)]
			private bool _shareProfit;

			// Token: 0x04001D4C RID: 7500
			[SaveableField(4)]
			private bool _counterOfferGiven;

			// Token: 0x04001D4D RID: 7501
			[SaveableField(5)]
			private int _deliveredPrisonerCount;

			// Token: 0x04001D4E RID: 7502
			[SaveableField(6)]
			private int _rewardGold;

			// Token: 0x04001D4F RID: 7503
			[SaveableField(8)]
			private int _maximumPrisonerCount;

			// Token: 0x04001D50 RID: 7504
			[SaveableField(9)]
			private bool _playerReachedMaximumAmount;

			// Token: 0x04001D51 RID: 7505
			private const float _questPrisonerValueMultiplier = 5f;

			// Token: 0x04001D52 RID: 7506
			[SaveableField(7)]
			private JournalLog _questProgressLogTest;
		}

		// Token: 0x02000729 RID: 1833
		public class LandLordNeedsManualLaborersIssueBehaviorTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005B04 RID: 23300 RVA: 0x001A8EDA File Offset: 0x001A70DA
			public LandLordNeedsManualLaborersIssueBehaviorTypeDefiner()
				: base(810000)
			{
			}

			// Token: 0x06005B05 RID: 23301 RVA: 0x001A8EE7 File Offset: 0x001A70E7
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue), 1, null);
				base.AddClassDefinition(typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest), 2, null);
			}
		}
	}
}
