using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.AgentOrigins;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.Settlements.Locations;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000371 RID: 881
	public class LordsNeedsTutorIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060033D5 RID: 13269 RVA: 0x000D58A0 File Offset: 0x000D3AA0
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060033D6 RID: 13270 RVA: 0x000D58BC File Offset: 0x000D3ABC
		public void OnCheckForIssue(Hero hero)
		{
			Hero hero2;
			if (this.ConditionsHold(hero, out hero2))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssue), IssueBase.IssueFrequency.Common, hero2));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssue), IssueBase.IssueFrequency.Common));
		}

		// Token: 0x060033D7 RID: 13271 RVA: 0x000D5924 File Offset: 0x000D3B24
		private bool SuitableCondition(Hero hero)
		{
			return hero.Age >= 18f && hero.Age < 23f && hero.PartyBelongedTo == null && hero.PartyBelongedToAsPrisoner == null && hero.IsActive && hero.CurrentSettlement != null && hero.Level <= 15 && !hero.IsFemale && hero.Clan != Clan.PlayerClan && !LordsNeedsTutorIssueBehavior._alreadyChosenHeroes.Contains(hero);
		}

		// Token: 0x060033D8 RID: 13272 RVA: 0x000D599C File Offset: 0x000D3B9C
		private bool ConditionsHold(Hero issueGiver, out Hero youngHero)
		{
			youngHero = null;
			if (issueGiver.IsLord && issueGiver.Clan != Clan.PlayerClan && issueGiver.Age > 30f && !issueGiver.IsMinorFactionHero)
			{
				youngHero = issueGiver.Clan.AliveLords.FirstOrDefault<Hero>(new Func<Hero, bool>(this.SuitableCondition));
				if (youngHero != null && youngHero != issueGiver && !this.SuitableCondition(issueGiver))
				{
					return true;
				}
			}
			return false;
		}

		// Token: 0x060033D9 RID: 13273 RVA: 0x000D5A0C File Offset: 0x000D3C0C
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			PotentialIssueData potentialIssueData = pid;
			return new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssue(issueOwner, potentialIssueData.RelatedObject as Hero);
		}

		// Token: 0x060033DA RID: 13274 RVA: 0x000D5A32 File Offset: 0x000D3C32
		public override void SyncData(IDataStore dataStore)
		{
			dataStore.SyncData<List<Hero>>("_alreadyChosenHeroes", ref LordsNeedsTutorIssueBehavior._alreadyChosenHeroes);
		}

		// Token: 0x060033DB RID: 13275 RVA: 0x000D5A45 File Offset: 0x000D3C45
		private static void SetAlreadyChosenHero(Hero hero)
		{
			if (LordsNeedsTutorIssueBehavior._alreadyChosenHeroes == null)
			{
				LordsNeedsTutorIssueBehavior._alreadyChosenHeroes = new List<Hero> { hero };
				return;
			}
			if (!LordsNeedsTutorIssueBehavior._alreadyChosenHeroes.Contains(hero))
			{
				LordsNeedsTutorIssueBehavior._alreadyChosenHeroes.Add(hero);
			}
		}

		// Token: 0x04000ED4 RID: 3796
		private const int YoungHeroAgeMinValue = 18;

		// Token: 0x04000ED5 RID: 3797
		private const int YoungHeroAgeMaxValue = 23;

		// Token: 0x04000ED6 RID: 3798
		private const IssueBase.IssueFrequency LordsNeedsTutorIssueFrequency = IssueBase.IssueFrequency.Common;

		// Token: 0x04000ED7 RID: 3799
		private const int QuestDurationInDays = 200;

		// Token: 0x04000ED8 RID: 3800
		private static List<Hero> _alreadyChosenHeroes = new List<Hero>();

		// Token: 0x02000739 RID: 1849
		public class LordsNeedsTutorIssue : IssueBase
		{
			// Token: 0x06005CDD RID: 23773 RVA: 0x001B0328 File Offset: 0x001AE528
			internal static void AutoGeneratedStaticCollectObjectsLordsNeedsTutorIssue(object o, List<object> collectedObjects)
			{
				((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005CDE RID: 23774 RVA: 0x001B0336 File Offset: 0x001AE536
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._youngHero);
			}

			// Token: 0x06005CDF RID: 23775 RVA: 0x001B034B File Offset: 0x001AE54B
			internal static object AutoGeneratedGetMemberValue_youngHero(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssue)o)._youngHero;
			}

			// Token: 0x1700127A RID: 4730
			// (get) Token: 0x06005CE0 RID: 23776 RVA: 0x001B0358 File Offset: 0x001AE558
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700127B RID: 4731
			// (get) Token: 0x06005CE1 RID: 23777 RVA: 0x001B035B File Offset: 0x001AE55B
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700127C RID: 4732
			// (get) Token: 0x06005CE2 RID: 23778 RVA: 0x001B035E File Offset: 0x001AE55E
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=VtSg9OYK}I've heard good things about you. They say that you are an accomplished warrior. [if:convo_thinking][ib:closed]Some also say an accomplished commander. I have a proposal for you. There is a young lord from my clan. He is an aspiring warrior and I must say he quite admires you. He wants to learn from you. What do you say? Are you willing to take him under your wings for a while? Let's say {QUEST_DURATION} days?", null);
					textObject.SetTextVariable("QUEST_DURATION", 200);
					return textObject;
				}
			}

			// Token: 0x1700127D RID: 4733
			// (get) Token: 0x06005CE3 RID: 23779 RVA: 0x001B037C File Offset: 0x001AE57C
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=a1n2zCaD}What exactly do you wish from me?", null);
				}
			}

			// Token: 0x1700127E RID: 4734
			// (get) Token: 0x06005CE4 RID: 23780 RVA: 0x001B0389 File Offset: 0x001AE589
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					return new TextObject("{=JlFfuFEC}How about you take him with you? [if:convo_merry][ib:confident3]Feed and protect him, sure, but don't treat him any differently from your companions. Let him stay with you for a year, and then let him return to us? I will send you a worthwhile gift and, perhaps more valuably, you will gain my lifelong friendship, assuming everything goes well?", null);
				}
			}

			// Token: 0x1700127F RID: 4735
			// (get) Token: 0x06005CE5 RID: 23781 RVA: 0x001B0396 File Offset: 0x001AE596
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=iTYoUNdC}All right. I'll take him with me.", null);
				}
			}

			// Token: 0x17001280 RID: 4736
			// (get) Token: 0x06005CE6 RID: 23782 RVA: 0x001B03A4 File Offset: 0x001AE5A4
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=XmGjTZz0}{?QUEST_GIVER.GENDER}Lady{?}Lord{\\?} Needs a Tutor", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001281 RID: 4737
			// (get) Token: 0x06005CE7 RID: 23783 RVA: 0x001B03D8 File Offset: 0x001AE5D8
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=MSr3HRa1}{QUEST_GIVER.NAME}, a {?QUEST_GIVER.GENDER}lady{?}lord{\\?} of the {CLAN}, wants young member of the clan trained in the arts of war.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					textObject.SetTextVariable("CLAN", base.IssueOwner.Clan.Name);
					return textObject;
				}
			}

			// Token: 0x06005CE8 RID: 23784 RVA: 0x001B0426 File Offset: 0x001AE626
			public LordsNeedsTutorIssue(Hero issueOwner, Hero youngHero)
				: base(issueOwner, CampaignTime.DaysFromNow(200f))
			{
				this._youngHero = youngHero;
			}

			// Token: 0x06005CE9 RID: 23785 RVA: 0x001B0440 File Offset: 0x001AE640
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.ClanInfluence)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005CEA RID: 23786 RVA: 0x001B0455 File Offset: 0x001AE655
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005CEB RID: 23787 RVA: 0x001B0457 File Offset: 0x001AE657
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005CEC RID: 23788 RVA: 0x001B0459 File Offset: 0x001AE659
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest(questId, base.IssueOwner, this._youngHero);
			}

			// Token: 0x06005CED RID: 23789 RVA: 0x001B046D File Offset: 0x001AE66D
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Common;
			}

			// Token: 0x06005CEE RID: 23790 RVA: 0x001B0470 File Offset: 0x001AE670
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				relationHero = null;
				skill = null;
				requiredGold = 0;
				flag = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (Hero.MainHero.IsKingdomLeader)
				{
					flag |= IssueBase.PreconditionFlags.MainHeroIsKingdomLeader;
				}
				if (issueGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				if (Clan.PlayerClan.Tier < 2)
				{
					flag |= IssueBase.PreconditionFlags.ClanTier;
				}
				if (Clan.PlayerClan.Companions.Count >= Clan.PlayerClan.CompanionLimit)
				{
					flag |= IssueBase.PreconditionFlags.CompanionLimitReached;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005CEF RID: 23791 RVA: 0x001B0518 File Offset: 0x001AE718
			public override bool IssueStayAliveConditions()
			{
				return this._youngHero.Age >= 18f && this._youngHero.Age < (float)(23 - 200 / CampaignTime.DaysInYear) && this._youngHero.PartyBelongedTo == null && this._youngHero.PartyBelongedToAsPrisoner == null && this._youngHero.IsActive && this._youngHero.CurrentSettlement != null && this._youngHero.Level <= 20 && base.IssueOwner.Clan != Clan.PlayerClan && this._youngHero.Clan != Clan.PlayerClan && (this._youngHero.Spouse == null || this._youngHero.Children.IsEmpty<Hero>());
			}

			// Token: 0x06005CF0 RID: 23792 RVA: 0x001B05E1 File Offset: 0x001AE7E1
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001DA9 RID: 7593
			[SaveableField(1)]
			private Hero _youngHero;

			// Token: 0x04001DAA RID: 7594
			private const int MinimumRelationToTakeQuest = -10;
		}

		// Token: 0x0200073A RID: 1850
		public class LordsNeedsTutorIssueQuest : QuestBase
		{
			// Token: 0x06005CF1 RID: 23793 RVA: 0x001B05E3 File Offset: 0x001AE7E3
			internal static void AutoGeneratedStaticCollectObjectsLordsNeedsTutorIssueQuest(object o, List<object> collectedObjects)
			{
				((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005CF2 RID: 23794 RVA: 0x001B05F1 File Offset: 0x001AE7F1
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._youngHero);
				collectedObjects.Add(this._oldSkillValues);
				collectedObjects.Add(this._startQuestLog);
			}

			// Token: 0x06005CF3 RID: 23795 RVA: 0x001B061E File Offset: 0x001AE81E
			internal static object AutoGeneratedGetMemberValue_youngHero(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._youngHero;
			}

			// Token: 0x06005CF4 RID: 23796 RVA: 0x001B062B File Offset: 0x001AE82B
			internal static object AutoGeneratedGetMemberValue_checkForMissionEnd(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._checkForMissionEnd;
			}

			// Token: 0x06005CF5 RID: 23797 RVA: 0x001B063D File Offset: 0x001AE83D
			internal static object AutoGeneratedGetMemberValue_firstConversationInitialized(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._firstConversationInitialized;
			}

			// Token: 0x06005CF6 RID: 23798 RVA: 0x001B064F File Offset: 0x001AE84F
			internal static object AutoGeneratedGetMemberValue_questCompletedStartConversation(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._questCompletedStartConversation;
			}

			// Token: 0x06005CF7 RID: 23799 RVA: 0x001B0661 File Offset: 0x001AE861
			internal static object AutoGeneratedGetMemberValue_youngHeroBeginningSkillPoints(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._youngHeroBeginningSkillPoints;
			}

			// Token: 0x06005CF8 RID: 23800 RVA: 0x001B0673 File Offset: 0x001AE873
			internal static object AutoGeneratedGetMemberValue_randomForQuestReward(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._randomForQuestReward;
			}

			// Token: 0x06005CF9 RID: 23801 RVA: 0x001B0685 File Offset: 0x001AE885
			internal static object AutoGeneratedGetMemberValue_oldSkillValues(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._oldSkillValues;
			}

			// Token: 0x06005CFA RID: 23802 RVA: 0x001B0692 File Offset: 0x001AE892
			internal static object AutoGeneratedGetMemberValue_startQuestLog(object o)
			{
				return ((LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest)o)._startQuestLog;
			}

			// Token: 0x17001282 RID: 4738
			// (get) Token: 0x06005CFB RID: 23803 RVA: 0x001B069F File Offset: 0x001AE89F
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001283 RID: 4739
			// (get) Token: 0x06005CFC RID: 23804 RVA: 0x001B06A4 File Offset: 0x001AE8A4
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=XmGjTZz0}{?QUEST_GIVER.GENDER}Lady{?}Lord{\\?} Needs a Tutor", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001284 RID: 4740
			// (get) Token: 0x06005CFD RID: 23805 RVA: 0x001B06D8 File Offset: 0x001AE8D8
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=Celvao0J}{QUEST_GIVER.LINK} a {?QUEST_GIVER.GENDER}Lady{?}Lord{\\?} from {CLAN} clan has asked you to take a young clan member under your wings and train him for {DURATION} days. You have accepted to train him personally.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("DURATION", 200);
					textObject.SetTextVariable("CLAN", base.QuestGiver.Clan.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x17001285 RID: 4741
			// (get) Token: 0x06005CFE RID: 23806 RVA: 0x001B0738 File Offset: 0x001AE938
			private TextObject SuccessQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=j0QKnNqK}The training of {YOUNG_HERO.LINK} has been completed successfully. Both He and his clan is grateful to you.", null);
					StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001286 RID: 4742
			// (get) Token: 0x06005CFF RID: 23807 RVA: 0x001B076C File Offset: 0x001AE96C
			private TextObject FailTimedOutQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=taz5cAtw}You failed to train the {YOUNG_HERO.LINK} enough as {QUEST_GIVER.LINK} expected. {?QUEST_GIVER.GENDER}She{?}He{\\?} is disappointed.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001287 RID: 4743
			// (get) Token: 0x06005D00 RID: 23808 RVA: 0x001B07B8 File Offset: 0x001AE9B8
			private TextObject PupilHasDiedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=abmSQFR5}{YOUNG_HERO.LINK} has died under your care. {QUEST_GIVER.LINK} is furious.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001288 RID: 4744
			// (get) Token: 0x06005D01 RID: 23809 RVA: 0x001B0804 File Offset: 0x001AEA04
			private TextObject PupilEscapedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=dL8196qY}{YOUNG_HERO.LINK} has escaped. Find him to continue your quest.", null);
					StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001289 RID: 4745
			// (get) Token: 0x06005D02 RID: 23810 RVA: 0x001B0838 File Offset: 0x001AEA38
			private TextObject WarDeclaredQuestCancel
			{
				get
				{
					TextObject textObject = new TextObject("{=HkbK8cqw}Your clan is now at war with the {QUEST_GIVER.LINK}'s faction. Your agreement with {QUEST_GIVER.LINK} was terminated.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700128A RID: 4746
			// (get) Token: 0x06005D03 RID: 23811 RVA: 0x001B086C File Offset: 0x001AEA6C
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700128B RID: 4747
			// (get) Token: 0x06005D04 RID: 23812 RVA: 0x001B08A0 File Offset: 0x001AEAA0
			private TextObject PlayerKickedYoungHeroFromClan
			{
				get
				{
					TextObject textObject = new TextObject("{=x3f1w3Gc}You have kicked {YOUNG_HERO.LINK} from your clan. Your agreement with {QUEST_GIVER.LINK} was terminated.", null);
					StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700128C RID: 4748
			// (get) Token: 0x06005D05 RID: 23813 RVA: 0x001B08EC File Offset: 0x001AEAEC
			private TextObject PlayerBecameClanLeader
			{
				get
				{
					TextObject textObject = new TextObject("{=JiD05yDw}{YOUNG_HERO.LINK} now becomes the leader of his clan and your agreement with {QUEST_GIVER.LINK} was terminated.", null);
					StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700128D RID: 4749
			// (get) Token: 0x06005D06 RID: 23814 RVA: 0x001B0938 File Offset: 0x001AEB38
			private TextObject PlayerMarriedYoungHero
			{
				get
				{
					TextObject textObject = new TextObject("{=QGigAhFW}You have married with {YOUNG_HERO.LINK} who is the young noble you agreed to be his tutor. {QUEST_GIVER.LINK} no longer expects you to tutor {YOUNG_HERO.LINK} and wishes you a joyful marriage.", null);
					StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700128E RID: 4750
			// (get) Token: 0x06005D07 RID: 23815 RVA: 0x001B0982 File Offset: 0x001AEB82
			private TextObject CompanionLimitReachedQuestLogText
			{
				get
				{
					return new TextObject("{=rkQ7D36f}The quest was canceled because your party had more companions than you could manage.", null);
				}
			}

			// Token: 0x06005D08 RID: 23816 RVA: 0x001B0990 File Offset: 0x001AEB90
			public LordsNeedsTutorIssueQuest(string questId, Hero questGiver, Hero youngHero)
				: base(questId, questGiver, CampaignTime.DaysFromNow(200f), 0)
			{
				this._youngHero = youngHero;
				this._firstConversationInitialized = false;
				this._oldSkillValues = new Dictionary<SkillObject, int>();
				this._youngHero.SetHasMet();
				this._randomForQuestReward = MBRandom.RandomInt(2, 5);
				if (this._youngHero.GovernorOf != null)
				{
					ChangeGovernorAction.RemoveGovernorOf(this._youngHero);
				}
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005D09 RID: 23817 RVA: 0x001B0A05 File Offset: 0x001AEC05
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				this._targetSkillGain = this._youngHeroBeginningSkillPoints + 30;
			}

			// Token: 0x06005D0A RID: 23818 RVA: 0x001B0A1C File Offset: 0x001AEC1C
			protected override void SetDialogs()
			{
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetYoungHeroFirstDialogFlow(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetYoungHeroSecondDialogFlow(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetYoungHeroFailedDialogFlow(), this);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=1WxrzNXx}He'll be delighted. I'll tell him to join you as soon as possible.", null), null, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.NotableDialogCondition))
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=OoNULWKy}How is the training going? Are you happy with your student?[if:convo_delighted][ib:hip]", null), null, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.NotableDialogCondition))
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += MapEventHelper.OnConversationEnd;
					})
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=jyxo4YgW}Yes, he is a promising boy.", null), null, null, null)
					.NpcLine(new TextObject("{=QsL6qcDb}That's very good to hear! Thank you.[if:convo_merry]", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=SbbAhpTu}He is yet to prove himself actually.", null), null, null, null)
					.NpcLine(new TextObject("{=aHid0t6n}Give him some chance I'm sure he will prove himself soon.", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005D0B RID: 23819 RVA: 0x001B0B7C File Offset: 0x001AED7C
			private bool NotableDialogCondition()
			{
				StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, null, false);
				return Hero.OneToOneConversationHero == base.QuestGiver;
			}

			// Token: 0x06005D0C RID: 23820 RVA: 0x001B0BA4 File Offset: 0x001AEDA4
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				AddCompanionAction.Apply(Clan.PlayerClan, this._youngHero);
				MobileParty.MainParty.MemberRoster.AddToCounts(this._youngHero.CharacterObject, 1, false, 0, 0, true, -1);
				this._youngHeroBeginningSkillPoints = this._youngHero.HeroDeveloper.GetTotalSkillPoints();
				this._targetSkillGain = this._youngHeroBeginningSkillPoints + 30;
				TextObject textObject = new TextObject("{=8GbGTDtL}{YOUNG_HERO.LINK}'s experience progress", null);
				StringHelpers.SetCharacterProperties("YOUNG_HERO", this._youngHero.CharacterObject, textObject, false);
				this._startQuestLog = base.AddDiscreteLog(this.PlayerStartsQuestLogText, textObject, this._youngHero.HeroDeveloper.GetTotalSkillPoints() - this._youngHeroBeginningSkillPoints, 30, null, false);
				this._checkForMissionEnd = true;
				foreach (SkillObject skillObject in Skills.All)
				{
					this._oldSkillValues.Add(skillObject, this._youngHero.GetSkillValue(skillObject));
					this._youngHero.HeroDeveloper.AddFocus(skillObject, 1, false);
				}
				LordsNeedsTutorIssueBehavior.SetAlreadyChosenHero(this._youngHero);
			}

			// Token: 0x06005D0D RID: 23821 RVA: 0x001B0CDC File Offset: 0x001AEEDC
			protected override void RegisterEvents()
			{
				CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, new Action<Hero, Hero, KillCharacterAction.KillCharacterActionDetail, bool>(this.OnHeroKilled));
				CampaignEvents.HeroPrisonerTaken.AddNonSerializedListener(this, new Action<PartyBase, Hero>(this.OnPrisonerTaken));
				CampaignEvents.HeroGainedSkill.AddNonSerializedListener(this, new Action<Hero, SkillObject, int, bool>(this.OnHeroGainedSkill));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanLeaderChangedEvent.AddNonSerializedListener(this, new Action<Hero, Hero>(this.OnClanLeaderChanged));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.CompanionRemoved.AddNonSerializedListener(this, new Action<Hero, RemoveCompanionAction.RemoveCompanionDetail>(this.OnCompanionRemoved));
				CampaignEvents.BeforeHeroesMarried.AddNonSerializedListener(this, new Action<Hero, Hero, bool>(this.OnHeroesMarried));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.SettlementEntered.AddNonSerializedListener(this, new Action<MobileParty, Settlement, Hero>(this.OnSettlementEntered));
				CampaignEvents.OnGameLoadFinishedEvent.AddNonSerializedListener(this, new Action(this.OnGameLoadFinished));
				CampaignEvents.PerkResetEvent.AddNonSerializedListener(this, new Action<Hero, PerkObject>(this.OnPerkReset));
				CampaignEvents.NewCompanionAdded.AddNonSerializedListener(this, new Action<Hero>(this.OnNewCompanionAdded));
			}

			// Token: 0x06005D0E RID: 23822 RVA: 0x001B0E14 File Offset: 0x001AF014
			private void OnNewCompanionAdded(Hero hero)
			{
				this.CheckCompanionLimit();
			}

			// Token: 0x06005D0F RID: 23823 RVA: 0x001B0E1C File Offset: 0x001AF01C
			private void OnPerkReset(Hero hero, PerkObject perk)
			{
				if (hero == Hero.MainHero)
				{
					this.CheckCompanionLimit();
				}
			}

			// Token: 0x06005D10 RID: 23824 RVA: 0x001B0E2C File Offset: 0x001AF02C
			private void CheckCompanionLimit()
			{
				if (Clan.PlayerClan.Companions.Count > Clan.PlayerClan.CompanionLimit)
				{
					base.AddLog(this.CompanionLimitReachedQuestLogText, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005D11 RID: 23825 RVA: 0x001B0E5E File Offset: 0x001AF05E
			private void OnGameLoadFinished()
			{
				if (Settlement.CurrentSettlement != null && Settlement.CurrentSettlement.HeroesWithoutParty.Contains(this._youngHero))
				{
					this.SpawnYoungHeroInLordsHall();
				}
				this.CheckCompanionLimit();
			}

			// Token: 0x06005D12 RID: 23826 RVA: 0x001B0E8A File Offset: 0x001AF08A
			private void OnSettlementEntered(MobileParty party, Settlement settlement, Hero hero)
			{
				if (party != null && party.IsMainParty && settlement.HeroesWithoutParty.Contains(this._youngHero))
				{
					this.SpawnYoungHeroInLordsHall();
				}
			}

			// Token: 0x06005D13 RID: 23827 RVA: 0x001B0EB0 File Offset: 0x001AF0B0
			public override void OnHeroCanBeSelectedInInventoryInfoIsRequested(Hero hero, ref bool result)
			{
				this.CommonRestrictionInfoIsRequested(hero, ref result);
			}

			// Token: 0x06005D14 RID: 23828 RVA: 0x001B0EBA File Offset: 0x001AF0BA
			public override void OnHeroCanHavePartyRoleOrBeGovernorInfoIsRequested(Hero hero, ref bool result)
			{
				this.CommonRestrictionInfoIsRequested(hero, ref result);
			}

			// Token: 0x06005D15 RID: 23829 RVA: 0x001B0EC4 File Offset: 0x001AF0C4
			public override void OnHeroCanLeadPartyInfoIsRequested(Hero hero, ref bool result)
			{
				this.CommonRestrictionInfoIsRequested(hero, ref result);
			}

			// Token: 0x06005D16 RID: 23830 RVA: 0x001B0ECE File Offset: 0x001AF0CE
			public override void OnHeroCanHaveCampaignIssuesInfoIsRequested(Hero hero, ref bool result)
			{
				this.CommonRestrictionInfoIsRequested(hero, ref result);
			}

			// Token: 0x06005D17 RID: 23831 RVA: 0x001B0ED8 File Offset: 0x001AF0D8
			public override void OnHeroCanMarryInfoIsRequested(Hero hero, ref bool result)
			{
				this.CommonRestrictionInfoIsRequested(hero, ref result);
			}

			// Token: 0x06005D18 RID: 23832 RVA: 0x001B0EE2 File Offset: 0x001AF0E2
			private void CommonRestrictionInfoIsRequested(Hero hero, ref bool result)
			{
				if (hero == this._youngHero)
				{
					result = false;
				}
			}

			// Token: 0x06005D19 RID: 23833 RVA: 0x001B0EF0 File Offset: 0x001AF0F0
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005D1A RID: 23834 RVA: 0x001B0F03 File Offset: 0x001AF103
			private void OnHeroesMarried(Hero hero1, Hero hero2, bool showNotification = true)
			{
				if ((hero1 == Hero.MainHero && hero2 == this._youngHero) || (hero2 == Hero.MainHero && hero1 == this._youngHero))
				{
					this._doNotForceYoungHeroOutFromClan = true;
					base.CompleteQuestWithCancel(this.PlayerMarriedYoungHero);
				}
			}

			// Token: 0x06005D1B RID: 23835 RVA: 0x001B0F3A File Offset: 0x001AF13A
			private void OnClanLeaderChanged(Hero oldLeader, Hero newLeader)
			{
				if (base.IsOngoing && newLeader == this._youngHero)
				{
					base.AddLog(this.PlayerBecameClanLeader, false);
					base.CompleteQuestWithFail(null);
				}
			}

			// Token: 0x06005D1C RID: 23836 RVA: 0x001B0F62 File Offset: 0x001AF162
			private void OnCompanionRemoved(Hero companion, RemoveCompanionAction.RemoveCompanionDetail detail)
			{
				if (base.IsOngoing && companion == this._youngHero)
				{
					base.AddLog(this.PlayerKickedYoungHeroFromClan, false);
					base.CompleteQuestWithFail(null);
				}
			}

			// Token: 0x06005D1D RID: 23837 RVA: 0x001B0F8A File Offset: 0x001AF18A
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.WarDeclaredQuestCancel);
				}
			}

			// Token: 0x06005D1E RID: 23838 RVA: 0x001B0FB4 File Offset: 0x001AF1B4
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.WarDeclaredQuestCancel, false);
			}

			// Token: 0x06005D1F RID: 23839 RVA: 0x001B0FCC File Offset: 0x001AF1CC
			public void OnHeroGainedSkill(Hero hero, SkillObject skill, int change = 1, bool shouldNotify = true)
			{
				if (hero == this._youngHero)
				{
					int num = MBMath.ClampInt(this._youngHero.HeroDeveloper.GetTotalSkillPoints() - this._youngHeroBeginningSkillPoints, 0, 30);
					this._startQuestLog.UpdateCurrentProgress(num);
					if (this._youngHero.HeroDeveloper.GetTotalSkillPoints() >= this._targetSkillGain)
					{
						this._questCompletedStartConversation = true;
					}
				}
			}

			// Token: 0x06005D20 RID: 23840 RVA: 0x001B1030 File Offset: 0x001AF230
			private void OnPrisonerTaken(PartyBase capturer, Hero prisoner)
			{
				if (prisoner == Hero.MainHero && this._youngHero.IsPlayerCompanion && MobileParty.MainParty.MapEventSide != null)
				{
					if (MobileParty.MainParty.MapEventSide.Parties.First<MapEventParty>((MapEventParty x) => x.Party == PartyBase.MainParty).Troops.FindIndexOfCharacter(this._youngHero.CharacterObject).IsValid)
					{
						base.AddLog(this.PupilEscapedLogText, false);
						EndCaptivityAction.ApplyByEscape(this._youngHero, null, true);
					}
				}
			}

			// Token: 0x06005D21 RID: 23841 RVA: 0x001B10CE File Offset: 0x001AF2CE
			private void OnHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification = true)
			{
				if (victim == this._youngHero)
				{
					base.AddLog(this.PupilHasDiedLogText, false);
					this.RelationshipChangeWithQuestGiver = -40;
					base.CompleteQuestWithFail(null);
				}
			}

			// Token: 0x06005D22 RID: 23842 RVA: 0x001B10F8 File Offset: 0x001AF2F8
			protected override void HourlyTick()
			{
				if (base.IsOngoing && !Hero.MainHero.IsPrisoner && !MobileParty.MainParty.IsInRaftState && Settlement.CurrentSettlement == null && PlayerEncounter.Current == null && MapEvent.PlayerMapEvent == null && this._youngHero.PartyBelongedTo == MobileParty.MainParty && GameStateManager.Current.ActiveState is MapState && ((this._checkForMissionEnd && !this._firstConversationInitialized) || this._questCompletedStartConversation))
				{
					CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, PartyBase.MainParty, false, false, false, false, false, false), new ConversationCharacterData(this._youngHero.CharacterObject, PartyBase.MainParty, false, false, false, false, false, false));
					if (this._checkForMissionEnd)
					{
						this._checkForMissionEnd = false;
					}
				}
			}

			// Token: 0x06005D23 RID: 23843 RVA: 0x001B11C8 File Offset: 0x001AF3C8
			private void SpawnYoungHeroInLordsHall()
			{
				Monster monsterWithSuffix = FaceGen.GetMonsterWithSuffix(this._youngHero.CharacterObject.Race, "_settlement");
				ValueTuple<string, Monster> valueTuple = new ValueTuple<string, Monster>(ActionSetCode.GenerateActionSetNameWithSuffix(monsterWithSuffix, this._youngHero.CharacterObject.IsFemale, "_lord"), monsterWithSuffix);
				IFaction mapFaction = this._youngHero.MapFaction;
				uint num = ((mapFaction != null) ? mapFaction.Color : 4291609515U);
				IFaction mapFaction2 = this._youngHero.MapFaction;
				uint num2 = ((mapFaction2 != null) ? mapFaction2.Color : 4291609515U);
				AgentData agentData = new AgentData(new SimpleAgentOrigin(this._youngHero.CharacterObject, -1, null, default(UniqueTroopDescriptor))).Monster(valueTuple.Item2).NoHorses(true).ClothingColor1(num)
					.ClothingColor2(num2);
				LocationComplex.Current.GetLocationWithId("lordshall").AddCharacter(new LocationCharacter(agentData, new LocationCharacter.AddBehaviorsDelegate(SandBoxManager.Instance.AgentBehaviorManager.AddFixedCharacterBehaviors), "sp_notable", true, LocationCharacter.CharacterRelations.Neutral, valueTuple.Item1, true, false, null, false, false, true, null, false));
			}

			// Token: 0x06005D24 RID: 23844 RVA: 0x001B12D4 File Offset: 0x001AF4D4
			private DialogFlow GetYoungHeroFirstDialogFlow()
			{
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(new TextObject("{=XH66Leg5}Greetings, my {?PLAYER.GENDER}lady{?}lord{\\?}. I have heard much of your deeds. Thank you for agreeing to train me. I hope I won't disappoint you.[if:convo_grateful][ib:demure]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == this._youngHero && !this._firstConversationInitialized)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.FirstConversationEndConsequence;
					})
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=oJJiKTSL}You are welcome.", null), null, null, null)
					.NpcLine(new TextObject("{=wlKtDR2z}Thank you, {?PLAYER.GENDER}my lady{?}sir{\\?}.", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=FHeJ8bsX}We will see about that.", null), null, null, null)
					.NpcLine(new TextObject("{=kc3RfwFb}I'll try to be useful to you, {?PLAYER.GENDER}my lady{?}sir{\\?}.", null), null, null, null, null)
					.EndPlayerOptions()
					.PlayerLine(new TextObject("{=kJwpbptU}Well, try to stay close to me at all times and try to learn as much as you can.", null), null, null, null)
					.NpcLine(new TextObject("{=EaifHOao}Yes, {?PLAYER.GENDER}my lady{?}sir{\\?}, I will.", null), null, null, null, null)
					.CloseDialog();
			}

			// Token: 0x06005D25 RID: 23845 RVA: 0x001B13AE File Offset: 0x001AF5AE
			private DialogFlow GetYoungHeroFailedDialogFlow()
			{
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(new TextObject("{=vbbc6sIU}I regret to tell you that my progress under your tutelage is not satisfactory. I should return to my clan to resume my studies. Thank you for your trouble anyway.", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == this._youngHero && this._showQuestFailedConversation)
					.CloseDialog();
			}

			// Token: 0x06005D26 RID: 23846 RVA: 0x001B13E6 File Offset: 0x001AF5E6
			private void FirstConversationEndConsequence()
			{
				this._youngHero.SetHasMet();
				this._firstConversationInitialized = true;
			}

			// Token: 0x06005D27 RID: 23847 RVA: 0x001B13FC File Offset: 0x001AF5FC
			private DialogFlow GetYoungHeroSecondDialogFlow()
			{
				return DialogFlow.CreateDialogFlow("start", 125).BeginNpcOptions(null, false).NpcOption(new TextObject("{=APEBfqyW}Greetings my {?PLAYER.GENDER}lady{?}lord{\\?}. Do you wish something from me?[if:convo_innocent_smile][ib:normal2]", null), new ConversationSentence.OnConditionDelegate(this.default_conversation_with_young_hero_condition), null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=BO0f1Klt}So - how do you find life in our company? Is it all you expected?.", null), null, null, null)
					.NpcLine(new TextObject("{=e3e79n9B}It is all I expected and more, captain. I am glad that you took me with you.[if:convo_grateful][ib:normal2]", null), null, null, null, null)
					.PlayerLine(new TextObject("{=dbG3PGXL}I'm glad you think that way. Combat aside, have you learned anything special?", null), null, null, null)
					.NpcLine(new TextObject("{=8L9W34D6}{NPC_EXPERIENCE_LINE}", null), null, null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.npc_experience_line_condition))
					.PlayerLine(new TextObject("{=Rh0DlvvE}I'm glad you see it that way. Go on. Continue your training.", null), null, null, null)
					.NpcLine(new TextObject("{=dnvPDnzS}I will, my {?PLAYER.GENDER}lady{?}lord{\\?}. Thank you[if:convo_grateful][ib:demure]", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=Lk6ln3sR}We seem to have got separated but I have found you. Join me, as we need to continue your training.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.PupilJoinMeCondition))
					.NpcLine(new TextObject("{=0coOJAvg}Yes, {?PLAYER.GENDER}madam{?}sir{\\?}. Thank you.", null), null, null, null, null)
					.Consequence(delegate
					{
						MobileParty.MainParty.MemberRoster.AddToCounts(this._youngHero.CharacterObject, 1, false, 0, 0, true, -1);
					})
					.CloseDialog()
					.EndPlayerOptions()
					.NpcOption(new TextObject("{=kUbovNbE}My {?PLAYER.GENDER}lady{?}lord{\\?}. The agreed training time with you is over. I thank you for everything. It's been a very productive for me.[if:convo_delighted][ib:demure]", null), new ConversationSentence.OnConditionDelegate(this.quest_finished_conversation_with_young_hero_condition), null, null, null, null)
					.PlayerLine(new TextObject("{=bS0bBgp3}I'm happy to hear this. Tell me, what is the most important lesson you've learned from me?", null), null, null, null)
					.NpcLine(new TextObject("{=8L9W34D6}{NPC_EXPERIENCE_LINE}", null), null, null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.npc_experience_line_condition))
					.PlayerLine(new TextObject("{=orprhyYl}I'm glad you see it that way. Very well then, off you go. Send my regards to your family. I hope to see you again one day. I am sure you will make an excellent commander.", null), null, null, null)
					.NpcLine(new TextObject("{=IBXfCLMp}I certainly hope too {?PLAYER.GENDER}lady{?}lord{\\?}! Again, I want to thank you for everything, before I go, please accept this gift as a humble gratitude.[if:convo_calm_friendly]", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestCompletedWithSuccessAfterConversation))
					.CloseDialog()
					.EndNpcOptions();
			}

			// Token: 0x06005D28 RID: 23848 RVA: 0x001B15BB File Offset: 0x001AF7BB
			private bool PupilJoinMeCondition()
			{
				return MobileParty.MainParty.MemberRoster.GetTroopRoster().All<TroopRosterElement>((TroopRosterElement x) => x.Character != this._youngHero.CharacterObject);
			}

			// Token: 0x06005D29 RID: 23849 RVA: 0x001B15E0 File Offset: 0x001AF7E0
			private void QuestCompletedWithSuccessAfterConversation()
			{
				this.RelationshipChangeWithQuestGiver = 25;
				ChangeRelationAction.ApplyPlayerRelation(this._youngHero, 15, true, true);
				base.CompleteQuestWithSuccess();
				base.AddLog(this.SuccessQuestLogText, false);
				ItemObject randomElementWithPredicate = Items.All.GetRandomElementWithPredicate<ItemObject>((ItemObject x) => x.IsTradeGood && x.ItemCategory == DefaultItemCategories.Jewelry);
				TextObject textObject = new TextObject("{=lWvuM5aj}{GIFT_NUMBER} pieces of {JEWELRY} have been added to your inventory.", null);
				textObject.SetTextVariable("GIFT_NUMBER", this._randomForQuestReward);
				textObject.SetTextVariable("JEWELRY", randomElementWithPredicate.Name);
				MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				MobileParty.MainParty.ItemRoster.AddToCounts(randomElementWithPredicate, this._randomForQuestReward);
				GainRenownAction.Apply(Hero.MainHero, 5f, false);
			}

			// Token: 0x06005D2A RID: 23850 RVA: 0x001B16A8 File Offset: 0x001AF8A8
			private bool npc_experience_line_condition()
			{
				List<KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>> list = new List<KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>>();
				list.Add(new KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>(new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition(this.strength_increased_condition), new TextObject("{=hMiJvlJ5}Yes, Since we last spoke, I've learned a lot about hand-to-hand combat, my {?PLAYER.GENDER}lady{?}lord{\\?}. Correct timing and putting your whole body behind the blow means a lot more than I initially thought.[if:convo_calm_friendly][ib:warrior]", null)));
				list.Add(new KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>(new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition(this.perception_increased_condition), new TextObject("{=TrQzYwVD}Yes, {?PLAYER.GENDER}my lady{?}lord{\\?}. Since we last spoke I had chance to increase my understanding of ranged combat. How to breath, calculate distance, and lead the target if necessary.[if:convo_calm_friendly][ib:normal]", null)));
				list.Add(new KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>(new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition(this.endurance_increased_condition), new TextObject("{=XF7shG4k}Since we last spoke I've been training vigorously. I feel tougher, much more energetic and alive now.[if:convo_calm_friendly][ib:warrior2]", null)));
				list.Add(new KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>(new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition(this.cunning_increased_condition), new TextObject("{=H6l9cm7I}I've been paying attention to your subtler methods, {?PLAYER.GENDER}my lady{?}lord{\\?}, I've been observing that courage and strength in numbers is not enough to win most engagements. You have to be aware of the situation and seize the opportunities when they present themselves.[if:convo_calm_friendly][ib:hip]", null)));
				list.Add(new KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>(new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition(this.social_increased_condition), new TextObject("{=bNAbWn4E}I've been watching how you deal with different kinds of folk: how to present yourself, how to address people from various walks of life properly, how to inspire greatness to those who trust in you.[if:convo_calm_friendly][ib:confident]", null)));
				list.Add(new KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject>(new LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition(this.intelligence_increased_condition), new TextObject("{=9bd0jJD8}I've been studying a lot, {?PLAYER.GENDER}my lady{?}lord{\\?}. The manuscripts I've acquired on the way on various subjects are invaluable. Seeing professionals in action complements the theoretical knowledge I've learned from the manuscripts.[if:convo_calm_friendly][ib:demure2]", null)));
				MBList<TextObject> mblist = new MBList<TextObject>();
				foreach (KeyValuePair<LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest.ExperienceIncreaseCondition, TextObject> keyValuePair in list)
				{
					if (keyValuePair.Key())
					{
						mblist.Add(keyValuePair.Value);
					}
				}
				if (mblist.Count != 0)
				{
					MBTextManager.SetTextVariable("NPC_EXPERIENCE_LINE", mblist.GetRandomElement<TextObject>(), false);
					return true;
				}
				MBTextManager.SetTextVariable("NPC_EXPERIENCE_LINE", new TextObject("{=XFafAocV}Nothing specific, captain. But I'm paying close attention to everything you do.[if:convo_excited][ib:nervous]", null), false);
				return true;
			}

			// Token: 0x06005D2B RID: 23851 RVA: 0x001B1814 File Offset: 0x001AFA14
			private bool default_conversation_with_young_hero_condition()
			{
				return Hero.OneToOneConversationHero == this._youngHero && this._firstConversationInitialized && !this._questCompletedStartConversation && !this._showQuestFailedConversation;
			}

			// Token: 0x06005D2C RID: 23852 RVA: 0x001B183E File Offset: 0x001AFA3E
			private bool quest_finished_conversation_with_young_hero_condition()
			{
				return Hero.OneToOneConversationHero == this._youngHero && this._firstConversationInitialized && this._questCompletedStartConversation && !this._showQuestFailedConversation;
			}

			// Token: 0x06005D2D RID: 23853 RVA: 0x001B1868 File Offset: 0x001AFA68
			private bool strength_increased_condition()
			{
				int num = 0;
				foreach (KeyValuePair<SkillObject, int> keyValuePair in this._oldSkillValues)
				{
					if (keyValuePair.Key.Attributes.Contains(DefaultCharacterAttributes.Vigor))
					{
						num += this._youngHero.GetSkillValue(keyValuePair.Key) - keyValuePair.Value;
					}
				}
				return num > 15;
			}

			// Token: 0x06005D2E RID: 23854 RVA: 0x001B18F0 File Offset: 0x001AFAF0
			private bool perception_increased_condition()
			{
				int num = 0;
				foreach (KeyValuePair<SkillObject, int> keyValuePair in this._oldSkillValues)
				{
					if (keyValuePair.Key.Attributes.Contains(DefaultCharacterAttributes.Control))
					{
						num += this._youngHero.GetSkillValue(keyValuePair.Key) - keyValuePair.Value;
					}
				}
				return num > 15;
			}

			// Token: 0x06005D2F RID: 23855 RVA: 0x001B1978 File Offset: 0x001AFB78
			private bool endurance_increased_condition()
			{
				int num = 0;
				foreach (KeyValuePair<SkillObject, int> keyValuePair in this._oldSkillValues)
				{
					if (keyValuePair.Key.Attributes.Contains(DefaultCharacterAttributes.Endurance))
					{
						num += this._youngHero.GetSkillValue(keyValuePair.Key) - keyValuePair.Value;
					}
				}
				return num > 15;
			}

			// Token: 0x06005D30 RID: 23856 RVA: 0x001B1A00 File Offset: 0x001AFC00
			private bool cunning_increased_condition()
			{
				int num = 0;
				foreach (KeyValuePair<SkillObject, int> keyValuePair in this._oldSkillValues)
				{
					if (keyValuePair.Key.Attributes.Contains(DefaultCharacterAttributes.Cunning))
					{
						num += this._youngHero.GetSkillValue(keyValuePair.Key) - keyValuePair.Value;
					}
				}
				return num > 15;
			}

			// Token: 0x06005D31 RID: 23857 RVA: 0x001B1A88 File Offset: 0x001AFC88
			private bool social_increased_condition()
			{
				int num = 0;
				foreach (KeyValuePair<SkillObject, int> keyValuePair in this._oldSkillValues)
				{
					if (keyValuePair.Key.Attributes.Contains(DefaultCharacterAttributes.Social))
					{
						num += this._youngHero.GetSkillValue(keyValuePair.Key) - keyValuePair.Value;
					}
				}
				return num > 15;
			}

			// Token: 0x06005D32 RID: 23858 RVA: 0x001B1B10 File Offset: 0x001AFD10
			private bool intelligence_increased_condition()
			{
				int num = 0;
				foreach (KeyValuePair<SkillObject, int> keyValuePair in this._oldSkillValues)
				{
					if (keyValuePair.Key.Attributes.Contains(DefaultCharacterAttributes.Intelligence))
					{
						num += this._youngHero.GetSkillValue(keyValuePair.Key) - keyValuePair.Value;
					}
				}
				return num > 15;
			}

			// Token: 0x06005D33 RID: 23859 RVA: 0x001B1B98 File Offset: 0x001AFD98
			protected override void OnFinalize()
			{
				if (this._youngHero.IsAlive)
				{
					if (this._youngHero.CompanionOf == Clan.PlayerClan)
					{
						RemoveCompanionAction.ApplyAfterQuest(Clan.PlayerClan, this._youngHero);
						if (!this._doNotForceYoungHeroOutFromClan)
						{
							this._youngHero.Clan = base.QuestGiver.Clan;
						}
						foreach (Hero hero in this._youngHero.Children)
						{
							hero.Clan = this._youngHero.Clan;
						}
						if (this._youngHero.Spouse != null)
						{
							this._youngHero.Spouse.Clan = this._youngHero.Clan;
						}
					}
					foreach (SkillObject skillObject in Skills.All)
					{
						this._youngHero.HeroDeveloper.AddFocus(skillObject, -1, false);
					}
				}
			}

			// Token: 0x06005D34 RID: 23860 RVA: 0x001B1CC0 File Offset: 0x001AFEC0
			protected override void OnCompleteWithSuccess()
			{
			}

			// Token: 0x06005D35 RID: 23861 RVA: 0x001B1CC4 File Offset: 0x001AFEC4
			protected override void OnTimedOut()
			{
				base.AddLog(this.FailTimedOutQuestLogText, false);
				this.RelationshipChangeWithQuestGiver = -10;
				this._showQuestFailedConversation = true;
				if (Settlement.CurrentSettlement == null && PlayerEncounter.Current == null && MapEvent.PlayerMapEvent == null && GameStateManager.Current.ActiveState is MapState)
				{
					CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, PartyBase.MainParty, false, false, false, false, false, false), new ConversationCharacterData(this._youngHero.CharacterObject, PartyBase.MainParty, false, false, false, false, false, false));
				}
			}

			// Token: 0x04001DAB RID: 7595
			private const int MinimumSkillGainToComment = 15;

			// Token: 0x04001DAC RID: 7596
			private const int TargetSkillPointDelta = 30;

			// Token: 0x04001DAD RID: 7597
			[SaveableField(10)]
			private Hero _youngHero;

			// Token: 0x04001DAE RID: 7598
			[SaveableField(20)]
			private bool _checkForMissionEnd;

			// Token: 0x04001DAF RID: 7599
			[SaveableField(30)]
			private bool _firstConversationInitialized;

			// Token: 0x04001DB0 RID: 7600
			[SaveableField(40)]
			private bool _questCompletedStartConversation;

			// Token: 0x04001DB1 RID: 7601
			[SaveableField(50)]
			private int _youngHeroBeginningSkillPoints;

			// Token: 0x04001DB2 RID: 7602
			[SaveableField(60)]
			private int _randomForQuestReward;

			// Token: 0x04001DB3 RID: 7603
			private int _targetSkillGain;

			// Token: 0x04001DB4 RID: 7604
			[SaveableField(70)]
			private Dictionary<SkillObject, int> _oldSkillValues;

			// Token: 0x04001DB5 RID: 7605
			private bool _doNotForceYoungHeroOutFromClan;

			// Token: 0x04001DB6 RID: 7606
			private bool _showQuestFailedConversation;

			// Token: 0x04001DB7 RID: 7607
			[SaveableField(80)]
			private JournalLog _startQuestLog;

			// Token: 0x020008EC RID: 2284
			// (Invoke) Token: 0x060069D0 RID: 27088
			private delegate bool ExperienceIncreaseCondition();
		}

		// Token: 0x0200073B RID: 1851
		public class LordsNeedsTutorIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005D3B RID: 23867 RVA: 0x001B1DD2 File Offset: 0x001AFFD2
			public LordsNeedsTutorIssueTypeDefiner()
				: base(80120)
			{
			}

			// Token: 0x06005D3C RID: 23868 RVA: 0x001B1DDF File Offset: 0x001AFFDF
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssue), 1, null);
				base.AddClassDefinition(typeof(LordsNeedsTutorIssueBehavior.LordsNeedsTutorIssueQuest), 2, null);
			}
		}
	}
}
