using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000370 RID: 880
	public class LordNeedsHorsesIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060033CD RID: 13261 RVA: 0x000D5694 File Offset: 0x000D3894
		private void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnIssueSelected), typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x060033CE RID: 13262 RVA: 0x000D56F8 File Offset: 0x000D38F8
		private IssueBase OnIssueSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue(issueOwner);
		}

		// Token: 0x060033CF RID: 13263 RVA: 0x000D5700 File Offset: 0x000D3900
		private bool ConditionsHold(Hero issueGiver)
		{
			if (!issueGiver.IsKingdomLeader)
			{
				Clan clan = issueGiver.Clan;
				if (((clan != null) ? clan.Leader : null) != issueGiver)
				{
					return false;
				}
			}
			if (issueGiver.Culture.StringId != "nord" && !issueGiver.IsMinorFactionHero && issueGiver.Clan != Clan.PlayerClan)
			{
				MobileParty partyBelongedTo = issueGiver.PartyBelongedTo;
				if (partyBelongedTo != null && partyBelongedTo.Party.MemberRoster.TotalManCount > 50)
				{
					int num2;
					float num = LordNeedsHorsesIssueBehavior.ComputeMountsOverInfantryCountRatio(partyBelongedTo, out num2);
					return num2 >= 10 && num < 0.6f;
				}
			}
			return false;
		}

		// Token: 0x060033D0 RID: 13264 RVA: 0x000D5790 File Offset: 0x000D3990
		public static float ComputeMountsOverInfantryCountRatio(MobileParty issueParty, out int numInfantry)
		{
			if (issueParty == null)
			{
				Debug.FailedAssert("Cannot compute mounts over infantry ratio as related party is null", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Issues\\LordNeedsHorsesIssueBehavior.cs", "ComputeMountsOverInfantryCountRatio", 917);
				numInfantry = 0;
				return float.MaxValue;
			}
			int numberOfMounts = issueParty.ItemRoster.NumberOfMounts;
			numInfantry = 0;
			foreach (TroopRosterElement troopRosterElement in issueParty.Party.MemberRoster.GetTroopRoster())
			{
				if (troopRosterElement.Character.IsInfantry)
				{
					numInfantry += troopRosterElement.Number;
				}
			}
			if (numInfantry != 0)
			{
				return (float)numberOfMounts / (float)numInfantry;
			}
			return float.MaxValue;
		}

		// Token: 0x060033D1 RID: 13265 RVA: 0x000D5844 File Offset: 0x000D3A44
		public static bool IsMountCamel(ItemObject mountObject)
		{
			HorseComponent horseComponent;
			return (horseComponent = ((mountObject != null) ? mountObject.ItemComponent : null) as HorseComponent) != null && horseComponent.Monster.MonsterUsage == "camel";
		}

		// Token: 0x060033D2 RID: 13266 RVA: 0x000D587D File Offset: 0x000D3A7D
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060033D3 RID: 13267 RVA: 0x000D5896 File Offset: 0x000D3A96
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000ED3 RID: 3795
		private const IssueBase.IssueFrequency LordNeedsHorsesIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000736 RID: 1846
		public class LordNeedsHorsesIssue : IssueBase
		{
			// Token: 0x06005C81 RID: 23681 RVA: 0x001AEBF5 File Offset: 0x001ACDF5
			internal static void AutoGeneratedStaticCollectObjectsLordNeedsHorsesIssue(object o, List<object> collectedObjects)
			{
				((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005C82 RID: 23682 RVA: 0x001AEC03 File Offset: 0x001ACE03
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._mountObjectToBeDelivered);
			}

			// Token: 0x06005C83 RID: 23683 RVA: 0x001AEC18 File Offset: 0x001ACE18
			internal static object AutoGeneratedGetMemberValue_numMountsToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o)._numMountsToBeDelivered;
			}

			// Token: 0x06005C84 RID: 23684 RVA: 0x001AEC2A File Offset: 0x001ACE2A
			internal static object AutoGeneratedGetMemberValue_mountObjectToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o)._mountObjectToBeDelivered;
			}

			// Token: 0x06005C85 RID: 23685 RVA: 0x001AEC37 File Offset: 0x001ACE37
			internal static object AutoGeneratedGetMemberValue_mountValuePerUnit(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o)._mountValuePerUnit;
			}

			// Token: 0x17001259 RID: 4697
			// (get) Token: 0x06005C86 RID: 23686 RVA: 0x001AEC49 File Offset: 0x001ACE49
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 2 + MathF.Ceiling(4f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700125A RID: 4698
			// (get) Token: 0x06005C87 RID: 23687 RVA: 0x001AEC5E File Offset: 0x001ACE5E
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x1700125B RID: 4699
			// (get) Token: 0x06005C88 RID: 23688 RVA: 0x001AEC61 File Offset: 0x001ACE61
			protected override int RewardGold
			{
				get
				{
					return 500 + MathF.Ceiling(1.5f * (float)this.IssueNumMountsToBeDelivered * (float)this._mountValuePerUnit);
				}
			}

			// Token: 0x1700125C RID: 4700
			// (get) Token: 0x06005C89 RID: 23689 RVA: 0x001AEC83 File Offset: 0x001ACE83
			private int IssueNumMountsToBeDelivered
			{
				get
				{
					if (this._numMountsToBeDelivered == 0)
					{
						this._numMountsToBeDelivered = 1 + MathF.Ceiling(12f * base.IssueDifficultyMultiplier);
					}
					return this._numMountsToBeDelivered;
				}
			}

			// Token: 0x1700125D RID: 4701
			// (get) Token: 0x06005C8A RID: 23690 RVA: 0x001AECAC File Offset: 0x001ACEAC
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 3 + MathF.Ceiling(6f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700125E RID: 4702
			// (get) Token: 0x06005C8B RID: 23691 RVA: 0x001AECC1 File Offset: 0x001ACEC1
			private int AlternativeSolutionGoldRequirement
			{
				get
				{
					return this.IssueNumMountsToBeDelivered * this._mountValuePerUnit;
				}
			}

			// Token: 0x1700125F RID: 4703
			// (get) Token: 0x06005C8C RID: 23692 RVA: 0x001AECD0 File Offset: 0x001ACED0
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001260 RID: 4704
			// (get) Token: 0x06005C8D RID: 23693 RVA: 0x001AECE5 File Offset: 0x001ACEE5
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=TBpMffcv}Campaigning this season has taken even a higher toll on {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} than it has on my men. The animals will drop dead of exhaustion while my troops soldier on. Yet if we don't keep our stocks up, the enemy will run rings around us.[if:convo_undecided_closed][ib:closed]", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			// Token: 0x17001261 RID: 4705
			// (get) Token: 0x06005C8E RID: 23694 RVA: 0x001AED0F File Offset: 0x001ACF0F
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=jjNSVzx3}What do you need, my {?ISSUE_GIVER.GENDER}lady{?}lord{\\?}?", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x17001262 RID: 4706
			// (get) Token: 0x06005C8F RID: 23695 RVA: 0x001AED34 File Offset: 0x001ACF34
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=ugHO6Sa6}I need more {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}, specifically, we need {MOUNT_COUNT} and they need to be {PLURAL(MOUNT_NAME)}, because we know how to use them and how they fit our needs. Bring them to me and a bag of {REWARD}{GOLD_ICON} will be right in your pocket.[if:convo_undecided_closed]", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("MOUNT_COUNT", this.IssueNumMountsToBeDelivered);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					return textObject;
				}
			}

			// Token: 0x17001263 RID: 4707
			// (get) Token: 0x06005C90 RID: 23696 RVA: 0x001AEDB5 File Offset: 0x001ACFB5
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=0YRl5Yie}I'll bring your {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} by myself.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			// Token: 0x17001264 RID: 4708
			// (get) Token: 0x06005C91 RID: 23697 RVA: 0x001AEDDF File Offset: 0x001ACFDF
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001265 RID: 4709
			// (get) Token: 0x06005C92 RID: 23698 RVA: 0x001AEDE4 File Offset: 0x001ACFE4
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=YHG17dqZ}One of your companions who is good at haggling and riding would be appropriate for this task. {?MOUNT_TYPE_IS_CAMEL}Camels{?}Horses{\\?} should cost no more than {REQUIRED_GOLD_AMOUNT}{GOLD_ICON} denars and this should be covered by yourself. You'll also need some cavalry to bring the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}. A purse of {REWARD_GOLD_AMOUNT}{GOLD_ICON} denars will be waiting for you when you get the job done.[if:convo_undecided_closed]", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("REQUIRED_GOLD_AMOUNT", this.AlternativeSolutionGoldRequirement);
					textObject.SetTextVariable("REWARD_GOLD_AMOUNT", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001266 RID: 4710
			// (get) Token: 0x06005C93 RID: 23699 RVA: 0x001AEE4E File Offset: 0x001AD04E
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=loJja04L}My men will bring your {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} as soon as possible.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			// Token: 0x17001267 RID: 4711
			// (get) Token: 0x06005C94 RID: 23700 RVA: 0x001AEE78 File Offset: 0x001AD078
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=6EJbUGpi}You will be rewarded when your companion returns with the animals we discussed.[if:convo_approving]", null);
				}
			}

			// Token: 0x17001268 RID: 4712
			// (get) Token: 0x06005C95 RID: 23701 RVA: 0x001AEE85 File Offset: 0x001AD085
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=YF6PPWlT}Very good. I'm sure your men will bring my {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} as soon as possible.[if:convo_approving]", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			// Token: 0x17001269 RID: 4713
			// (get) Token: 0x06005C96 RID: 23702 RVA: 0x001AEEB0 File Offset: 0x001AD0B0
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=PCigQKQ8}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} for {?QUEST_GIVER.GENDER}her{?}his{\\?} party. You asked your companion {COMPANION.LINK} and {TROOP_COUNT} of your horsemen to deliver {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK}. {?QUEST_GIVER.GENDER}She{?}He{\\?} will pay you {REWARD}{GOLD_ICON} denars when the task is done. They will rejoin your party in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("TROOP_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					textObject.SetTextVariable("MOUNT_COUNT", this.IssueNumMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					textObject.SetTextVariable("RETURN_DAYS", MathF.Ceiling(base.AlternativeSolutionReturnTimeForTroops.RemainingDaysFromNow));
					return textObject;
				}
			}

			// Token: 0x1700126A RID: 4714
			// (get) Token: 0x06005C97 RID: 23703 RVA: 0x001AEF9C File Offset: 0x001AD19C
			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=tJc5mZua}Your companion has successfully delivered the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} {QUEST_GIVER.LINK} requested. You received {QUEST_REWARD}{GOLD_ICON} gold in return for your service.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("QUEST_REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700126B RID: 4715
			// (get) Token: 0x06005C98 RID: 23704 RVA: 0x001AF00E File Offset: 0x001AD20E
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x06005C99 RID: 23705 RVA: 0x001AF011 File Offset: 0x001AD211
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, true);
			}

			// Token: 0x06005C9A RID: 23706 RVA: 0x001AF022 File Offset: 0x001AD222
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2 && character.IsMounted;
			}

			// Token: 0x06005C9B RID: 23707 RVA: 0x001AF035 File Offset: 0x001AD235
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, true) && QuestHelper.CheckGoldForAlternativeSolution(this.AlternativeSolutionGoldRequirement, out explanation);
			}

			// Token: 0x06005C9C RID: 23708 RVA: 0x001AF05F File Offset: 0x001AD25F
			public override void AlternativeSolutionStartConsequence()
			{
				Hero.MainHero.ChangeHeroGold(-this.AlternativeSolutionGoldRequirement);
			}

			// Token: 0x06005C9D RID: 23709 RVA: 0x001AF072 File Offset: 0x001AD272
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.RelationshipChangeWithIssueOwner = 2;
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
			}

			// Token: 0x06005C9E RID: 23710 RVA: 0x001AF08B File Offset: 0x001AD28B
			protected override void AlternativeSolutionEndWithFailureConsequence()
			{
				this.RelationshipChangeWithIssueOwner = -5;
			}

			// Token: 0x06005C9F RID: 23711 RVA: 0x001AF095 File Offset: 0x001AD295
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005CA0 RID: 23712 RVA: 0x001AF097 File Offset: 0x001AD297
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005CA1 RID: 23713 RVA: 0x001AF099 File Offset: 0x001AD299
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest(questId, base.IssueOwner, this.IssueNumMountsToBeDelivered, this._mountObjectToBeDelivered, this.RewardGold, CampaignTime.DaysFromNow(20f));
			}

			// Token: 0x06005CA2 RID: 23714 RVA: 0x001AF0C3 File Offset: 0x001AD2C3
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005CA3 RID: 23715 RVA: 0x001AF0C8 File Offset: 0x001AD2C8
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flag = IssueBase.PreconditionFlags.None;
				skill = null;
				requiredGold = 0;
				relationHero = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					relationHero = issueGiver;
					flag |= IssueBase.PreconditionFlags.Relation;
				}
				if (Hero.MainHero.IsKingdomLeader)
				{
					flag |= IssueBase.PreconditionFlags.MainHeroIsKingdomLeader;
				}
				if (issueGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005CA4 RID: 23716 RVA: 0x001AF132 File Offset: 0x001AD332
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x06005CA5 RID: 23717 RVA: 0x001AF134 File Offset: 0x001AD334
			public override bool IssueStayAliveConditions()
			{
				int num;
				return !base.IssueOwner.IsDead && base.IssueOwner.PartyBelongedTo != null && base.IssueOwner.Clan != Clan.PlayerClan && (base.IssueOwner.IsKingdomLeader || base.IssueOwner.Clan.Leader == base.IssueOwner) && LordNeedsHorsesIssueBehavior.ComputeMountsOverInfantryCountRatio(base.IssueOwner.PartyBelongedTo, out num) < 0.8f;
			}

			// Token: 0x1700126C RID: 4716
			// (get) Token: 0x06005CA6 RID: 23718 RVA: 0x001AF1AE File Offset: 0x001AD3AE
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=5zF6vI5s}Lord Needs {?MOUNT_TYPE_IS_CAMEL}Camels{?}Horses{\\?}", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			// Token: 0x1700126D RID: 4717
			// (get) Token: 0x06005CA7 RID: 23719 RVA: 0x001AF1D8 File Offset: 0x001AD3D8
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=GHbM1i6R}{QUEST_GIVER.LINK} needs {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} to speed up {?QUEST_GIVER.GENDER}her{?}his{\\?} party.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			// Token: 0x06005CA8 RID: 23720 RVA: 0x001AF228 File Offset: 0x001AD428
			public LordNeedsHorsesIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(20f))
			{
				MBList<ItemObject> mblist = new MBList<ItemObject>();
				foreach (ItemObject itemObject in Items.All)
				{
					if (itemObject.IsMountable && itemObject.Culture == issueOwner.Culture && !itemObject.NotMerchandise && itemObject.Tierf > 2f && itemObject.Tierf < 3f)
					{
						mblist.Add(itemObject);
					}
				}
				this._mountObjectToBeDelivered = mblist.GetRandomElement<ItemObject>();
				this._numMountsToBeDelivered = 1 + MathF.Ceiling(12f * base.IssueDifficultyMultiplier);
				if (this._mountObjectToBeDelivered == null)
				{
					this._mountObjectToBeDelivered = MBObjectManager.Instance.GetObject<ItemObject>("sumpter_horse");
				}
				ItemObject mountObjectToBeDelivered = this._mountObjectToBeDelivered;
				this._mountValuePerUnit = ((mountObjectToBeDelivered != null) ? mountObjectToBeDelivered.Value : 0);
			}

			// Token: 0x06005CA9 RID: 23721 RVA: 0x001AF324 File Offset: 0x001AD524
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.ClanInfluence)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005CAA RID: 23722 RVA: 0x001AF339 File Offset: 0x001AD539
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Trade) >= hero.GetSkillValue(DefaultSkills.Riding)) ? DefaultSkills.Trade : DefaultSkills.Riding, 120);
			}

			// Token: 0x04001D91 RID: 7569
			private const int IssueDueTimeInDays = 20;

			// Token: 0x04001D92 RID: 7570
			internal const int IssueGiverMinimumPartySize = 50;

			// Token: 0x04001D93 RID: 7571
			internal const int IssueGiverMinimumInfantryCount = 10;

			// Token: 0x04001D94 RID: 7572
			internal const float IssuePreConditionMinPlayerRelation = -10f;

			// Token: 0x04001D95 RID: 7573
			internal const float IssuePreConditionMountsOverInfantryRatioThreshold = 0.6f;

			// Token: 0x04001D96 RID: 7574
			internal const float IssueStayingAliveMountsOverInfantryRatioThreshold = 0.8f;

			// Token: 0x04001D97 RID: 7575
			private const int AlternativeSolutionCompanionSkillThreshold = 120;

			// Token: 0x04001D98 RID: 7576
			private const int AlternativeSolutionRenownRewardOnSuccess = 1;

			// Token: 0x04001D99 RID: 7577
			private const int AlternativeSolutionRelationRewardOnSuccess = 2;

			// Token: 0x04001D9A RID: 7578
			private const int AlternativeSolutionRelationPenaltyOnFail = -5;

			// Token: 0x04001D9B RID: 7579
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x04001D9C RID: 7580
			[SaveableField(4)]
			private int _numMountsToBeDelivered;

			// Token: 0x04001D9D RID: 7581
			[SaveableField(2)]
			private readonly ItemObject _mountObjectToBeDelivered;

			// Token: 0x04001D9E RID: 7582
			[SaveableField(3)]
			private readonly int _mountValuePerUnit;
		}

		// Token: 0x02000737 RID: 1847
		public class LordNeedsHorsesIssueQuest : QuestBase
		{
			// Token: 0x06005CAB RID: 23723 RVA: 0x001AF366 File Offset: 0x001AD566
			internal static void AutoGeneratedStaticCollectObjectsLordNeedsHorsesIssueQuest(object o, List<object> collectedObjects)
			{
				((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005CAC RID: 23724 RVA: 0x001AF374 File Offset: 0x001AD574
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._mountObjectToBeDelivered);
				collectedObjects.Add(this._questJournalEntry);
			}

			// Token: 0x06005CAD RID: 23725 RVA: 0x001AF395 File Offset: 0x001AD595
			internal static object AutoGeneratedGetMemberValue_numMountsToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o)._numMountsToBeDelivered;
			}

			// Token: 0x06005CAE RID: 23726 RVA: 0x001AF3A7 File Offset: 0x001AD5A7
			internal static object AutoGeneratedGetMemberValue_mountObjectToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o)._mountObjectToBeDelivered;
			}

			// Token: 0x06005CAF RID: 23727 RVA: 0x001AF3B4 File Offset: 0x001AD5B4
			internal static object AutoGeneratedGetMemberValue_questJournalEntry(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o)._questJournalEntry;
			}

			// Token: 0x1700126E RID: 4718
			// (get) Token: 0x06005CB0 RID: 23728 RVA: 0x001AF3C1 File Offset: 0x001AD5C1
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=5zF6vI5s}Lord Needs {?MOUNT_TYPE_IS_CAMEL}Camels{?}Horses{\\?}", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			// Token: 0x1700126F RID: 4719
			// (get) Token: 0x06005CB1 RID: 23729 RVA: 0x001AF3EB File Offset: 0x001AD5EB
			private TextObject JournalTaskName
			{
				get
				{
					TextObject textObject = new TextObject("{=plHZYtxF}{PLURAL(REQUESTED_MOUNT_NAME)} in Inventory: ", null);
					textObject.SetTextVariable("REQUESTED_MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					return textObject;
				}
			}

			// Token: 0x17001270 RID: 4720
			// (get) Token: 0x06005CB2 RID: 23730 RVA: 0x001AF410 File Offset: 0x001AD610
			private TextObject OnQuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=GQ96SX4M}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} for {?QUEST_GIVER.GENDER}her{?}his{\\?} party. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to bring {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {?QUEST_GIVER.GENDER}her{?}him{\\?} or one of {?QUEST_GIVER.GENDER}her{?}his{\\?} garrison commanders. {?QUEST_GIVER.GENDER}She{?}He{\\?} will pay you {REWARD_GOLD}{GOLD_ICON} denars when the task is done.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					textObject.SetTextVariable("REWARD_GOLD", this.RewardGold);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001271 RID: 4721
			// (get) Token: 0x06005CB3 RID: 23731 RVA: 0x001AF4AC File Offset: 0x001AD6AC
			private TextObject OnQuestSucceededLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=aGvLxsub}You have successfully delivered {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK} as requested. You received {GOLD_REWARD}{GOLD_ICON} denars in return for your service.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					textObject.SetTextVariable("GOLD_REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001272 RID: 4722
			// (get) Token: 0x06005CB4 RID: 23732 RVA: 0x001AF52C File Offset: 0x001AD72C
			private TextObject OnQuestFailedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=yLuzvTtd}You had promised to deliver {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK}. But you've failed to complete this task. {QUEST_GIVER.LINK} was displeased.", null);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001273 RID: 4723
			// (get) Token: 0x06005CB5 RID: 23733 RVA: 0x001AF588 File Offset: 0x001AD788
			private TextObject OnQuestTimedOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=BFEYIMdi}You had promised to deliver {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK}. But you've failed to complete this task in time. {QUEST_GIVER.LINK} was displeased.", null);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001274 RID: 4724
			// (get) Token: 0x06005CB6 RID: 23734 RVA: 0x001AF5E4 File Offset: 0x001AD7E4
			private TextObject OnQuestCancelled2LogText
			{
				get
				{
					TextObject textObject = new TextObject("{=pYgl86Cr}Your clan had entered a war with the {QUEST_GIVER.LINK}'s faction. Your agreement was canceled. You can no longer deliver the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001275 RID: 4725
			// (get) Token: 0x06005CB7 RID: 23735 RVA: 0x001AF634 File Offset: 0x001AD834
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001276 RID: 4726
			// (get) Token: 0x06005CB8 RID: 23736 RVA: 0x001AF668 File Offset: 0x001AD868
			private TextObject OnQuestCancelled3LogText
			{
				get
				{
					TextObject textObject = new TextObject("{=qEh4gdjU}{QUEST_GIVER.LINK} was imprisoned and your agreement with {?QUEST_GIVER.GENDER}her{?}him{\\?} was canceled. You can no longer deliver the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001277 RID: 4727
			// (get) Token: 0x06005CB9 RID: 23737 RVA: 0x001AF6B8 File Offset: 0x001AD8B8
			private TextObject OnQuestMountRequirementSatisfiedQuickText
			{
				get
				{
					TextObject textObject = new TextObject("{=ZCPrYXaO}You have enough {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}. Return back to {QUEST_GIVER.LINK}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001278 RID: 4728
			// (get) Token: 0x06005CBA RID: 23738 RVA: 0x001AF708 File Offset: 0x001AD908
			private TextObject OnQuestMountRequirementNotSatisfiedQuickText
			{
				get
				{
					TextObject textObject = new TextObject("{=aFNfxhwz}You no longer have enough {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} for {QUEST_GIVER.LINK}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001279 RID: 4729
			// (get) Token: 0x06005CBB RID: 23739 RVA: 0x001AF757 File Offset: 0x001AD957
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x06005CBC RID: 23740 RVA: 0x001AF75C File Offset: 0x001AD95C
			public LordNeedsHorsesIssueQuest(string questId, Hero questGiver, int numMountsToBeDelivered, ItemObject mountObjectToBeDelivered, int rewardGold, CampaignTime duration)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._numMountsToBeDelivered = numMountsToBeDelivered;
				this._mountObjectToBeDelivered = mountObjectToBeDelivered;
				this._playerInventoryVersionNo = MobileParty.MainParty.ItemRoster.VersionNo;
				this._questGiversAgentCharacterObject = null;
				base.AddTrackedObject(base.QuestGiver);
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005CBD RID: 23741 RVA: 0x001AF7B8 File Offset: 0x001AD9B8
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				this._numMountsInInventory = this.GetNumQuestMountsInInventory();
				this._playerInventoryVersionNo = MobileParty.MainParty.ItemRoster.VersionNo;
				if (this._questJournalEntry == null)
				{
					this._questJournalEntry = base.JournalEntries.FirstOrDefault<JournalLog>((JournalLog x) => x.Range == this._numMountsToBeDelivered && x.Type == LogType.Discreate);
					if (this._questJournalEntry == null)
					{
						if (base.JournalEntries.Count > 0)
						{
							for (int i = 0; i < base.JournalEntries.Count; i++)
							{
								if (base.JournalEntries[i].Type == LogType.Discreate)
								{
									base.RemoveLog(base.JournalEntries[i]);
								}
							}
							this._questJournalEntry = base.AddDiscreteLog(this.OnQuestStartedLogText, this.JournalTaskName, MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered), this._numMountsToBeDelivered, null, false);
						}
						else
						{
							this._questJournalEntry = base.AddDiscreteLog(this.OnQuestStartedLogText, this.JournalTaskName, MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered), this._numMountsToBeDelivered, null, false);
						}
					}
				}
				this.UpdateQuestJournalEntry();
			}

			// Token: 0x06005CBE RID: 23742 RVA: 0x001AF8D8 File Offset: 0x001ADAD8
			protected override void SetDialogs()
			{
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetGarrisonCommanderDialogFlow(), this);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine("{=qR3gQrLi}Splendid. We'll need to keep moving around, though, so it might be tricky to find us. My fellow nobles will usually know where to find me though, if you ask them.[if:convo_approving][ib:hip2]", null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.OnQuestAccepted))
					.CloseDialog();
				new TextObject(LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? "{=nysBXpEO}camels" : "{=6YbGQDme}horses", null);
				TextObject textObject = new TextObject("{=bmW77NvO}What about my {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}?", null);
				textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				TextObject textObject2 = new TextObject("{=TLcnbALt}Here are your {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}.", null);
				textObject2.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject2, false);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				TextObject textObject3 = new TextObject("{=6bt9jYai}I am still looking for the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} you have requested.", null);
				textObject3.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				TextObject textObject4 = new TextObject("{=pV7DLTAu}I am sorry, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}. I cannot deliver the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} you requested.", null);
				textObject4.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject4, false);
				TextObject textObject5 = new TextObject("{=inkr6Dzy}Too bad. Perhaps someone else will be able to get me the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} that I need.", null);
				textObject5.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += MapEventHelper.OnConversationEnd;
					})
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject2, null, null, null)
					.Condition(() => this.GetNumQuestMountsInInventory() >= this._numMountsToBeDelivered)
					.NpcLine("{=9HJbLneH}Thank you for your help, {PLAYER.NAME}. Here is the purse I promised you. Farewell.[if:convo_happy][ib:hip]", null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(base.CompleteQuestWithSuccess))
					.CloseDialog()
					.PlayerOption(textObject3, null, null, null)
					.NpcLine("{=cH0iAEfq}Please take care of this as quickly as you can. I need those animals.[if:convo_undecided_closed]", null, null, null, null)
					.CloseDialog()
					.PlayerOption(textObject4, null, null, null)
					.NpcLine(textObject5, null, null, null, null)
					.Consequence(delegate
					{
						this.OnQuestDeclined();
					})
					.CloseDialog()
					.EndPlayerOptions();
			}

			// Token: 0x06005CBF RID: 23743 RVA: 0x001AFB54 File Offset: 0x001ADD54
			private DialogFlow GetGarrisonCommanderDialogFlow()
			{
				TextObject textObject = new TextObject("{=JxhEOqyT}We were waiting for you, {?PLAYER.GENDER}madam{?}sir{\\?}. Have you brought the horses that our {?ISSUE_OWNER.GENDER}lady{?}lord{\\?} requested?", null);
				StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.QuestGiver.CharacterObject, textObject, false);
				return DialogFlow.CreateDialogFlow("start", 300).NpcLine(textObject, null, null, null, null).Condition(() => CharacterObject.OneToOneConversationCharacter == this._questGiversAgentCharacterObject)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=ZEy3gE7w}Here are your horses.", null), null, null, null)
					.Condition(() => this.GetNumQuestMountsInInventory() >= this._numMountsToBeDelivered)
					.NpcLine(new TextObject("{=g8qb3Ame}Thank you.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += base.CompleteQuestWithSuccess;
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=G5tyQj6N}Not yet.", null), null, null, null)
					.NpcLine(new TextObject("{=sjTpEzju}Very well. We'll keep waiting.", null), null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions();
			}

			// Token: 0x06005CC0 RID: 23744 RVA: 0x001AFC38 File Offset: 0x001ADE38
			private void OnQuestAccepted()
			{
				base.StartQuest();
				this._numMountsInInventory = this.GetNumQuestMountsInInventory();
				this._questJournalEntry = base.AddDiscreteLog(this.OnQuestStartedLogText, this.JournalTaskName, MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered), this._numMountsToBeDelivered, null, false);
			}

			// Token: 0x06005CC1 RID: 23745 RVA: 0x001AFC89 File Offset: 0x001ADE89
			private void OnQuestDeclined()
			{
				base.AddLog(this.OnQuestFailedLogText, false);
				base.CompleteQuestWithFail(null);
			}

			// Token: 0x06005CC2 RID: 23746 RVA: 0x001AFCA0 File Offset: 0x001ADEA0
			protected override void RegisterEvents()
			{
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnPlayerInventoryExchange));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.HeroPrisonerTaken.AddNonSerializedListener(this, new Action<PartyBase, Hero>(this.OnHeroPrisonerTaken));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.SettlementEntered.AddNonSerializedListener(this, new Action<MobileParty, Settlement, Hero>(this.OnSettlementEntered));
			}

			// Token: 0x06005CC3 RID: 23747 RVA: 0x001AFD38 File Offset: 0x001ADF38
			private void OnSettlementEntered(MobileParty mobileParty, Settlement settlement, Hero hero)
			{
				if (!Campaign.Current.ConversationManager.IsConversationFlowActive && hero == Hero.MainHero && mobileParty == MobileParty.MainParty && settlement.IsFortification && settlement.OwnerClan == base.QuestGiver.Clan)
				{
					MobileParty garrisonParty = Settlement.CurrentSettlement.Town.GarrisonParty;
					MBList<TroopRosterElement> mblist;
					if (garrisonParty == null)
					{
						mblist = null;
					}
					else
					{
						TroopRoster memberRoster = garrisonParty.MemberRoster;
						mblist = ((memberRoster != null) ? memberRoster.GetTroopRoster() : null);
					}
					MBList<TroopRosterElement> mblist2 = mblist;
					CharacterObject characterObject;
					if (mblist2 == null || mblist2.Count == 0)
					{
						characterObject = base.QuestGiver.Culture.Guard;
					}
					else
					{
						characterObject = mblist2.MaxBy<TroopRosterElement, int>((TroopRosterElement troop) => troop.Character.Tier).Character;
					}
					this._questGiversAgentCharacterObject = characterObject;
					CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, PartyBase.MainParty, false, false, false, false, false, false), new ConversationCharacterData(this._questGiversAgentCharacterObject, null, false, false, false, false, false, false));
				}
			}

			// Token: 0x06005CC4 RID: 23748 RVA: 0x001AFE36 File Offset: 0x001AE036
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005CC5 RID: 23749 RVA: 0x001AFE4C File Offset: 0x001AE04C
			private void UpdateQuestJournalEntry()
			{
				int num = MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered);
				if (num != this._questJournalEntry.CurrentProgress)
				{
					base.UpdateQuestTaskStage(this._questJournalEntry, num);
				}
			}

			// Token: 0x06005CC6 RID: 23750 RVA: 0x001AFE88 File Offset: 0x001AE088
			private void CheckAndHandleQuestSuccessConditions()
			{
				int numQuestMountsInInventory = this.GetNumQuestMountsInInventory();
				if (numQuestMountsInInventory != this._numMountsInInventory)
				{
					if (this._numMountsInInventory < this._numMountsToBeDelivered && numQuestMountsInInventory >= this._numMountsToBeDelivered)
					{
						MBInformationManager.AddQuickInformation(this.OnQuestMountRequirementSatisfiedQuickText, 0, null, null, "");
					}
					else if (this._numMountsInInventory >= this._numMountsToBeDelivered && numQuestMountsInInventory < this._numMountsToBeDelivered)
					{
						MBInformationManager.AddQuickInformation(this.OnQuestMountRequirementNotSatisfiedQuickText, 0, null, null, "");
					}
					this._numMountsInInventory = numQuestMountsInInventory;
					this.UpdateQuestJournalEntry();
				}
			}

			// Token: 0x06005CC7 RID: 23751 RVA: 0x001AFF08 File Offset: 0x001AE108
			protected override void HourlyTick()
			{
				int versionNo = MobileParty.MainParty.ItemRoster.VersionNo;
				if (this._playerInventoryVersionNo != versionNo)
				{
					this.CheckAndHandleQuestSuccessConditions();
					this._playerInventoryVersionNo = versionNo;
				}
			}

			// Token: 0x06005CC8 RID: 23752 RVA: 0x001AFF3C File Offset: 0x001AE13C
			private void OnPlayerInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				bool flag = false;
				foreach (ValueTuple<ItemRosterElement, int> valueTuple in purchasedItems)
				{
					ItemRosterElement itemRosterElement = valueTuple.Item1;
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						flag = true;
						break;
					}
				}
				bool flag2 = false;
				foreach (ValueTuple<ItemRosterElement, int> valueTuple2 in soldItems)
				{
					ItemRosterElement itemRosterElement = valueTuple2.Item1;
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						flag2 = true;
						break;
					}
				}
				if (flag || flag2)
				{
					this.CheckAndHandleQuestSuccessConditions();
				}
				this._playerInventoryVersionNo = MobileParty.MainParty.ItemRoster.VersionNo;
			}

			// Token: 0x06005CC9 RID: 23753 RVA: 0x001B0028 File Offset: 0x001AE228
			private void OnHeroPrisonerTaken(PartyBase capturer, Hero prisoner)
			{
				if (prisoner == base.QuestGiver)
				{
					base.CompleteQuestWithCancel(this.OnQuestCancelled3LogText);
				}
			}

			// Token: 0x06005CCA RID: 23754 RVA: 0x001B003F File Offset: 0x001AE23F
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.OnQuestCancelled2LogText);
				}
			}

			// Token: 0x06005CCB RID: 23755 RVA: 0x001B0069 File Offset: 0x001AE269
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.OnQuestCancelled2LogText, false);
			}

			// Token: 0x06005CCC RID: 23756 RVA: 0x001B0084 File Offset: 0x001AE284
			protected override void OnCompleteWithSuccess()
			{
				base.AddLog(this.OnQuestSucceededLogText, false);
				int num = this._numMountsToBeDelivered;
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						int amount = itemRosterElement.Amount;
						if (amount >= num)
						{
							this.GiveMounts(Hero.MainHero, base.QuestGiver, itemRosterElement, num);
							break;
						}
						num -= amount;
						this.GiveMounts(Hero.MainHero, base.QuestGiver, itemRosterElement, amount);
					}
				}
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				this.RelationshipChangeWithQuestGiver = 2;
			}

			// Token: 0x06005CCD RID: 23757 RVA: 0x001B0164 File Offset: 0x001AE364
			private void GiveMounts(Hero giver, Hero receiver, ItemRosterElement item, int count)
			{
				if (giver.PartyBelongedTo != null)
				{
					giver.PartyBelongedTo.Party.ItemRoster.AddToCounts(item.EquipmentElement, -count);
					if (receiver.PartyBelongedTo != null)
					{
						receiver.PartyBelongedTo.Party.ItemRoster.AddToCounts(item.EquipmentElement, count);
					}
				}
			}

			// Token: 0x06005CCE RID: 23758 RVA: 0x001B01C0 File Offset: 0x001AE3C0
			protected override void OnFinalize()
			{
				base.RemoveTrackedObject(base.QuestGiver);
			}

			// Token: 0x06005CCF RID: 23759 RVA: 0x001B01CE File Offset: 0x001AE3CE
			public override void OnFailed()
			{
				this.RelationshipChangeWithQuestGiver = -3;
			}

			// Token: 0x06005CD0 RID: 23760 RVA: 0x001B01D8 File Offset: 0x001AE3D8
			protected override void OnTimedOut()
			{
				base.AddLog(this.OnQuestTimedOutLogText, false);
				this.RelationshipChangeWithQuestGiver = -5;
			}

			// Token: 0x06005CD1 RID: 23761 RVA: 0x001B01F0 File Offset: 0x001AE3F0
			private int GetNumQuestMountsInInventory()
			{
				int num = 0;
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						num += itemRosterElement.Amount;
					}
				}
				return num;
			}

			// Token: 0x04001D9F RID: 7583
			private const int RenownChangeOnSuccess = 1;

			// Token: 0x04001DA0 RID: 7584
			private const int RelationChangeOnSuccess = 2;

			// Token: 0x04001DA1 RID: 7585
			private const int RelationChangeOnFailure = -3;

			// Token: 0x04001DA2 RID: 7586
			private const int RelationChangeOnTimeOut = -5;

			// Token: 0x04001DA3 RID: 7587
			[SaveableField(1)]
			private readonly int _numMountsToBeDelivered;

			// Token: 0x04001DA4 RID: 7588
			[SaveableField(2)]
			private readonly ItemObject _mountObjectToBeDelivered;

			// Token: 0x04001DA5 RID: 7589
			[SaveableField(3)]
			private JournalLog _questJournalEntry;

			// Token: 0x04001DA6 RID: 7590
			private int _numMountsInInventory;

			// Token: 0x04001DA7 RID: 7591
			private int _playerInventoryVersionNo;

			// Token: 0x04001DA8 RID: 7592
			private CharacterObject _questGiversAgentCharacterObject;
		}

		// Token: 0x02000738 RID: 1848
		public class LordNeedsHorsesIssueBehaviorTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005CDA RID: 23770 RVA: 0x001B02F3 File Offset: 0x001AE4F3
			public LordNeedsHorsesIssueBehaviorTypeDefiner()
				: base(510000)
			{
			}

			// Token: 0x06005CDB RID: 23771 RVA: 0x001B0300 File Offset: 0x001AE500
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue), 1, null);
				base.AddClassDefinition(typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest), 2, null);
			}

			// Token: 0x06005CDC RID: 23772 RVA: 0x001B0326 File Offset: 0x001AE526
			protected override void DefineEnumTypes()
			{
			}
		}
	}
}
