using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000375 RID: 885
	public class NearbyBanditBaseIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x17000C61 RID: 3169
		// (get) Token: 0x060033FE RID: 13310 RVA: 0x000D6447 File Offset: 0x000D4647
		private float NearbyHideoutMaxRange
		{
			get
			{
				return Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.Default) * 0.5f;
			}
		}

		// Token: 0x060033FF RID: 13311 RVA: 0x000D645C File Offset: 0x000D465C
		private Settlement FindSuitableHideout(Hero issueOwner)
		{
			Settlement settlement = null;
			float num = float.MaxValue;
			for (int i = 0; i < Campaign.Current.AllHideouts.Count; i++)
			{
				Hideout hideout = Campaign.Current.AllHideouts[i];
				if (hideout.IsInfested)
				{
					float distance = Campaign.Current.Models.MapDistanceModel.GetDistance(hideout.Settlement, issueOwner.CurrentSettlement, false, false, MobileParty.NavigationType.Default);
					if (distance <= this.NearbyHideoutMaxRange && distance < num)
					{
						num = distance;
						settlement = hideout.Settlement;
					}
				}
			}
			return settlement;
		}

		// Token: 0x06003400 RID: 13312 RVA: 0x000D64E4 File Offset: 0x000D46E4
		private void OnCheckForIssue(Hero hero)
		{
			if (hero.IsNotable)
			{
				if (this.ConditionsHold(hero))
				{
					Settlement settlement = this.FindSuitableHideout(hero);
					if (settlement != null)
					{
						Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnIssueSelected), typeof(NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue), IssueBase.IssueFrequency.VeryCommon, settlement));
						return;
					}
					Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue), IssueBase.IssueFrequency.VeryCommon));
					return;
				}
				else
				{
					Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue), IssueBase.IssueFrequency.VeryCommon));
				}
			}
		}

		// Token: 0x06003401 RID: 13313 RVA: 0x000D6580 File Offset: 0x000D4780
		private IssueBase OnIssueSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			PotentialIssueData potentialIssueData = pid;
			return new NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue(issueOwner, potentialIssueData.RelatedObject as Settlement);
		}

		// Token: 0x06003402 RID: 13314 RVA: 0x000D65A6 File Offset: 0x000D47A6
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.IsHeadman && issueGiver.CurrentSettlement != null && issueGiver.CurrentSettlement.Village.Bound.Town.Security <= 50f;
		}

		// Token: 0x06003403 RID: 13315 RVA: 0x000D65E0 File Offset: 0x000D47E0
		private void OnIssueUpdated(IssueBase issue, IssueBase.IssueUpdateDetails details, Hero issueSolver = null)
		{
			NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue nearbyBanditBaseIssue;
			if ((nearbyBanditBaseIssue = issue as NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue) != null && details == IssueBase.IssueUpdateDetails.IssueFinishedByAILord)
			{
				foreach (MobileParty mobileParty in nearbyBanditBaseIssue.TargetHideout.Parties)
				{
					mobileParty.SetMovePatrolAroundSettlement(nearbyBanditBaseIssue.TargetHideout, MobileParty.NavigationType.Default, false);
				}
			}
		}

		// Token: 0x06003404 RID: 13316 RVA: 0x000D664C File Offset: 0x000D484C
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
			CampaignEvents.OnIssueUpdatedEvent.AddNonSerializedListener(this, new Action<IssueBase, IssueBase.IssueUpdateDetails, Hero>(this.OnIssueUpdated));
		}

		// Token: 0x06003405 RID: 13317 RVA: 0x000D667C File Offset: 0x000D487C
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EDF RID: 3807
		private const IssueBase.IssueFrequency NearbyHideoutIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000747 RID: 1863
		public class NearbyBanditBaseIssue : IssueBase
		{
			// Token: 0x06005E62 RID: 24162 RVA: 0x001B69FB File Offset: 0x001B4BFB
			internal static void AutoGeneratedStaticCollectObjectsNearbyBanditBaseIssue(object o, List<object> collectedObjects)
			{
				((NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005E63 RID: 24163 RVA: 0x001B6A09 File Offset: 0x001B4C09
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetHideout);
				collectedObjects.Add(this._issueSettlement);
			}

			// Token: 0x06005E64 RID: 24164 RVA: 0x001B6A2A File Offset: 0x001B4C2A
			internal static object AutoGeneratedGetMemberValue_targetHideout(object o)
			{
				return ((NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue)o)._targetHideout;
			}

			// Token: 0x06005E65 RID: 24165 RVA: 0x001B6A37 File Offset: 0x001B4C37
			internal static object AutoGeneratedGetMemberValue_issueSettlement(object o)
			{
				return ((NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue)o)._issueSettlement;
			}

			// Token: 0x170012E4 RID: 4836
			// (get) Token: 0x06005E66 RID: 24166 RVA: 0x001B6A44 File Offset: 0x001B4C44
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Casualties | IssueBase.AlternativeSolutionScaleFlag.FailureRisk;
				}
			}

			// Token: 0x170012E5 RID: 4837
			// (get) Token: 0x06005E67 RID: 24167 RVA: 0x001B6A48 File Offset: 0x001B4C48
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 10;
				}
			}

			// Token: 0x170012E6 RID: 4838
			// (get) Token: 0x06005E68 RID: 24168 RVA: 0x001B6A4C File Offset: 0x001B4C4C
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 4 + MathF.Ceiling(6f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170012E7 RID: 4839
			// (get) Token: 0x06005E69 RID: 24169 RVA: 0x001B6A61 File Offset: 0x001B4C61
			protected override int RewardGold
			{
				get
				{
					return 3000;
				}
			}

			// Token: 0x170012E8 RID: 4840
			// (get) Token: 0x06005E6A RID: 24170 RVA: 0x001B6A68 File Offset: 0x001B4C68
			internal Settlement TargetHideout
			{
				get
				{
					return this._targetHideout;
				}
			}

			// Token: 0x170012E9 RID: 4841
			// (get) Token: 0x06005E6B RID: 24171 RVA: 0x001B6A70 File Offset: 0x001B4C70
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=vw2Q9jJH}Yes... There's this old ruin, a place that offers a good view of the roads, and is yet hard to reach. Needless to say, it attracts bandits. A new gang has moved in and they have been giving hell to the caravans and travellers passing by.[ib:closed][if:convo_undecided_open]", null);
				}
			}

			// Token: 0x170012EA RID: 4842
			// (get) Token: 0x06005E6C RID: 24172 RVA: 0x001B6A7D File Offset: 0x001B4C7D
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=IqH0jFdK}So you need someone to deal with these bastards?", null);
				}
			}

			// Token: 0x170012EB RID: 4843
			// (get) Token: 0x06005E6D RID: 24173 RVA: 0x001B6A8A File Offset: 0x001B4C8A
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					return new TextObject("{=zstiYI49}Any bandits there can easily spot and evade a large army moving against them, but if you can enter the hideout with a small group of determined warriors you can catch them unaware.[ib:closed][if:convo_thinking]", null);
				}
			}

			// Token: 0x170012EC RID: 4844
			// (get) Token: 0x06005E6E RID: 24174 RVA: 0x001B6A97 File Offset: 0x001B4C97
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=uhYprSnG}I will go to the hideout myself and ambush the bandits.", null);
				}
			}

			// Token: 0x170012ED RID: 4845
			// (get) Token: 0x06005E6F RID: 24175 RVA: 0x001B6AA4 File Offset: 0x001B4CA4
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(1000f + 1250f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06005E70 RID: 24176 RVA: 0x001B6AB9 File Offset: 0x001B4CB9
			public override bool CanBeCompletedByAI()
			{
				return Hero.MainHero.PartyBelongedToAsPrisoner != this._targetHideout.Party;
			}

			// Token: 0x170012EE RID: 4846
			// (get) Token: 0x06005E71 RID: 24177 RVA: 0x001B6AD5 File Offset: 0x001B4CD5
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=IFasMslv}I will assign a companion with {TROOP_COUNT} good men for {RETURN_DAYS} days.", null);
					textObject.SetTextVariable("TROOP_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x170012EF RID: 4847
			// (get) Token: 0x06005E72 RID: 24178 RVA: 0x001B6B06 File Offset: 0x001B4D06
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=DgVU7owN}I pray for your warriors. The people here will be very glad to hear of their success.[ib:hip][if:convo_excited]", null);
				}
			}

			// Token: 0x170012F0 RID: 4848
			// (get) Token: 0x06005E73 RID: 24179 RVA: 0x001B6B14 File Offset: 0x001B4D14
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=aXOgAKfj}Thank you, {?PLAYER.GENDER}madam{?}sir{\\?}. I hope your people will be successful.[ib:hip][if:convo_excited]", null);
					StringHelpers.SetCharacterProperties("PLAYER", Hero.MainHero.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170012F1 RID: 4849
			// (get) Token: 0x06005E74 RID: 24180 RVA: 0x001B6B45 File Offset: 0x001B4D45
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=VNXgZ8mt}Alternatively, if you can assign a companion with {TROOP_COUNT} or so men to this task, they can do the job.[ib:closed][if:convo_undecided_open]", null);
					textObject.SetTextVariable("TROOP_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					return textObject;
				}
			}

			// Token: 0x170012F2 RID: 4850
			// (get) Token: 0x06005E75 RID: 24181 RVA: 0x001B6B64 File Offset: 0x001B4D64
			public override TextObject IssueAsRumorInSettlement
			{
				get
				{
					TextObject textObject = new TextObject("{=ctgihUte}I hope {QUEST_GIVER.NAME} has a plan to get rid of those bandits.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170012F3 RID: 4851
			// (get) Token: 0x06005E76 RID: 24182 RVA: 0x001B6B96 File Offset: 0x001B4D96
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x170012F4 RID: 4852
			// (get) Token: 0x06005E77 RID: 24183 RVA: 0x001B6B9C File Offset: 0x001B4D9C
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=G4kpabSf}{ISSUE_GIVER.LINK}, a headman from {ISSUE_SETTLEMENT}, has told you about recent bandit attacks on local villagers and asked you to clear out the outlaws' hideout. You asked {COMPANION.LINK} to take {TROOP_COUNT} of your best men to go and take care of it. They should report back to you in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("PLAYER", Hero.MainHero.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("ISSUE_SETTLEMENT", this._issueSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("TROOP_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x170012F5 RID: 4853
			// (get) Token: 0x06005E78 RID: 24184 RVA: 0x001B6C3F File Offset: 0x001B4E3F
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170012F6 RID: 4854
			// (get) Token: 0x06005E79 RID: 24185 RVA: 0x001B6C42 File Offset: 0x001B4E42
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=ENYbLO8r}Bandit Base Near {SETTLEMENT}", null);
					textObject.SetTextVariable("SETTLEMENT", this._issueSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x170012F7 RID: 4855
			// (get) Token: 0x06005E7A RID: 24186 RVA: 0x001B6C68 File Offset: 0x001B4E68
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=vZ01a4cG}{QUEST_GIVER.LINK} wants you to clear the hideout that attracts more bandits to {?QUEST_GIVER.GENDER}her{?}his{\\?} region.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170012F8 RID: 4856
			// (get) Token: 0x06005E7B RID: 24187 RVA: 0x001B6C9C File Offset: 0x001B4E9C
			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=SN3pjZiK}You received a message from {QUEST_GIVER.LINK}.{newline}\"Thank you for clearing out that bandits' nest. Please accept these {REWARD}{GOLD_ICON} denars with our gratitude.\"", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170012F9 RID: 4857
			// (get) Token: 0x06005E7C RID: 24188 RVA: 0x001B6CF4 File Offset: 0x001B4EF4
			public override TextObject IssueAlternativeSolutionFailLog
			{
				get
				{
					TextObject textObject = new TextObject("{=qsMnnfQ3}You failed to clear the hideout in time to prevent further attacks. {QUEST_GIVER.LINK} is disappointed.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x170012FA RID: 4858
			// (get) Token: 0x06005E7D RID: 24189 RVA: 0x001B6D26 File Offset: 0x001B4F26
			protected override bool IssueQuestCanBeDuplicated
			{
				get
				{
					return false;
				}
			}

			// Token: 0x06005E7E RID: 24190 RVA: 0x001B6D29 File Offset: 0x001B4F29
			public NearbyBanditBaseIssue(Hero issueOwner, Settlement targetHideout)
				: base(issueOwner, CampaignTime.DaysFromNow(15f))
			{
				this._targetHideout = targetHideout;
			}

			// Token: 0x06005E7F RID: 24191 RVA: 0x001B6D43 File Offset: 0x001B4F43
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementProsperity)
				{
					return -0.2f;
				}
				if (issueEffect == DefaultIssueEffects.SettlementSecurity)
				{
					return -1f;
				}
				return 0f;
			}

			// Token: 0x06005E80 RID: 24192 RVA: 0x001B6D68 File Offset: 0x001B4F68
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				int skillValue = hero.GetSkillValue(DefaultSkills.OneHanded);
				int skillValue2 = hero.GetSkillValue(DefaultSkills.TwoHanded);
				int skillValue3 = hero.GetSkillValue(DefaultSkills.Polearm);
				if (skillValue >= skillValue2 && skillValue >= skillValue3)
				{
					return new ValueTuple<SkillObject, int>(DefaultSkills.OneHanded, 120);
				}
				return new ValueTuple<SkillObject, int>((skillValue2 >= skillValue3) ? DefaultSkills.TwoHanded : DefaultSkills.Polearm, 120);
			}

			// Token: 0x06005E81 RID: 24193 RVA: 0x001B6DC5 File Offset: 0x001B4FC5
			protected override void AfterIssueCreation()
			{
				this._issueSettlement = base.IssueOwner.CurrentSettlement;
			}

			// Token: 0x06005E82 RID: 24194 RVA: 0x001B6DD8 File Offset: 0x001B4FD8
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005E83 RID: 24195 RVA: 0x001B6DE9 File Offset: 0x001B4FE9
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x06005E84 RID: 24196 RVA: 0x001B6DF7 File Offset: 0x001B4FF7
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005E85 RID: 24197 RVA: 0x001B6E14 File Offset: 0x001B5014
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.RelationshipChangeWithIssueOwner = 5;
				base.IssueOwner.AddPower(5f);
				this._issueSettlement.Village.Bound.Town.Prosperity += 10f;
				TraitLevelingHelper.OnIssueSolvedThroughAlternativeSolution(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 50)
				});
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
			}

			// Token: 0x06005E86 RID: 24198 RVA: 0x001B6E8E File Offset: 0x001B508E
			protected override void AlternativeSolutionEndWithFailureConsequence()
			{
				this.RelationshipChangeWithIssueOwner = -5;
				base.IssueOwner.AddPower(-5f);
				this._issueSettlement.Village.Bound.Town.Prosperity += -10f;
			}

			// Token: 0x06005E87 RID: 24199 RVA: 0x001B6ECE File Offset: 0x001B50CE
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005E88 RID: 24200 RVA: 0x001B6ED0 File Offset: 0x001B50D0
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005E89 RID: 24201 RVA: 0x001B6ED2 File Offset: 0x001B50D2
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssueQuest(questId, base.IssueOwner, this._targetHideout, this._issueSettlement, this.RewardGold, CampaignTime.DaysFromNow(30f));
			}

			// Token: 0x06005E8A RID: 24202 RVA: 0x001B6EFC File Offset: 0x001B50FC
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005E8B RID: 24203 RVA: 0x001B6F00 File Offset: 0x001B5100
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				if (MobileParty.MainParty.MemberRoster.TotalHealthyCount - 1 < 25)
				{
					flags |= IssueBase.PreconditionFlags.NotEnoughTroops;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005E8C RID: 24204 RVA: 0x001B6F74 File Offset: 0x001B5174
			public override bool IssueStayAliveConditions()
			{
				return this._targetHideout.Hideout.IsInfested && base.IssueOwner.CurrentSettlement.IsVillage && !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid && base.IssueOwner.CurrentSettlement.Village.Bound.Town.Security <= 80f;
			}

			// Token: 0x06005E8D RID: 24205 RVA: 0x001B6FF4 File Offset: 0x001B51F4
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001DDE RID: 7646
			private const int QuestSolutionNeededMinimumHealthyMenCount = 25;

			// Token: 0x04001DDF RID: 7647
			private const int AlternativeSolutionFinalMenCount = 10;

			// Token: 0x04001DE0 RID: 7648
			private const int AlternativeSolutionMinimumTroopTier = 2;

			// Token: 0x04001DE1 RID: 7649
			private const int AlternativeSolutionCompanionSkillThreshold = 120;

			// Token: 0x04001DE2 RID: 7650
			private const int AlternativeSolutionRelationRewardOnSuccess = 5;

			// Token: 0x04001DE3 RID: 7651
			private const int AlternativeSolutionRelationPenaltyOnFail = -5;

			// Token: 0x04001DE4 RID: 7652
			private const int IssueOwnerPowerBonusOnSuccess = 5;

			// Token: 0x04001DE5 RID: 7653
			private const int IssueOwnerPowerPenaltyOnFail = -5;

			// Token: 0x04001DE6 RID: 7654
			private const int SettlementProsperityBonusOnSuccess = 10;

			// Token: 0x04001DE7 RID: 7655
			private const int SettlementProsperityPenaltyOnFail = -10;

			// Token: 0x04001DE8 RID: 7656
			private const int IssueDuration = 15;

			// Token: 0x04001DE9 RID: 7657
			private const int QuestTimeLimit = 30;

			// Token: 0x04001DEA RID: 7658
			[SaveableField(100)]
			private readonly Settlement _targetHideout;

			// Token: 0x04001DEB RID: 7659
			[SaveableField(101)]
			private Settlement _issueSettlement;
		}

		// Token: 0x02000748 RID: 1864
		public class NearbyBanditBaseIssueQuest : QuestBase
		{
			// Token: 0x06005E8E RID: 24206 RVA: 0x001B6FF6 File Offset: 0x001B51F6
			internal static void AutoGeneratedStaticCollectObjectsNearbyBanditBaseIssueQuest(object o, List<object> collectedObjects)
			{
				((NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005E8F RID: 24207 RVA: 0x001B7004 File Offset: 0x001B5204
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetHideout);
				collectedObjects.Add(this._questSettlement);
			}

			// Token: 0x06005E90 RID: 24208 RVA: 0x001B7025 File Offset: 0x001B5225
			internal static object AutoGeneratedGetMemberValue_targetHideout(object o)
			{
				return ((NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssueQuest)o)._targetHideout;
			}

			// Token: 0x06005E91 RID: 24209 RVA: 0x001B7032 File Offset: 0x001B5232
			internal static object AutoGeneratedGetMemberValue_questSettlement(object o)
			{
				return ((NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssueQuest)o)._questSettlement;
			}

			// Token: 0x170012FB RID: 4859
			// (get) Token: 0x06005E92 RID: 24210 RVA: 0x001B703F File Offset: 0x001B523F
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=ENYbLO8r}Bandit Base Near {SETTLEMENT}", null);
					textObject.SetTextVariable("SETTLEMENT", this._questSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x170012FC RID: 4860
			// (get) Token: 0x06005E93 RID: 24211 RVA: 0x001B7063 File Offset: 0x001B5263
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170012FD RID: 4861
			// (get) Token: 0x06005E94 RID: 24212 RVA: 0x001B7068 File Offset: 0x001B5268
			private TextObject OnQuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=ogsh3V6G}{QUEST_GIVER.LINK}, a headman from {QUEST_SETTLEMENT}, has told you about the hideout of some bandits who have recently been attacking local villagers. You told {?QUEST_GIVER.GENDER}her{?}him{\\?} that you will take care of the situation yourself. {QUEST_GIVER.LINK} also marked the location of the hideout on your map.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", this._questSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x170012FE RID: 4862
			// (get) Token: 0x06005E95 RID: 24213 RVA: 0x001B70B4 File Offset: 0x001B52B4
			private TextObject OnQuestSucceededLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=SN3pjZiK}You received a message from {QUEST_GIVER.LINK}.{newline}\"Thank you for clearing out that bandits' nest. Please accept these {REWARD}{GOLD_ICON} denars with our gratitude.\"", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x170012FF RID: 4863
			// (get) Token: 0x06005E96 RID: 24214 RVA: 0x001B710C File Offset: 0x001B530C
			private TextObject OnQuestFailedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=qsMnnfQ3}You failed to clear the hideout in time to prevent further attacks. {QUEST_GIVER.LINK} is disappointed.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001300 RID: 4864
			// (get) Token: 0x06005E97 RID: 24215 RVA: 0x001B7140 File Offset: 0x001B5340
			private TextObject OnQuestFailedFromWarCausedByPlayerLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=B8KZ6tx2}You are accused in {SETTLEMENT} of a crime. This has angered {QUEST_GIVER.LINK} and {?QUEST_GIVER.GENDER}she{?}he{\\?} broke off your agreement.", null);
					textObject.SetTextVariable("SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001301 RID: 4865
			// (get) Token: 0x06005E98 RID: 24216 RVA: 0x001B7190 File Offset: 0x001B5390
			private TextObject OnQuestCanceledLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=4Bub0GY6}Hideout was cleared by someone else. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x06005E99 RID: 24217 RVA: 0x001B71C2 File Offset: 0x001B53C2
			public NearbyBanditBaseIssueQuest(string questId, Hero questGiver, Settlement targetHideout, Settlement questSettlement, int rewardGold, CampaignTime duration)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._targetHideout = targetHideout;
				this._questSettlement = questSettlement;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005E9A RID: 24218 RVA: 0x001B71EB File Offset: 0x001B53EB
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06005E9B RID: 24219 RVA: 0x001B71F3 File Offset: 0x001B53F3
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005E9C RID: 24220 RVA: 0x001B71F8 File Offset: 0x001B53F8
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine("{=spj8bYVo}Good! I'll mark the hideout for you on a map.[if:convo_excited]", null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.OnQuestAccepted))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine("{=l9wYpIuV}Any news? Have you managed to clear out the hideout yet?[if:convo_astonished]", null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption("{=wErSpkjy}I'm still working on it.", null, null, null)
					.NpcLine("{=XTt6gZ7h}Do make haste, if you can. As long as those bandits are up there, no traveller is safe![if:convo_grave]", null, null, null, null)
					.CloseDialog()
					.PlayerOption("{=I8raOMRH}Sorry. No progress yet.", null, null, null)
					.NpcLine("{=kWruAXaF}Well... You know as long as those bandits remain there, no traveller is safe.[if:convo_grave]", null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005E9D RID: 24221 RVA: 0x001B72D0 File Offset: 0x001B54D0
			private void OnQuestAccepted()
			{
				base.StartQuest();
				this._targetHideout.Hideout.IsSpotted = true;
				this._targetHideout.IsVisible = true;
				base.AddTrackedObject(this._targetHideout);
				QuestHelper.AddMapArrowFromPointToTarget(new TextObject("{=xpsQyPaV}Direction to Bandits", null), this._questSettlement.Position, this._targetHideout.Position, 5f, 0.1f);
				TextObject textObject = new TextObject("{=XGa8MkbJ}{QUEST_GIVER.NAME} has marked the hideout on your map", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				base.AddLog(this.OnQuestStartedLogText, false);
			}

			// Token: 0x06005E9E RID: 24222 RVA: 0x001B737C File Offset: 0x001B557C
			private void OnQuestSucceeded()
			{
				base.AddLog(this.OnQuestSucceededLogText, false);
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 50)
				});
				base.QuestGiver.AddPower(5f);
				this.RelationshipChangeWithQuestGiver = 5;
				this._questSettlement.Village.Bound.Town.Prosperity += 10f;
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005E9F RID: 24223 RVA: 0x001B741C File Offset: 0x001B561C
			private void OnQuestFailed(bool isTimedOut)
			{
				base.AddLog(this.OnQuestFailedLogText, false);
				this.RelationshipChangeWithQuestGiver = -5;
				base.QuestGiver.AddPower(-5f);
				this._questSettlement.Village.Bound.Town.Prosperity += -10f;
				this._questSettlement.Village.Bound.Town.Security += -5f;
				if (!isTimedOut)
				{
					base.CompleteQuestWithFail(null);
				}
			}

			// Token: 0x06005EA0 RID: 24224 RVA: 0x001B74A5 File Offset: 0x001B56A5
			private void OnQuestCanceled()
			{
				base.AddLog(this.OnQuestCanceledLogText, false);
				base.CompleteQuestWithFail(null);
			}

			// Token: 0x06005EA1 RID: 24225 RVA: 0x001B74BC File Offset: 0x001B56BC
			protected override void OnTimedOut()
			{
				this.OnQuestFailed(true);
			}

			// Token: 0x06005EA2 RID: 24226 RVA: 0x001B74C8 File Offset: 0x001B56C8
			protected override void RegisterEvents()
			{
				CampaignEvents.MapEventEnded.AddNonSerializedListener(this, new Action<MapEvent>(this.OnMapEventEnded));
				CampaignEvents.OnHideoutDeactivatedEvent.AddNonSerializedListener(this, new Action<Settlement>(this.OnHideoutCleared));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
			}

			// Token: 0x06005EA3 RID: 24227 RVA: 0x001B7531 File Offset: 0x001B5731
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				if (DiplomacyHelper.IsWarCausedByPlayer(faction1, faction2, detail))
				{
					this.WarCausedByPlayerFail();
				}
			}

			// Token: 0x06005EA4 RID: 24228 RVA: 0x001B7544 File Offset: 0x001B5744
			private void WarCausedByPlayerFail()
			{
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
				TraitLevelingHelper.OnIssueFailed(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -50)
				});
				this._questSettlement.Village.Bound.Town.Prosperity += -10f;
				this._questSettlement.Village.Bound.Town.Security += -10f;
				base.CompleteQuestWithFail(this.OnQuestFailedFromWarCausedByPlayerLogText);
			}

			// Token: 0x06005EA5 RID: 24229 RVA: 0x001B75E0 File Offset: 0x001B57E0
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06005EA6 RID: 24230 RVA: 0x001B75F3 File Offset: 0x001B57F3
			private void OnHideoutCleared(Settlement hideout)
			{
				if (this._targetHideout == hideout)
				{
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06005EA7 RID: 24231 RVA: 0x001B7608 File Offset: 0x001B5808
			private void OnMapEventEnded(MapEvent mapEvent)
			{
				if (mapEvent.IsHideoutBattle && mapEvent.MapEventSettlement == this._targetHideout)
				{
					if (mapEvent.InvolvedParties.Contains(PartyBase.MainParty))
					{
						if (mapEvent.BattleState == BattleState.DefenderVictory)
						{
							this.OnQuestFailed(false);
							return;
						}
						if (mapEvent.BattleState == BattleState.AttackerVictory)
						{
							this.OnQuestSucceeded();
							return;
						}
					}
					else if (mapEvent.BattleState == BattleState.AttackerVictory)
					{
						this.OnQuestCanceled();
					}
				}
			}

			// Token: 0x04001DEC RID: 7660
			private const int QuestGiverRelationBonus = 5;

			// Token: 0x04001DED RID: 7661
			private const int QuestGiverRelationPenalty = -5;

			// Token: 0x04001DEE RID: 7662
			private const int WarCausedByPlayerQuestGiverRelationPenalty = -5;

			// Token: 0x04001DEF RID: 7663
			private const int QuestGiverPowerBonus = 5;

			// Token: 0x04001DF0 RID: 7664
			private const int QuestGiverPowerPenalty = -5;

			// Token: 0x04001DF1 RID: 7665
			private const int WarCausedByPlayerQuestGiverPowerPenalty = -10;

			// Token: 0x04001DF2 RID: 7666
			private const int TownProsperityBonus = 10;

			// Token: 0x04001DF3 RID: 7667
			private const int TownProsperityPenalty = -10;

			// Token: 0x04001DF4 RID: 7668
			private const int WarCausedByPlayerTownProsperityPenalty = -10;

			// Token: 0x04001DF5 RID: 7669
			private const int TownSecurityPenalty = -5;

			// Token: 0x04001DF6 RID: 7670
			private const int WarCausedByPlayerTownSecurityPenalty = -10;

			// Token: 0x04001DF7 RID: 7671
			private const int WarCausedByPlayerFailHonorPenalty = -50;

			// Token: 0x04001DF8 RID: 7672
			private const int QuestGuid = 1056731;

			// Token: 0x04001DF9 RID: 7673
			[SaveableField(100)]
			private readonly Settlement _targetHideout;

			// Token: 0x04001DFA RID: 7674
			[SaveableField(101)]
			private readonly Settlement _questSettlement;
		}

		// Token: 0x02000749 RID: 1865
		public class NearbyBanditBaseIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005EAA RID: 24234 RVA: 0x001B768B File Offset: 0x001B588B
			public NearbyBanditBaseIssueTypeDefiner()
				: base(400000)
			{
			}

			// Token: 0x06005EAB RID: 24235 RVA: 0x001B7698 File Offset: 0x001B5898
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssue), 1, null);
				base.AddClassDefinition(typeof(NearbyBanditBaseIssueBehavior.NearbyBanditBaseIssueQuest), 2, null);
			}
		}
	}
}
