using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000376 RID: 886
	public class RaidAnEnemyTerritoryIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x06003407 RID: 13319 RVA: 0x000D6686 File Offset: 0x000D4886
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003408 RID: 13320 RVA: 0x000D66A0 File Offset: 0x000D48A0
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x06003409 RID: 13321 RVA: 0x000D6704 File Offset: 0x000D4904
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.IsLord && issueGiver.MapFaction.IsKingdomFaction && issueGiver == ((Kingdom)issueGiver.MapFaction).Leader && issueGiver.GetTraitLevel(DefaultTraits.Mercy) <= 0 && issueGiver.GetTraitLevel(DefaultTraits.Calculating) >= 0 && this.GetAtWarWithFactionCount(issueGiver) >= 1;
		}

		// Token: 0x0600340A RID: 13322 RVA: 0x000D6764 File Offset: 0x000D4964
		private int GetAtWarWithFactionCount(Hero issueGiver)
		{
			int num = 0;
			foreach (Kingdom kingdom in Kingdom.All)
			{
				if (issueGiver.MapFaction != kingdom && issueGiver.MapFaction.IsAtWarWith(kingdom) && kingdom.Settlements.Count > 1)
				{
					num++;
				}
			}
			return num;
		}

		// Token: 0x0600340B RID: 13323 RVA: 0x000D67DC File Offset: 0x000D49DC
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			return new RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryIssue(issueOwner);
		}

		// Token: 0x0600340C RID: 13324 RVA: 0x000D67E4 File Offset: 0x000D49E4
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EE0 RID: 3808
		private const int BaseRewardGold = 15000;

		// Token: 0x04000EE1 RID: 3809
		private const int ExtraRewardMultiplier = 3000;

		// Token: 0x04000EE2 RID: 3810
		private const int TargetRaidVillageCount = 3;

		// Token: 0x04000EE3 RID: 3811
		private const IssueBase.IssueFrequency RaidAnEnemyTerritoryIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x0200074A RID: 1866
		public class RaidAnEnemyTerritoryIssue : IssueBase
		{
			// Token: 0x06005EAC RID: 24236 RVA: 0x001B76BE File Offset: 0x001B58BE
			internal static void AutoGeneratedStaticCollectObjectsRaidAnEnemyTerritoryIssue(object o, List<object> collectedObjects)
			{
				((RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005EAD RID: 24237 RVA: 0x001B76CC File Offset: 0x001B58CC
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._enemyKingdom);
			}

			// Token: 0x06005EAE RID: 24238 RVA: 0x001B76E1 File Offset: 0x001B58E1
			internal static object AutoGeneratedGetMemberValue_enemyKingdom(object o)
			{
				return ((RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryIssue)o)._enemyKingdom;
			}

			// Token: 0x17001302 RID: 4866
			// (get) Token: 0x06005EAF RID: 24239 RVA: 0x001B76F0 File Offset: 0x001B58F0
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=CrzFdo2H}Yes. It's about the war with the {ENEMYFACTION_INFORMALNAME}. [ib:hip][if:convo_excited]We need to tie up some of their forces. A relatively small force moving quickly through their lands and raiding their villages succesfully should be a good distraction. Their lords will need to chase the raiders and won't be able to threaten us elsewhere. You seem to be the right {?PLAYER.GENDER}warrior{?}man{\\?} for the job. What do you say? You'll have my gratitude and you'll be well rewarded if you succeed.", null);
					if (base.IssueOwner.GetTraitLevel(DefaultTraits.Mercy) + base.IssueOwner.GetTraitLevel(DefaultTraits.Honor) >= 0)
					{
						textObject = new TextObject("{=OlIWwLbP}Yes. It's about the war with the {ENEMYFACTION_INFORMALNAME}. [ib:closed][if:convo_pondering]We need to tie up some of their forces, and the easiest way to do that would be to raid their villages. It's a cruel business and will be hard on the common folk, but their lords will need to chase the raiders and it will prevent them from doing the same to us. If you take this on, I shall reward you if you succeed.", null);
					}
					textObject.SetTextVariable("ENEMYFACTION_INFORMALNAME", this._enemyKingdom.InformalName);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001303 RID: 4867
			// (get) Token: 0x06005EB0 RID: 24240 RVA: 0x001B7764 File Offset: 0x001B5964
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=bLfXzCyc}I'm at your service my {?ISSUE_OWNER.GENDER}lady{?}lord{\\?}. Just tell me the details.", null);
					StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001304 RID: 4868
			// (get) Token: 0x06005EB1 RID: 24241 RVA: 0x001B7798 File Offset: 0x001B5998
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=aRfMtTUT}Good. See if you can hit {NUMBER_OF_TARGET_VILLAGE} villages. They won't be able to ignore that kind of damage. I'll give you {BASE_REWARD}{GOLD_ICON} for doing that, and {EXTRA_REWARD}{GOLD_ICON} more for every extra one that you raid. Agreed?[if:convo_mocking_revenge]", null);
					if (base.IssueOwner.GetTraitLevel(DefaultTraits.Mercy) + base.IssueOwner.GetTraitLevel(DefaultTraits.Honor) > 0)
					{
						textObject = new TextObject("{=AEVIa5sQ}So be it. See if you can hit {NUMBER_OF_TARGET_VILLAGE} villages. [if:convo_stern]They won't be able to ignore that, and it will put a dent in their revenues. I'll give you {BASE_REWARD}{GOLD_ICON} for doing that, and {EXTRA_REWARD}{GOLD_ICON} more for every extra one that you raid. Do you agree?", null);
					}
					textObject.SetTextVariable("NUMBER_OF_TARGET_VILLAGE", 3);
					textObject.SetTextVariable("BASE_REWARD", 15000);
					textObject.SetTextVariable("EXTRA_REWARD", 3000);
					return textObject;
				}
			}

			// Token: 0x17001305 RID: 4869
			// (get) Token: 0x06005EB2 RID: 24242 RVA: 0x001B7814 File Offset: 0x001B5A14
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=nrRvyKgL}I'll strike into their territory as you command, my {?ISSUE_OWNER.GENDER}lady{?}lord{\\?}.", null);
					StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001306 RID: 4870
			// (get) Token: 0x06005EB3 RID: 24243 RVA: 0x001B7846 File Offset: 0x001B5A46
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001307 RID: 4871
			// (get) Token: 0x06005EB4 RID: 24244 RVA: 0x001B7849 File Offset: 0x001B5A49
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001308 RID: 4872
			// (get) Token: 0x06005EB5 RID: 24245 RVA: 0x001B784C File Offset: 0x001B5A4C
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=DSlhMswt}Raid an Enemy Territory", null);
				}
			}

			// Token: 0x17001309 RID: 4873
			// (get) Token: 0x06005EB6 RID: 24246 RVA: 0x001B785C File Offset: 0x001B5A5C
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=JEuZoV1E}{ISSUE_OWNER.LINK} asks you to raid enemy villages to distract enemy war parties.", null);
					StringHelpers.SetCharacterProperties("ISSUE_OWNER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x06005EB7 RID: 24247 RVA: 0x001B788E File Offset: 0x001B5A8E
			public RaidAnEnemyTerritoryIssue(Hero issueGiver)
				: base(issueGiver, CampaignTime.DaysFromNow(60f))
			{
				this._enemyKingdom = Kingdom.All.Where<Kingdom>((Kingdom k) => k.IsAtWarWith(base.IssueOwner.MapFaction)).GetRandomElementInefficiently<Kingdom>();
			}

			// Token: 0x06005EB8 RID: 24248 RVA: 0x001B78C2 File Offset: 0x001B5AC2
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.ClanInfluence)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005EB9 RID: 24249 RVA: 0x001B78D7 File Offset: 0x001B5AD7
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005EBA RID: 24250 RVA: 0x001B78D9 File Offset: 0x001B5AD9
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005EBB RID: 24251 RVA: 0x001B78DB File Offset: 0x001B5ADB
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(60f), this._enemyKingdom);
			}

			// Token: 0x06005EBC RID: 24252 RVA: 0x001B78F9 File Offset: 0x001B5AF9
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005EBD RID: 24253 RVA: 0x001B78FC File Offset: 0x001B5AFC
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flag = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					relationHero = issueGiver;
					flag |= IssueBase.PreconditionFlags.Relation;
				}
				if (Clan.PlayerClan.Kingdom != issueGiver.MapFaction)
				{
					flag |= IssueBase.PreconditionFlags.NotInSameFaction;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005EBE RID: 24254 RVA: 0x001B794E File Offset: 0x001B5B4E
			public override bool IssueStayAliveConditions()
			{
				return this._enemyKingdom.IsAtWarWith(base.IssueOwner.MapFaction) && !this._enemyKingdom.IsEliminated && base.IssueOwner.MapFaction.IsKingdomFaction;
			}

			// Token: 0x06005EBF RID: 24255 RVA: 0x001B7987 File Offset: 0x001B5B87
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001DFB RID: 7675
			private const int IssueDurationInDays = 60;

			// Token: 0x04001DFC RID: 7676
			private const int RelationLimitWithPlayer = -10;

			// Token: 0x04001DFD RID: 7677
			[SaveableField(10)]
			private readonly Kingdom _enemyKingdom;
		}

		// Token: 0x0200074B RID: 1867
		public class RaidAnEnemyTerritoryQuest : QuestBase
		{
			// Token: 0x06005EC1 RID: 24257 RVA: 0x001B799C File Offset: 0x001B5B9C
			internal static void AutoGeneratedStaticCollectObjectsRaidAnEnemyTerritoryQuest(object o, List<object> collectedObjects)
			{
				((RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005EC2 RID: 24258 RVA: 0x001B79AA File Offset: 0x001B5BAA
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._raidedVillagesTrackLog);
				collectedObjects.Add(this._enemyKingdom);
				collectedObjects.Add(this._raidedVillages);
			}

			// Token: 0x06005EC3 RID: 24259 RVA: 0x001B79D7 File Offset: 0x001B5BD7
			internal static object AutoGeneratedGetMemberValue_raidedVillagesTrackLog(object o)
			{
				return ((RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryQuest)o)._raidedVillagesTrackLog;
			}

			// Token: 0x06005EC4 RID: 24260 RVA: 0x001B79E4 File Offset: 0x001B5BE4
			internal static object AutoGeneratedGetMemberValue_enemyKingdom(object o)
			{
				return ((RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryQuest)o)._enemyKingdom;
			}

			// Token: 0x06005EC5 RID: 24261 RVA: 0x001B79F1 File Offset: 0x001B5BF1
			internal static object AutoGeneratedGetMemberValue_raidedVillages(object o)
			{
				return ((RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryQuest)o)._raidedVillages;
			}

			// Token: 0x1700130A RID: 4874
			// (get) Token: 0x06005EC6 RID: 24262 RVA: 0x001B79FE File Offset: 0x001B5BFE
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=DSlhMswt}Raid an Enemy Territory", null);
				}
			}

			// Token: 0x1700130B RID: 4875
			// (get) Token: 0x06005EC7 RID: 24263 RVA: 0x001B7A0B File Offset: 0x001B5C0B
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700130C RID: 4876
			// (get) Token: 0x06005EC8 RID: 24264 RVA: 0x001B7A10 File Offset: 0x001B5C10
			private TextObject QuestAcceptedByPlayerLog
			{
				get
				{
					TextObject textObject = new TextObject("{=sYfvsMwN}{QUEST_GIVER.LINK} asked you to successfully raid {NUMBER_OF_TARGET_VILLAGE} {ENEMYFACTION_INFORMALNAME} villages to distract their lords and weaken their armies. {?QUEST_GIVER.GENDER}She{?}He{\\?} offers {REWARD_GOLD}{GOLD_ICON} to thank you for your deeds.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("NUMBER_OF_TARGET_VILLAGE", 3);
					textObject.SetTextVariable("ENEMYFACTION_INFORMALNAME", this._enemyKingdom.InformalName);
					textObject.SetTextVariable("EXTRA_REWARD", 3000);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("REWARD_GOLD", 15000);
					return textObject;
				}
			}

			// Token: 0x1700130D RID: 4877
			// (get) Token: 0x06005EC9 RID: 24265 RVA: 0x001B7A99 File Offset: 0x001B5C99
			private TextObject MainHeroRaidedAllVillagesLog
			{
				get
				{
					return new TextObject("{=gMvDCnlx}You have successfully raided enemy villages and distracted enemy forces as promised.", null);
				}
			}

			// Token: 0x1700130E RID: 4878
			// (get) Token: 0x06005ECA RID: 24266 RVA: 0x001B7AA8 File Offset: 0x001B5CA8
			private TextObject MainHeroCouldNotRaidedAllVillagesLog
			{
				get
				{
					TextObject textObject = new TextObject("{=nRkLFBMl}You failed to raid at least {NUMBER_OF_TARGET_VILLAGE} villages and then report back. {QUEST_GIVER.LINK} is disappointed.", null);
					textObject.SetTextVariable("NUMBER_OF_TARGET_VILLAGE", 3);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700130F RID: 4879
			// (get) Token: 0x06005ECB RID: 24267 RVA: 0x001B7AE8 File Offset: 0x001B5CE8
			private TextObject QuestGiverDiedLog
			{
				get
				{
					TextObject textObject = new TextObject("{=65BTaOl8}{QUEST_GIVER.LINK} died and your mission is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001310 RID: 4880
			// (get) Token: 0x06005ECC RID: 24268 RVA: 0x001B7B1C File Offset: 0x001B5D1C
			private TextObject EnemyIsOutOfVillagesLog
			{
				get
				{
					TextObject textObject = new TextObject("{=bIDvq6wA}The enemy no longer holds any villages. {QUEST_GIVER.LINK} has canceled your mission.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001311 RID: 4881
			// (get) Token: 0x06005ECD RID: 24269 RVA: 0x001B7B50 File Offset: 0x001B5D50
			private TextObject DeclaredWarOnQuestGiverFactionLog
			{
				get
				{
					TextObject textObject = new TextObject("{=2diuD0rT}Your clan/faction is now at war with {QUEST_GIVER.LINK}'s faction. Your agreement with {QUEST_GIVER.LINK} has been canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001312 RID: 4882
			// (get) Token: 0x06005ECE RID: 24270 RVA: 0x001B7B84 File Offset: 0x001B5D84
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001313 RID: 4883
			// (get) Token: 0x06005ECF RID: 24271 RVA: 0x001B7BB8 File Offset: 0x001B5DB8
			private TextObject DeclaredPeaceBetweenQuestGiverAndEnemyFactionsLog
			{
				get
				{
					TextObject textObject = new TextObject("{=AXsbnTBb}{QUEST_GIVER.LINK} has made peace with the {ENEMYFACTION_INFORMALNAME}. Your agreement with {QUEST_GIVER.LINK} has been canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("ENEMYFACTION_INFORMALNAME", this._enemyKingdom.InformalName);
					return textObject;
				}
			}

			// Token: 0x17001314 RID: 4884
			// (get) Token: 0x06005ED0 RID: 24272 RVA: 0x001B7C01 File Offset: 0x001B5E01
			private TextObject FactionLeftLog
			{
				get
				{
					TextObject textObject = new TextObject("{=c63DWZhr}You left {FACTION}. Your agreement with {QUEST_GIVER.LINK} is terminated.", null);
					textObject.SetTextVariable("FACTION", base.QuestGiver.MapFaction.EncyclopediaLinkWithName);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x06005ED1 RID: 24273 RVA: 0x001B7C41 File Offset: 0x001B5E41
			public RaidAnEnemyTerritoryQuest(string questId, Hero questGiver, CampaignTime duration, Kingdom enemyKingdom)
				: base(questId, questGiver, duration, 15000)
			{
				this._enemyKingdom = enemyKingdom;
				this._raidedVillages = new List<Settlement>();
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005ED2 RID: 24274 RVA: 0x001B7C70 File Offset: 0x001B5E70
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06005ED3 RID: 24275 RVA: 0x001B7C78 File Offset: 0x001B5E78
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005ED4 RID: 24276 RVA: 0x001B7C7A File Offset: 0x001B5E7A
			protected override void OnTimedOut()
			{
				if (this._raidedVillages.Count >= 3)
				{
					this.MainHeroRaidedAllVillages();
					return;
				}
				this.MainHeroCouldNotRaidedAllVillages();
			}

			// Token: 0x06005ED5 RID: 24277 RVA: 0x001B7C97 File Offset: 0x001B5E97
			protected override void OnBeforeTimedOut(ref bool completeWithSuccess, ref bool doNotResolveTheQuest)
			{
				if (this._raidedVillages.Count >= 3)
				{
					this.ApplyQuestSuccessConsequences();
					completeWithSuccess = true;
				}
			}

			// Token: 0x06005ED6 RID: 24278 RVA: 0x001B7CB0 File Offset: 0x001B5EB0
			protected override void RegisterEvents()
			{
				base.RegisterEvents();
				CampaignEvents.RaidCompletedEvent.AddNonSerializedListener(this, new Action<BattleSideEnum, RaidEventComponent>(this.OnRaidCompleted));
				CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, new Action<Hero, Hero, KillCharacterAction.KillCharacterActionDetail, bool>(this.OnHeroKilled));
				CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener(this, new Action<Settlement, bool, Hero, Hero, Hero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail>(this.OnSettlementOwnerChanged));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.MakePeace.AddNonSerializedListener(this, new Action<IFaction, IFaction, MakePeaceAction.MakePeaceDetail>(this.OnMakePeace));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
			}

			// Token: 0x06005ED7 RID: 24279 RVA: 0x001B7D4D File Offset: 0x001B5F4D
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (clan == Clan.PlayerClan && oldKingdom == base.QuestGiver.MapFaction)
				{
					this.FactionLeft();
				}
			}

			// Token: 0x06005ED8 RID: 24280 RVA: 0x001B7D6C File Offset: 0x001B5F6C
			protected override void DailyTick()
			{
				if (base.QuestDueTime.IsPast && this._raidedVillages.Count >= 3)
				{
					this.MainHeroRaidedAllVillages();
				}
			}

			// Token: 0x06005ED9 RID: 24281 RVA: 0x001B7DA0 File Offset: 0x001B5FA0
			private void OnRaidCompleted(BattleSideEnum winnerSide, RaidEventComponent raidEvent)
			{
				MapEvent mapEvent = raidEvent.MapEvent;
				if (mapEvent.IsRaid && mapEvent.IsPlayerMapEvent && mapEvent.MapEventSettlement.IsVillage && mapEvent.PlayerSide == winnerSide && raidEvent.MapEventSettlement.SettlementHitPoints == 0f && !this._raidedVillages.Contains(mapEvent.MapEventSettlement))
				{
					this._raidedVillages.Add(mapEvent.MapEventSettlement);
					this._raidedVillagesTrackLog.UpdateCurrentProgress(this._raidedVillages.Count);
					if (this._raidedVillages.Count >= 3)
					{
						TextObject textObject = new TextObject("{=VM9xDun7}You have successfully raided target villages. Go back to {QUEST_GIVER.LINK} to get your reward.", null);
						textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
						MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
					}
				}
			}

			// Token: 0x06005EDA RID: 24282 RVA: 0x001B7E6F File Offset: 0x001B606F
			private void OnHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification = true)
			{
				if (victim == base.QuestGiver)
				{
					if (this._raidedVillages.Count < 3)
					{
						this.QuestGiverDied();
						return;
					}
					this.MainHeroRaidedAllVillages();
				}
			}

			// Token: 0x06005EDB RID: 24283 RVA: 0x001B7E98 File Offset: 0x001B6098
			private void OnSettlementOwnerChanged(Settlement settlement, bool openToClaim, Hero newOwner, Hero oldOwner, Hero capturerHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail)
			{
				if (oldOwner.MapFaction == this._enemyKingdom && this._enemyKingdom.Settlements.Count < 3 - this._raidedVillages.Count)
				{
					if (this._raidedVillages.Count < 3)
					{
						this.EnemyIsOutOfVillages();
						return;
					}
					this.MainHeroRaidedAllVillages();
				}
			}

			// Token: 0x06005EDC RID: 24284 RVA: 0x001B7EF0 File Offset: 0x001B60F0
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				if ((faction1 == base.QuestGiver.MapFaction && faction2 == Clan.PlayerClan) || (faction1 == Clan.PlayerClan && faction2 == base.QuestGiver.MapFaction))
				{
					if (this._raidedVillages.Count < 3)
					{
						QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.DeclaredWarOnQuestGiverFactionLog, false);
						return;
					}
					this.MainHeroRaidedAllVillages();
				}
			}

			// Token: 0x06005EDD RID: 24285 RVA: 0x001B7F54 File Offset: 0x001B6154
			private void OnMakePeace(IFaction side1Faction, IFaction side2Faction, MakePeaceAction.MakePeaceDetail detail)
			{
				if ((side1Faction == base.QuestGiver.MapFaction && side2Faction == this._enemyKingdom) || (side1Faction == this._enemyKingdom && side2Faction == base.QuestGiver.MapFaction))
				{
					if (this._raidedVillages.Count < 3)
					{
						this.DeclaredPeaceBetweenQuestGiverAndEnemyFactions();
						return;
					}
					this.MainHeroRaidedAllVillages();
				}
			}

			// Token: 0x06005EDE RID: 24286 RVA: 0x001B7FAC File Offset: 0x001B61AC
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=R21SLyGK}Excellent. You are a brave and loyal warrior. You have my thanks.[ib:hip][if:convo_excited]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedByPlayerConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=eMrClHp2}Is there any progress on the task I gave you?[ib:hip][if:convo_astonished]", null), null, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.DiscussCondition))
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=XOv5B84a}Yes, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}. I raided {RAIDED_VILLAGE_COUNT} villages as you commanded.", null), null, null, null)
					.Condition(() => this._raidedVillages.Count >= 3)
					.NpcLine(new TextObject("{=J4yakjtP}Splendid. You have served me well. Take your well-earned reward.[ib:hip][if:convo_grateful]", null), null, null, null, null)
					.Consequence(delegate
					{
						this.MainHeroRaidedAllVillages();
						MapEventHelper.OnConversationEnd();
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=8JvcDnh6}Not yet my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}. I am working on it.", null), null, null, null)
					.NpcLine(new TextObject("{=EuhvSsPZ}Good. Keep them busy.[if:convo_normal]", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(MapEventHelper.OnConversationEnd))
					.CloseDialog()
					.PlayerOption(new TextObject("{=pnQN6LrV}The time is not quite right, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}. I don't want to ride into a trap.", null), null, null, null)
					.NpcLine(new TextObject("{=DXD3ag49}Well... I hope this delay is for a good reason.[ib:closed2][if:convo_thinking]", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(MapEventHelper.OnConversationEnd))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005EDF RID: 24287 RVA: 0x001B8116 File Offset: 0x001B6316
			private void QuestAcceptedByPlayerConsequences()
			{
				base.StartQuest();
				this._raidedVillagesTrackLog = base.AddDiscreteLog(this.QuestAcceptedByPlayerLog, new TextObject("{=RFH1lDMj}Raided Village Count", null), 0, 3, null, false);
			}

			// Token: 0x06005EE0 RID: 24288 RVA: 0x001B813F File Offset: 0x001B633F
			private bool DiscussCondition()
			{
				if (Hero.OneToOneConversationHero == base.QuestGiver)
				{
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, null, false);
					MBTextManager.SetTextVariable("RAIDED_VILLAGE_COUNT", this._raidedVillages.Count);
					return true;
				}
				return false;
			}

			// Token: 0x06005EE1 RID: 24289 RVA: 0x001B817E File Offset: 0x001B637E
			private void MainHeroRaidedAllVillages()
			{
				this.ApplyQuestSuccessConsequences();
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06005EE2 RID: 24290 RVA: 0x001B818C File Offset: 0x001B638C
			private void ApplyQuestSuccessConsequences()
			{
				base.AddLog(this.MainHeroRaidedAllVillagesLog, false);
				Clan.PlayerClan.AddRenown(5f, true);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 10)
				});
				ChangeClanInfluenceAction.Apply(Clan.PlayerClan, 20f);
				this.RelationshipChangeWithQuestGiver = 10;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				if (this._raidedVillages.Count > 3)
				{
					int num = (this._raidedVillages.Count - 3) * 3000;
					GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				}
			}

			// Token: 0x06005EE3 RID: 24291 RVA: 0x001B822E File Offset: 0x001B642E
			private void MainHeroCouldNotRaidedAllVillages()
			{
				base.AddLog(this.MainHeroCouldNotRaidedAllVillagesLog, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -10)
				});
				this.RelationshipChangeWithQuestGiver = -5;
			}

			// Token: 0x06005EE4 RID: 24292 RVA: 0x001B8265 File Offset: 0x001B6465
			private void QuestGiverDied()
			{
				base.AddLog(this.QuestGiverDiedLog, false);
				base.CompleteQuestWithCancel(null);
			}

			// Token: 0x06005EE5 RID: 24293 RVA: 0x001B827C File Offset: 0x001B647C
			private void EnemyIsOutOfVillages()
			{
				base.AddLog(this.EnemyIsOutOfVillagesLog, false);
				base.CompleteQuestWithCancel(null);
			}

			// Token: 0x06005EE6 RID: 24294 RVA: 0x001B8293 File Offset: 0x001B6493
			private void DeclaredPeaceBetweenQuestGiverAndEnemyFactions()
			{
				base.AddLog(this.DeclaredPeaceBetweenQuestGiverAndEnemyFactionsLog, false);
				base.CompleteQuestWithCancel(null);
			}

			// Token: 0x06005EE7 RID: 24295 RVA: 0x001B82AA File Offset: 0x001B64AA
			private void FactionLeft()
			{
				base.AddLog(this.FactionLeftLog, false);
				base.CompleteQuestWithCancel(null);
			}

			// Token: 0x04001DFE RID: 7678
			private const int RenownBonus = 5;

			// Token: 0x04001DFF RID: 7679
			private const int HonorXpBonus = 10;

			// Token: 0x04001E00 RID: 7680
			private const int InfluenceBonus = 20;

			// Token: 0x04001E01 RID: 7681
			private const int RelationBonusWithQuestGiver = 10;

			// Token: 0x04001E02 RID: 7682
			private const int HonorXpPenalty = -10;

			// Token: 0x04001E03 RID: 7683
			private const int RelationPenaltyWithQuestGiver = -5;

			// Token: 0x04001E04 RID: 7684
			[SaveableField(10)]
			private JournalLog _raidedVillagesTrackLog;

			// Token: 0x04001E05 RID: 7685
			[SaveableField(20)]
			private readonly Kingdom _enemyKingdom;

			// Token: 0x04001E06 RID: 7686
			[SaveableField(30)]
			private readonly List<Settlement> _raidedVillages;
		}

		// Token: 0x0200074C RID: 1868
		public class RaidAnEnemyTerritoryIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005EEB RID: 24299 RVA: 0x001B82F0 File Offset: 0x001B64F0
			public RaidAnEnemyTerritoryIssueTypeDefiner()
				: base(586800)
			{
			}

			// Token: 0x06005EEC RID: 24300 RVA: 0x001B82FD File Offset: 0x001B64FD
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryIssue), 1, null);
				base.AddClassDefinition(typeof(RaidAnEnemyTerritoryIssueBehavior.RaidAnEnemyTerritoryQuest), 2, null);
			}
		}
	}
}
