using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x0200037A RID: 890
	public class TheConquestOfSettlementIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x06003448 RID: 13384 RVA: 0x000D81B4 File Offset: 0x000D63B4
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003449 RID: 13385 RVA: 0x000D81D0 File Offset: 0x000D63D0
		private void OnCheckForIssue(Hero hero)
		{
			Settlement settlement;
			if (this.ConditionsHold(hero, out settlement))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue), IssueBase.IssueFrequency.VeryCommon, settlement));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x0600344A RID: 13386 RVA: 0x000D8238 File Offset: 0x000D6438
		private bool ConditionsHold(Hero issueGiver, out Settlement targetSettlement)
		{
			targetSettlement = null;
			if (issueGiver.IsLord && issueGiver.MapFaction.IsKingdomFaction && issueGiver.IsFactionLeader && !issueGiver.IsPrisoner && issueGiver.GetMapPoint() != null)
			{
				if (issueGiver.Clan.Settlements.Any<Settlement>((Settlement x) => x.IsFortification))
				{
					float num = Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.Default) * 2f;
					MBList<Settlement> mblist = new MBList<Settlement>();
					CampaignVec2 campaignPosition = issueGiver.GetCampaignPosition();
					foreach (Town town in Campaign.Current.AllTowns)
					{
						if (town.MapFaction.IsAtWarWith(issueGiver.MapFaction) && Campaign.Current.Models.MapDistanceModel.GetDistance(town.Settlement, in campaignPosition, false, MobileParty.NavigationType.Default) < num)
						{
							mblist.Add(town.Settlement);
						}
					}
					foreach (Town town2 in Campaign.Current.AllCastles)
					{
						if (town2.MapFaction.IsAtWarWith(issueGiver.MapFaction) && Campaign.Current.Models.MapDistanceModel.GetDistance(town2.Settlement, in campaignPosition, false, MobileParty.NavigationType.Default) < num)
						{
							mblist.Add(town2.Settlement);
						}
					}
					if (mblist.Count > 0)
					{
						targetSettlement = mblist.GetRandomElement<Settlement>();
					}
				}
			}
			return targetSettlement != null;
		}

		// Token: 0x0600344B RID: 13387 RVA: 0x000D83F8 File Offset: 0x000D65F8
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			PotentialIssueData potentialIssueData = pid;
			return new TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue(issueOwner, (Settlement)potentialIssueData.RelatedObject);
		}

		// Token: 0x0600344C RID: 13388 RVA: 0x000D841E File Offset: 0x000D661E
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EEB RID: 3819
		private const IssueBase.IssueFrequency TheConquestOfSettlementIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000760 RID: 1888
		public class TheConquestOfSettlementIssue : IssueBase
		{
			// Token: 0x0600601D RID: 24605 RVA: 0x001BC39F File Offset: 0x001BA59F
			internal static void AutoGeneratedStaticCollectObjectsTheConquestOfSettlementIssue(object o, List<object> collectedObjects)
			{
				((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600601E RID: 24606 RVA: 0x001BC3AD File Offset: 0x001BA5AD
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
			}

			// Token: 0x0600601F RID: 24607 RVA: 0x001BC3C2 File Offset: 0x001BA5C2
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue)o)._targetSettlement;
			}

			// Token: 0x1700135F RID: 4959
			// (get) Token: 0x06006020 RID: 24608 RVA: 0x001BC3CF File Offset: 0x001BA5CF
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=mvzh0HVk}The Conquest of {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001360 RID: 4960
			// (get) Token: 0x06006021 RID: 24609 RVA: 0x001BC3F4 File Offset: 0x001BA5F4
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=xeZR3r5u}{QUEST_GIVER.LINK} wants you siege and take over the {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001361 RID: 4961
			// (get) Token: 0x06006022 RID: 24610 RVA: 0x001BC43D File Offset: 0x001BA63D
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=Oi20UrO2}Our war with the {TARGET_SETTLEMENT_FACTION_INFORMAL_NAME} is going well enough. But there are some who say that we don't have enough to show for all the blood and silver we've spent. A clear victory at this stage would do a lot of good. I think I would like to see our banner flying from the towers of {TARGET_SETTLEMENT}.[ib:normal2][if:convo_thinking]", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT_FACTION_INFORMAL_NAME", this._targetSettlement.MapFaction.InformalName);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001362 RID: 4962
			// (get) Token: 0x06006023 RID: 24611 RVA: 0x001BC480 File Offset: 0x001BA680
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=qKrUyqsD}Of course, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}. But sieges are always costly...", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001363 RID: 4963
			// (get) Token: 0x06006024 RID: 24612 RVA: 0x001BC4B4 File Offset: 0x001BA6B4
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=yf3NVFi0}Yes, they are. That's why I am offering you the sum of {REWARD_GOLD}{GOLD_ICON} if you can take {TARGET_SETTLEMENT} within {TIME_LIMIT} days.[if:convo_thinking] I count you among the most resourceful of my captains. I think you can do this, with courage, Heaven's favor and a bit of luck. Can I tell my other lords that you will do this?", null);
					textObject.SetTextVariable("REWARD_GOLD", this.RewardGold);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("TIME_LIMIT", 60);
					return textObject;
				}
			}

			// Token: 0x17001364 RID: 4964
			// (get) Token: 0x06006025 RID: 24613 RVA: 0x001BC503 File Offset: 0x001BA703
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=scmTEn90}You may tell them. {TARGET_SETTLEMENT} will be ours within 60 days.", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001365 RID: 4965
			// (get) Token: 0x06006026 RID: 24614 RVA: 0x001BC527 File Offset: 0x001BA727
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001366 RID: 4966
			// (get) Token: 0x06006027 RID: 24615 RVA: 0x001BC52A File Offset: 0x001BA72A
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001367 RID: 4967
			// (get) Token: 0x06006028 RID: 24616 RVA: 0x001BC52D File Offset: 0x001BA72D
			protected override int RewardGold
			{
				get
				{
					return 20000;
				}
			}

			// Token: 0x06006029 RID: 24617 RVA: 0x001BC534 File Offset: 0x001BA734
			public TheConquestOfSettlementIssue(Hero issueOwner, Settlement targetSettlement)
				: base(issueOwner, CampaignTime.DaysFromNow(60f))
			{
				this._targetSettlement = targetSettlement;
			}

			// Token: 0x0600602A RID: 24618 RVA: 0x001BC54E File Offset: 0x001BA74E
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementSecurity)
				{
					return -1f;
				}
				if (issueEffect == DefaultIssueEffects.SettlementLoyalty)
				{
					return -1f;
				}
				return 0f;
			}

			// Token: 0x0600602B RID: 24619 RVA: 0x001BC571 File Offset: 0x001BA771
			protected override void OnGameLoad()
			{
			}

			// Token: 0x0600602C RID: 24620 RVA: 0x001BC573 File Offset: 0x001BA773
			protected override void HourlyTick()
			{
			}

			// Token: 0x0600602D RID: 24621 RVA: 0x001BC575 File Offset: 0x001BA775
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest(questId, base.IssueOwner, this._targetSettlement, CampaignTime.DaysFromNow(60f), this.RewardGold);
			}

			// Token: 0x0600602E RID: 24622 RVA: 0x001BC599 File Offset: 0x001BA799
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x0600602F RID: 24623 RVA: 0x001BC59C File Offset: 0x001BA79C
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				relationHero = null;
				skill = null;
				requiredGold = 0;
				flags = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (issueGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				if (Clan.PlayerClan.Kingdom != issueGiver.MapFaction)
				{
					flags |= IssueBase.PreconditionFlags.NotInSameFaction;
				}
				if (Clan.PlayerClan.IsUnderMercenaryService)
				{
					flags |= IssueBase.PreconditionFlags.ClanIsMercenary;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06006030 RID: 24624 RVA: 0x001BC624 File Offset: 0x001BA824
			public override bool IssueStayAliveConditions()
			{
				if (this._targetSettlement.MapFaction.IsAtWarWith(base.IssueOwner.MapFaction) && base.IssueOwner.MapFaction.IsKingdomFaction)
				{
					return base.IssueOwner.Clan.Settlements.Any<Settlement>((Settlement x) => x.IsFortification);
				}
				return false;
			}

			// Token: 0x06006031 RID: 24625 RVA: 0x001BC696 File Offset: 0x001BA896
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001E61 RID: 7777
			private const int QuestTimeLimit = 60;

			// Token: 0x04001E62 RID: 7778
			[SaveableField(10)]
			private Settlement _targetSettlement;
		}

		// Token: 0x02000761 RID: 1889
		public class TheConquestOfSettlementIssueQuest : QuestBase
		{
			// Token: 0x06006032 RID: 24626 RVA: 0x001BC698 File Offset: 0x001BA898
			internal static void AutoGeneratedStaticCollectObjectsTheConquestOfSettlementIssueQuest(object o, List<object> collectedObjects)
			{
				((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06006033 RID: 24627 RVA: 0x001BC6A6 File Offset: 0x001BA8A6
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._targetSettlement);
			}

			// Token: 0x06006034 RID: 24628 RVA: 0x001BC6BB File Offset: 0x001BA8BB
			internal static object AutoGeneratedGetMemberValue_targetSettlement(object o)
			{
				return ((TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest)o)._targetSettlement;
			}

			// Token: 0x17001368 RID: 4968
			// (get) Token: 0x06006035 RID: 24629 RVA: 0x001BC6C8 File Offset: 0x001BA8C8
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=mvzh0HVk}The Conquest of {TARGET_SETTLEMENT}", null);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001369 RID: 4969
			// (get) Token: 0x06006036 RID: 24630 RVA: 0x001BC6EC File Offset: 0x001BA8EC
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700136A RID: 4970
			// (get) Token: 0x06006037 RID: 24631 RVA: 0x001BC6F0 File Offset: 0x001BA8F0
			private TextObject QuestStartedLog
			{
				get
				{
					TextObject textObject = new TextObject("{=b1T6qywr}{QUEST_GIVER.LINK} from {QUEST_GIVER.FACTION} asked you to take over {TARGET_SETTLEMENT} in the name of {QUEST_GIVER.FACTION} to fortify war efforts. {QUEST_GIVER.LINK} said {?QUEST_GIVER.GENDER}she{?}he{\\?} will aid you with {REWARD}{GOLD_ICON} once the {TARGET_SETTLEMENT} is fallen.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, true);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x1700136B RID: 4971
			// (get) Token: 0x06006038 RID: 24632 RVA: 0x001BC74C File Offset: 0x001BA94C
			private TextObject WarDeclaredQuestCancelLog
			{
				get
				{
					TextObject textObject = new TextObject("{=PakhagOy}Your clan is now at war with {QUEST_GIVER.LINK}'s lord. Your agreement with {QUEST_GIVER.LINK} was canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700136C RID: 4972
			// (get) Token: 0x06006039 RID: 24633 RVA: 0x001BC780 File Offset: 0x001BA980
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700136D RID: 4973
			// (get) Token: 0x0600603A RID: 24634 RVA: 0x001BC7B4 File Offset: 0x001BA9B4
			private TextObject QuestTimeOutFailLog
			{
				get
				{
					TextObject textObject = new TextObject("{=lEcg67Qk}You have failed to take over {TARGET_SETTLEMENT} in time. {QUEST_GIVER.LINK} is disappointed that you have failed to take the fortress in time.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700136E RID: 4974
			// (get) Token: 0x0600603B RID: 24635 RVA: 0x001BC800 File Offset: 0x001BAA00
			private TextObject QuestSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=6d2VIgH3}{QUEST_GIVER.LINK}: Thank you. My lords see you as an example, and see your conquest of {TARGET_SETTLEMENT} as be a stepping stone toward further victories. {?QUEST_GIVER.GENDER}She{?}He{\\?} is grateful for your service and gave you {REWARD}{GOLD_ICON} denars.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					return textObject;
				}
			}

			// Token: 0x1700136F RID: 4975
			// (get) Token: 0x0600603C RID: 24636 RVA: 0x001BC85C File Offset: 0x001BAA5C
			private TextObject QuestLesserSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=1NtZ4BJh}{QUEST_GIVER.LINK}: Thank you. My lords see the conquest of {TARGET_SETTLEMENT} was a stepping stone toward further victories. {?QUEST_GIVER.GENDER}She{?}He{\\?} is grateful for your service. Because you didn't lead the army, {?QUEST_GIVER.GENDER}she{?}he{\\?} gave you {LESSER_REWARD}{GOLD_ICON} denars.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001370 RID: 4976
			// (get) Token: 0x0600603D RID: 24637 RVA: 0x001BC8A8 File Offset: 0x001BAAA8
			private TextObject TargetSettlementTakenByAnotherFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=diUtbbaH}{TARGET_SETTLEMENT} is taken by the {NEW_OWNER_FACTION}. Your agreement with {QUEST_GIVER.LINK} is no longer valid.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001371 RID: 4977
			// (get) Token: 0x0600603E RID: 24638 RVA: 0x001BC8F4 File Offset: 0x001BAAF4
			private TextObject TargetSettlementTakenByPlayerFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=bEak0k5N}{TARGET_SETTLEMENT} is taken. You did not participate in this battle. Your agreement with {QUEST_GIVER.LINK} is moot.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001372 RID: 4978
			// (get) Token: 0x0600603F RID: 24639 RVA: 0x001BC940 File Offset: 0x001BAB40
			private TextObject LeftFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=d8TeoRNf}You are no longer in the same faction with {QUEST_GIVER.LINK}. Your agreement with {QUEST_GIVER.LINK} is no longer valid.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001373 RID: 4979
			// (get) Token: 0x06006040 RID: 24640 RVA: 0x001BC974 File Offset: 0x001BAB74
			private TextObject DefectedToAnotherFaction
			{
				get
				{
					TextObject textObject = new TextObject("{=8iVkBa6D}{TARGET_SETTLEMENT_OWNER.LINK} has defected to the {FACTION_NAME} along with {TARGET_SETTLEMENT}. Your agreement with {QUEST_GIVER.LINK} is moot.", null);
					StringHelpers.SetCharacterProperties("TARGET_SETTLEMENT_OWNER", this._targetSettlement.OwnerClan.Leader.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001374 RID: 4980
			// (get) Token: 0x06006041 RID: 24641 RVA: 0x001BC9E0 File Offset: 0x001BABE0
			private TextObject NoLongerEnemy
			{
				get
				{
					TextObject textObject = new TextObject("{=HknxaCpK}{TARGET_SETTLEMENT_OWNER.FACTION} and {QUEST_GIVER.FACTION} had made peace. Your agreement with {QUEST_GIVER.LINK} is moot.", null);
					StringHelpers.SetCharacterProperties("TARGET_SETTLEMENT_OWNER", this._targetSettlement.OwnerClan.Leader.CharacterObject, textObject, true);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, true);
					return textObject;
				}
			}

			// Token: 0x06006042 RID: 24642 RVA: 0x001BCA34 File Offset: 0x001BAC34
			public TheConquestOfSettlementIssueQuest(string questId, Hero questGiver, Settlement targetSettlement, CampaignTime duration, int rewardGold)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._targetSettlement = targetSettlement;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06006043 RID: 24643 RVA: 0x001BCA58 File Offset: 0x001BAC58
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=QP3BbOW3}Very good. You have my blessing to summon an army if you wish, or, if you prefer to strike quickly, you may do so on your own...[ib:hip][if:convo_mocking_aristocratic]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				TextObject textObject = new TextObject("{=ICNtSonV}How are your preparations to take {TARGET_SETTLEMENT} coming along, {PLAYER.NAME}? I have assured my other lords that you will take it, so it will look bad if you fail.", null);
				textObject.SetTextVariable("TARGET_SETTLEMENT", this._targetSettlement.Name);
				TextObject textObject2 = new TextObject("{=m4pZhnyd}They are going as planned, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}...", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				TextObject textObject3 = new TextObject("{=jFXkosnJ}This may be tricky, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}...", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject3, false);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject2, null, null, null)
					.NpcLine(new TextObject("{=opMDusHz}Good. I look forward to presenting you with your reward.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += MapEventHelper.OnConversationEnd;
					})
					.CloseDialog()
					.PlayerOption(textObject3, null, null, null)
					.NpcLine(new TextObject("{=R85IMErK}Well, if you fail we will deal with that, but I would prefer not to.", null), null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += MapEventHelper.OnConversationEnd;
					})
					.CloseDialog()
					.EndPlayerOptions();
			}

			// Token: 0x06006044 RID: 24644 RVA: 0x001BCBE2 File Offset: 0x001BADE2
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddLog(this.QuestStartedLog, false);
				base.AddTrackedObject(this._targetSettlement);
			}

			// Token: 0x06006045 RID: 24645 RVA: 0x001BCC04 File Offset: 0x001BAE04
			protected override void HourlyTick()
			{
			}

			// Token: 0x06006046 RID: 24646 RVA: 0x001BCC08 File Offset: 0x001BAE08
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.SiegeCompletedEvent.AddNonSerializedListener(this, new Action<Settlement, MobileParty, bool, MapEvent.BattleTypes>(this.OnSiegeCompleted));
				CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener(this, new Action<Settlement, bool, Hero, Hero, Hero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail>(this.OnSettlementOwnerChanged));
				CampaignEvents.MakePeace.AddNonSerializedListener(this, new Action<IFaction, IFaction, MakePeaceAction.MakePeaceDetail>(this.OnPeaceDeclared));
			}

			// Token: 0x06006047 RID: 24647 RVA: 0x001BCC9F File Offset: 0x001BAE9F
			private void OnPeaceDeclared(IFaction faction1, IFaction faction2, MakePeaceAction.MakePeaceDetail detail)
			{
				if (!base.QuestGiver.MapFaction.IsAtWarWith(this._targetSettlement.MapFaction))
				{
					base.CompleteQuestWithCancel(this.NoLongerEnemy);
				}
			}

			// Token: 0x06006048 RID: 24648 RVA: 0x001BCCCC File Offset: 0x001BAECC
			private void OnSettlementOwnerChanged(Settlement settlement, bool openToClaim, Hero newOwner, Hero oldOwner, Hero capturerHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail)
			{
				if (base.IsOngoing && settlement == this._targetSettlement)
				{
					if (newOwner == Hero.MainHero && detail == ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail.ByBarter)
					{
						this.QuestSuccess(2);
						return;
					}
					if (newOwner.MapFaction != oldOwner.MapFaction && newOwner.MapFaction != base.QuestGiver.MapFaction && !newOwner.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
					{
						TextObject targetSettlementTakenByAnotherFaction = this.TargetSettlementTakenByAnotherFaction;
						targetSettlementTakenByAnotherFaction.SetTextVariable("NEW_OWNER_FACTION", newOwner.MapFaction.EncyclopediaLinkWithName);
						base.CompleteQuestWithCancel(targetSettlementTakenByAnotherFaction);
					}
				}
			}

			// Token: 0x06006049 RID: 24649 RVA: 0x001BCD60 File Offset: 0x001BAF60
			private void OnSiegeCompleted(Settlement siegeSettlement, MobileParty attackerParty, bool isWin, MapEvent.BattleTypes battleType)
			{
				if (isWin && siegeSettlement == this._targetSettlement)
				{
					if (attackerParty.MapFaction == base.QuestGiver.MapFaction)
					{
						if (attackerParty == MobileParty.MainParty)
						{
							this.QuestSuccess(10);
							return;
						}
						if (siegeSettlement.Party.MapEvent.InvolvedParties.Contains(PartyBase.MainParty))
						{
							this.QuestLesserSuccess();
							return;
						}
						base.CompleteQuestWithCancel(this.TargetSettlementTakenByPlayerFaction);
						return;
					}
					else
					{
						TextObject targetSettlementTakenByAnotherFaction = this.TargetSettlementTakenByAnotherFaction;
						targetSettlementTakenByAnotherFaction.SetTextVariable("NEW_OWNER_FACTION", attackerParty.MapFaction.EncyclopediaLinkWithName);
						base.CompleteQuestWithCancel(targetSettlementTakenByAnotherFaction);
					}
				}
			}

			// Token: 0x0600604A RID: 24650 RVA: 0x001BCDF8 File Offset: 0x001BAFF8
			private void QuestLesserSuccess()
			{
				TextObject questLesserSuccessLog = this.QuestLesserSuccessLog;
				int num = this.RewardGold / 4;
				questLesserSuccessLog.SetTextVariable("LESSER_REWARD", num);
				base.AddLog(questLesserSuccessLog, false);
				GainRenownAction.Apply(Hero.MainHero, 5f, false);
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				this.RelationshipChangeWithQuestGiver = 1;
				foreach (Settlement settlement in base.QuestGiver.Clan.Settlements.Where<Settlement>((Settlement x) => x.IsFortification))
				{
					settlement.Town.Security += 2f;
					settlement.Town.Loyalty += 2f;
				}
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x0600604B RID: 24651 RVA: 0x001BCEE8 File Offset: 0x001BB0E8
			private void QuestSuccess(int boost)
			{
				base.AddLog(this.QuestSuccessLog, false);
				this.RelationshipChangeWithQuestGiver = 5;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				foreach (Settlement settlement in base.QuestGiver.Clan.Settlements.Where<Settlement>((Settlement x) => x.IsFortification))
				{
					settlement.Town.Security += (float)boost;
					settlement.Town.Loyalty += (float)boost;
				}
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x0600604C RID: 24652 RVA: 0x001BCFB0 File Offset: 0x001BB1B0
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x0600604D RID: 24653 RVA: 0x001BCFC4 File Offset: 0x001BB1C4
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (clan == Clan.PlayerClan && oldKingdom == base.QuestGiver.MapFaction)
				{
					base.AddLog(this.LeftFaction, false);
					base.CompleteQuestWithFail(null);
					return;
				}
				if (clan.Settlements.Contains(this._targetSettlement))
				{
					if (detail == ChangeKingdomAction.ChangeKingdomActionDetail.JoinKingdomByDefection)
					{
						if (newKingdom == base.QuestGiver.MapFaction)
						{
							this.QuestSuccess(1);
							return;
						}
						TextObject defectedToAnotherFaction = this.DefectedToAnotherFaction;
						defectedToAnotherFaction.SetTextVariable("FACTION_NAME", newKingdom.EncyclopediaLinkWithName);
						base.CompleteQuestWithCancel(defectedToAnotherFaction);
						return;
					}
					else if ((detail == ChangeKingdomAction.ChangeKingdomActionDetail.LeaveKingdom || detail == ChangeKingdomAction.ChangeKingdomActionDetail.LeaveWithRebellion || detail == ChangeKingdomAction.ChangeKingdomActionDetail.LeaveAsMercenary) && !base.QuestGiver.MapFaction.IsAtWarWith(clan.MapFaction))
					{
						base.CompleteQuestWithCancel(this.NoLongerEnemy);
						return;
					}
				}
				else if (base.QuestGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.WarDeclaredQuestCancelLog);
				}
			}

			// Token: 0x0600604E RID: 24654 RVA: 0x001BD0A8 File Offset: 0x001BB2A8
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.WarDeclaredQuestCancelLog, false);
			}

			// Token: 0x0600604F RID: 24655 RVA: 0x001BD0C0 File Offset: 0x001BB2C0
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06006050 RID: 24656 RVA: 0x001BD0C8 File Offset: 0x001BB2C8
			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestTimeOutFailLog, false);
				this.RelationshipChangeWithQuestGiver = -10;
				foreach (Settlement settlement in base.QuestGiver.Clan.Settlements.Where<Settlement>((Settlement x) => x.IsFortification))
				{
					settlement.Town.Security += -10f;
					settlement.Town.Loyalty += -10f;
				}
			}

			// Token: 0x04001E63 RID: 7779
			private const int SuccessLoyaltySecurityBoost = 10;

			// Token: 0x04001E64 RID: 7780
			private const int LesserSuccessLoyaltySecurityBoost = 2;

			// Token: 0x04001E65 RID: 7781
			private const int SuccessRelationBoost = 5;

			// Token: 0x04001E66 RID: 7782
			private const int LesserSuccessRelationBoost = 1;

			// Token: 0x04001E67 RID: 7783
			private const int TimeoutSecurityLoyaltyPenalty = -10;

			// Token: 0x04001E68 RID: 7784
			private const int TimeoutRelationyPenalty = -10;

			// Token: 0x04001E69 RID: 7785
			[SaveableField(10)]
			private Settlement _targetSettlement;
		}

		// Token: 0x02000762 RID: 1890
		public class TheConquestOfSettlementIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06006053 RID: 24659 RVA: 0x001BD19E File Offset: 0x001BB39E
			public TheConquestOfSettlementIssueTypeDefiner()
				: base(620000)
			{
			}

			// Token: 0x06006054 RID: 24660 RVA: 0x001BD1AB File Offset: 0x001BB3AB
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssue), 1, null);
				base.AddClassDefinition(typeof(TheConquestOfSettlementIssueBehavior.TheConquestOfSettlementIssueQuest), 2, null);
			}
		}
	}
}
