using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x0200037B RID: 891
	public class VillageNeedsCraftingMaterialsIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x0600344E RID: 13390 RVA: 0x000D8428 File Offset: 0x000D6628
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x0600344F RID: 13391 RVA: 0x000D8444 File Offset: 0x000D6644
		private void OnCheckForIssue(Hero hero)
		{
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, this.ConditionsHold(hero) ? new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue), IssueBase.IssueFrequency.Rare, null) : new PotentialIssueData(typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue), IssueBase.IssueFrequency.Rare));
		}

		// Token: 0x06003450 RID: 13392 RVA: 0x000D8499 File Offset: 0x000D6699
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.IsRuralNotable && !issueGiver.MapFaction.IsAtWarWith(Clan.PlayerClan);
		}

		// Token: 0x06003451 RID: 13393 RVA: 0x000D84B8 File Offset: 0x000D66B8
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			return new VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue(issueOwner);
		}

		// Token: 0x06003452 RID: 13394 RVA: 0x000D84C0 File Offset: 0x000D66C0
		private static ItemObject SelectCraftingMaterial()
		{
			int num = MBRandom.RandomInt(0, 2);
			if (num == 0)
			{
				return DefaultItems.IronIngot1;
			}
			if (num != 1)
			{
				return DefaultItems.IronIngot1;
			}
			return DefaultItems.IronIngot2;
		}

		// Token: 0x06003453 RID: 13395 RVA: 0x000D84EF File Offset: 0x000D66EF
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EEC RID: 3820
		private const IssueBase.IssueFrequency VillageNeedsCraftingMaterialsIssueFrequency = IssueBase.IssueFrequency.Rare;

		// Token: 0x02000764 RID: 1892
		public class VillageNeedsCraftingMaterialsIssue : IssueBase
		{
			// Token: 0x06006058 RID: 24664 RVA: 0x001BD1ED File Offset: 0x001BB3ED
			internal static void AutoGeneratedStaticCollectObjectsVillageNeedsCraftingMaterialsIssue(object o, List<object> collectedObjects)
			{
				((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06006059 RID: 24665 RVA: 0x001BD1FB File Offset: 0x001BB3FB
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._requestedItem);
			}

			// Token: 0x0600605A RID: 24666 RVA: 0x001BD210 File Offset: 0x001BB410
			internal static object AutoGeneratedGetMemberValue_requestedItem(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue)o)._requestedItem;
			}

			// Token: 0x0600605B RID: 24667 RVA: 0x001BD21D File Offset: 0x001BB41D
			internal static object AutoGeneratedGetMemberValue_promisedPayment(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue)o)._promisedPayment;
			}

			// Token: 0x17001375 RID: 4981
			// (get) Token: 0x0600605C RID: 24668 RVA: 0x001BD22F File Offset: 0x001BB42F
			private int _numberOfRequestedItem
			{
				get
				{
					return MathF.Round((float)((int)(750f / (float)this._requestedItem.Value)) * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001376 RID: 4982
			// (get) Token: 0x0600605D RID: 24669 RVA: 0x001BD251 File Offset: 0x001BB451
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return 500 + (int)(700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001377 RID: 4983
			// (get) Token: 0x0600605E RID: 24670 RVA: 0x001BD266 File Offset: 0x001BB466
			protected override bool IssueQuestCanBeDuplicated
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001378 RID: 4984
			// (get) Token: 0x0600605F RID: 24671 RVA: 0x001BD269 File Offset: 0x001BB469
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 4;
				}
			}

			// Token: 0x17001379 RID: 4985
			// (get) Token: 0x06006060 RID: 24672 RVA: 0x001BD26C File Offset: 0x001BB46C
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return (int)(2f + 4f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06006061 RID: 24673 RVA: 0x001BD281 File Offset: 0x001BB481
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.VillageHearth)
				{
					return -0.2f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06006062 RID: 24674 RVA: 0x001BD2A4 File Offset: 0x001BB4A4
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>(DefaultSkills.Crafting, 120);
			}

			// Token: 0x06006063 RID: 24675 RVA: 0x001BD2B2 File Offset: 0x001BB4B2
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 0, false);
			}

			// Token: 0x06006064 RID: 24676 RVA: 0x001BD2CC File Offset: 0x001BB4CC
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.GetPayment(), false);
				this.RelationshipChangeWithIssueOwner = 5;
				base.IssueSettlement.Village.Hearth += 60f;
				base.IssueOwner.AddPower(10f);
			}

			// Token: 0x06006065 RID: 24677 RVA: 0x001BD31E File Offset: 0x001BB51E
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 0, false);
			}

			// Token: 0x1700137A RID: 4986
			// (get) Token: 0x06006066 RID: 24678 RVA: 0x001BD32F File Offset: 0x001BB52F
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=eR7P1cVA}{VILLAGE} Needs Crafting Materials", null);
					textObject.SetTextVariable("VILLAGE", base.IssueOwner.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x1700137B RID: 4987
			// (get) Token: 0x06006067 RID: 24679 RVA: 0x001BD358 File Offset: 0x001BB558
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=5CJrR0X3}{ISSUE_GIVER.LINK} in the village requested crafting materials for their ongoing project.", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x1700137C RID: 4988
			// (get) Token: 0x06006068 RID: 24680 RVA: 0x001BD37C File Offset: 0x001BB57C
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=095beaQ5}Yes, there's a lot of work we need to do around the village, and we're short on the materials that our smith needs to make us tools and fittings. Do you think you could get us some? We'll pay well.[ib:demure][if:convo_dismayed]", null);
				}
			}

			// Token: 0x1700137D RID: 4989
			// (get) Token: 0x06006069 RID: 24681 RVA: 0x001BD389 File Offset: 0x001BB589
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=xmu89biL}Maybe I can help. What do you need exactly?", null);
				}
			}

			// Token: 0x1700137E RID: 4990
			// (get) Token: 0x0600606A RID: 24682 RVA: 0x001BD398 File Offset: 0x001BB598
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=PftlaE0x}We need {REQUESTED_ITEM_COUNT} {?(REQUESTED_ITEM_COUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} in {NUMBER_OF_DAYS} days. We need to repair some roofs before the next big storms. I can offer {PAYMENT}{GOLD_ICON}. What do you say?", null);
					textObject.SetTextVariable("PAYMENT", this.GetPayment());
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					textObject.SetTextVariable("REQUESTED_ITEM_COUNT", this._numberOfRequestedItem);
					textObject.SetTextVariable("NUMBER_OF_DAYS", 30);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x1700137F RID: 4991
			// (get) Token: 0x0600606B RID: 24683 RVA: 0x001BD40A File Offset: 0x001BB60A
			public override TextObject IssuePlayerResponseAfterAlternativeExplanation
			{
				get
				{
					return new TextObject("{=i96OaGH3}Is there anything else I could do to help?", null);
				}
			}

			// Token: 0x17001380 RID: 4992
			// (get) Token: 0x0600606C RID: 24684 RVA: 0x001BD417 File Offset: 0x001BB617
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					return new TextObject("{=WzdhPF7M}Well, if we had some extra skilled labor, we could probably melt down old tools and reforge them. That's too much work for just our smith by himself, but maybe he could do it with someone proficient in crafting to help him.[ib:demure2][if:convo_thinking]", null);
				}
			}

			// Token: 0x17001381 RID: 4993
			// (get) Token: 0x0600606D RID: 24685 RVA: 0x001BD424 File Offset: 0x001BB624
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=WsmH9Cfd}I will provide what you need.", null);
				}
			}

			// Token: 0x17001382 RID: 4994
			// (get) Token: 0x0600606E RID: 24686 RVA: 0x001BD431 File Offset: 0x001BB631
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=8DWTTnpP}My comrade will help your smith to produce what you need.", null);
				}
			}

			// Token: 0x17001383 RID: 4995
			// (get) Token: 0x0600606F RID: 24687 RVA: 0x001BD43E File Offset: 0x001BB63E
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=xlagNKZ2}Thank you. With their help, we should be able to make what we need.[if:convo_astonished]", null);
				}
			}

			// Token: 0x17001384 RID: 4996
			// (get) Token: 0x06006070 RID: 24688 RVA: 0x001BD44B File Offset: 0x001BB64B
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=P3Uu0Ham}Your companion is still working with our smith. I hope they will finish the order in time.[if:convo_approving]", null);
				}
			}

			// Token: 0x17001385 RID: 4997
			// (get) Token: 0x06006071 RID: 24689 RVA: 0x001BD458 File Offset: 0x001BB658
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001386 RID: 4998
			// (get) Token: 0x06006072 RID: 24690 RVA: 0x001BD45B File Offset: 0x001BB65B
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001387 RID: 4999
			// (get) Token: 0x06006073 RID: 24691 RVA: 0x001BD45E File Offset: 0x001BB65E
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x17001388 RID: 5000
			// (get) Token: 0x06006074 RID: 24692 RVA: 0x001BD464 File Offset: 0x001BB664
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=1XuYGQcT}{ISSUE_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}her{?}his{\\?} local smith needs {REQUESTED_ITEM} to forge more tools. You asked your companion {COMPANION.LINK} to help the local smith and craft {REQUESTED_ITEM_COUNT} {?(REQUESTED_ITEM_COUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} for the village. Your companion will rejoin your party in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					textObject.SetTextVariable("REQUESTED_ITEM_COUNT", this._numberOfRequestedItem);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x17001389 RID: 5001
			// (get) Token: 0x06006075 RID: 24693 RVA: 0x001BD508 File Offset: 0x001BB708
			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=n86jgG3m}Your companion {COMPANION.LINK} has helped the local smith and produced {REQUESTED_AMOUNT} {?(REQUESTED_AMOUNT > 1)}{PLURAL(REQUESTED_GOOD)}{?}{REQUESTED_GOOD}{\\?} as you promised.", null);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this._numberOfRequestedItem);
					textObject.SetTextVariable("REQUESTED_GOOD", this._requestedItem.Name);
					return textObject;
				}
			}

			// Token: 0x06006076 RID: 24694 RVA: 0x001BD563 File Offset: 0x001BB763
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06006077 RID: 24695 RVA: 0x001BD565 File Offset: 0x001BB765
			protected override void HourlyTick()
			{
			}

			// Token: 0x06006078 RID: 24696 RVA: 0x001BD567 File Offset: 0x001BB767
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this.GetPayment(), this._requestedItem, this._numberOfRequestedItem);
			}

			// Token: 0x06006079 RID: 24697 RVA: 0x001BD591 File Offset: 0x001BB791
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Rare;
			}

			// Token: 0x0600607A RID: 24698 RVA: 0x001BD594 File Offset: 0x001BB794
			public override void AlternativeSolutionStartConsequence()
			{
				this._promisedPayment = this.GetPayment();
			}

			// Token: 0x0600607B RID: 24699 RVA: 0x001BD5A4 File Offset: 0x001BB7A4
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x0600607C RID: 24700 RVA: 0x001BD5F8 File Offset: 0x001BB7F8
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x0600607D RID: 24701 RVA: 0x001BD5FA File Offset: 0x001BB7FA
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid;
			}

			// Token: 0x0600607E RID: 24702 RVA: 0x001BD623 File Offset: 0x001BB823
			public VillageNeedsCraftingMaterialsIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				this._requestedItem = VillageNeedsCraftingMaterialsIssueBehavior.SelectCraftingMaterial();
			}

			// Token: 0x0600607F RID: 24703 RVA: 0x001BD644 File Offset: 0x001BB844
			private int GetPayment()
			{
				if (this._promisedPayment != 0)
				{
					return this._promisedPayment;
				}
				return 750 + (base.IssueSettlement.Village.Bound.Town.MarketData.GetPrice(this._requestedItem, null, false, null) + QuestHelper.GetAveragePriceOfItemInTheWorld(this._requestedItem) / 2) * this._numberOfRequestedItem;
			}

			// Token: 0x04001E6C RID: 7788
			private const int TimeLimit = 30;

			// Token: 0x04001E6D RID: 7789
			private const int PowerChangeForQuestGiver = 10;

			// Token: 0x04001E6E RID: 7790
			private const int RelationWithIssueOwnerRewardOnSuccess = 5;

			// Token: 0x04001E6F RID: 7791
			private const int VillageHeartChangeOnAlternativeSuccess = 60;

			// Token: 0x04001E70 RID: 7792
			private const int RequiredSkillValueForAlternativeSolution = 120;

			// Token: 0x04001E71 RID: 7793
			[SaveableField(1)]
			private readonly ItemObject _requestedItem;

			// Token: 0x04001E72 RID: 7794
			[SaveableField(4)]
			private int _promisedPayment;
		}

		// Token: 0x02000765 RID: 1893
		public class VillageNeedsCraftingMaterialsIssueQuest : QuestBase
		{
			// Token: 0x06006080 RID: 24704 RVA: 0x001BD6A3 File Offset: 0x001BB8A3
			internal static void AutoGeneratedStaticCollectObjectsVillageNeedsCraftingMaterialsIssueQuest(object o, List<object> collectedObjects)
			{
				((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06006081 RID: 24705 RVA: 0x001BD6B1 File Offset: 0x001BB8B1
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._requestedItem);
				collectedObjects.Add(this._playerAcceptedQuestLog);
				collectedObjects.Add(this._playerHasNeededItemsLog);
			}

			// Token: 0x06006082 RID: 24706 RVA: 0x001BD6DE File Offset: 0x001BB8DE
			internal static object AutoGeneratedGetMemberValue_requestedItemAmount(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._requestedItemAmount;
			}

			// Token: 0x06006083 RID: 24707 RVA: 0x001BD6F0 File Offset: 0x001BB8F0
			internal static object AutoGeneratedGetMemberValue_requestedItem(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._requestedItem;
			}

			// Token: 0x06006084 RID: 24708 RVA: 0x001BD6FD File Offset: 0x001BB8FD
			internal static object AutoGeneratedGetMemberValue_playerAcceptedQuestLog(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._playerAcceptedQuestLog;
			}

			// Token: 0x06006085 RID: 24709 RVA: 0x001BD70A File Offset: 0x001BB90A
			internal static object AutoGeneratedGetMemberValue_playerHasNeededItemsLog(object o)
			{
				return ((VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest)o)._playerHasNeededItemsLog;
			}

			// Token: 0x1700138A RID: 5002
			// (get) Token: 0x06006086 RID: 24710 RVA: 0x001BD718 File Offset: 0x001BB918
			private TextObject QuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=YZeKScP5}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}her{?}his{\\?} local smith needs {REQUESTED_ITEM} to forge more tools. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to bring {REQUESTED_ITEM_AMOUNT} {?(REQUESTED_ITEM_AMOUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("REQUESTED_ITEM_AMOUNT", this._requestedItemAmount);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700138B RID: 5003
			// (get) Token: 0x06006087 RID: 24711 RVA: 0x001BD774 File Offset: 0x001BB974
			private TextObject QuestSuccessLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=LiDSTrvV}You brought {REQUESTED_ITEM_AMOUNT} {?(REQUESTED_ITEM_AMOUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?} as promised.", null);
					textObject.SetTextVariable("REQUESTED_ITEM_AMOUNT", this._requestedItemAmount);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700138C RID: 5004
			// (get) Token: 0x06006088 RID: 24712 RVA: 0x001BD7D0 File Offset: 0x001BB9D0
			private TextObject QuestCanceledWarDeclaredLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700138D RID: 5005
			// (get) Token: 0x06006089 RID: 24713 RVA: 0x001BD804 File Offset: 0x001BBA04
			private TextObject QuestGiverVillageRaidedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=gJG0xmAq}{QUEST_GIVER.LINK}'s village {QUEST_SETTLEMENT} was raided. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x1700138E RID: 5006
			// (get) Token: 0x0600608A RID: 24714 RVA: 0x001BD854 File Offset: 0x001BBA54
			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=nmz1ky2D}You failed to deliver {REQUESTED_ITEM_AMOUNT} {?(REQUESTED_ITEM_AMOUNT > 1)}{PLURAL(REQUESTED_ITEM)}{?}{REQUESTED_ITEM}{\\?} to {QUEST_GIVER.LINK} in time.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_ITEM_AMOUNT", this._requestedItemAmount);
					textObject.SetTextVariable("REQUESTED_ITEM", this._requestedItem.Name);
					return textObject;
				}
			}

			// Token: 0x1700138F RID: 5007
			// (get) Token: 0x0600608B RID: 24715 RVA: 0x001BD8AF File Offset: 0x001BBAAF
			private TextObject PlayerHasNeededItemsLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=MxpPkytG}You now have enough {ITEM} to complete the quest. Return to {QUEST_SETTLEMENT} to hand them over.", null);
					textObject.SetTextVariable("ITEM", this._requestedItem.Name);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x0600608C RID: 24716 RVA: 0x001BD8EF File Offset: 0x001BBAEF
			public VillageNeedsCraftingMaterialsIssueQuest(string questId, Hero questGiver, CampaignTime duration, int rewardGold, ItemObject requestedItem, int requestedItemAmount)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._requestedItem = requestedItem;
				this._requestedItemAmount = requestedItemAmount;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x17001390 RID: 5008
			// (get) Token: 0x0600608D RID: 24717 RVA: 0x001BD918 File Offset: 0x001BBB18
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=LgiRMbgE}{ISSUE_SETTLEMENT} Needs Crafting Materials", null);
					textObject.SetTextVariable("ISSUE_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001391 RID: 5009
			// (get) Token: 0x0600608E RID: 24718 RVA: 0x001BD941 File Offset: 0x001BBB41
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x0600608F RID: 24719 RVA: 0x001BD944 File Offset: 0x001BBB44
			protected override void SetDialogs()
			{
				TextObject textObject = new TextObject("{=UbUokDyI}Thank you. We'd appreciate it if you got the goods to us as quickly as possible. Good luck![ib:nervous2][if:convo_excited]", null);
				TextObject textObject2 = new TextObject("{=4c9ySfVj}Did you find what we needed, {?PLAYER.GENDER}madam{?}sir{\\?}?", null);
				TextObject textObject3 = new TextObject("{=nEGe8rUd}Thank you for your help, {?PLAYER.GENDER}madam{?}sir{\\?}. Here is what we promised.", null);
				TextObject textObject4 = new TextObject("{=sTfr1C8H}Thank you. But if the storms come before you find them, well, that would be bad for us.[ib:nervous2][if:convo_nervous]", null);
				textObject2.SetCharacterProperties("PLAYER", Hero.MainHero.CharacterObject, false);
				textObject3.SetCharacterProperties("PLAYER", Hero.MainHero.CharacterObject, false);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(textObject, null, null, null, null).Condition(() => CharacterObject.OneToOneConversationCharacter == base.QuestGiver.CharacterObject)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject2, null, null, null, null).Condition(() => CharacterObject.OneToOneConversationCharacter == base.QuestGiver.CharacterObject)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=bLRGix1b}Yes, I have them with me.", null), null, null, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.CompleteQuestClickableConditions))
					.NpcLine(textObject3, null, null, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.Success;
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=D8KFcE2i}Not yet, I am still working on it.", null), null, null, null)
					.NpcLine(textObject4, null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06006090 RID: 24720 RVA: 0x001BDA94 File Offset: 0x001BBC94
			private bool CompleteQuestClickableConditions(out TextObject explanation)
			{
				if (this._playerAcceptedQuestLog.CurrentProgress >= this._requestedItemAmount)
				{
					explanation = null;
					return true;
				}
				explanation = new TextObject("{=EmBla2xa}You don't have enough {ITEM}", null);
				explanation.SetTextVariable("ITEM", this._requestedItem.Name);
				return false;
			}

			// Token: 0x06006091 RID: 24721 RVA: 0x001BDAD4 File Offset: 0x001BBCD4
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06006092 RID: 24722 RVA: 0x001BDADC File Offset: 0x001BBCDC
			protected override void HourlyTick()
			{
			}

			// Token: 0x06006093 RID: 24723 RVA: 0x001BDAE0 File Offset: 0x001BBCE0
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				int requiredItemCountOnPlayer = this.GetRequiredItemCountOnPlayer();
				TextObject textObject = new TextObject("{=nAEhfGJk}Collect {ITEM}", null);
				textObject.SetTextVariable("ITEM", this._requestedItem.Name);
				this._playerAcceptedQuestLog = base.AddDiscreteLog(this.QuestStartedLogText, textObject, requiredItemCountOnPlayer, this._requestedItemAmount, null, false);
			}

			// Token: 0x06006094 RID: 24724 RVA: 0x001BDB39 File Offset: 0x001BBD39
			protected override void OnTimedOut()
			{
				this.Fail();
			}

			// Token: 0x06006095 RID: 24725 RVA: 0x001BDB44 File Offset: 0x001BBD44
			private void Success()
			{
				base.AddLog(this.QuestSuccessLogText, false);
				ItemRosterElement itemRosterElement = new ItemRosterElement(this._requestedItem, this._requestedItemAmount, null);
				GiveItemAction.ApplyForParties(PartyBase.MainParty, Settlement.CurrentSettlement.Party, in itemRosterElement);
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.QuestGiver.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = 5;
				base.QuestGiver.CurrentSettlement.Village.Hearth += 30f;
				base.CompleteQuestWithSuccess();
			}

			// Token: 0x06006096 RID: 24726 RVA: 0x001BDBF8 File Offset: 0x001BBDF8
			private void Fail()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
				base.QuestGiver.CurrentSettlement.Village.Hearth += -40f;
				base.CompleteQuestWithFail(null);
			}

			// Token: 0x06006097 RID: 24727 RVA: 0x001BDC54 File Offset: 0x001BBE54
			private int GetRequiredItemCountOnPlayer()
			{
				int itemNumber = PartyBase.MainParty.ItemRoster.GetItemNumber(this._requestedItem);
				if (itemNumber >= this._requestedItemAmount)
				{
					TextObject textObject = new TextObject("{=MTCrXEvj}You have enough {ITEM} to complete the quest. Return to {QUEST_SETTLEMENT} to hand it over.", null);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					textObject.SetTextVariable("ITEM", this._requestedItem.Name);
					MBInformationManager.AddQuickInformation(textObject, 0, null, null, "");
				}
				if (itemNumber <= this._requestedItemAmount)
				{
					return itemNumber;
				}
				return this._requestedItemAmount;
			}

			// Token: 0x06006098 RID: 24728 RVA: 0x001BDCDC File Offset: 0x001BBEDC
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.RaidCompletedEvent.AddNonSerializedListener(this, new Action<BattleSideEnum, RaidEventComponent>(this.OnRaidCompleted));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnPlayerInventoryExchange));
				CampaignEvents.OnNewItemCraftedEvent.AddNonSerializedListener(this, new Action<ItemObject, ItemModifier, bool>(this.OnItemCrafted));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
				CampaignEvents.OnEquipmentSmeltedByHeroEvent.AddNonSerializedListener(this, new Action<Hero, EquipmentElement>(this.OnEquipmentSmeltedByHero));
				CampaignEvents.OnItemsRefinedEvent.AddNonSerializedListener(this, new Action<Hero, Crafting.RefiningFormula>(this.OnItemsRefined));
			}

			// Token: 0x06006099 RID: 24729 RVA: 0x001BDDA1 File Offset: 0x001BBFA1
			private void OnItemsRefined(Hero hero, Crafting.RefiningFormula refiningFormula)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x0600609A RID: 24730 RVA: 0x001BDDA9 File Offset: 0x001BBFA9
			private void OnEquipmentSmeltedByHero(Hero hero, EquipmentElement equipmentElement)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x0600609B RID: 24731 RVA: 0x001BDDB1 File Offset: 0x001BBFB1
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.QuestCanceledWarDeclaredLogText, this.QuestCanceledWarDeclaredLogText, false);
			}

			// Token: 0x0600609C RID: 24732 RVA: 0x001BDDC9 File Offset: 0x001BBFC9
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x0600609D RID: 24733 RVA: 0x001BDDDC File Offset: 0x001BBFDC
			private void OnItemCrafted(ItemObject item, ItemModifier overriddenItemModifier, bool isCraftingOrderItem)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x0600609E RID: 24734 RVA: 0x001BDDE4 File Offset: 0x001BBFE4
			private void OnPlayerInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				this.UpdateQuestLog();
			}

			// Token: 0x0600609F RID: 24735 RVA: 0x001BDDEC File Offset: 0x001BBFEC
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLogText);
				}
			}

			// Token: 0x060060A0 RID: 24736 RVA: 0x001BDE1B File Offset: 0x001BC01B
			private void OnRaidCompleted(BattleSideEnum battleSide, RaidEventComponent mapEvent)
			{
				if (mapEvent.MapEventSettlement == base.QuestGiver.CurrentSettlement)
				{
					base.CompleteQuestWithCancel(this.QuestGiverVillageRaidedLogText);
				}
			}

			// Token: 0x060060A1 RID: 24737 RVA: 0x001BDE3C File Offset: 0x001BC03C
			private void CheckIfPlayerReadyToReturnItems()
			{
				if (this._playerHasNeededItemsLog == null && this._playerAcceptedQuestLog.CurrentProgress >= this._requestedItemAmount)
				{
					this._playerHasNeededItemsLog = base.AddLog(this.PlayerHasNeededItemsLogText, false);
					return;
				}
				if (this._playerHasNeededItemsLog != null && this._playerAcceptedQuestLog.CurrentProgress < this._requestedItemAmount)
				{
					base.RemoveLog(this._playerHasNeededItemsLog);
					this._playerHasNeededItemsLog = null;
				}
			}

			// Token: 0x060060A2 RID: 24738 RVA: 0x001BDEA6 File Offset: 0x001BC0A6
			private void UpdateQuestLog()
			{
				this._playerAcceptedQuestLog.UpdateCurrentProgress(this.GetRequiredItemCountOnPlayer());
				this.CheckIfPlayerReadyToReturnItems();
			}

			// Token: 0x04001E73 RID: 7795
			[SaveableField(10)]
			private readonly int _requestedItemAmount;

			// Token: 0x04001E74 RID: 7796
			[SaveableField(20)]
			private readonly ItemObject _requestedItem;

			// Token: 0x04001E75 RID: 7797
			[SaveableField(30)]
			private JournalLog _playerAcceptedQuestLog;

			// Token: 0x04001E76 RID: 7798
			[SaveableField(40)]
			private JournalLog _playerHasNeededItemsLog;

			// Token: 0x04001E77 RID: 7799
			private const int SuccessRelationBonus = 5;

			// Token: 0x04001E78 RID: 7800
			private const int FailRelationPenalty = -5;

			// Token: 0x04001E79 RID: 7801
			private const int SuccessPowerBonus = 10;

			// Token: 0x04001E7A RID: 7802
			private const int FailPowerPenalty = -10;

			// Token: 0x04001E7B RID: 7803
			private const int SuccessHonorBonus = 30;

			// Token: 0x04001E7C RID: 7804
			private const int FailWithCrimeHonorPenalty = -50;

			// Token: 0x04001E7D RID: 7805
			private const int SuccessHearthBonus = 30;

			// Token: 0x04001E7E RID: 7806
			private const int FailToDeliverInTimeHearthPenalty = -40;
		}

		// Token: 0x02000766 RID: 1894
		public class VillageNeedsCraftingMaterialsIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x060060A6 RID: 24742 RVA: 0x001BDF04 File Offset: 0x001BC104
			public VillageNeedsCraftingMaterialsIssueTypeDefiner()
				: base(601000)
			{
			}

			// Token: 0x060060A7 RID: 24743 RVA: 0x001BDF11 File Offset: 0x001BC111
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssue), 1, null);
				base.AddClassDefinition(typeof(VillageNeedsCraftingMaterialsIssueBehavior.VillageNeedsCraftingMaterialsIssueQuest), 2, null);
			}
		}
	}
}
