using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.Core
{
	// Token: 0x02000012 RID: 18
	public class BannerComponent : WeaponComponent
	{
		// Token: 0x1700002F RID: 47
		// (get) Token: 0x060000BA RID: 186 RVA: 0x00004170 File Offset: 0x00002370
		// (set) Token: 0x060000BB RID: 187 RVA: 0x00004178 File Offset: 0x00002378
		public int BannerLevel { get; private set; }

		// Token: 0x17000030 RID: 48
		// (get) Token: 0x060000BC RID: 188 RVA: 0x00004181 File Offset: 0x00002381
		// (set) Token: 0x060000BD RID: 189 RVA: 0x00004189 File Offset: 0x00002389
		public BannerEffect BannerEffect { get; private set; }

		// Token: 0x060000BE RID: 190 RVA: 0x00004192 File Offset: 0x00002392
		public BannerComponent(ItemObject item)
			: base(item)
		{
		}

		// Token: 0x060000BF RID: 191 RVA: 0x0000419C File Offset: 0x0000239C
		public override ItemComponent GetCopy()
		{
			return new BannerComponent(this.Item)
			{
				BannerLevel = this.BannerLevel,
				BannerEffect = this.BannerEffect
			};
		}

		// Token: 0x060000C0 RID: 192 RVA: 0x000041CE File Offset: 0x000023CE
		public float GetBannerEffectBonus()
		{
			return this.BannerEffect.GetBonusAtLevel(this.BannerLevel);
		}

		// Token: 0x060000C1 RID: 193 RVA: 0x000041E4 File Offset: 0x000023E4
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			this.BannerLevel = ((node.Attributes["banner_level"] != null) ? int.Parse(node.Attributes["banner_level"].Value) : 1);
			this.BannerEffect = MBObjectManager.Instance.GetObject<BannerEffect>(node.Attributes["effect"].Value);
		}

		// Token: 0x060000C2 RID: 194 RVA: 0x00004253 File Offset: 0x00002453
		internal static void AutoGeneratedStaticCollectObjectsBannerComponent(object o, List<object> collectedObjects)
		{
			((BannerComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060000C3 RID: 195 RVA: 0x00004261 File Offset: 0x00002461
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}
	}
}
