using System;
using System.Collections;
using System.Collections.Generic;
using TaleWorlds.Library;

namespace TaleWorlds.Core
{
	// Token: 0x0200002A RID: 42
	public class EntitySystem<T> where T : class, IEntityComponent
	{
		// Token: 0x060002AC RID: 684 RVA: 0x0000BD09 File Offset: 0x00009F09
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x170000CB RID: 203
		// (get) Token: 0x060002AD RID: 685 RVA: 0x0000BD0B File Offset: 0x00009F0B
		public MBReadOnlyList<T> Components
		{
			get
			{
				return this._components;
			}
		}

		// Token: 0x060002AE RID: 686 RVA: 0x0000BD13 File Offset: 0x00009F13
		public EntitySystem()
		{
			this._components = new MBList<T>();
			this._componentsOfTypes = new Dictionary<Type, IList>();
		}

		// Token: 0x060002AF RID: 687 RVA: 0x0000BD31 File Offset: 0x00009F31
		public TComponent AddComponent<TComponent>() where TComponent : class, T, new()
		{
			return this.AddComponent(typeof(TComponent)) as TComponent;
		}

		// Token: 0x060002B0 RID: 688 RVA: 0x0000BD54 File Offset: 0x00009F54
		public T AddComponent(Type componentType)
		{
			T t = componentType.GetConstructor(Type.EmptyTypes).Invoke(new object[0]) as T;
			this._components.Add(t);
			Type type = t.GetType();
			while (type != null && type != typeof(object))
			{
				if (!this._componentsOfTypes.ContainsKey(type))
				{
					IList list = Activator.CreateInstance(typeof(List<>).MakeGenericType(new Type[] { type })) as IList;
					this._componentsOfTypes.Add(type, list);
				}
				this._componentsOfTypes[type].Add(t);
				type = type.BaseType;
			}
			t.OnInitialize();
			return t;
		}

		// Token: 0x060002B1 RID: 689 RVA: 0x0000BE24 File Offset: 0x0000A024
		public TComponent GetComponent<TComponent>() where TComponent : class, T
		{
			if (this._componentsOfTypes.ContainsKey(typeof(TComponent)))
			{
				IList list = this._componentsOfTypes[typeof(TComponent)];
				if (list.Count > 0)
				{
					return list[0] as TComponent;
				}
			}
			return default(TComponent);
		}

		// Token: 0x060002B2 RID: 690 RVA: 0x0000BE84 File Offset: 0x0000A084
		public T GetComponent(Type componentType)
		{
			if (this._componentsOfTypes.ContainsKey(componentType))
			{
				IList list = this._componentsOfTypes[componentType];
				if (list.Count > 0)
				{
					return list[0] as T;
				}
			}
			return default(T);
		}

		// Token: 0x060002B3 RID: 691 RVA: 0x0000BED0 File Offset: 0x0000A0D0
		public List<TComponent> GetComponents<TComponent>() where TComponent : T
		{
			if (this._componentsOfTypes.ContainsKey(typeof(TComponent)))
			{
				IList list = this._componentsOfTypes[typeof(TComponent)];
				if (list.Count > 0)
				{
					return list as List<TComponent>;
				}
			}
			return new List<TComponent>();
		}

		// Token: 0x060002B4 RID: 692 RVA: 0x0000BF1F File Offset: 0x0000A11F
		public MBList<T> GetComponents()
		{
			return this._components;
		}

		// Token: 0x060002B5 RID: 693 RVA: 0x0000BF27 File Offset: 0x0000A127
		public void Finalize(T component)
		{
			component.OnFinalize();
		}

		// Token: 0x060002B6 RID: 694 RVA: 0x0000BF34 File Offset: 0x0000A134
		public void RemoveComponent(T component)
		{
			component.OnFinalize();
			this._components.Remove(component);
			Type type = component.GetType();
			while (type != null && type != typeof(object))
			{
				this._componentsOfTypes[type].Remove(component);
				type = type.BaseType;
			}
		}

		// Token: 0x060002B7 RID: 695 RVA: 0x0000BFA0 File Offset: 0x0000A1A0
		public void RemoveComponent<TComponent>() where TComponent : class, T
		{
			TComponent component = this.GetComponent<TComponent>();
			if (component != null)
			{
				this.RemoveComponent((T)((object)component));
			}
		}

		// Token: 0x060002B8 RID: 696 RVA: 0x0000BFCD File Offset: 0x0000A1CD
		public void SortComponents<TComponent>(Comparison<T> comparison) where TComponent : class, T
		{
			this._components.Sort(comparison);
		}

		// Token: 0x040001CA RID: 458
		private readonly MBList<T> _components;

		// Token: 0x040001CB RID: 459
		private readonly Dictionary<Type, IList> _componentsOfTypes;
	}
}
