using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.Library;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
	// Token: 0x02000038 RID: 56
	public class PropertyOwnerF<T> : IReadOnlyPropertyOwnerF<T> where T : MBObjectBase
	{
		// Token: 0x06000433 RID: 1075 RVA: 0x000100D8 File Offset: 0x0000E2D8
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._attributes);
		}

		// Token: 0x06000434 RID: 1076 RVA: 0x000100E6 File Offset: 0x0000E2E6
		public PropertyOwnerF()
		{
			this._attributes = new Dictionary<T, float>();
		}

		// Token: 0x06000435 RID: 1077 RVA: 0x000100F9 File Offset: 0x0000E2F9
		public PropertyOwnerF(PropertyOwnerF<T> propertyOwner)
		{
			this._attributes = new Dictionary<T, float>(propertyOwner._attributes);
		}

		// Token: 0x06000436 RID: 1078 RVA: 0x00010112 File Offset: 0x0000E312
		public void SetPropertyValue(T attribute, float value)
		{
			if (!value.ApproximatelyEqualsTo(0f, 1E-05f))
			{
				this._attributes[attribute] = value;
				return;
			}
			if (this.HasProperty(attribute))
			{
				this._attributes.Remove(attribute);
			}
		}

		// Token: 0x06000437 RID: 1079 RVA: 0x0001014C File Offset: 0x0000E34C
		public float GetPropertyValue(T attribute)
		{
			if (attribute == null)
			{
				Debug.FailedAssert("attribute in GetPropertyValue can not be null!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\PropertyOwner.cs", "GetPropertyValue", 144);
				return 0f;
			}
			float num;
			if (!this._attributes.TryGetValue(attribute, out num))
			{
				return 0f;
			}
			return num;
		}

		// Token: 0x06000438 RID: 1080 RVA: 0x00010197 File Offset: 0x0000E397
		public bool HasProperty(T attribute)
		{
			return this._attributes.ContainsKey(attribute);
		}

		// Token: 0x06000439 RID: 1081 RVA: 0x000101A5 File Offset: 0x0000E3A5
		public void ClearAllProperty()
		{
			this._attributes.Clear();
		}

		// Token: 0x0600043A RID: 1082 RVA: 0x000101B2 File Offset: 0x0000E3B2
		public MBList<T> GetProperties()
		{
			return this._attributes.Keys.ToMBList<T>();
		}

		// Token: 0x0600043B RID: 1083 RVA: 0x000101C4 File Offset: 0x0000E3C4
		public void Serialize(XmlWriter writer)
		{
			writer.WriteStartElement("attributes");
			foreach (KeyValuePair<T, float> keyValuePair in this._attributes)
			{
				writer.WriteStartElement("attribute");
				writer.WriteAttributeString("id", keyValuePair.Key.StringId);
				writer.WriteAttributeString("value", keyValuePair.Value.ToString());
				writer.WriteEndElement();
			}
			writer.WriteEndElement();
		}

		// Token: 0x0600043C RID: 1084 RVA: 0x00010268 File Offset: 0x0000E468
		public void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			foreach (object obj in node.ChildNodes)
			{
				XmlNode xmlNode = (XmlNode)obj;
				if (xmlNode.NodeType != XmlNodeType.Comment)
				{
					XmlAttributeCollection attributes = xmlNode.Attributes;
					string value = attributes["id"].Value;
					string value2 = attributes["value"].Value;
					T @object = Game.Current.ObjectManager.GetObject<T>(value);
					if (@object != null)
					{
						float num = Convert.ToSingle(value2);
						this.SetPropertyValue(@object, num);
					}
				}
			}
		}

		// Token: 0x0400022D RID: 557
		[SaveableField(10)]
		protected Dictionary<T, float> _attributes;
	}
}
