using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.Core
{
	// Token: 0x0200003F RID: 63
	public class ShipHull : MBObjectBase
	{
		// Token: 0x060004F9 RID: 1273 RVA: 0x00012032 File Offset: 0x00010232
		internal static void AutoGeneratedStaticCollectObjectsShipHull(object o, List<object> collectedObjects)
		{
			((ShipHull)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060004FA RID: 1274 RVA: 0x00012040 File Offset: 0x00010240
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x170001B0 RID: 432
		// (get) Token: 0x060004FB RID: 1275 RVA: 0x00012049 File Offset: 0x00010249
		// (set) Token: 0x060004FC RID: 1276 RVA: 0x00012051 File Offset: 0x00010251
		public TextObject Name { get; private set; }

		// Token: 0x170001B1 RID: 433
		// (get) Token: 0x060004FD RID: 1277 RVA: 0x0001205A File Offset: 0x0001025A
		// (set) Token: 0x060004FE RID: 1278 RVA: 0x00012062 File Offset: 0x00010262
		public TextObject Description { get; private set; }

		// Token: 0x060004FF RID: 1279 RVA: 0x0001206B File Offset: 0x0001026B
		public override string ToString()
		{
			return this.Name.ToString();
		}

		// Token: 0x06000500 RID: 1280 RVA: 0x00012078 File Offset: 0x00010278
		public override TextObject GetName()
		{
			return this.Name;
		}

		// Token: 0x170001B2 RID: 434
		// (get) Token: 0x06000501 RID: 1281 RVA: 0x00012080 File Offset: 0x00010280
		public string EncyclopediaLink
		{
			get
			{
				return typeof(ShipHull).ToString() + "-" + base.StringId;
			}
		}

		// Token: 0x170001B3 RID: 435
		// (get) Token: 0x06000502 RID: 1282 RVA: 0x000120A1 File Offset: 0x000102A1
		public TextObject EncyclopediaLinkWithName
		{
			get
			{
				return HyperlinkTexts.GetShipHyperlinkText(this.EncyclopediaLink, this.Name);
			}
		}

		// Token: 0x170001B4 RID: 436
		// (get) Token: 0x06000503 RID: 1283 RVA: 0x000120B4 File Offset: 0x000102B4
		// (set) Token: 0x06000504 RID: 1284 RVA: 0x000120BC File Offset: 0x000102BC
		public float BaseSpeed { get; private set; }

		// Token: 0x170001B5 RID: 437
		// (get) Token: 0x06000505 RID: 1285 RVA: 0x000120C5 File Offset: 0x000102C5
		// (set) Token: 0x06000506 RID: 1286 RVA: 0x000120CD File Offset: 0x000102CD
		public int Value { get; private set; }

		// Token: 0x170001B6 RID: 438
		// (get) Token: 0x06000507 RID: 1287 RVA: 0x000120D6 File Offset: 0x000102D6
		// (set) Token: 0x06000508 RID: 1288 RVA: 0x000120DE File Offset: 0x000102DE
		public bool HasHold { get; private set; }

		// Token: 0x170001B7 RID: 439
		// (get) Token: 0x06000509 RID: 1289 RVA: 0x000120E7 File Offset: 0x000102E7
		// (set) Token: 0x0600050A RID: 1290 RVA: 0x000120EF File Offset: 0x000102EF
		public bool CanNavigateShallowWater { get; private set; }

		// Token: 0x170001B8 RID: 440
		// (get) Token: 0x0600050B RID: 1291 RVA: 0x000120F8 File Offset: 0x000102F8
		// (set) Token: 0x0600050C RID: 1292 RVA: 0x00012100 File Offset: 0x00010300
		public bool CanEquipFigurehead { get; private set; }

		// Token: 0x170001B9 RID: 441
		// (get) Token: 0x0600050D RID: 1293 RVA: 0x00012109 File Offset: 0x00010309
		// (set) Token: 0x0600050E RID: 1294 RVA: 0x00012111 File Offset: 0x00010311
		public float ProductionBuildWeight { get; private set; }

		// Token: 0x170001BA RID: 442
		// (get) Token: 0x0600050F RID: 1295 RVA: 0x0001211A File Offset: 0x0001031A
		// (set) Token: 0x06000510 RID: 1296 RVA: 0x00012122 File Offset: 0x00010322
		public int SeaWorthiness { get; private set; }

		// Token: 0x170001BB RID: 443
		// (get) Token: 0x06000511 RID: 1297 RVA: 0x0001212B File Offset: 0x0001032B
		// (set) Token: 0x06000512 RID: 1298 RVA: 0x00012133 File Offset: 0x00010333
		public ShipHull.ShipType Type { get; private set; }

		// Token: 0x170001BC RID: 444
		// (get) Token: 0x06000513 RID: 1299 RVA: 0x0001213C File Offset: 0x0001033C
		// (set) Token: 0x06000514 RID: 1300 RVA: 0x00012144 File Offset: 0x00010344
		public bool IsTradeShip { get; private set; }

		// Token: 0x170001BD RID: 445
		// (get) Token: 0x06000515 RID: 1301 RVA: 0x0001214D File Offset: 0x0001034D
		// (set) Token: 0x06000516 RID: 1302 RVA: 0x00012155 File Offset: 0x00010355
		public string MissionShipObjectId { get; private set; }

		// Token: 0x170001BE RID: 446
		// (get) Token: 0x06000517 RID: 1303 RVA: 0x0001215E File Offset: 0x0001035E
		// (set) Token: 0x06000518 RID: 1304 RVA: 0x00012166 File Offset: 0x00010366
		public int DefaultFormationGroup { get; private set; }

		// Token: 0x170001BF RID: 447
		// (get) Token: 0x06000519 RID: 1305 RVA: 0x0001216F File Offset: 0x0001036F
		// (set) Token: 0x0600051A RID: 1306 RVA: 0x00012177 File Offset: 0x00010377
		public int InventoryCapacity { get; private set; }

		// Token: 0x170001C0 RID: 448
		// (get) Token: 0x0600051B RID: 1307 RVA: 0x00012180 File Offset: 0x00010380
		// (set) Token: 0x0600051C RID: 1308 RVA: 0x00012188 File Offset: 0x00010388
		public int MaxHitPoints { get; private set; }

		// Token: 0x170001C1 RID: 449
		// (get) Token: 0x0600051D RID: 1309 RVA: 0x00012191 File Offset: 0x00010391
		// (set) Token: 0x0600051E RID: 1310 RVA: 0x00012199 File Offset: 0x00010399
		public int MaxFireHitPoints { get; private set; }

		// Token: 0x170001C2 RID: 450
		// (get) Token: 0x0600051F RID: 1311 RVA: 0x000121A2 File Offset: 0x000103A2
		// (set) Token: 0x06000520 RID: 1312 RVA: 0x000121AA File Offset: 0x000103AA
		public int MaxSailHitPoints { get; private set; }

		// Token: 0x170001C3 RID: 451
		// (get) Token: 0x06000521 RID: 1313 RVA: 0x000121B3 File Offset: 0x000103B3
		// (set) Token: 0x06000522 RID: 1314 RVA: 0x000121BB File Offset: 0x000103BB
		public int TotalCrewCapacity { get; private set; }

		// Token: 0x170001C4 RID: 452
		// (get) Token: 0x06000523 RID: 1315 RVA: 0x000121C4 File Offset: 0x000103C4
		// (set) Token: 0x06000524 RID: 1316 RVA: 0x000121CC File Offset: 0x000103CC
		public int MainDeckCrewCapacity { get; private set; }

		// Token: 0x170001C5 RID: 453
		// (get) Token: 0x06000525 RID: 1317 RVA: 0x000121D5 File Offset: 0x000103D5
		// (set) Token: 0x06000526 RID: 1318 RVA: 0x000121DD File Offset: 0x000103DD
		public int SkeletalCrewCapacity { get; private set; }

		// Token: 0x170001C6 RID: 454
		// (get) Token: 0x06000527 RID: 1319 RVA: 0x000121E6 File Offset: 0x000103E6
		// (set) Token: 0x06000528 RID: 1320 RVA: 0x000121EE File Offset: 0x000103EE
		public float MapVisualScale { get; private set; }

		// Token: 0x06000529 RID: 1321 RVA: 0x000121F8 File Offset: 0x000103F8
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			this.Name = new TextObject(node.Attributes["name"].Value, null);
			this.Description = new TextObject(node.Attributes["description"].Value, null);
			float num;
			float.TryParse(node.Attributes["base_speed"].Value, out num);
			this.BaseSpeed = num;
			XmlAttribute xmlAttribute = node.Attributes["has_hold"];
			this.HasHold = bool.Parse(xmlAttribute.Value);
			XmlAttribute xmlAttribute2 = node.Attributes["value"];
			this.Value = Convert.ToInt32(xmlAttribute2.Value);
			XmlAttribute xmlAttribute3 = node.Attributes["is_trade_ship"];
			this.IsTradeShip = bool.Parse(xmlAttribute3.Value);
			XmlAttribute xmlAttribute4 = node.Attributes["can_navigate_shallow_water"];
			this.CanNavigateShallowWater = bool.Parse(xmlAttribute4.Value);
			XmlAttribute xmlAttribute5 = node.Attributes["can_equip_figurehead"];
			this.CanEquipFigurehead = bool.Parse(xmlAttribute5.Value);
			this.SeaWorthiness = Convert.ToInt32(node.Attributes["sea_worthiness"].Value);
			this.Type = (ShipHull.ShipType)Enum.Parse(typeof(ShipHull.ShipType), node.Attributes["ship_type"].InnerText, true);
			this.ProductionBuildWeight = Convert.ToSingle(node.Attributes["production_build_weight"].Value);
			Dictionary<string, ShipSlot> dictionary = new Dictionary<string, ShipSlot>();
			this.InventoryCapacity = Convert.ToInt32(node.Attributes["inventory_capacity"].Value);
			this.MapVisualScale = Convert.ToSingle(node.Attributes["map_visual_scale"].Value);
			bool flag = false;
			this.MaxHitPoints = this.DeserializeScalarAttribute<int>(node, "max_hitpoints", true, out flag);
			this.MaxFireHitPoints = this.DeserializeScalarAttribute<int>(node, "max_fire_hitpoints", true, out flag);
			this.MaxSailHitPoints = this.DeserializeScalarAttribute<int>(node, "max_sail_hitpoints", true, out flag);
			this.TotalCrewCapacity = this.DeserializeScalarAttribute<int>(node, "total_crew_capacity", true, out flag);
			this.MainDeckCrewCapacity = this.DeserializeScalarAttribute<int>(node, "main_deck_crew_capacity", true, out flag);
			this.SkeletalCrewCapacity = this.DeserializeScalarAttribute<int>(node, "skeletal_crew_capacity", true, out flag);
			foreach (object obj in node.ChildNodes)
			{
				XmlNode xmlNode = (XmlNode)obj;
				if (xmlNode.Name == "AvailableSlots")
				{
					foreach (object obj2 in xmlNode.ChildNodes)
					{
						XmlNode xmlNode2 = (XmlNode)obj2;
						string value = xmlNode2.Attributes["id"].Value;
						string value2 = xmlNode2.Attributes["tag_id"].Value;
						ShipSlot @object = MBObjectManager.Instance.GetObject<ShipSlot>(value);
						if (@object != null)
						{
							dictionary.Add(value2, @object);
						}
						else
						{
							Debug.FailedAssert("ShipSlot does not exist! Ship slot id: " + value + "\nShip slot cannot be added!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\NavalCore\\ShipHull.cs", "Deserialize", 147);
						}
					}
				}
			}
			this.AvailableSlots = dictionary.GetReadOnlyDictionary<string, ShipSlot>();
			XmlAttribute xmlAttribute6 = node.Attributes["mission_ship"];
			this.MissionShipObjectId = xmlAttribute6.Value;
			XmlNode xmlNode3 = node.Attributes["default_group"];
			this.DefaultFormationGroup = ((xmlNode3 != null) ? this.FetchDefaultFormationGroup(xmlNode3.InnerText) : 0);
		}

		// Token: 0x0600052A RID: 1322 RVA: 0x000125D8 File Offset: 0x000107D8
		private int FetchDefaultFormationGroup(string innerText)
		{
			FormationClass formationClass;
			if (Enum.TryParse<FormationClass>(innerText, true, out formationClass))
			{
				return (int)formationClass;
			}
			return -1;
		}

		// Token: 0x0600052B RID: 1323 RVA: 0x000125F4 File Offset: 0x000107F4
		private T DeserializeScalarAttribute<T>(XmlNode node, string attributeName, bool isRequiredAttribute, out bool isAttributeValid)
		{
			XmlAttribute xmlAttribute = node.Attributes[attributeName];
			isAttributeValid = xmlAttribute != null && !string.IsNullOrEmpty(xmlAttribute.InnerText);
			if (isAttributeValid)
			{
				return (T)((object)Convert.ChangeType(xmlAttribute.Value, typeof(T)));
			}
			return default(T);
		}

		// Token: 0x0400026E RID: 622
		public MBReadOnlyDictionary<string, ShipSlot> AvailableSlots;

		// Token: 0x02000108 RID: 264
		public enum ShipType
		{
			// Token: 0x0400075E RID: 1886
			Light,
			// Token: 0x0400075F RID: 1887
			Medium,
			// Token: 0x04000760 RID: 1888
			Heavy
		}
	}
}
