using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
	// Token: 0x02000027 RID: 39
	public class WeaponDesign
	{
		// Token: 0x0600021E RID: 542 RVA: 0x0000A3E4 File Offset: 0x000085E4
		internal static void AutoGeneratedStaticCollectObjectsWeaponDesign(object o, List<object> collectedObjects)
		{
			((WeaponDesign)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600021F RID: 543 RVA: 0x0000A3F4 File Offset: 0x000085F4
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this.Template);
			collectedObjects.Add(this.TopPivotOffsets);
			collectedObjects.Add(this.BottomPivotOffsets);
			collectedObjects.Add(this._usedPieces);
			collectedObjects.Add(this._piecePivotDistances);
			collectedObjects.Add(this.WeaponName);
		}

		// Token: 0x06000220 RID: 544 RVA: 0x0000A449 File Offset: 0x00008649
		internal static object AutoGeneratedGetMemberValueWeaponName(object o)
		{
			return ((WeaponDesign)o).WeaponName;
		}

		// Token: 0x06000221 RID: 545 RVA: 0x0000A456 File Offset: 0x00008656
		internal static object AutoGeneratedGetMemberValueHandToBottomLength(object o)
		{
			return ((WeaponDesign)o).HandToBottomLength;
		}

		// Token: 0x06000222 RID: 546 RVA: 0x0000A468 File Offset: 0x00008668
		internal static object AutoGeneratedGetMemberValueWeaponFlags(object o)
		{
			return ((WeaponDesign)o).WeaponFlags;
		}

		// Token: 0x06000223 RID: 547 RVA: 0x0000A47A File Offset: 0x0000867A
		internal static object AutoGeneratedGetMemberValueCraftedWeaponLength(object o)
		{
			return ((WeaponDesign)o).CraftedWeaponLength;
		}

		// Token: 0x06000224 RID: 548 RVA: 0x0000A48C File Offset: 0x0000868C
		internal static object AutoGeneratedGetMemberValueTemplate(object o)
		{
			return ((WeaponDesign)o).Template;
		}

		// Token: 0x06000225 RID: 549 RVA: 0x0000A499 File Offset: 0x00008699
		internal static object AutoGeneratedGetMemberValueTopPivotOffsets(object o)
		{
			return ((WeaponDesign)o).TopPivotOffsets;
		}

		// Token: 0x06000226 RID: 550 RVA: 0x0000A4A6 File Offset: 0x000086A6
		internal static object AutoGeneratedGetMemberValueBottomPivotOffsets(object o)
		{
			return ((WeaponDesign)o).BottomPivotOffsets;
		}

		// Token: 0x06000227 RID: 551 RVA: 0x0000A4B3 File Offset: 0x000086B3
		internal static object AutoGeneratedGetMemberValueHolsterShiftAmount(object o)
		{
			return ((WeaponDesign)o).HolsterShiftAmount;
		}

		// Token: 0x06000228 RID: 552 RVA: 0x0000A4C5 File Offset: 0x000086C5
		internal static object AutoGeneratedGetMemberValue_usedPieces(object o)
		{
			return ((WeaponDesign)o)._usedPieces;
		}

		// Token: 0x06000229 RID: 553 RVA: 0x0000A4D2 File Offset: 0x000086D2
		internal static object AutoGeneratedGetMemberValue_piecePivotDistances(object o)
		{
			return ((WeaponDesign)o)._piecePivotDistances;
		}

		// Token: 0x17000095 RID: 149
		// (get) Token: 0x0600022A RID: 554 RVA: 0x0000A4DF File Offset: 0x000086DF
		// (set) Token: 0x0600022B RID: 555 RVA: 0x0000A4E7 File Offset: 0x000086E7
		[SaveableProperty(21)]
		public TextObject WeaponName { get; private set; }

		// Token: 0x17000096 RID: 150
		// (get) Token: 0x0600022C RID: 556 RVA: 0x0000A4F0 File Offset: 0x000086F0
		public WeaponDesignElement[] UsedPieces
		{
			get
			{
				return this._usedPieces;
			}
		}

		// Token: 0x17000097 RID: 151
		// (get) Token: 0x0600022D RID: 557 RVA: 0x0000A4F8 File Offset: 0x000086F8
		public float[] PiecePivotDistances
		{
			get
			{
				return this._piecePivotDistances;
			}
		}

		// Token: 0x17000098 RID: 152
		// (get) Token: 0x0600022E RID: 558 RVA: 0x0000A500 File Offset: 0x00008700
		public float TotalLength
		{
			get
			{
				return this.CraftedWeaponLength + this.HandToBottomLength;
			}
		}

		// Token: 0x17000099 RID: 153
		// (get) Token: 0x0600022F RID: 559 RVA: 0x0000A50F File Offset: 0x0000870F
		// (set) Token: 0x06000230 RID: 560 RVA: 0x0000A517 File Offset: 0x00008717
		[SaveableProperty(50)]
		public float HandToBottomLength { get; private set; }

		// Token: 0x1700009A RID: 154
		// (get) Token: 0x06000231 RID: 561 RVA: 0x0000A520 File Offset: 0x00008720
		// (set) Token: 0x06000232 RID: 562 RVA: 0x0000A528 File Offset: 0x00008728
		public string HashedCode
		{
			get
			{
				return this._hashedCode;
			}
			private set
			{
				this._hashedCode = value;
				this._cachedHashedCodeInt = Common.GetDJB2(this._hashedCode);
			}
		}

		// Token: 0x1700009B RID: 155
		// (get) Token: 0x06000233 RID: 563 RVA: 0x0000A542 File Offset: 0x00008742
		public float BottomPivotOffset
		{
			get
			{
				return this.BottomPivotOffsets[this.BottomPivotOffsets.Count - 1];
			}
		}

		// Token: 0x06000234 RID: 564 RVA: 0x0000A55C File Offset: 0x0000875C
		public WeaponDesign(CraftingTemplate template, TextObject weaponName, WeaponDesignElement[] usedPieces, string customId = null)
		{
			this.Template = template;
			this._usedPieces = usedPieces.ToArray<WeaponDesignElement>();
			this.WeaponName = weaponName;
			this._piecePivotDistances = new float[usedPieces.Length];
			this.CalculatePivotDistances();
			this.CraftedWeaponLength = this.CalculateWeaponLength();
			this.HolsterShiftAmount = this.CalculateHolsterShiftAmount();
			foreach (WeaponDesignElement weaponDesignElement in usedPieces)
			{
				this.WeaponFlags |= weaponDesignElement.CraftingPiece.AdditionalWeaponFlags;
			}
			if (!string.IsNullOrEmpty(customId))
			{
				this.HashedCode = customId;
			}
		}

		// Token: 0x06000235 RID: 565 RVA: 0x0000A5F4 File Offset: 0x000087F4
		private void CalculatePivotDistances()
		{
			float num = 0f;
			float num2 = 0f;
			foreach (PieceData pieceData in this.Template.BuildOrders)
			{
				WeaponDesignElement weaponDesignElement = this.UsedPieces[(int)pieceData.PieceType];
				if (weaponDesignElement == null || !weaponDesignElement.IsValid)
				{
					this._piecePivotDistances[(int)pieceData.PieceType] = float.NaN;
				}
				else
				{
					int num3 = MathF.Sign(pieceData.Order);
					if (num3 == 0)
					{
						num2 += weaponDesignElement.ScaledPieceOffset;
						num -= weaponDesignElement.ScaledPieceOffset;
					}
					else if (num3 < 0)
					{
						num += weaponDesignElement.ScaledDistanceToNextPiece;
						num += weaponDesignElement.ScaledPieceOffset;
						num -= weaponDesignElement.ScaledNextPieceOffset;
					}
					else if (num3 > 0)
					{
						num2 += weaponDesignElement.ScaledDistanceToPreviousPiece;
						num2 += weaponDesignElement.ScaledPieceOffset;
						num2 -= weaponDesignElement.ScaledPreviousPieceOffset;
					}
					this._piecePivotDistances[(int)pieceData.PieceType] = (float)num3 * ((num3 < 0) ? num : num2) + ((num3 == 0) ? weaponDesignElement.ScaledPieceOffset : 0f);
					this.AddTopPivotOffset(num2);
					this.AddBottomPivotOffset(num);
					if (num3 == 0)
					{
						num += weaponDesignElement.ScaledDistanceToPreviousPiece - weaponDesignElement.ScaledPreviousPieceOffset;
						num2 += weaponDesignElement.ScaledDistanceToNextPiece - weaponDesignElement.ScaledNextPieceOffset;
					}
					if (num3 < 0)
					{
						num += weaponDesignElement.ScaledDistanceToPreviousPiece - weaponDesignElement.ScaledPreviousPieceOffset;
					}
					if (num3 > 0)
					{
						num2 += weaponDesignElement.ScaledDistanceToNextPiece - weaponDesignElement.ScaledNextPieceOffset;
					}
				}
			}
			this.AddTopPivotOffset(num2);
			this.AddBottomPivotOffset(num);
			this.HandToBottomLength = num;
		}

		// Token: 0x06000236 RID: 566 RVA: 0x0000A784 File Offset: 0x00008984
		public override bool Equals(object obj)
		{
			if (obj == null)
			{
				return false;
			}
			WeaponDesign weaponDesign = obj as WeaponDesign;
			return weaponDesign != null && this.HashedCode == weaponDesign.HashedCode;
		}

		// Token: 0x06000237 RID: 567 RVA: 0x0000A7B3 File Offset: 0x000089B3
		public override int GetHashCode()
		{
			return this._cachedHashedCodeInt;
		}

		// Token: 0x06000238 RID: 568 RVA: 0x0000A7BB File Offset: 0x000089BB
		public void SetWeaponName(TextObject name)
		{
			this.WeaponName = name;
		}

		// Token: 0x06000239 RID: 569 RVA: 0x0000A7C4 File Offset: 0x000089C4
		public static bool operator ==(WeaponDesign x, WeaponDesign y)
		{
			bool flag = x == null;
			bool flag2 = y == null;
			return (flag && flag2) || (!flag && x.Equals(y));
		}

		// Token: 0x0600023A RID: 570 RVA: 0x0000A7EE File Offset: 0x000089EE
		public static bool operator !=(WeaponDesign x, WeaponDesign y)
		{
			return !(x == y);
		}

		// Token: 0x0600023B RID: 571 RVA: 0x0000A7FA File Offset: 0x000089FA
		private void AddTopPivotOffset(float offset)
		{
			if (this.TopPivotOffsets == null)
			{
				this.TopPivotOffsets = new List<float>();
			}
			this.TopPivotOffsets.Add(offset);
		}

		// Token: 0x0600023C RID: 572 RVA: 0x0000A81B File Offset: 0x00008A1B
		private void AddBottomPivotOffset(float offset)
		{
			if (this.BottomPivotOffsets == null)
			{
				this.BottomPivotOffsets = new List<float>();
			}
			this.BottomPivotOffsets.Add(offset);
		}

		// Token: 0x0600023D RID: 573 RVA: 0x0000A83C File Offset: 0x00008A3C
		private Vec3 CalculateHolsterShiftAmount()
		{
			WeaponDesignElement weaponDesignElement = this.UsedPieces[2];
			Vec3 vec = (this.Template.ItemHolsterPositionShift + weaponDesignElement.CraftingPiece.ItemHolsterPosShift) * weaponDesignElement.ScaleFactor;
			if (this.UsedPieces[1] != null)
			{
				vec += Vec3.Up * this.UsedPieces[1].ScaledLength;
			}
			return vec;
		}

		// Token: 0x0600023E RID: 574 RVA: 0x0000A8A4 File Offset: 0x00008AA4
		private float CalculateWeaponLength()
		{
			int num = 0;
			float num2 = this._piecePivotDistances[num] + this._usedPieces[num].ScaledDistanceToNextPiece;
			float num3 = 0f;
			foreach (WeaponDesignElement weaponDesignElement in this._usedPieces)
			{
				if (weaponDesignElement.IsValid && weaponDesignElement.ScaledDistanceToNextPiece > num3)
				{
					float scaledPieceOffset = weaponDesignElement.ScaledPieceOffset;
					num3 = weaponDesignElement.ScaledDistanceToNextPiece + scaledPieceOffset;
				}
			}
			return MathF.Max(num2, num3);
		}

		// Token: 0x0400018B RID: 395
		[SaveableField(10)]
		public readonly WeaponFlags WeaponFlags;

		// Token: 0x0400018D RID: 397
		[SaveableField(30)]
		private readonly WeaponDesignElement[] _usedPieces;

		// Token: 0x0400018E RID: 398
		[CachedData]
		private int _cachedHashedCodeInt;

		// Token: 0x0400018F RID: 399
		[SaveableField(40)]
		private readonly float[] _piecePivotDistances;

		// Token: 0x04000191 RID: 401
		[SaveableField(60)]
		public readonly float CraftedWeaponLength;

		// Token: 0x04000192 RID: 402
		[SaveableField(70)]
		public readonly CraftingTemplate Template;

		// Token: 0x04000193 RID: 403
		[SaveableField(80)]
		public List<float> TopPivotOffsets;

		// Token: 0x04000194 RID: 404
		[SaveableField(90)]
		public List<float> BottomPivotOffsets;

		// Token: 0x04000195 RID: 405
		[SaveableField(100)]
		public readonly Vec3 HolsterShiftAmount;

		// Token: 0x04000196 RID: 406
		private string _hashedCode;
	}
}
