using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.Map.DistanceCache;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements.Buildings;
using TaleWorlds.CampaignSystem.Settlements.Locations;
using TaleWorlds.CampaignSystem.Siege;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;
using TaleWorlds.SaveSystem.Load;

namespace TaleWorlds.CampaignSystem.Settlements
{
	// Token: 0x020003B4 RID: 948
	public sealed class Settlement : MBObjectBase, ILocatable<Settlement>, IMapPoint, ITrackableCampaignObject, ITrackableBase, ISiegeEventSide, IRandomOwner, ISettlementDataHolder
	{
		// Token: 0x0600373E RID: 14142 RVA: 0x000E5770 File Offset: 0x000E3970
		internal static void AutoGeneratedStaticCollectObjectsSettlement(object o, List<object> collectedObjects)
		{
			((Settlement)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600373F RID: 14143 RVA: 0x000E5780 File Offset: 0x000E3980
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Stash);
			collectedObjects.Add(this._nextLocatable);
			collectedObjects.Add(this._settlementWallSectionHitPointsRatioList);
			collectedObjects.Add(this._boundVillages);
			collectedObjects.Add(this._lastAttackerParty);
			collectedObjects.Add(this._siegeEngineMissiles);
			collectedObjects.Add(this.Party);
			collectedObjects.Add(this.SiegeEvent);
			collectedObjects.Add(this.SettlementComponent);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.LastThreatTime, collectedObjects);
			collectedObjects.Add(this.SiegeEngines);
			collectedObjects.Add(this.SiegeStrategy);
			collectedObjects.Add(this.Alleys);
			collectedObjects.Add(this.LocationComplex);
		}

		// Token: 0x06003740 RID: 14144 RVA: 0x000E5841 File Offset: 0x000E3A41
		internal static object AutoGeneratedGetMemberValueParty(object o)
		{
			return ((Settlement)o).Party;
		}

		// Token: 0x06003741 RID: 14145 RVA: 0x000E584E File Offset: 0x000E3A4E
		internal static object AutoGeneratedGetMemberValueBribePaid(object o)
		{
			return ((Settlement)o).BribePaid;
		}

		// Token: 0x06003742 RID: 14146 RVA: 0x000E5860 File Offset: 0x000E3A60
		internal static object AutoGeneratedGetMemberValueSiegeEvent(object o)
		{
			return ((Settlement)o).SiegeEvent;
		}

		// Token: 0x06003743 RID: 14147 RVA: 0x000E586D File Offset: 0x000E3A6D
		internal static object AutoGeneratedGetMemberValueIsActive(object o)
		{
			return ((Settlement)o).IsActive;
		}

		// Token: 0x06003744 RID: 14148 RVA: 0x000E587F File Offset: 0x000E3A7F
		internal static object AutoGeneratedGetMemberValueNearbyLandThreatIntensity(object o)
		{
			return ((Settlement)o).NearbyLandThreatIntensity;
		}

		// Token: 0x06003745 RID: 14149 RVA: 0x000E5891 File Offset: 0x000E3A91
		internal static object AutoGeneratedGetMemberValueNearbyNavalThreatIntensity(object o)
		{
			return ((Settlement)o).NearbyNavalThreatIntensity;
		}

		// Token: 0x06003746 RID: 14150 RVA: 0x000E58A3 File Offset: 0x000E3AA3
		internal static object AutoGeneratedGetMemberValueNearbyLandAllyIntensity(object o)
		{
			return ((Settlement)o).NearbyLandAllyIntensity;
		}

		// Token: 0x06003747 RID: 14151 RVA: 0x000E58B5 File Offset: 0x000E3AB5
		internal static object AutoGeneratedGetMemberValueNearbyNavalAllyIntensity(object o)
		{
			return ((Settlement)o).NearbyNavalAllyIntensity;
		}

		// Token: 0x06003748 RID: 14152 RVA: 0x000E58C7 File Offset: 0x000E3AC7
		internal static object AutoGeneratedGetMemberValueSettlementHitPoints(object o)
		{
			return ((Settlement)o).SettlementHitPoints;
		}

		// Token: 0x06003749 RID: 14153 RVA: 0x000E58D9 File Offset: 0x000E3AD9
		internal static object AutoGeneratedGetMemberValueSettlementComponent(object o)
		{
			return ((Settlement)o).SettlementComponent;
		}

		// Token: 0x0600374A RID: 14154 RVA: 0x000E58E6 File Offset: 0x000E3AE6
		internal static object AutoGeneratedGetMemberValueGarrisonWagePaymentLimit(object o)
		{
			return ((Settlement)o).GarrisonWagePaymentLimit;
		}

		// Token: 0x0600374B RID: 14155 RVA: 0x000E58F8 File Offset: 0x000E3AF8
		internal static object AutoGeneratedGetMemberValueLastThreatTime(object o)
		{
			return ((Settlement)o).LastThreatTime;
		}

		// Token: 0x0600374C RID: 14156 RVA: 0x000E590A File Offset: 0x000E3B0A
		internal static object AutoGeneratedGetMemberValueSiegeEngines(object o)
		{
			return ((Settlement)o).SiegeEngines;
		}

		// Token: 0x0600374D RID: 14157 RVA: 0x000E5917 File Offset: 0x000E3B17
		internal static object AutoGeneratedGetMemberValueNumberOfTroopsKilledOnSide(object o)
		{
			return ((Settlement)o).NumberOfTroopsKilledOnSide;
		}

		// Token: 0x0600374E RID: 14158 RVA: 0x000E5929 File Offset: 0x000E3B29
		internal static object AutoGeneratedGetMemberValueSiegeStrategy(object o)
		{
			return ((Settlement)o).SiegeStrategy;
		}

		// Token: 0x0600374F RID: 14159 RVA: 0x000E5936 File Offset: 0x000E3B36
		internal static object AutoGeneratedGetMemberValueAlleys(object o)
		{
			return ((Settlement)o).Alleys;
		}

		// Token: 0x06003750 RID: 14160 RVA: 0x000E5943 File Offset: 0x000E3B43
		internal static object AutoGeneratedGetMemberValueLocationComplex(object o)
		{
			return ((Settlement)o).LocationComplex;
		}

		// Token: 0x06003751 RID: 14161 RVA: 0x000E5950 File Offset: 0x000E3B50
		internal static object AutoGeneratedGetMemberValueCurrentSiegeState(object o)
		{
			return ((Settlement)o).CurrentSiegeState;
		}

		// Token: 0x06003752 RID: 14162 RVA: 0x000E5962 File Offset: 0x000E3B62
		internal static object AutoGeneratedGetMemberValueHasVisited(object o)
		{
			return ((Settlement)o).HasVisited;
		}

		// Token: 0x06003753 RID: 14163 RVA: 0x000E5974 File Offset: 0x000E3B74
		internal static object AutoGeneratedGetMemberValueLastVisitTimeOfOwner(object o)
		{
			return ((Settlement)o).LastVisitTimeOfOwner;
		}

		// Token: 0x06003754 RID: 14164 RVA: 0x000E5986 File Offset: 0x000E3B86
		internal static object AutoGeneratedGetMemberValueStash(object o)
		{
			return ((Settlement)o).Stash;
		}

		// Token: 0x06003755 RID: 14165 RVA: 0x000E5993 File Offset: 0x000E3B93
		internal static object AutoGeneratedGetMemberValue_isVisible(object o)
		{
			return ((Settlement)o)._isVisible;
		}

		// Token: 0x06003756 RID: 14166 RVA: 0x000E59A5 File Offset: 0x000E3BA5
		internal static object AutoGeneratedGetMemberValue_nextLocatable(object o)
		{
			return ((Settlement)o)._nextLocatable;
		}

		// Token: 0x06003757 RID: 14167 RVA: 0x000E59B2 File Offset: 0x000E3BB2
		internal static object AutoGeneratedGetMemberValue_readyMilitia(object o)
		{
			return ((Settlement)o)._readyMilitia;
		}

		// Token: 0x06003758 RID: 14168 RVA: 0x000E59C4 File Offset: 0x000E3BC4
		internal static object AutoGeneratedGetMemberValue_settlementWallSectionHitPointsRatioList(object o)
		{
			return ((Settlement)o)._settlementWallSectionHitPointsRatioList;
		}

		// Token: 0x06003759 RID: 14169 RVA: 0x000E59D1 File Offset: 0x000E3BD1
		internal static object AutoGeneratedGetMemberValue_boundVillages(object o)
		{
			return ((Settlement)o)._boundVillages;
		}

		// Token: 0x0600375A RID: 14170 RVA: 0x000E59DE File Offset: 0x000E3BDE
		internal static object AutoGeneratedGetMemberValue_lastAttackerParty(object o)
		{
			return ((Settlement)o)._lastAttackerParty;
		}

		// Token: 0x0600375B RID: 14171 RVA: 0x000E59EB File Offset: 0x000E3BEB
		internal static object AutoGeneratedGetMemberValue_siegeEngineMissiles(object o)
		{
			return ((Settlement)o)._siegeEngineMissiles;
		}

		// Token: 0x17000D08 RID: 3336
		// (get) Token: 0x0600375C RID: 14172 RVA: 0x000E59F8 File Offset: 0x000E3BF8
		// (set) Token: 0x0600375D RID: 14173 RVA: 0x000E5A00 File Offset: 0x000E3C00
		[SaveableProperty(101)]
		public PartyBase Party { get; private set; }

		// Token: 0x17000D09 RID: 3337
		// (get) Token: 0x0600375E RID: 14174 RVA: 0x000E5A09 File Offset: 0x000E3C09
		// (set) Token: 0x0600375F RID: 14175 RVA: 0x000E5A11 File Offset: 0x000E3C11
		[SaveableProperty(116)]
		public int BribePaid { get; set; }

		// Token: 0x17000D0A RID: 3338
		// (get) Token: 0x06003760 RID: 14176 RVA: 0x000E5A1A File Offset: 0x000E3C1A
		// (set) Token: 0x06003761 RID: 14177 RVA: 0x000E5A22 File Offset: 0x000E3C22
		[SaveableProperty(111)]
		public SiegeEvent SiegeEvent { get; set; }

		// Token: 0x17000D0B RID: 3339
		// (get) Token: 0x06003762 RID: 14178 RVA: 0x000E5A2B File Offset: 0x000E3C2B
		// (set) Token: 0x06003763 RID: 14179 RVA: 0x000E5A33 File Offset: 0x000E3C33
		[SaveableProperty(112)]
		public bool IsActive { get; set; }

		// Token: 0x17000D0C RID: 3340
		// (get) Token: 0x06003764 RID: 14180 RVA: 0x000E5A3C File Offset: 0x000E3C3C
		public Hero Owner
		{
			get
			{
				return this.OwnerClan.Leader;
			}
		}

		// Token: 0x17000D0D RID: 3341
		// (get) Token: 0x06003765 RID: 14181 RVA: 0x000E5A4C File Offset: 0x000E3C4C
		public Banner Banner
		{
			get
			{
				if (this.Party.CustomBanner != null)
				{
					return this.Party.CustomBanner;
				}
				if (this.SettlementComponent != null && this.SettlementComponent.GetDefaultComponentBanner() != null)
				{
					return this.SettlementComponent.GetDefaultComponentBanner();
				}
				if (this.OwnerClan != null)
				{
					return this.OwnerClan.Banner;
				}
				return null;
			}
		}

		// Token: 0x17000D0E RID: 3342
		// (get) Token: 0x06003766 RID: 14182 RVA: 0x000E5AA8 File Offset: 0x000E3CA8
		// (set) Token: 0x06003767 RID: 14183 RVA: 0x000E5AB0 File Offset: 0x000E3CB0
		public bool IsVisible
		{
			get
			{
				return this._isVisible;
			}
			set
			{
				if (this._isVisible != value)
				{
					this._isVisible = value;
					this.Party.OnVisibilityChanged(value);
				}
			}
		}

		// Token: 0x17000D0F RID: 3343
		// (get) Token: 0x06003768 RID: 14184 RVA: 0x000E5ACE File Offset: 0x000E3CCE
		// (set) Token: 0x06003769 RID: 14185 RVA: 0x000E5AD6 File Offset: 0x000E3CD6
		[CachedData]
		public bool IsInspected { get; set; }

		// Token: 0x17000D10 RID: 3344
		// (get) Token: 0x0600376A RID: 14186 RVA: 0x000E5ADF File Offset: 0x000E3CDF
		public int WallSectionCount
		{
			get
			{
				if (!this.IsFortification)
				{
					return 0;
				}
				return 2;
			}
		}

		// Token: 0x17000D11 RID: 3345
		// (get) Token: 0x0600376B RID: 14187 RVA: 0x000E5AEC File Offset: 0x000E3CEC
		// (set) Token: 0x0600376C RID: 14188 RVA: 0x000E5AF4 File Offset: 0x000E3CF4
		int ILocatable<Settlement>.LocatorNodeIndex
		{
			get
			{
				return this._locatorNodeIndex;
			}
			set
			{
				this._locatorNodeIndex = value;
			}
		}

		// Token: 0x17000D12 RID: 3346
		// (get) Token: 0x0600376D RID: 14189 RVA: 0x000E5AFD File Offset: 0x000E3CFD
		// (set) Token: 0x0600376E RID: 14190 RVA: 0x000E5B05 File Offset: 0x000E3D05
		[SaveableProperty(115)]
		public float NearbyLandThreatIntensity { get; set; }

		// Token: 0x17000D13 RID: 3347
		// (get) Token: 0x0600376F RID: 14191 RVA: 0x000E5B0E File Offset: 0x000E3D0E
		// (set) Token: 0x06003770 RID: 14192 RVA: 0x000E5B16 File Offset: 0x000E3D16
		[SaveableProperty(139)]
		public float NearbyNavalThreatIntensity { get; set; }

		// Token: 0x17000D14 RID: 3348
		// (get) Token: 0x06003771 RID: 14193 RVA: 0x000E5B1F File Offset: 0x000E3D1F
		// (set) Token: 0x06003772 RID: 14194 RVA: 0x000E5B27 File Offset: 0x000E3D27
		[SaveableProperty(128)]
		public float NearbyLandAllyIntensity { get; set; }

		// Token: 0x17000D15 RID: 3349
		// (get) Token: 0x06003773 RID: 14195 RVA: 0x000E5B30 File Offset: 0x000E3D30
		// (set) Token: 0x06003774 RID: 14196 RVA: 0x000E5B38 File Offset: 0x000E3D38
		[SaveableProperty(140)]
		public float NearbyNavalAllyIntensity { get; set; }

		// Token: 0x17000D16 RID: 3350
		// (get) Token: 0x06003775 RID: 14197 RVA: 0x000E5B41 File Offset: 0x000E3D41
		// (set) Token: 0x06003776 RID: 14198 RVA: 0x000E5B49 File Offset: 0x000E3D49
		Settlement ILocatable<Settlement>.NextLocatable
		{
			get
			{
				return this._nextLocatable;
			}
			set
			{
				this._nextLocatable = value;
			}
		}

		// Token: 0x17000D17 RID: 3351
		// (get) Token: 0x06003777 RID: 14199 RVA: 0x000E5B52 File Offset: 0x000E3D52
		public int RandomValue
		{
			get
			{
				return this.Party.RandomValue;
			}
		}

		// Token: 0x17000D18 RID: 3352
		// (get) Token: 0x06003778 RID: 14200 RVA: 0x000E5B60 File Offset: 0x000E3D60
		public Vec2 GetPosition2D
		{
			get
			{
				return this.Position.ToVec2();
			}
		}

		// Token: 0x17000D19 RID: 3353
		// (get) Token: 0x06003779 RID: 14201 RVA: 0x000E5B7B File Offset: 0x000E3D7B
		// (set) Token: 0x0600377A RID: 14202 RVA: 0x000E5BB8 File Offset: 0x000E3DB8
		public float Militia
		{
			get
			{
				return (float)((this.MilitiaPartyComponent != null && this.MilitiaPartyComponent.MobileParty.IsActive) ? this.MilitiaPartyComponent.MobileParty.Party.NumberOfAllMembers : 0) + this._readyMilitia;
			}
			set
			{
				int num = ((this.MilitiaPartyComponent != null && this.MilitiaPartyComponent.MobileParty.IsActive) ? this.MilitiaPartyComponent.MobileParty.Party.NumberOfAllMembers : 0);
				this._readyMilitia = value - (float)num;
				if (this._readyMilitia < (float)(-(float)num))
				{
					this._readyMilitia = (float)(-(float)num);
				}
				if (this._readyMilitia < -1f || this._readyMilitia > 1f)
				{
					if (this.MilitiaPartyComponent != null)
					{
						this.TransferReadyMilitiasToMilitiaParty();
						return;
					}
					this.SpawnMilitiaParty();
				}
			}
		}

		// Token: 0x17000D1A RID: 3354
		// (get) Token: 0x0600377B RID: 14203 RVA: 0x000E5C45 File Offset: 0x000E3E45
		public MBReadOnlyList<float> SettlementWallSectionHitPointsRatioList
		{
			get
			{
				return this._settlementWallSectionHitPointsRatioList;
			}
		}

		// Token: 0x17000D1B RID: 3355
		// (get) Token: 0x0600377C RID: 14204 RVA: 0x000E5C50 File Offset: 0x000E3E50
		public float SettlementTotalWallHitPoints
		{
			get
			{
				float num = 0f;
				foreach (float num2 in this._settlementWallSectionHitPointsRatioList)
				{
					num += num2;
				}
				return num * this.MaxHitPointsOfOneWallSection;
			}
		}

		// Token: 0x17000D1C RID: 3356
		// (get) Token: 0x0600377D RID: 14205 RVA: 0x000E5CB0 File Offset: 0x000E3EB0
		public float MaxHitPointsOfOneWallSection
		{
			get
			{
				if (this.WallSectionCount == 0)
				{
					return 0f;
				}
				return this.MaxWallHitPoints / (float)this.WallSectionCount;
			}
		}

		// Token: 0x0600377E RID: 14206 RVA: 0x000E5CD0 File Offset: 0x000E3ED0
		public void SetWallSectionHitPointsRatioAtIndex(int index, float hitPointsRatio)
		{
			float num = this._settlementWallSectionHitPointsRatioList[index];
			this._settlementWallSectionHitPointsRatioList[index] = MBMath.ClampFloat(hitPointsRatio, 0f, 1f);
			if (num <= 0f && this._settlementWallSectionHitPointsRatioList[index] > 0f)
			{
				this.Party.SetVisualAsDirty();
			}
		}

		// Token: 0x17000D1D RID: 3357
		// (get) Token: 0x0600377F RID: 14207 RVA: 0x000E5D2A File Offset: 0x000E3F2A
		// (set) Token: 0x06003780 RID: 14208 RVA: 0x000E5D32 File Offset: 0x000E3F32
		[SaveableProperty(121)]
		public float SettlementHitPoints { get; internal set; }

		// Token: 0x17000D1E RID: 3358
		// (get) Token: 0x06003781 RID: 14209 RVA: 0x000E5D3B File Offset: 0x000E3F3B
		public float MaxWallHitPoints
		{
			get
			{
				return Campaign.Current.Models.WallHitPointCalculationModel.CalculateMaximumWallHitPoint(this.Town);
			}
		}

		// Token: 0x17000D1F RID: 3359
		// (get) Token: 0x06003782 RID: 14210 RVA: 0x000E5D57 File Offset: 0x000E3F57
		public MBReadOnlyList<MobileParty> Parties
		{
			get
			{
				return this._partiesCache;
			}
		}

		// Token: 0x17000D20 RID: 3360
		// (get) Token: 0x06003783 RID: 14211 RVA: 0x000E5D5F File Offset: 0x000E3F5F
		// (set) Token: 0x06003784 RID: 14212 RVA: 0x000E5D67 File Offset: 0x000E3F67
		public PatrolPartyComponent PatrolParty { get; private set; }

		// Token: 0x17000D21 RID: 3361
		// (get) Token: 0x06003785 RID: 14213 RVA: 0x000E5D70 File Offset: 0x000E3F70
		public MBReadOnlyList<Hero> HeroesWithoutParty
		{
			get
			{
				return this._heroesWithoutPartyCache;
			}
		}

		// Token: 0x17000D22 RID: 3362
		// (get) Token: 0x06003786 RID: 14214 RVA: 0x000E5D78 File Offset: 0x000E3F78
		public MBReadOnlyList<Hero> Notables
		{
			get
			{
				return this._notablesCache;
			}
		}

		// Token: 0x17000D23 RID: 3363
		// (get) Token: 0x06003787 RID: 14215 RVA: 0x000E5D80 File Offset: 0x000E3F80
		// (set) Token: 0x06003788 RID: 14216 RVA: 0x000E5D88 File Offset: 0x000E3F88
		[SaveableProperty(152)]
		public SettlementComponent SettlementComponent { get; private set; }

		// Token: 0x17000D24 RID: 3364
		// (get) Token: 0x06003789 RID: 14217 RVA: 0x000E5D91 File Offset: 0x000E3F91
		// (set) Token: 0x0600378A RID: 14218 RVA: 0x000E5D99 File Offset: 0x000E3F99
		public CampaignVec2 GatePosition { get; private set; }

		// Token: 0x17000D25 RID: 3365
		// (get) Token: 0x0600378B RID: 14219 RVA: 0x000E5DA2 File Offset: 0x000E3FA2
		// (set) Token: 0x0600378C RID: 14220 RVA: 0x000E5DAA File Offset: 0x000E3FAA
		public CampaignVec2 PortPosition { get; private set; }

		// Token: 0x0600378D RID: 14221 RVA: 0x000E5DB3 File Offset: 0x000E3FB3
		public void SetPortPosition(CampaignVec2 position)
		{
			this.PortPosition = position;
			this.HasPort = position.ToVec2() != Vec2.Zero;
		}

		// Token: 0x17000D26 RID: 3366
		// (get) Token: 0x0600378E RID: 14222 RVA: 0x000E5DD4 File Offset: 0x000E3FD4
		public PathFaceRecord CurrentNavigationFace
		{
			get
			{
				return this.Position.Face;
			}
		}

		// Token: 0x17000D27 RID: 3367
		// (get) Token: 0x0600378F RID: 14223 RVA: 0x000E5DEF File Offset: 0x000E3FEF
		// (set) Token: 0x06003790 RID: 14224 RVA: 0x000E5DF7 File Offset: 0x000E3FF7
		public CampaignVec2 Position
		{
			get
			{
				return this._position;
			}
			private set
			{
				this._position = value;
				Campaign.Current.SettlementLocator.UpdateLocator(this);
			}
		}

		// Token: 0x06003791 RID: 14225 RVA: 0x000E5E14 File Offset: 0x000E4014
		public Vec3 GetPositionAsVec3()
		{
			return this.Position.AsVec3();
		}

		// Token: 0x17000D28 RID: 3368
		// (get) Token: 0x06003792 RID: 14226 RVA: 0x000E5E2F File Offset: 0x000E402F
		// (set) Token: 0x06003793 RID: 14227 RVA: 0x000E5E37 File Offset: 0x000E4037
		public bool HasPort { get; private set; }

		// Token: 0x17000D29 RID: 3369
		// (get) Token: 0x06003794 RID: 14228 RVA: 0x000E5E40 File Offset: 0x000E4040
		public IFaction MapFaction
		{
			get
			{
				SettlementComponent settlementComponent = this.SettlementComponent;
				if (settlementComponent == null)
				{
					return null;
				}
				return settlementComponent.MapFaction;
			}
		}

		// Token: 0x17000D2A RID: 3370
		// (get) Token: 0x06003795 RID: 14229 RVA: 0x000E5E53 File Offset: 0x000E4053
		public TextObject Name
		{
			get
			{
				if (!TextObject.IsNullOrEmpty(this.Party.CustomName))
				{
					return this.Party.CustomName;
				}
				return this._name;
			}
		}

		// Token: 0x17000D2B RID: 3371
		// (get) Token: 0x06003796 RID: 14230 RVA: 0x000E5E79 File Offset: 0x000E4079
		// (set) Token: 0x06003797 RID: 14231 RVA: 0x000E5E81 File Offset: 0x000E4081
		public TextObject EncyclopediaText { get; private set; }

		// Token: 0x17000D2C RID: 3372
		// (get) Token: 0x06003798 RID: 14232 RVA: 0x000E5E8A File Offset: 0x000E408A
		public string EncyclopediaLink
		{
			get
			{
				return (Campaign.Current.EncyclopediaManager.GetIdentifier(typeof(Settlement)) + "-" + base.StringId) ?? "";
			}
		}

		// Token: 0x17000D2D RID: 3373
		// (get) Token: 0x06003799 RID: 14233 RVA: 0x000E5EBE File Offset: 0x000E40BE
		public TextObject EncyclopediaLinkWithName
		{
			get
			{
				return HyperlinkTexts.GetSettlementHyperlinkText(this.EncyclopediaLink, this.Name);
			}
		}

		// Token: 0x17000D2E RID: 3374
		// (get) Token: 0x0600379A RID: 14234 RVA: 0x000E5ED1 File Offset: 0x000E40D1
		// (set) Token: 0x0600379B RID: 14235 RVA: 0x000E5ED9 File Offset: 0x000E40D9
		[SaveableProperty(122)]
		public int GarrisonWagePaymentLimit { get; private set; }

		// Token: 0x0600379C RID: 14236 RVA: 0x000E5EE2 File Offset: 0x000E40E2
		public void SetGarrisonWagePaymentLimit(int limit)
		{
			this.GarrisonWagePaymentLimit = limit;
		}

		// Token: 0x17000D2F RID: 3375
		// (get) Token: 0x0600379D RID: 14237 RVA: 0x000E5EEB File Offset: 0x000E40EB
		public ItemRoster ItemRoster
		{
			get
			{
				return this.Party.ItemRoster;
			}
		}

		// Token: 0x17000D30 RID: 3376
		// (get) Token: 0x0600379E RID: 14238 RVA: 0x000E5EF8 File Offset: 0x000E40F8
		public MBReadOnlyList<Village> BoundVillages
		{
			get
			{
				return this._boundVillages;
			}
		}

		// Token: 0x17000D31 RID: 3377
		// (get) Token: 0x0600379F RID: 14239 RVA: 0x000E5F00 File Offset: 0x000E4100
		// (set) Token: 0x060037A0 RID: 14240 RVA: 0x000E5F08 File Offset: 0x000E4108
		public MobileParty LastAttackerParty
		{
			get
			{
				return this._lastAttackerParty;
			}
			set
			{
				if (this._lastAttackerParty != value)
				{
					this._lastAttackerParty = value;
					if (value != null && (this.IsFortification || this.IsVillage))
					{
						foreach (Settlement settlement in Settlement.All)
						{
							if ((settlement.IsFortification || settlement.IsVillage) && settlement.LastAttackerParty == value)
							{
								settlement.LastAttackerParty = null;
							}
						}
					}
					this._lastAttackerParty = value;
					if (this._lastAttackerParty != null)
					{
						this.LastThreatTime = CampaignTime.Now;
					}
				}
			}
		}

		// Token: 0x17000D32 RID: 3378
		// (get) Token: 0x060037A1 RID: 14241 RVA: 0x000E5FB4 File Offset: 0x000E41B4
		// (set) Token: 0x060037A2 RID: 14242 RVA: 0x000E5FBC File Offset: 0x000E41BC
		[SaveableProperty(137)]
		public CampaignTime LastThreatTime { get; private set; }

		// Token: 0x17000D33 RID: 3379
		// (get) Token: 0x060037A3 RID: 14243 RVA: 0x000E5FC5 File Offset: 0x000E41C5
		// (set) Token: 0x060037A4 RID: 14244 RVA: 0x000E5FCD File Offset: 0x000E41CD
		[SaveableProperty(149)]
		public SiegeEvent.SiegeEnginesContainer SiegeEngines { get; private set; }

		// Token: 0x17000D34 RID: 3380
		// (get) Token: 0x060037A5 RID: 14245 RVA: 0x000E5FD6 File Offset: 0x000E41D6
		public MBReadOnlyList<SiegeEvent.SiegeEngineMissile> SiegeEngineMissiles
		{
			get
			{
				return this._siegeEngineMissiles;
			}
		}

		// Token: 0x17000D35 RID: 3381
		// (get) Token: 0x060037A6 RID: 14246 RVA: 0x000E5FDE File Offset: 0x000E41DE
		public BattleSideEnum BattleSide
		{
			get
			{
				return BattleSideEnum.Defender;
			}
		}

		// Token: 0x17000D36 RID: 3382
		// (get) Token: 0x060037A7 RID: 14247 RVA: 0x000E5FE1 File Offset: 0x000E41E1
		// (set) Token: 0x060037A8 RID: 14248 RVA: 0x000E5FE9 File Offset: 0x000E41E9
		[SaveableProperty(150)]
		public int NumberOfTroopsKilledOnSide { get; private set; }

		// Token: 0x17000D37 RID: 3383
		// (get) Token: 0x060037A9 RID: 14249 RVA: 0x000E5FF2 File Offset: 0x000E41F2
		// (set) Token: 0x060037AA RID: 14250 RVA: 0x000E5FFA File Offset: 0x000E41FA
		[SaveableProperty(151)]
		public SiegeStrategy SiegeStrategy { get; private set; }

		// Token: 0x060037AB RID: 14251 RVA: 0x000E6003 File Offset: 0x000E4203
		public IEnumerable<PartyBase> GetInvolvedPartiesForEventType(MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
		{
			return Campaign.Current.Models.EncounterModel.GetDefenderPartiesOfSettlement(this, mapEventType);
		}

		// Token: 0x060037AC RID: 14252 RVA: 0x000E601B File Offset: 0x000E421B
		public PartyBase GetNextInvolvedPartyForEventType(ref int partyIndex, MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
		{
			return Campaign.Current.Models.EncounterModel.GetNextDefenderPartyOfSettlement(this, ref partyIndex, mapEventType);
		}

		// Token: 0x060037AD RID: 14253 RVA: 0x000E6034 File Offset: 0x000E4234
		public bool HasInvolvedPartyForEventType(PartyBase party, MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
		{
			int num = -1;
			for (PartyBase partyBase = Campaign.Current.Models.EncounterModel.GetNextDefenderPartyOfSettlement(this, ref num, mapEventType); partyBase != null; partyBase = Campaign.Current.Models.EncounterModel.GetNextDefenderPartyOfSettlement(this, ref num, mapEventType))
			{
				if (partyBase == party)
				{
					return true;
				}
			}
			return false;
		}

		// Token: 0x060037AE RID: 14254 RVA: 0x000E6081 File Offset: 0x000E4281
		internal void AddBoundVillageInternal(Village village)
		{
			this._boundVillages.Add(village);
		}

		// Token: 0x060037AF RID: 14255 RVA: 0x000E608F File Offset: 0x000E428F
		internal void RemoveBoundVillageInternal(Village village)
		{
			this._boundVillages.Remove(village);
		}

		// Token: 0x17000D38 RID: 3384
		// (get) Token: 0x060037B0 RID: 14256 RVA: 0x000E609E File Offset: 0x000E429E
		// (set) Token: 0x060037B1 RID: 14257 RVA: 0x000E60A6 File Offset: 0x000E42A6
		[SaveableProperty(133)]
		public List<Alley> Alleys { get; private set; }

		// Token: 0x060037B2 RID: 14258 RVA: 0x000E60B0 File Offset: 0x000E42B0
		private void InitSettlement()
		{
			this._partiesCache = new MBList<MobileParty>();
			this._heroesWithoutPartyCache = new MBList<Hero>();
			this._notablesCache = new MBList<Hero>();
			this._boundVillages = new MBList<Village>();
			this.SettlementHitPoints = 1f;
			this.CurrentSiegeState = Settlement.SiegeState.OnTheWalls;
			float currentTime = Campaign.CurrentTime;
			this.LastVisitTimeOfOwner = currentTime;
		}

		// Token: 0x17000D39 RID: 3385
		// (get) Token: 0x060037B3 RID: 14259 RVA: 0x000E6108 File Offset: 0x000E4308
		public bool IsTown
		{
			get
			{
				return this.Town != null && this.Town.IsTown;
			}
		}

		// Token: 0x17000D3A RID: 3386
		// (get) Token: 0x060037B4 RID: 14260 RVA: 0x000E611F File Offset: 0x000E431F
		public bool IsCastle
		{
			get
			{
				return this.Town != null && this.Town.IsCastle;
			}
		}

		// Token: 0x17000D3B RID: 3387
		// (get) Token: 0x060037B5 RID: 14261 RVA: 0x000E6136 File Offset: 0x000E4336
		public bool IsFortification
		{
			get
			{
				return this.IsTown || this.IsCastle;
			}
		}

		// Token: 0x17000D3C RID: 3388
		// (get) Token: 0x060037B6 RID: 14262 RVA: 0x000E6148 File Offset: 0x000E4348
		public bool IsVillage
		{
			get
			{
				return this.Village != null;
			}
		}

		// Token: 0x17000D3D RID: 3389
		// (get) Token: 0x060037B7 RID: 14263 RVA: 0x000E6153 File Offset: 0x000E4353
		public bool IsHideout
		{
			get
			{
				return this.Hideout != null;
			}
		}

		// Token: 0x17000D3E RID: 3390
		// (get) Token: 0x060037B8 RID: 14264 RVA: 0x000E615E File Offset: 0x000E435E
		public bool IsStarving
		{
			get
			{
				return this.Town != null && this.Town.FoodStocks <= 0f;
			}
		}

		// Token: 0x17000D3F RID: 3391
		// (get) Token: 0x060037B9 RID: 14265 RVA: 0x000E617F File Offset: 0x000E437F
		public bool IsRaided
		{
			get
			{
				return this.IsVillage && this.Village.VillageState == Village.VillageStates.Looted;
			}
		}

		// Token: 0x17000D40 RID: 3392
		// (get) Token: 0x060037BA RID: 14266 RVA: 0x000E6199 File Offset: 0x000E4399
		public bool InRebelliousState
		{
			get
			{
				return (this.IsTown || this.IsCastle) && this.Town.InRebelliousState;
			}
		}

		// Token: 0x17000D41 RID: 3393
		// (get) Token: 0x060037BB RID: 14267 RVA: 0x000E61B8 File Offset: 0x000E43B8
		public bool IsUnderRaid
		{
			get
			{
				return this.Party.MapEvent != null && this.Party.MapEvent.IsRaid;
			}
		}

		// Token: 0x17000D42 RID: 3394
		// (get) Token: 0x060037BC RID: 14268 RVA: 0x000E61D9 File Offset: 0x000E43D9
		public bool IsUnderSiege
		{
			get
			{
				return this.SiegeEvent != null;
			}
		}

		// Token: 0x060037BD RID: 14269 RVA: 0x000E61E4 File Offset: 0x000E43E4
		public bool IsUnderRebellionAttack()
		{
			if (this.Party.MapEvent != null && this.Party.MapEvent.IsSiegeAssault)
			{
				Hero owner = this.Party.MapEvent.AttackerSide.LeaderParty.MobileParty.Party.Owner;
				if (owner != null && owner.Clan.IsRebelClan)
				{
					return true;
				}
			}
			return false;
		}

		// Token: 0x060037BE RID: 14270 RVA: 0x000E6248 File Offset: 0x000E4448
		public Settlement()
			: this(new TextObject("{=!}unnamed", null), null, null)
		{
		}

		// Token: 0x060037BF RID: 14271 RVA: 0x000E6260 File Offset: 0x000E4460
		public Settlement(TextObject name, LocationComplex locationComplex, PartyTemplateObject pt)
		{
			this._name = name;
			this._isVisible = true;
			this.IsActive = true;
			this.Party = new PartyBase(this);
			this.InitSettlement();
			this._position = CampaignVec2.Invalid;
			this.LocationComplex = locationComplex;
			this.Alleys = new List<Alley>();
			this.HasVisited = false;
			this.Stash = new ItemRoster();
			((ILocatable<Settlement>)this).LocatorNodeIndex = -1;
		}

		// Token: 0x060037C0 RID: 14272 RVA: 0x000E62E6 File Offset: 0x000E44E6
		public float GetSettlementValueForEnemyHero(Hero hero)
		{
			return Campaign.Current.Models.SettlementValueModel.CalculateSettlementValueForEnemyHero(this, hero);
		}

		// Token: 0x17000D43 RID: 3395
		// (get) Token: 0x060037C1 RID: 14273 RVA: 0x000E62FE File Offset: 0x000E44FE
		// (set) Token: 0x060037C2 RID: 14274 RVA: 0x000E6306 File Offset: 0x000E4506
		[SaveableProperty(138)]
		public LocationComplex LocationComplex { get; private set; }

		// Token: 0x17000D44 RID: 3396
		// (get) Token: 0x060037C3 RID: 14275 RVA: 0x000E6310 File Offset: 0x000E4510
		public static Settlement CurrentSettlement
		{
			get
			{
				if (PlayerCaptivity.CaptorParty != null && PlayerCaptivity.CaptorParty.IsSettlement)
				{
					return PlayerCaptivity.CaptorParty.Settlement;
				}
				if (PlayerEncounter.EncounterSettlement != null)
				{
					return PlayerEncounter.EncounterSettlement;
				}
				if (MobileParty.MainParty.CurrentSettlement != null)
				{
					return MobileParty.MainParty.CurrentSettlement;
				}
				return null;
			}
		}

		// Token: 0x060037C4 RID: 14276 RVA: 0x000E6360 File Offset: 0x000E4560
		public bool IsSettlementBusy(object asker)
		{
			return this.GetSettlementBusynessPriority(asker) > 0;
		}

		// Token: 0x060037C5 RID: 14277 RVA: 0x000E636C File Offset: 0x000E456C
		public bool IsSettlementBusy(object asker, int limitingPriority)
		{
			return this.GetSettlementBusynessPriority(asker) > limitingPriority;
		}

		// Token: 0x060037C6 RID: 14278 RVA: 0x000E6378 File Offset: 0x000E4578
		public int GetSettlementBusynessPriority(object asker)
		{
			int num = 0;
			CampaignEventDispatcher.Instance.IsSettlementBusy(this, asker, ref num);
			return num;
		}

		// Token: 0x060037C7 RID: 14279 RVA: 0x000E6398 File Offset: 0x000E4598
		public float GetValue(Hero hero = null, bool countAlsoBoundedSettlements = true)
		{
			float num = 0f;
			if (this.IsVillage)
			{
				num = 100000f + this.Village.Hearth * 250f;
				num *= ((this.Village.VillageState == Village.VillageStates.Looted) ? 0.8f : ((this.Village.VillageState == Village.VillageStates.BeingRaided) ? 0.85f : (0.8f + (0.667f + 0.333f * this.Village.Settlement.SettlementHitPoints) * 0.2f)));
			}
			else if (this.IsCastle)
			{
				num = 250000f + this.Town.Prosperity * 1000f;
			}
			else if (this.IsTown)
			{
				num = 750000f + this.Town.Prosperity * 1000f;
			}
			float num2 = 1f;
			if (hero != null && hero.Clan.Settlements.Count > 0)
			{
				float num3 = MathF.Pow(Campaign.Current.Models.MapDistanceModel.GetDistance(hero.Clan.FactionMidSettlement, this, false, false, MobileParty.NavigationType.All) / Campaign.Current.GetAverageDistanceBetweenClosestTwoTownsWithNavigationType(MobileParty.NavigationType.All) * 4f, 2f);
				num3 = MathF.Clamp(num3, 0f, 100f);
				num3 -= 16f;
				num2 *= (100f - num3) / 100f;
			}
			if (countAlsoBoundedSettlements)
			{
				foreach (Village village in this.BoundVillages)
				{
					num += village.Settlement.GetValue(hero, false);
				}
			}
			return num * num2;
		}

		// Token: 0x060037C8 RID: 14280 RVA: 0x000E6540 File Offset: 0x000E4740
		public override TextObject GetName()
		{
			return this.Name;
		}

		// Token: 0x060037C9 RID: 14281 RVA: 0x000E6548 File Offset: 0x000E4748
		public float GetSettlementValueForFaction(IFaction faction)
		{
			return Campaign.Current.Models.SettlementValueModel.CalculateSettlementValueForFaction(this, faction);
		}

		// Token: 0x060037CA RID: 14282 RVA: 0x000E6560 File Offset: 0x000E4760
		public override string ToString()
		{
			return this.Name.ToString();
		}

		// Token: 0x060037CB RID: 14283 RVA: 0x000E656D File Offset: 0x000E476D
		internal void AddMobileParty(MobileParty mobileParty)
		{
			if (!this._partiesCache.Contains(mobileParty))
			{
				this._partiesCache.Add(mobileParty);
				return;
			}
			Debug.FailedAssert("mobileParty is already in mobileParties List!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Settlements\\Settlement.cs", "AddMobileParty", 676);
		}

		// Token: 0x060037CC RID: 14284 RVA: 0x000E65A3 File Offset: 0x000E47A3
		internal void RemoveMobileParty(MobileParty mobileParty)
		{
			if (this._partiesCache.Contains(mobileParty))
			{
				this._partiesCache.Remove(mobileParty);
				return;
			}
			Debug.FailedAssert("mobileParty is not in mobileParties List", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Settlements\\Settlement.cs", "RemoveMobileParty", 688);
		}

		// Token: 0x060037CD RID: 14285 RVA: 0x000E65DA File Offset: 0x000E47DA
		internal void SetPatrolParty(PatrolPartyComponent patrolParty)
		{
			this.PatrolParty = patrolParty;
		}

		// Token: 0x060037CE RID: 14286 RVA: 0x000E65E3 File Offset: 0x000E47E3
		internal void AddHeroWithoutParty(Hero individual)
		{
			if (!this._heroesWithoutPartyCache.Contains(individual))
			{
				this._heroesWithoutPartyCache.Add(individual);
				this.CollectNotablesToCache();
				return;
			}
			Debug.FailedAssert("Notable is already in Notable List!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Settlements\\Settlement.cs", "AddHeroWithoutParty", 713);
		}

		// Token: 0x060037CF RID: 14287 RVA: 0x000E6620 File Offset: 0x000E4820
		public void OnPartyInteraction(MobileParty engagingParty)
		{
			if (engagingParty.ShortTermTargetSettlement != null && ((engagingParty.IsCurrentlyAtSea && engagingParty.IsTargetingPort) || (engagingParty.ShortTermTargetSettlement.IsVillage && engagingParty.DefaultBehavior == AiBehavior.DefendSettlement) || ((engagingParty.ShortTermTargetSettlement.Party.SiegeEvent == null || engagingParty == MobileParty.MainParty || engagingParty.MapFaction == engagingParty.ShortTermTargetSettlement.SiegeEvent.BesiegerCamp.MapFaction) && (engagingParty.ShortTermTargetSettlement.Party.MapEvent == null || engagingParty == MobileParty.MainParty || engagingParty.MapFaction == engagingParty.ShortTermTargetSettlement.Party.MapEvent.AttackerSide.LeaderParty.MapFaction || (engagingParty.ShortTermTargetSettlement.Party.MapEvent.IsSallyOut && engagingParty.MapFaction == engagingParty.ShortTermTargetSettlement.Party.MapEvent.DefenderSide.LeaderParty.MapFaction)))))
			{
				if (engagingParty == MobileParty.MainParty && (engagingParty.ShortTermTargetSettlement.Party.MapEvent == null || !engagingParty.ShortTermTargetSettlement.Party.MapEvent.IsRaid || engagingParty.ShortTermTargetSettlement.Party.MapEvent.DefenderSide.NumRemainingSimulationTroops > 0))
				{
					MapState mapState = Game.Current.GameStateManager.ActiveState as MapState;
					if (mapState != null)
					{
						mapState.OnMainPartyEncounter();
					}
				}
				if (engagingParty.ShortTermTargetSettlement.Party.MapEvent != null && engagingParty.ShortTermTargetSettlement.Party.MapEvent.IsRaid && engagingParty.DefaultBehavior == AiBehavior.RaidSettlement)
				{
					engagingParty.Ai.RethinkAtNextHourlyTick = true;
					engagingParty.SetMoveModeHold();
					return;
				}
				if (engagingParty.DefaultBehavior == AiBehavior.DefendSettlement && engagingParty.ShortTermTargetSettlement.IsVillage)
				{
					MobileParty lastAttackerParty = engagingParty.ShortTermTargetSettlement.LastAttackerParty;
					if (lastAttackerParty != null && lastAttackerParty.MapEvent != null && lastAttackerParty.MapEvent.IsRaid)
					{
						EncounterManager.StartPartyEncounter(engagingParty.Party, engagingParty.ShortTermTargetSettlement.LastAttackerParty.Party);
						return;
					}
				}
				else
				{
					EncounterManager.StartSettlementEncounter(engagingParty, engagingParty.ShortTermTargetSettlement);
				}
			}
		}

		// Token: 0x060037D0 RID: 14288 RVA: 0x000E6839 File Offset: 0x000E4A39
		internal void RemoveHeroWithoutParty(Hero individual)
		{
			if (this._heroesWithoutPartyCache.Contains(individual))
			{
				this._heroesWithoutPartyCache.Remove(individual);
				this.CollectNotablesToCache();
				return;
			}
			Debug.FailedAssert("Notable is not in Notable List", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Settlements\\Settlement.cs", "RemoveHeroWithoutParty", 783);
		}

		// Token: 0x060037D1 RID: 14289 RVA: 0x000E6878 File Offset: 0x000E4A78
		private void CollectNotablesToCache()
		{
			this._notablesCache.Clear();
			foreach (Hero hero in this.HeroesWithoutParty)
			{
				if (hero.IsNotable)
				{
					this._notablesCache.Add(hero);
				}
			}
		}

		// Token: 0x060037D2 RID: 14290 RVA: 0x000E68E4 File Offset: 0x000E4AE4
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			this._name = new TextObject(node.Attributes["name"].Value, null);
			Vec2 vec = new Vec2((float)Convert.ToDouble(node.Attributes["posX"].Value), (float)Convert.ToDouble(node.Attributes["posY"].Value));
			this.Position = new CampaignVec2(vec, true);
			this.GatePosition = new CampaignVec2(vec, true);
			if (node.Attributes["gate_posX"] != null)
			{
				this.GatePosition = new CampaignVec2(new Vec2((float)Convert.ToDouble(node.Attributes["gate_posX"].Value), (float)Convert.ToDouble(node.Attributes["gate_posY"].Value)), true);
			}
			this.PortPosition = new CampaignVec2(vec, false);
			if (node.Attributes["port_posX"] != null)
			{
				CampaignVec2 campaignVec = new CampaignVec2(new Vec2((float)Convert.ToDouble(node.Attributes["port_posX"].Value), (float)Convert.ToDouble(node.Attributes["port_posY"].Value)), false);
				this.SetPortPosition(campaignVec);
			}
			this.Culture = objectManager.ReadObjectReferenceFromXml<CultureObject>("culture", node);
			this.EncyclopediaText = ((node.Attributes["text"] != null) ? new TextObject(node.Attributes["text"].Value, null) : TextObject.GetEmpty());
			foreach (object obj in node.ChildNodes)
			{
				XmlNode xmlNode = (XmlNode)obj;
				if (xmlNode.Name == "Components")
				{
					foreach (object obj2 in xmlNode.ChildNodes)
					{
						XmlNode xmlNode2 = (XmlNode)obj2;
						SettlementComponent settlementComponent;
						if (xmlNode2.Name == "CustomSettlementComponent")
						{
							XmlAttribute xmlAttribute = xmlNode2.Attributes["component_name"];
							string text = ((xmlAttribute != null) ? xmlAttribute.Value : null);
							settlementComponent = (SettlementComponent)objectManager.CreateObjectFromXmlNode(xmlNode2, text);
						}
						else
						{
							settlementComponent = (SettlementComponent)objectManager.CreateObjectFromXmlNode(xmlNode2);
						}
						this.SetSettlementComponent(settlementComponent);
					}
				}
				if (xmlNode.Name == "Locations")
				{
					LocationComplexTemplate locationComplexTemplate = (LocationComplexTemplate)objectManager.ReadObjectReferenceFromXml("complex_template", typeof(LocationComplexTemplate), xmlNode);
					if (Campaign.Current.CampaignGameLoadingType != Campaign.GameLoadingType.SavedCampaign || this.LocationComplex == null)
					{
						this.LocationComplex = new LocationComplex(locationComplexTemplate);
					}
					else
					{
						this.LocationComplex.Initialize(locationComplexTemplate);
					}
					foreach (object obj3 in xmlNode.ChildNodes)
					{
						XmlNode xmlNode3 = (XmlNode)obj3;
						if (xmlNode3.Name == "Location")
						{
							Location locationWithId = this.LocationComplex.GetLocationWithId(xmlNode3.Attributes["id"].Value);
							if (xmlNode3.Attributes["max_prosperity"] != null)
							{
								locationWithId.ProsperityMax = int.Parse(xmlNode3.Attributes["max_prosperity"].Value);
							}
							bool flag = false;
							for (int i = 0; i < 4; i++)
							{
								string text2 = "scene_name" + ((i > 0) ? ("_" + i) : "");
								string text3 = ((xmlNode3.Attributes[text2] != null) ? xmlNode3.Attributes[text2].Value : "");
								flag = flag || !string.IsNullOrEmpty(text3);
								locationWithId.SetSceneName(i, text3);
							}
						}
					}
				}
				if (xmlNode.Name == "CommonAreas")
				{
					int num = 0;
					foreach (object obj4 in xmlNode.ChildNodes)
					{
						XmlNode xmlNode4 = (XmlNode)obj4;
						if (xmlNode4.Name == "Area")
						{
							string value = xmlNode4.Attributes["name"].Value;
							string text4 = "alley_" + (num + 1);
							if (Campaign.Current.CampaignGameLoadingType != Campaign.GameLoadingType.SavedCampaign)
							{
								this.Alleys.Add(new Alley(this, text4, new TextObject(value, null)));
							}
							else
							{
								this.Alleys[num].Initialize(this, text4, new TextObject(value, null));
							}
							num++;
						}
					}
				}
			}
			if (Campaign.Current.CampaignGameLoadingType != Campaign.GameLoadingType.SavedCampaign)
			{
				Clan clan = objectManager.ReadObjectReferenceFromXml<Clan>("owner", node);
				if (clan != null && this.Town != null)
				{
					this.Town.OwnerClan = clan;
				}
			}
			this._name.SetSettlementProperties(this);
		}

		// Token: 0x060037D3 RID: 14291 RVA: 0x000E6E94 File Offset: 0x000E5094
		public void OnFinishLoadState()
		{
			if (this.IsFortification)
			{
				foreach (Building building in this.Town.Buildings)
				{
					if (building.BuildingType.IsDailyProject && building.CurrentLevel != 1)
					{
						building.CurrentLevel = 1;
					}
				}
			}
			this.Party.UpdateVisibilityAndInspected(MobileParty.MainParty.Position, 0f);
		}

		// Token: 0x060037D4 RID: 14292 RVA: 0x000E6F24 File Offset: 0x000E5124
		public void OnGameCreated()
		{
			SettlementComponent settlementComponent = this.SettlementComponent;
			if (settlementComponent != null)
			{
				settlementComponent.OnInit();
			}
			this.Party.SetLevelMaskIsDirty();
			for (int i = 0; i < this.WallSectionCount; i++)
			{
				this._settlementWallSectionHitPointsRatioList.Add(1f);
			}
		}

		// Token: 0x060037D5 RID: 14293 RVA: 0x000E6F6E File Offset: 0x000E516E
		public void OnSessionStart()
		{
			PartyBase party = this.Party;
			if (party != null)
			{
				party.SetVisualAsDirty();
			}
			this.SettlementComponent.OnSessionStart();
		}

		// Token: 0x060037D6 RID: 14294 RVA: 0x000E6F8C File Offset: 0x000E518C
		[LoadInitializationCallback]
		private void OnLoad()
		{
			((ILocatable<Settlement>)this).LocatorNodeIndex = -1;
			this._partiesCache = new MBList<MobileParty>();
			this._heroesWithoutPartyCache = new MBList<Hero>();
			this._notablesCache = new MBList<Hero>();
		}

		// Token: 0x060037D7 RID: 14295 RVA: 0x000E6FB8 File Offset: 0x000E51B8
		public void CheckPositionsForMapChangeAndUpdateIfNeeded()
		{
			foreach (MobileParty mobileParty in MobileParty.All)
			{
				if (mobileParty.CurrentSettlement == this)
				{
					if (this.IsFortification)
					{
						CampaignVec2 campaignVec = (mobileParty.IsCurrentlyAtSea ? this.PortPosition : this.GatePosition);
						mobileParty.SetPositionAfterMapChange(campaignVec);
					}
					else
					{
						float num = (this.IsVillage ? Campaign.Current.Models.EncounterModel.NeededMaximumDistanceForEncounteringVillage : Campaign.Current.Models.EncounterModel.NeededMaximumDistanceForEncounteringTown);
						if (mobileParty.Position.Distance(this.GatePosition) > num)
						{
							mobileParty.SetPositionAfterMapChange(this.GatePosition);
						}
					}
				}
			}
			if (this.Party.SiegeEvent != null)
			{
				this.Party.SiegeEvent.SetPositionAfterMapChange(this.GatePosition);
				return;
			}
			if (this.Party.MapEvent != null)
			{
				switch (this.Party.MapEvent.EventType)
				{
				case MapEvent.BattleTypes.FieldBattle:
				case MapEvent.BattleTypes.Siege:
				case MapEvent.BattleTypes.SallyOut:
				case MapEvent.BattleTypes.SiegeOutside:
				case MapEvent.BattleTypes.BlockadeBattle:
				case MapEvent.BattleTypes.BlockadeSallyOutBattle:
					break;
				case MapEvent.BattleTypes.Raid:
				case MapEvent.BattleTypes.IsForcingVolunteers:
				case MapEvent.BattleTypes.IsForcingSupplies:
				case MapEvent.BattleTypes.Hideout:
					this.Party.MapEvent.SetPositionAfterMapChange(this.GatePosition);
					break;
				default:
					return;
				}
			}
		}

		// Token: 0x060037D8 RID: 14296 RVA: 0x000E711C File Offset: 0x000E531C
		[LateLoadInitializationCallback]
		private void OnLateLoad(MetaData metaData, ObjectLoadData objectLoadData)
		{
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.0", 0))
			{
				object memberValueBySaveId = objectLoadData.GetMemberValueBySaveId(118);
				if (memberValueBySaveId != null)
				{
					this._oldProsperityObsolete = (float)memberValueBySaveId;
				}
			}
		}

		// Token: 0x060037D9 RID: 14297 RVA: 0x000E715F File Offset: 0x000E535F
		public static Settlement Find(string idString)
		{
			return MBObjectManager.Instance.GetObject<Settlement>(idString);
		}

		// Token: 0x060037DA RID: 14298 RVA: 0x000E716C File Offset: 0x000E536C
		public static Settlement FindFirst(Func<Settlement, bool> predicate)
		{
			return Settlement.All.FirstOrDefault<Settlement>(predicate);
		}

		// Token: 0x060037DB RID: 14299 RVA: 0x000E7179 File Offset: 0x000E5379
		public static IEnumerable<Settlement> FindAll(Func<Settlement, bool> predicate)
		{
			return Settlement.All.Where<Settlement>(predicate);
		}

		// Token: 0x17000D45 RID: 3397
		// (get) Token: 0x060037DC RID: 14300 RVA: 0x000E7186 File Offset: 0x000E5386
		public static MBReadOnlyList<Settlement> All
		{
			get
			{
				return Campaign.Current.Settlements;
			}
		}

		// Token: 0x17000D46 RID: 3398
		// (get) Token: 0x060037DD RID: 14301 RVA: 0x000E7192 File Offset: 0x000E5392
		public static Settlement GetFirst
		{
			get
			{
				return Settlement.All.FirstOrDefault<Settlement>();
			}
		}

		// Token: 0x060037DE RID: 14302 RVA: 0x000E719E File Offset: 0x000E539E
		public static LocatableSearchData<Settlement> StartFindingLocatablesAroundPosition(Vec2 position, float radius)
		{
			return Campaign.Current.SettlementLocator.StartFindingLocatablesAroundPosition(position, radius);
		}

		// Token: 0x060037DF RID: 14303 RVA: 0x000E71B1 File Offset: 0x000E53B1
		public static Settlement FindNextLocatable(ref LocatableSearchData<Settlement> data)
		{
			return Campaign.Current.SettlementLocator.FindNextLocatable(ref data);
		}

		// Token: 0x060037E0 RID: 14304 RVA: 0x000E71C3 File Offset: 0x000E53C3
		public void OnPlayerEncounterFinish()
		{
			LocationComplex locationComplex = this.LocationComplex;
			if (locationComplex == null)
			{
				return;
			}
			locationComplex.ClearTempCharacters();
		}

		// Token: 0x060037E1 RID: 14305 RVA: 0x000E71D5 File Offset: 0x000E53D5
		public Vec3 GetPosition()
		{
			return this.GetPositionAsVec3();
		}

		// Token: 0x060037E2 RID: 14306 RVA: 0x000E71DD File Offset: 0x000E53DD
		TextObject ITrackableBase.GetName()
		{
			return this.Name;
		}

		// Token: 0x060037E3 RID: 14307 RVA: 0x000E71E5 File Offset: 0x000E53E5
		Vec3 ITrackableBase.GetPosition()
		{
			return this.GetPosition();
		}

		// Token: 0x060037E4 RID: 14308 RVA: 0x000E71ED File Offset: 0x000E53ED
		Banner ITrackableCampaignObject.GetBanner()
		{
			return this.Banner;
		}

		// Token: 0x17000D47 RID: 3399
		// (get) Token: 0x060037E5 RID: 14309 RVA: 0x000E71F5 File Offset: 0x000E53F5
		// (set) Token: 0x060037E6 RID: 14310 RVA: 0x000E71FD File Offset: 0x000E53FD
		[SaveableProperty(142)]
		public Settlement.SiegeState CurrentSiegeState { get; private set; }

		// Token: 0x17000D48 RID: 3400
		// (get) Token: 0x060037E7 RID: 14311 RVA: 0x000E7208 File Offset: 0x000E5408
		public Clan OwnerClan
		{
			get
			{
				if (this.Village != null)
				{
					return this.Village.Bound.OwnerClan;
				}
				if (this.Town != null)
				{
					return this.Town.OwnerClan;
				}
				if (this.IsHideout)
				{
					return this.Hideout.MapFaction as Clan;
				}
				return null;
			}
		}

		// Token: 0x060037E8 RID: 14312 RVA: 0x000E725C File Offset: 0x000E545C
		public void SetNextSiegeState()
		{
			if (this.CurrentSiegeState == Settlement.SiegeState.InTheLordsHall)
			{
				return;
			}
			this.CurrentSiegeState++;
		}

		// Token: 0x060037E9 RID: 14313 RVA: 0x000E7276 File Offset: 0x000E5476
		public void ResetSiegeState()
		{
			this.CurrentSiegeState = Settlement.SiegeState.OnTheWalls;
		}

		// Token: 0x060037EA RID: 14314 RVA: 0x000E7280 File Offset: 0x000E5480
		public void AddGarrisonParty()
		{
			GarrisonPartyComponent.CreateGarrisonParty(string.Concat(new string[]
			{
				"garrison_party_",
				base.StringId,
				"_",
				this.OwnerClan.StringId,
				"_1"
			}), this);
		}

		// Token: 0x060037EB RID: 14315 RVA: 0x000E72D0 File Offset: 0x000E54D0
		protected override void AfterLoad()
		{
			if (this.SiegeEvent != null && this.SiegeEvent.BesiegerCamp.LeaderParty == null)
			{
				if (this.SiegeEvent.BesiegedSettlement.Party.MapEvent != null)
				{
					this.SiegeEvent.BesiegedSettlement.Party.MapEvent.FinalizeEvent();
				}
				else if (this.SiegeEvent != null)
				{
					this.SiegeEvent.FinalizeSiegeEvent();
				}
			}
			this._notablesCache = new MBList<Hero>();
			this.CollectNotablesToCache();
			this.Party.AfterLoad();
			foreach (Alley alley in this.Alleys)
			{
				alley.AfterLoad();
			}
			if (this.Town != null && this._oldProsperityObsolete > 0f)
			{
				this.Town.Prosperity = this._oldProsperityObsolete;
			}
		}

		// Token: 0x060037EC RID: 14316 RVA: 0x000E73C4 File Offset: 0x000E55C4
		private void SpawnMilitiaParty()
		{
			MilitiaPartyComponent.CreateMilitiaParty("militias_of_" + base.StringId + "_aaa1", this);
			this.TransferReadyMilitiasToMilitiaParty();
		}

		// Token: 0x060037ED RID: 14317 RVA: 0x000E73E8 File Offset: 0x000E55E8
		private void TransferReadyMilitiasToMilitiaParty()
		{
			if (this._readyMilitia >= 1f)
			{
				int num = MathF.Floor(this._readyMilitia);
				this._readyMilitia -= (float)num;
				if (num > 0)
				{
					this.AddMilitiasToParty(this.MilitiaPartyComponent.MobileParty, num);
					return;
				}
			}
			else if ((int)this._readyMilitia < -1)
			{
				int num2 = MathF.Ceiling(this._readyMilitia);
				this._readyMilitia -= (float)num2;
				Settlement.RemoveMilitiasFromParty(this.MilitiaPartyComponent.MobileParty, -num2);
			}
		}

		// Token: 0x060037EE RID: 14318 RVA: 0x000E746C File Offset: 0x000E566C
		private void AddMilitiasToParty(MobileParty militiaParty, int militiaNumberToAdd)
		{
			float num;
			float num2;
			Campaign.Current.Models.SettlementMilitiaModel.CalculateMilitiaSpawnRate(this, out num, out num2);
			this.AddTroopToMilitiaParty(militiaParty, this.Culture.MeleeMilitiaTroop, this.Culture.MeleeEliteMilitiaTroop, num, militiaNumberToAdd);
			this.AddTroopToMilitiaParty(militiaParty, this.Culture.RangedMilitiaTroop, this.Culture.RangedEliteMilitiaTroop, num2, militiaNumberToAdd);
		}

		// Token: 0x060037EF RID: 14319 RVA: 0x000E74D0 File Offset: 0x000E56D0
		private void AddTroopToMilitiaParty(MobileParty militiaParty, CharacterObject militiaTroop, CharacterObject veteranMilitiaTroop, float troopRatio, int militiaNumberToAdd)
		{
			int num = MBRandom.RoundRandomized(troopRatio * (float)militiaNumberToAdd);
			float resultNumber = Campaign.Current.Models.SettlementMilitiaModel.CalculateVeteranMilitiaSpawnChance(this).ResultNumber;
			for (int i = 0; i < num; i++)
			{
				if (MBRandom.RandomFloat < resultNumber)
				{
					militiaParty.MemberRoster.AddToCounts(veteranMilitiaTroop, 1, false, 0, 0, true, -1);
				}
				else
				{
					militiaParty.MemberRoster.AddToCounts(militiaTroop, 1, false, 0, 0, true, -1);
				}
			}
		}

		// Token: 0x060037F0 RID: 14320 RVA: 0x000E7544 File Offset: 0x000E5744
		private static void RemoveMilitiasFromParty(MobileParty militiaParty, int numberToRemove)
		{
			if (militiaParty.MemberRoster.TotalManCount <= numberToRemove)
			{
				militiaParty.MemberRoster.Clear();
				return;
			}
			float num = (float)numberToRemove / (float)militiaParty.MemberRoster.TotalManCount;
			int num2 = numberToRemove;
			for (int i = 0; i < militiaParty.MemberRoster.Count; i++)
			{
				int num3 = MBRandom.RoundRandomized((float)militiaParty.MemberRoster.GetElementNumber(i) * num);
				if (num3 > num2)
				{
					num3 = num2;
				}
				militiaParty.MemberRoster.AddToCountsAtIndex(i, -num3, 0, 0, false);
				num2 -= num3;
				if (num2 <= 0)
				{
					break;
				}
			}
			militiaParty.MemberRoster.RemoveZeroCounts();
		}

		// Token: 0x060037F1 RID: 14321 RVA: 0x000E75D3 File Offset: 0x000E57D3
		public void SetSiegeStrategy(SiegeStrategy strategy)
		{
			this.SiegeStrategy = strategy;
		}

		// Token: 0x060037F2 RID: 14322 RVA: 0x000E75DC File Offset: 0x000E57DC
		public void InitializeSiegeEventSide()
		{
			this.SiegeStrategy = DefaultSiegeStrategies.Custom;
			this.NumberOfTroopsKilledOnSide = 0;
			SiegeEvent.SiegeEngineConstructionProgress siegeEngineConstructionProgress = null;
			this.SiegeEngines = new SiegeEvent.SiegeEnginesContainer(BattleSideEnum.Defender, siegeEngineConstructionProgress);
			this._siegeEngineMissiles = new MBList<SiegeEvent.SiegeEngineMissile>();
			this.SetPrebuiltSiegeEngines();
		}

		// Token: 0x060037F3 RID: 14323 RVA: 0x000E761B File Offset: 0x000E581B
		public void OnTroopsKilledOnSide(int killCount)
		{
			this.NumberOfTroopsKilledOnSide += killCount;
		}

		// Token: 0x060037F4 RID: 14324 RVA: 0x000E762B File Offset: 0x000E582B
		public void AddSiegeEngineMissile(SiegeEvent.SiegeEngineMissile missile)
		{
			this._siegeEngineMissiles.Add(missile);
		}

		// Token: 0x060037F5 RID: 14325 RVA: 0x000E7639 File Offset: 0x000E5839
		public void RemoveDeprecatedMissiles()
		{
			this._siegeEngineMissiles.RemoveAll((SiegeEvent.SiegeEngineMissile missile) => missile.CollisionTime.IsPast);
		}

		// Token: 0x060037F6 RID: 14326 RVA: 0x000E7668 File Offset: 0x000E5868
		private void SetPrebuiltSiegeEngines()
		{
			foreach (SiegeEngineType siegeEngineType in Campaign.Current.Models.SiegeEventModel.GetPrebuiltSiegeEnginesOfSettlement(this))
			{
				float siegeEngineHitPoints = Campaign.Current.Models.SiegeEventModel.GetSiegeEngineHitPoints(this.SiegeEvent, siegeEngineType, BattleSideEnum.Defender);
				SiegeEvent.SiegeEngineConstructionProgress siegeEngineConstructionProgress = new SiegeEvent.SiegeEngineConstructionProgress(siegeEngineType, 1f, siegeEngineHitPoints);
				this.SiegeEngines.AddPrebuiltEngineToReserve(siegeEngineConstructionProgress);
				this.SiegeEvent.CreateSiegeObject(siegeEngineConstructionProgress, this.SiegeEvent.GetSiegeEventSide(BattleSideEnum.Defender));
			}
		}

		// Token: 0x060037F7 RID: 14327 RVA: 0x000E770C File Offset: 0x000E590C
		public void GetAttackTarget(ISiegeEventSide siegeEventSide, SiegeEngineType siegeEngine, int siegeEngineSlot, out SiegeBombardTargets targetType, out int targetIndex)
		{
			targetType = SiegeBombardTargets.None;
			targetIndex = -1;
			int num;
			float num2;
			this.SiegeEvent.FindAttackableRangedEngineWithHighestPriority(siegeEventSide, siegeEngineSlot, out num, out num2);
			if (num == -1)
			{
				return;
			}
			float num3 = num2;
			if (MBRandom.RandomFloat * num3 < num2)
			{
				targetIndex = num;
				targetType = SiegeBombardTargets.RangedEngines;
			}
		}

		// Token: 0x060037F8 RID: 14328 RVA: 0x000E774B File Offset: 0x000E594B
		public void FinalizeSiegeEvent()
		{
			this.ResetSiegeState();
			this.SiegeEvent = null;
			this.Party.SetLevelMaskIsDirty();
			this.Party.SetVisualAsDirty();
		}

		// Token: 0x060037F9 RID: 14329 RVA: 0x000E7770 File Offset: 0x000E5970
		private void SetSettlementComponent(SettlementComponent settlementComponent)
		{
			settlementComponent.Owner = this.Party;
			this.SettlementComponent = settlementComponent;
			Town town;
			if ((town = this.SettlementComponent as Town) != null)
			{
				this.Town = town;
				return;
			}
			Village village;
			if ((village = this.SettlementComponent as Village) != null)
			{
				this.Village = village;
				return;
			}
			Hideout hideout;
			if ((hideout = this.SettlementComponent as Hideout) != null)
			{
				this.Hideout = hideout;
			}
		}

		// Token: 0x060037FA RID: 14330 RVA: 0x000E77D4 File Offset: 0x000E59D4
		bool ITrackableCampaignObject.get_IsReady()
		{
			return base.IsReady;
		}

		// Token: 0x060037FB RID: 14331 RVA: 0x000E77DC File Offset: 0x000E59DC
		string ISettlementDataHolder.get_StringId()
		{
			return base.StringId;
		}

		// Token: 0x04001128 RID: 4392
		[SaveableField(107)]
		public bool HasVisited;

		// Token: 0x04001129 RID: 4393
		[SaveableField(110)]
		public float LastVisitTimeOfOwner;

		// Token: 0x0400112D RID: 4397
		[SaveableField(113)]
		private bool _isVisible;

		// Token: 0x0400112F RID: 4399
		[CachedData]
		private int _locatorNodeIndex;

		// Token: 0x04001134 RID: 4404
		[SaveableField(117)]
		private Settlement _nextLocatable;

		// Token: 0x04001135 RID: 4405
		[CachedData]
		private float _oldProsperityObsolete = -1f;

		// Token: 0x04001136 RID: 4406
		[SaveableField(119)]
		private float _readyMilitia;

		// Token: 0x04001137 RID: 4407
		[SaveableField(120)]
		private MBList<float> _settlementWallSectionHitPointsRatioList = new MBList<float>();

		// Token: 0x04001139 RID: 4409
		[CachedData]
		private MBList<MobileParty> _partiesCache;

		// Token: 0x0400113B RID: 4411
		[CachedData]
		private MBList<Hero> _heroesWithoutPartyCache;

		// Token: 0x0400113C RID: 4412
		[CachedData]
		private MBList<Hero> _notablesCache;

		// Token: 0x04001140 RID: 4416
		private CampaignVec2 _position;

		// Token: 0x04001142 RID: 4418
		public CultureObject Culture;

		// Token: 0x04001143 RID: 4419
		private TextObject _name;

		// Token: 0x04001146 RID: 4422
		[SaveableField(129)]
		private MBList<Village> _boundVillages;

		// Token: 0x04001147 RID: 4423
		[SaveableField(131)]
		private MobileParty _lastAttackerParty;

		// Token: 0x04001149 RID: 4425
		[SaveableField(148)]
		private MBList<SiegeEvent.SiegeEngineMissile> _siegeEngineMissiles;

		// Token: 0x0400114E RID: 4430
		public Town Town;

		// Token: 0x0400114F RID: 4431
		public Village Village;

		// Token: 0x04001150 RID: 4432
		public Hideout Hideout;

		// Token: 0x04001153 RID: 4435
		[CachedData]
		public MilitiaPartyComponent MilitiaPartyComponent;

		// Token: 0x04001154 RID: 4436
		[SaveableField(145)]
		public readonly ItemRoster Stash;

		// Token: 0x02000786 RID: 1926
		public enum SiegeState
		{
			// Token: 0x04001EB2 RID: 7858
			OnTheWalls,
			// Token: 0x04001EB3 RID: 7859
			InTheLordsHall,
			// Token: 0x04001EB4 RID: 7860
			Invalid
		}
	}
}
