using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Settlements
{
	// Token: 0x020003B6 RID: 950
	public abstract class SettlementComponent : MBObjectBase
	{
		// Token: 0x06003802 RID: 14338 RVA: 0x000E77EE File Offset: 0x000E59EE
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003803 RID: 14339 RVA: 0x000E77F7 File Offset: 0x000E59F7
		internal static object AutoGeneratedGetMemberValueGold(object o)
		{
			return ((SettlementComponent)o).Gold;
		}

		// Token: 0x06003804 RID: 14340 RVA: 0x000E7809 File Offset: 0x000E5A09
		internal static object AutoGeneratedGetMemberValueIsOwnerUnassigned(object o)
		{
			return ((SettlementComponent)o).IsOwnerUnassigned;
		}

		// Token: 0x17000D4D RID: 3405
		// (get) Token: 0x06003805 RID: 14341 RVA: 0x000E781B File Offset: 0x000E5A1B
		// (set) Token: 0x06003806 RID: 14342 RVA: 0x000E7823 File Offset: 0x000E5A23
		[SaveableProperty(50)]
		public int Gold { get; private set; }

		// Token: 0x06003807 RID: 14343 RVA: 0x000E782C File Offset: 0x000E5A2C
		public virtual SettlementComponent.ProsperityLevel GetProsperityLevel()
		{
			return SettlementComponent.ProsperityLevel.Mid;
		}

		// Token: 0x17000D4E RID: 3406
		// (get) Token: 0x06003808 RID: 14344 RVA: 0x000E782F File Offset: 0x000E5A2F
		// (set) Token: 0x06003809 RID: 14345 RVA: 0x000E7837 File Offset: 0x000E5A37
		public float BackgroundCropPosition { get; protected set; }

		// Token: 0x17000D4F RID: 3407
		// (get) Token: 0x0600380A RID: 14346 RVA: 0x000E7840 File Offset: 0x000E5A40
		// (set) Token: 0x0600380B RID: 14347 RVA: 0x000E7848 File Offset: 0x000E5A48
		public string BackgroundMeshName { get; protected set; }

		// Token: 0x17000D50 RID: 3408
		// (get) Token: 0x0600380C RID: 14348 RVA: 0x000E7851 File Offset: 0x000E5A51
		// (set) Token: 0x0600380D RID: 14349 RVA: 0x000E7859 File Offset: 0x000E5A59
		public string WaitMeshName { get; protected set; }

		// Token: 0x17000D51 RID: 3409
		// (get) Token: 0x0600380E RID: 14350 RVA: 0x000E7862 File Offset: 0x000E5A62
		// (set) Token: 0x0600380F RID: 14351 RVA: 0x000E786A File Offset: 0x000E5A6A
		public string CastleBackgroundMeshName { get; protected set; }

		// Token: 0x17000D52 RID: 3410
		// (get) Token: 0x06003810 RID: 14352 RVA: 0x000E7873 File Offset: 0x000E5A73
		// (set) Token: 0x06003811 RID: 14353 RVA: 0x000E787C File Offset: 0x000E5A7C
		public PartyBase Owner
		{
			get
			{
				return this._owner;
			}
			internal set
			{
				if (this._owner != value)
				{
					if (this._owner != null)
					{
						this._owner.ItemRoster.RosterUpdatedEvent -= this.OnInventoryUpdated;
					}
					this._owner = value;
					if (this._owner != null)
					{
						this._owner.ItemRoster.RosterUpdatedEvent += this.OnInventoryUpdated;
					}
				}
			}
		}

		// Token: 0x17000D53 RID: 3411
		// (get) Token: 0x06003812 RID: 14354 RVA: 0x000E78E3 File Offset: 0x000E5AE3
		public Settlement Settlement
		{
			get
			{
				return this._owner.Settlement;
			}
		}

		// Token: 0x17000D54 RID: 3412
		// (get) Token: 0x06003813 RID: 14355 RVA: 0x000E78F0 File Offset: 0x000E5AF0
		public Banner Banner
		{
			get
			{
				return this.Settlement.Banner;
			}
		}

		// Token: 0x06003814 RID: 14356 RVA: 0x000E78FD File Offset: 0x000E5AFD
		public virtual Banner GetDefaultComponentBanner()
		{
			return null;
		}

		// Token: 0x17000D55 RID: 3413
		// (get) Token: 0x06003815 RID: 14357
		public abstract IFaction MapFaction { get; }

		// Token: 0x06003816 RID: 14358 RVA: 0x000E7900 File Offset: 0x000E5B00
		protected virtual void OnInventoryUpdated(ItemRosterElement item, int count)
		{
		}

		// Token: 0x17000D56 RID: 3414
		// (get) Token: 0x06003817 RID: 14359 RVA: 0x000E7902 File Offset: 0x000E5B02
		public TextObject Name
		{
			get
			{
				return this.Owner.Name;
			}
		}

		// Token: 0x17000D57 RID: 3415
		// (get) Token: 0x06003819 RID: 14361 RVA: 0x000E7917 File Offset: 0x000E5B17
		// (set) Token: 0x0600381A RID: 14362 RVA: 0x000E791F File Offset: 0x000E5B1F
		[SaveableProperty(80)]
		public bool IsOwnerUnassigned { get; set; }

		// Token: 0x0600381B RID: 14363 RVA: 0x000E7928 File Offset: 0x000E5B28
		public virtual void OnPartyEntered(MobileParty mobileParty)
		{
		}

		// Token: 0x0600381C RID: 14364 RVA: 0x000E792A File Offset: 0x000E5B2A
		public virtual void OnPartyLeft(MobileParty mobileParty)
		{
		}

		// Token: 0x0600381D RID: 14365 RVA: 0x000E792C File Offset: 0x000E5B2C
		public virtual void OnInit()
		{
		}

		// Token: 0x0600381E RID: 14366 RVA: 0x000E792E File Offset: 0x000E5B2E
		public virtual void OnSessionStart()
		{
		}

		// Token: 0x0600381F RID: 14367 RVA: 0x000E7930 File Offset: 0x000E5B30
		public void ChangeGold(int changeAmount)
		{
			this.Gold += changeAmount;
			if (this.Gold < 0)
			{
				this.Gold = 0;
			}
		}

		// Token: 0x06003820 RID: 14368 RVA: 0x000E7950 File Offset: 0x000E5B50
		public int GetNumberOfTroops()
		{
			int num = 0;
			foreach (MobileParty mobileParty in this.Owner.Settlement.Parties)
			{
				if (mobileParty.IsMilitia || mobileParty.IsGarrison)
				{
					num += mobileParty.Party.NumberOfAllMembers;
				}
			}
			return num;
		}

		// Token: 0x06003821 RID: 14369 RVA: 0x000E79C8 File Offset: 0x000E5BC8
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
		}

		// Token: 0x06003822 RID: 14370 RVA: 0x000E79D2 File Offset: 0x000E5BD2
		public virtual int GetItemPrice(ItemObject item, MobileParty tradingParty = null, bool isSelling = false)
		{
			return 0;
		}

		// Token: 0x06003823 RID: 14371 RVA: 0x000E79D5 File Offset: 0x000E5BD5
		public virtual int GetItemPrice(EquipmentElement itemRosterElement, MobileParty tradingParty = null, bool isSelling = false)
		{
			return 0;
		}

		// Token: 0x17000D58 RID: 3416
		// (get) Token: 0x06003824 RID: 14372 RVA: 0x000E79D8 File Offset: 0x000E5BD8
		public virtual bool IsTown
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000D59 RID: 3417
		// (get) Token: 0x06003825 RID: 14373 RVA: 0x000E79DB File Offset: 0x000E5BDB
		public virtual bool IsCastle
		{
			get
			{
				return false;
			}
		}

		// Token: 0x06003826 RID: 14374 RVA: 0x000E79DE File Offset: 0x000E5BDE
		public virtual void OnRelatedPartyRemoved(MobileParty mobileParty)
		{
		}

		// Token: 0x06003827 RID: 14375 RVA: 0x000E79E0 File Offset: 0x000E5BE0
		public List<CharacterObject> GetPrisonerHeroes()
		{
			List<PartyBase> list = new List<PartyBase> { this.Owner };
			foreach (MobileParty mobileParty in this.Owner.Settlement.Parties)
			{
				if (mobileParty.IsGarrison)
				{
					list.Add(mobileParty.Party);
				}
			}
			List<CharacterObject> list2 = new List<CharacterObject>();
			foreach (PartyBase partyBase in list)
			{
				for (int i = 0; i < partyBase.PrisonRoster.Count; i++)
				{
					for (int j = 0; j < partyBase.PrisonRoster.GetElementNumber(i); j++)
					{
						CharacterObject character = partyBase.PrisonRoster.GetElementCopyAtIndex(i).Character;
						if (character.IsHero)
						{
							list2.Add(character);
						}
					}
				}
			}
			return list2;
		}

		// Token: 0x0400115A RID: 4442
		private PartyBase _owner;

		// Token: 0x02000788 RID: 1928
		public enum ProsperityLevel
		{
			// Token: 0x04001EB8 RID: 7864
			Low,
			// Token: 0x04001EB9 RID: 7865
			Mid,
			// Token: 0x04001EBA RID: 7866
			High,
			// Token: 0x04001EBB RID: 7867
			NumberOfLevels
		}
	}
}
