using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Naval
{
	// Token: 0x0200022C RID: 556
	public class AnchorPoint : IInteractablePoint, ITrackableCampaignObject, ITrackableBase
	{
		// Token: 0x060021D9 RID: 8665 RVA: 0x00095CD8 File Offset: 0x00093ED8
		internal static void AutoGeneratedStaticCollectObjectsAnchorPoint(object o, List<object> collectedObjects)
		{
			((AnchorPoint)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060021DA RID: 8666 RVA: 0x00095CE8 File Offset: 0x00093EE8
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			CampaignVec2.AutoGeneratedStaticCollectObjectsCampaignVec2(this._lastUsedDisembarkPosition, collectedObjects);
			CampaignVec2.AutoGeneratedStaticCollectObjectsCampaignVec2(this.Position, collectedObjects);
			CampaignVec2.AutoGeneratedStaticCollectObjectsCampaignVec2(this.TargetPosition, collectedObjects);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.ArrivalTime, collectedObjects);
		}

		// Token: 0x060021DB RID: 8667 RVA: 0x00095D39 File Offset: 0x00093F39
		internal static object AutoGeneratedGetMemberValuePosition(object o)
		{
			return ((AnchorPoint)o).Position;
		}

		// Token: 0x060021DC RID: 8668 RVA: 0x00095D4B File Offset: 0x00093F4B
		internal static object AutoGeneratedGetMemberValueTargetPosition(object o)
		{
			return ((AnchorPoint)o).TargetPosition;
		}

		// Token: 0x060021DD RID: 8669 RVA: 0x00095D5D File Offset: 0x00093F5D
		internal static object AutoGeneratedGetMemberValueArrivalTime(object o)
		{
			return ((AnchorPoint)o).ArrivalTime;
		}

		// Token: 0x060021DE RID: 8670 RVA: 0x00095D6F File Offset: 0x00093F6F
		internal static object AutoGeneratedGetMemberValueIsDisabled(object o)
		{
			return ((AnchorPoint)o).IsDisabled;
		}

		// Token: 0x060021DF RID: 8671 RVA: 0x00095D81 File Offset: 0x00093F81
		internal static object AutoGeneratedGetMemberValue_lastUsedDisembarkPosition(object o)
		{
			return ((AnchorPoint)o)._lastUsedDisembarkPosition;
		}

		// Token: 0x17000852 RID: 2130
		// (get) Token: 0x060021E0 RID: 8672 RVA: 0x00095D93 File Offset: 0x00093F93
		// (set) Token: 0x060021E1 RID: 8673 RVA: 0x00095D9B File Offset: 0x00093F9B
		public MobileParty Owner { get; private set; }

		// Token: 0x17000853 RID: 2131
		// (get) Token: 0x060021E2 RID: 8674 RVA: 0x00095DA4 File Offset: 0x00093FA4
		// (set) Token: 0x060021E3 RID: 8675 RVA: 0x00095DAC File Offset: 0x00093FAC
		[SaveableProperty(1)]
		public CampaignVec2 Position { get; private set; }

		// Token: 0x17000854 RID: 2132
		// (get) Token: 0x060021E4 RID: 8676 RVA: 0x00095DB5 File Offset: 0x00093FB5
		// (set) Token: 0x060021E5 RID: 8677 RVA: 0x00095DBD File Offset: 0x00093FBD
		[SaveableProperty(2)]
		public CampaignVec2 TargetPosition { get; private set; }

		// Token: 0x17000855 RID: 2133
		// (get) Token: 0x060021E6 RID: 8678 RVA: 0x00095DC8 File Offset: 0x00093FC8
		public bool IsMovingToPoint
		{
			get
			{
				return this.ArrivalTime != CampaignTime.Zero && !this.ArrivalTime.IsPast;
			}
		}

		// Token: 0x17000856 RID: 2134
		// (get) Token: 0x060021E7 RID: 8679 RVA: 0x00095DFA File Offset: 0x00093FFA
		public bool IsReady
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000857 RID: 2135
		// (get) Token: 0x060021E8 RID: 8680 RVA: 0x00095DFD File Offset: 0x00093FFD
		// (set) Token: 0x060021E9 RID: 8681 RVA: 0x00095E05 File Offset: 0x00094005
		[SaveableProperty(3)]
		public CampaignTime ArrivalTime { get; private set; } = CampaignTime.Zero;

		// Token: 0x17000858 RID: 2136
		// (get) Token: 0x060021EA RID: 8682 RVA: 0x00095E0E File Offset: 0x0009400E
		// (set) Token: 0x060021EB RID: 8683 RVA: 0x00095E16 File Offset: 0x00094016
		[SaveableProperty(5)]
		public bool IsDisabled { get; set; }

		// Token: 0x17000859 RID: 2137
		// (get) Token: 0x060021EC RID: 8684 RVA: 0x00095E20 File Offset: 0x00094020
		public bool IsValid
		{
			get
			{
				return this.Position.IsValid();
			}
		}

		// Token: 0x1700085A RID: 2138
		// (get) Token: 0x060021ED RID: 8685 RVA: 0x00095E3C File Offset: 0x0009403C
		public TextObject Name
		{
			get
			{
				if (this.Owner.LeaderHero != null)
				{
					TextObject textObject = new TextObject("{=MTuvy9kd}{TROOP.NAME}{.o} Fleet", null);
					textObject.SetCharacterProperties("TROOP", this.Owner.LeaderHero.CharacterObject, false);
					return textObject;
				}
				return new TextObject("{=p6QNVu8p}Fleet", null);
			}
		}

		// Token: 0x060021EE RID: 8686 RVA: 0x00095E8C File Offset: 0x0009408C
		public void CallFleet(Settlement settlement)
		{
			CampaignTime fleetTravelTimeToSettlement = Campaign.Current.Models.PartyTransitionModel.GetFleetTravelTimeToSettlement(this.Owner, settlement);
			if (fleetTravelTimeToSettlement == CampaignTime.Zero)
			{
				this.SetSettlement(settlement);
				return;
			}
			this.ResetPosition();
			this.TargetPosition = settlement.PortPosition;
			this.ArrivalTime = CampaignTime.Now + fleetTravelTimeToSettlement;
		}

		// Token: 0x060021EF RID: 8687 RVA: 0x00095EED File Offset: 0x000940ED
		public AnchorPoint(MobileParty owner)
		{
			this.Owner = owner;
			this.Position = CampaignVec2.Invalid;
		}

		// Token: 0x060021F0 RID: 8688 RVA: 0x00095F14 File Offset: 0x00094114
		public AnchorPoint(AnchorPoint anchor)
		{
			this.Owner = anchor.Owner;
			this.Position = anchor.Position;
			this.TargetPosition = anchor.TargetPosition;
			this._lastUsedDisembarkPosition = anchor._lastUsedDisembarkPosition;
			this.ArrivalTime = anchor.ArrivalTime;
			this.IsDisabled = anchor.IsDisabled;
		}

		// Token: 0x060021F1 RID: 8689 RVA: 0x00095F7C File Offset: 0x0009417C
		public void SetPosition(CampaignVec2 position)
		{
			this.Position = position;
			this.ResetMoveTarget();
			if (this.Owner.IsMainParty)
			{
				if (this.IsValid)
				{
					if (!Campaign.Current.VisualTrackerManager.CheckTracked(this))
					{
						Campaign.Current.VisualTrackerManager.RegisterObject(this);
						return;
					}
				}
				else if (Campaign.Current.VisualTrackerManager.CheckTracked(this))
				{
					Campaign.Current.VisualTrackerManager.RemoveTrackedObject(this, false);
				}
			}
		}

		// Token: 0x060021F2 RID: 8690 RVA: 0x00095FF1 File Offset: 0x000941F1
		public void SetSettlement(Settlement settlement)
		{
			this.SetPosition(settlement.PortPosition);
			this.SetLastUsedDisembarkPosition(settlement.GatePosition);
		}

		// Token: 0x060021F3 RID: 8691 RVA: 0x0009600B File Offset: 0x0009420B
		public void InitializeOnLoad(MobileParty owner)
		{
			this.Owner = owner;
		}

		// Token: 0x060021F4 RID: 8692 RVA: 0x00096014 File Offset: 0x00094214
		public bool CanPartyInteract(MobileParty mobileParty, float dt)
		{
			return mobileParty.IsMainParty && this.IsValid && !this.IsDisabled && mobileParty.Position.Distance(this.GetInteractionPosition(mobileParty)) < Campaign.Current.Models.EncounterModel.NeededMaximumLandDistanceForEncounteringMobileParty;
		}

		// Token: 0x060021F5 RID: 8693 RVA: 0x00096066 File Offset: 0x00094266
		public void SetLastUsedDisembarkPosition(CampaignVec2 pos)
		{
			this._lastUsedDisembarkPosition = pos;
		}

		// Token: 0x060021F6 RID: 8694 RVA: 0x0009606F File Offset: 0x0009426F
		public CampaignVec2 GetLastUsedDisembarkPosition()
		{
			return this._lastUsedDisembarkPosition;
		}

		// Token: 0x060021F7 RID: 8695 RVA: 0x00096077 File Offset: 0x00094277
		public CampaignVec2 GetInteractionPosition(MobileParty interactingParty)
		{
			if (this.IsValid)
			{
				return this._lastUsedDisembarkPosition;
			}
			return CampaignVec2.Invalid;
		}

		// Token: 0x060021F8 RID: 8696 RVA: 0x0009608D File Offset: 0x0009428D
		public void OnPartyInteraction(MobileParty mobileParty)
		{
			mobileParty.Ai.AiBehaviorInteractable = null;
			mobileParty.TargetPosition = this.Position;
			mobileParty.MoveTargetPoint = this.Position;
			mobileParty.SetSailAtPosition(this.Position);
		}

		// Token: 0x060021F9 RID: 8697 RVA: 0x000960C0 File Offset: 0x000942C0
		internal void HourlyTick()
		{
			if (this.ArrivalTime != CampaignTime.Zero && this.ArrivalTime.IsPast)
			{
				this.SetPosition(this.TargetPosition);
				if (this.Owner.IsMainParty)
				{
					InformationManager.DisplayMessage(new InformationMessage(new TextObject("{=qFAhDtrw}Your fleet has arrived at its destination.", null).ToString(), new Color(0f, 1f, 0f, 1f))
					{
						SoundEventPath = "event:/ui/panels/panel_call_fleet"
					});
				}
			}
		}

		// Token: 0x060021FA RID: 8698 RVA: 0x00096146 File Offset: 0x00094346
		TextObject ITrackableBase.GetName()
		{
			return this.Name;
		}

		// Token: 0x060021FB RID: 8699 RVA: 0x00096150 File Offset: 0x00094350
		public Vec3 GetPosition()
		{
			return this.Position.AsVec3();
		}

		// Token: 0x060021FC RID: 8700 RVA: 0x0009616B File Offset: 0x0009436B
		Banner ITrackableCampaignObject.GetBanner()
		{
			return this.Owner.Banner;
		}

		// Token: 0x060021FD RID: 8701 RVA: 0x00096178 File Offset: 0x00094378
		public bool IsAtSettlement(Settlement settlement)
		{
			return !this.IsMovingToPoint && this.IsValid && settlement.PortPosition.Distance(this.Position) < Campaign.Current.Models.EncounterModel.NeededMaximumDistanceForEncounteringTown;
		}

		// Token: 0x060021FE RID: 8702 RVA: 0x000961C4 File Offset: 0x000943C4
		public bool IsTargetingSettlement(Settlement settlement)
		{
			return this.IsMovingToPoint && settlement.PortPosition.Distance(this.TargetPosition) < Campaign.Current.Models.EncounterModel.NeededMaximumDistanceForEncounteringTown;
		}

		// Token: 0x060021FF RID: 8703 RVA: 0x00096208 File Offset: 0x00094408
		public void CheckPositionsForMapChangeAndUpdateIfNeeded()
		{
			if (this.Position.IsValid() && !NavigationHelper.IsPositionValidForNavigationType(this.Position, MobileParty.NavigationType.Naval))
			{
				CampaignVec2 closestNavMeshFaceCenterPositionForPosition = NavigationHelper.GetClosestNavMeshFaceCenterPositionForPosition(this.Position, Campaign.Current.Models.PartyNavigationModel.GetInvalidTerrainTypesForNavigationType(MobileParty.NavigationType.Naval));
				this.Position = NavigationHelper.FindReachablePointAroundPosition(closestNavMeshFaceCenterPositionForPosition, MobileParty.NavigationType.Naval, 8f, 1f, false);
			}
		}

		// Token: 0x06002200 RID: 8704 RVA: 0x0009626C File Offset: 0x0009446C
		public void ResetPosition()
		{
			this.SetPosition(new CampaignVec2(Vec2.Invalid, false));
		}

		// Token: 0x06002201 RID: 8705 RVA: 0x0009627F File Offset: 0x0009447F
		public void ResetMoveTarget()
		{
			this.ArrivalTime = CampaignTime.Zero;
			this.TargetPosition = CampaignVec2.Invalid;
		}

		// Token: 0x040009E3 RID: 2531
		[SaveableField(4)]
		private CampaignVec2 _lastUsedDisembarkPosition;
	}
}
