using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.CampaignBehaviors
{
	// Token: 0x020003D7 RID: 983
	public class CampaignBehaviorManager : ICampaignBehaviorManager
	{
		// Token: 0x06003AFA RID: 15098 RVA: 0x000F5229 File Offset: 0x000F3429
		public CampaignBehaviorManager(IEnumerable<CampaignBehaviorBase> inputComponents)
		{
			this.SetBehaviors(inputComponents);
			this._campaignBehaviorDataStore = new CampaignBehaviorDataStore();
			CampaignEvents.OnBeforeSaveEvent.AddNonSerializedListener(this, new Action(this.OnBeforeSave));
		}

		// Token: 0x06003AFB RID: 15099 RVA: 0x000F525A File Offset: 0x000F345A
		public void InitializeCampaignBehaviors(IEnumerable<CampaignBehaviorBase> inputComponents)
		{
			this.SetBehaviors(inputComponents);
			CampaignEvents.OnBeforeSaveEvent.AddNonSerializedListener(this, new Action(this.OnBeforeSave));
		}

		// Token: 0x06003AFC RID: 15100 RVA: 0x000F527A File Offset: 0x000F347A
		private void SetBehaviors(IEnumerable<CampaignBehaviorBase> inputComponents)
		{
			this._campaignBehaviors = inputComponents.ToList<CampaignBehaviorBase>();
		}

		// Token: 0x06003AFD RID: 15101 RVA: 0x000F5288 File Offset: 0x000F3488
		public void RegisterEvents()
		{
			foreach (CampaignBehaviorBase campaignBehaviorBase in this._campaignBehaviors)
			{
				campaignBehaviorBase.RegisterEvents();
			}
		}

		// Token: 0x06003AFE RID: 15102 RVA: 0x000F52D8 File Offset: 0x000F34D8
		private void OnBeforeSave()
		{
			this._campaignBehaviorDataStore.ClearBehaviorData();
			foreach (CampaignBehaviorBase campaignBehaviorBase in this._campaignBehaviors)
			{
				this._campaignBehaviorDataStore.SaveBehaviorData(campaignBehaviorBase);
			}
		}

		// Token: 0x06003AFF RID: 15103 RVA: 0x000F533C File Offset: 0x000F353C
		public void LoadBehaviorData()
		{
			foreach (CampaignBehaviorBase campaignBehaviorBase in this._campaignBehaviors)
			{
				this._campaignBehaviorDataStore.LoadBehaviorData(campaignBehaviorBase);
			}
			this._campaignBehaviorDataStore.ClearBehaviorData();
		}

		// Token: 0x06003B00 RID: 15104 RVA: 0x000F53A0 File Offset: 0x000F35A0
		public T GetBehavior<T>()
		{
			using (List<CampaignBehaviorBase>.Enumerator enumerator = this._campaignBehaviors.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					CampaignBehaviorBase campaignBehaviorBase;
					if ((campaignBehaviorBase = enumerator.Current) is T)
					{
						return (T)((object)campaignBehaviorBase);
					}
				}
			}
			return default(T);
		}

		// Token: 0x06003B01 RID: 15105 RVA: 0x000F540C File Offset: 0x000F360C
		public IEnumerable<T> GetBehaviors<T>()
		{
			return this._campaignBehaviors.OfType<T>();
		}

		// Token: 0x06003B02 RID: 15106 RVA: 0x000F5419 File Offset: 0x000F3619
		public void AddBehavior(CampaignBehaviorBase campaignBehavior)
		{
			this._campaignBehaviors.Add(campaignBehavior);
			campaignBehavior.RegisterEvents();
		}

		// Token: 0x06003B03 RID: 15107 RVA: 0x000F5430 File Offset: 0x000F3630
		public void RemoveBehavior<T>() where T : CampaignBehaviorBase
		{
			for (int i = this._campaignBehaviors.Count - 1; i >= 0; i--)
			{
				T t;
				if ((t = this._campaignBehaviors[i] as T) != null)
				{
					this._campaignBehaviors.Remove(t);
					CampaignEventDispatcher.Instance.RemoveListeners(t);
					return;
				}
			}
		}

		// Token: 0x06003B04 RID: 15108 RVA: 0x000F5497 File Offset: 0x000F3697
		public void ClearBehaviors()
		{
			this._campaignBehaviors.Clear();
		}

		// Token: 0x06003B05 RID: 15109 RVA: 0x000F54A4 File Offset: 0x000F36A4
		internal static void AutoGeneratedStaticCollectObjectsCampaignBehaviorManager(object o, List<object> collectedObjects)
		{
			((CampaignBehaviorManager)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003B06 RID: 15110 RVA: 0x000F54B2 File Offset: 0x000F36B2
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._campaignBehaviorDataStore);
		}

		// Token: 0x06003B07 RID: 15111 RVA: 0x000F54C0 File Offset: 0x000F36C0
		internal static object AutoGeneratedGetMemberValue_campaignBehaviorDataStore(object o)
		{
			return ((CampaignBehaviorManager)o)._campaignBehaviorDataStore;
		}

		// Token: 0x0400124B RID: 4683
		private List<CampaignBehaviorBase> _campaignBehaviors;

		// Token: 0x0400124C RID: 4684
		[SaveableField(1)]
		private readonly CampaignBehaviorDataStore _campaignBehaviorDataStore;
	}
}
