using System;
using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.CampaignSystem.Siege
{
	// Token: 0x020002DA RID: 730
	public class SiegeStrategy : MBObjectBase
	{
		// Token: 0x060027E6 RID: 10214 RVA: 0x000A6E20 File Offset: 0x000A5020
		internal static void AutoGeneratedStaticCollectObjectsSiegeStrategy(object o, List<object> collectedObjects)
		{
			((SiegeStrategy)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060027E7 RID: 10215 RVA: 0x000A6E2E File Offset: 0x000A502E
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x170009B2 RID: 2482
		// (get) Token: 0x060027E8 RID: 10216 RVA: 0x000A6E37 File Offset: 0x000A5037
		public static MBReadOnlyList<SiegeStrategy> All
		{
			get
			{
				return Campaign.Current.AllSiegeStrategies;
			}
		}

		// Token: 0x170009B3 RID: 2483
		// (get) Token: 0x060027E9 RID: 10217 RVA: 0x000A6E43 File Offset: 0x000A5043
		// (set) Token: 0x060027EA RID: 10218 RVA: 0x000A6E4B File Offset: 0x000A504B
		public TextObject Name { get; private set; }

		// Token: 0x170009B4 RID: 2484
		// (get) Token: 0x060027EB RID: 10219 RVA: 0x000A6E54 File Offset: 0x000A5054
		// (set) Token: 0x060027EC RID: 10220 RVA: 0x000A6E5C File Offset: 0x000A505C
		public TextObject Description { get; private set; }

		// Token: 0x060027ED RID: 10221 RVA: 0x000A6E65 File Offset: 0x000A5065
		public SiegeStrategy(string stringId)
			: base(stringId)
		{
		}

		// Token: 0x060027EE RID: 10222 RVA: 0x000A6E6E File Offset: 0x000A506E
		public void Initialize(TextObject name, TextObject description)
		{
			base.Initialize();
			this.Name = name;
			this.Description = description;
			base.AfterInitialized();
		}
	}
}
