using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election
{
	// Token: 0x020002C3 RID: 707
	public class KingdomPolicyDecision : KingdomDecision
	{
		// Token: 0x060025DC RID: 9692 RVA: 0x0009E734 File Offset: 0x0009C934
		internal static void AutoGeneratedStaticCollectObjectsKingdomPolicyDecision(object o, List<object> collectedObjects)
		{
			((KingdomPolicyDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060025DD RID: 9693 RVA: 0x0009E742 File Offset: 0x0009C942
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Policy);
			collectedObjects.Add(this._kingdomPolicies);
		}

		// Token: 0x060025DE RID: 9694 RVA: 0x0009E763 File Offset: 0x0009C963
		internal static object AutoGeneratedGetMemberValuePolicy(object o)
		{
			return ((KingdomPolicyDecision)o).Policy;
		}

		// Token: 0x060025DF RID: 9695 RVA: 0x0009E770 File Offset: 0x0009C970
		internal static object AutoGeneratedGetMemberValue_isInvertedDecision(object o)
		{
			return ((KingdomPolicyDecision)o)._isInvertedDecision;
		}

		// Token: 0x060025E0 RID: 9696 RVA: 0x0009E782 File Offset: 0x0009C982
		internal static object AutoGeneratedGetMemberValue_kingdomPolicies(object o)
		{
			return ((KingdomPolicyDecision)o)._kingdomPolicies;
		}

		// Token: 0x060025E1 RID: 9697 RVA: 0x0009E78F File Offset: 0x0009C98F
		public KingdomPolicyDecision(Clan proposerClan, PolicyObject policy, bool isInvertedDecision = false)
			: base(proposerClan)
		{
			this.Policy = policy;
			this._isInvertedDecision = isInvertedDecision;
			this._kingdomPolicies = new List<PolicyObject>(base.Kingdom.ActivePolicies);
		}

		// Token: 0x060025E2 RID: 9698 RVA: 0x0009E7BC File Offset: 0x0009C9BC
		public override bool IsAllowed()
		{
			return Campaign.Current.Models.KingdomDecisionPermissionModel.IsPolicyDecisionAllowed(this.Policy);
		}

		// Token: 0x060025E3 RID: 9699 RVA: 0x0009E7D8 File Offset: 0x0009C9D8
		public override int GetProposalInfluenceCost()
		{
			return Campaign.Current.Models.DiplomacyModel.GetInfluenceCostOfPolicyProposalAndDisavowal(base.ProposerClan);
		}

		// Token: 0x060025E4 RID: 9700 RVA: 0x0009E7F4 File Offset: 0x0009C9F4
		public override TextObject GetGeneralTitle()
		{
			return this.Policy.Name;
		}

		// Token: 0x060025E5 RID: 9701 RVA: 0x0009E804 File Offset: 0x0009CA04
		public override TextObject GetSupportTitle()
		{
			TextObject textObject;
			if (this._isInvertedDecision)
			{
				textObject = new TextObject("{=XGcST2dB}Vote to disavow {POLICY_NAME}", null);
			}
			else
			{
				textObject = new TextObject("{=iiH5gKzE}Vote for {POLICY_NAME}", null);
			}
			textObject.SetTextVariable("POLICY_NAME", this.Policy.Name);
			return textObject;
		}

		// Token: 0x060025E6 RID: 9702 RVA: 0x0009E850 File Offset: 0x0009CA50
		public override TextObject GetChooseTitle()
		{
			TextObject textObject;
			if (this._isInvertedDecision)
			{
				textObject = new TextObject("{=9DaDtQbo}Disavow {POLICY_NAME}", null);
			}
			else
			{
				textObject = new TextObject("{=UNz9Q7Bz}Decide on {POLICY_NAME}", null);
			}
			textObject.SetTextVariable("POLICY_NAME", this.Policy.Name);
			return textObject;
		}

		// Token: 0x060025E7 RID: 9703 RVA: 0x0009E89C File Offset: 0x0009CA9C
		public override TextObject GetSupportDescription()
		{
			TextObject textObject;
			if (this._isInvertedDecision)
			{
				textObject = new TextObject("{=ZPv3uCOb}{FACTION_LEADER} proposes disavowing the policy of {POLICY_NAME}. You can pick your stance regarding this decision.", null);
			}
			else
			{
				textObject = new TextObject("{=jFOva44m}{FACTION_LEADER} proposes the policy of {POLICY_NAME}. You can pick your stance regarding this decision.", null);
			}
			textObject.SetTextVariable("FACTION_LEADER", this.DetermineChooser().Leader.Name);
			textObject.SetTextVariable("POLICY_NAME", this.Policy.Name);
			return textObject;
		}

		// Token: 0x060025E8 RID: 9704 RVA: 0x0009E904 File Offset: 0x0009CB04
		public override TextObject GetChooseDescription()
		{
			TextObject textObject;
			if (this._isInvertedDecision)
			{
				textObject = new TextObject("{=1AU2jnNV}As {?IS_FEMALE}queen{?}king{\\?} you must decide whether to disavow the policy of {POLICY_NAME}.", null);
			}
			else
			{
				textObject = new TextObject("{=0EqPRs21}As {?IS_FEMALE}queen{?}king{\\?} you must decide whether to enforce the policy of {POLICY_NAME}.", null);
			}
			textObject.SetTextVariable("IS_FEMALE", this.DetermineChooser().Leader.IsFemale ? 1 : 0);
			textObject.SetTextVariable("POLICY_NAME", this.Policy.Name);
			return textObject;
		}

		// Token: 0x060025E9 RID: 9705 RVA: 0x0009E96F File Offset: 0x0009CB6F
		public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
		{
			yield return new KingdomPolicyDecision.PolicyDecisionOutcome(true);
			yield return new KingdomPolicyDecision.PolicyDecisionOutcome(false);
			yield break;
		}

		// Token: 0x060025EA RID: 9706 RVA: 0x0009E978 File Offset: 0x0009CB78
		public override Clan DetermineChooser()
		{
			return base.Kingdom.RulingClan;
		}

		// Token: 0x060025EB RID: 9707 RVA: 0x0009E985 File Offset: 0x0009CB85
		public float CalculateSupport(Clan clan)
		{
			return this.DetermineSupport(clan, new KingdomPolicyDecision.PolicyDecisionOutcome(true));
		}

		// Token: 0x060025EC RID: 9708 RVA: 0x0009E994 File Offset: 0x0009CB94
		protected override bool ShouldBeCancelledInternal()
		{
			if (!this._isInvertedDecision)
			{
				return base.Kingdom.ActivePolicies.Contains(this.Policy);
			}
			return !base.Kingdom.ActivePolicies.Contains(this.Policy);
		}

		// Token: 0x060025ED RID: 9709 RVA: 0x0009E9D0 File Offset: 0x0009CBD0
		public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
		{
			KingdomPolicyDecision.PolicyDecisionOutcome policyDecisionOutcome = possibleOutcome as KingdomPolicyDecision.PolicyDecisionOutcome;
			float num = 0.1f;
			float num2 = 0.1f;
			float num3 = 0.1f;
			if (clan.Kingdom != null && clan.Kingdom.RulingClan == clan)
			{
				num2 += 1f;
				num3 -= 1.5f;
				num -= 0.4f;
			}
			else if (clan.IsMinorFaction)
			{
				num += 1f;
				num3 -= 1.5f;
				num2 -= 0.3f;
			}
			else if (clan.Tier >= 3)
			{
				num -= 1.3f;
				num3 += (float)clan.Tier * 0.2f;
				num2 -= 1.3f;
			}
			else if (clan.Tier == 2)
			{
				num2 -= 0.1f;
				num3 += 0.4f;
				num -= 0.5f;
			}
			CultureObject culture = clan.Culture;
			num += 0.6f * (float)clan.Leader.GetTraitLevel(DefaultTraits.Egalitarian) - 0.9f * (float)clan.Leader.GetTraitLevel(DefaultTraits.Oligarchic);
			num3 += 0.6f * (float)clan.Leader.GetTraitLevel(DefaultTraits.Oligarchic) - 0.9f * (float)clan.Leader.GetTraitLevel(DefaultTraits.Egalitarian) - 0.5f * (float)clan.Leader.GetTraitLevel(DefaultTraits.Authoritarian);
			num2 += 0.8f * (float)clan.Leader.GetTraitLevel(DefaultTraits.Authoritarian) - 1.3f * (float)clan.Leader.GetTraitLevel(DefaultTraits.Oligarchic);
			float num4 = this.Policy.EgalitarianWeight * num + this.Policy.OligarchicWeight * num3 + this.Policy.AuthoritarianWeight * num2;
			if (this._isInvertedDecision)
			{
				num4 = -num4;
			}
			float num5;
			if (policyDecisionOutcome.ShouldDecisionBeEnforced)
			{
				num5 = 60f;
			}
			else
			{
				num5 = -100f;
			}
			return num4 * num5;
		}

		// Token: 0x060025EE RID: 9710 RVA: 0x0009EBA0 File Offset: 0x0009CDA0
		public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			foreach (DecisionOutcome decisionOutcome in possibleOutcomes)
			{
				if (((KingdomPolicyDecision.PolicyDecisionOutcome)decisionOutcome).ShouldDecisionBeEnforced)
				{
					decisionOutcome.SetSponsor(base.ProposerClan);
				}
				else
				{
					base.AssignDefaultSponsor(decisionOutcome);
				}
			}
		}

		// Token: 0x060025EF RID: 9711 RVA: 0x0009EC0C File Offset: 0x0009CE0C
		public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
		{
			bool shouldDecisionBeEnforced = ((KingdomPolicyDecision.PolicyDecisionOutcome)chosenOutcome).ShouldDecisionBeEnforced;
			if (shouldDecisionBeEnforced && !this._isInvertedDecision)
			{
				base.Kingdom.AddPolicy(this.Policy);
				return;
			}
			if (shouldDecisionBeEnforced && this._isInvertedDecision)
			{
				base.Kingdom.RemovePolicy(this.Policy);
			}
		}

		// Token: 0x060025F0 RID: 9712 RVA: 0x0009EC60 File Offset: 0x0009CE60
		public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, KingdomDecision.SupportStatus supportStatus, bool isShortVersion = false)
		{
			TextObject textObject;
			if ((((KingdomPolicyDecision.PolicyDecisionOutcome)chosenOutcome).ShouldDecisionBeEnforced && !this._isInvertedDecision) || (!((KingdomPolicyDecision.PolicyDecisionOutcome)chosenOutcome).ShouldDecisionBeEnforced && this._isInvertedDecision))
			{
				if (!this._kingdomPolicies.Contains(this.Policy))
				{
					textObject = new TextObject("{=Lbs2bNlg}The {KINGDOM} will start {POLICY_DESCRIPTION} ({POLICY}). {POLICY_SUPPORT}", null);
				}
				else
				{
					textObject = new TextObject("{=jnYwiCAz}The {KINGDOM} will continue {POLICY_DESCRIPTION} ({POLICY}). {POLICY_SUPPORT}", null);
				}
			}
			else if (this._kingdomPolicies.Contains(this.Policy))
			{
				textObject = new TextObject("{=2BVDp7Tg}The {KINGDOM} will stop {POLICY_DESCRIPTION} ({POLICY}). {POLICY_SUPPORT}", null);
			}
			else
			{
				textObject = new TextObject("{=faUooB7V}The {KINGDOM} will not be {POLICY_DESCRIPTION} ({POLICY}). {POLICY_SUPPORT}", null);
			}
			textObject.SetTextVariable("KINGDOM", base.Kingdom.InformalName);
			textObject.SetTextVariable("POLICY", this.Policy.Name);
			textObject.SetTextVariable("POLICY_DESCRIPTION", this.Policy.LogEntryDescription);
			if (isShortVersion || base.IsSingleClanDecision())
			{
				textObject.SetTextVariable("POLICY_SUPPORT", TextObject.GetEmpty());
			}
			else
			{
				textObject.SetTextVariable("POLICY_SUPPORT", "{=bqEO389P}This decision caused a split in the council.");
				if (supportStatus == KingdomDecision.SupportStatus.Majority)
				{
					textObject.SetTextVariable("POLICY_SUPPORT", "{=3W67kdtc}This decision had the support of the council.");
				}
				if (supportStatus == KingdomDecision.SupportStatus.Minority)
				{
					textObject.SetTextVariable("POLICY_SUPPORT", "{=b6MgRYlM}This decision was opposed by most of the council.");
				}
			}
			return textObject;
		}

		// Token: 0x060025F1 RID: 9713 RVA: 0x0009ED92 File Offset: 0x0009CF92
		public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			return possibleOutcomes.FirstOrDefault<DecisionOutcome>((DecisionOutcome t) => ((KingdomPolicyDecision.PolicyDecisionOutcome)t).ShouldDecisionBeEnforced);
		}

		// Token: 0x060025F2 RID: 9714 RVA: 0x0009EDB9 File Offset: 0x0009CFB9
		public override TextObject GetSecondaryEffects()
		{
			return this.Policy.SecondaryEffects;
		}

		// Token: 0x060025F3 RID: 9715 RVA: 0x0009EDC6 File Offset: 0x0009CFC6
		public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
		{
		}

		// Token: 0x04000B55 RID: 2901
		[SaveableField(200)]
		public readonly PolicyObject Policy;

		// Token: 0x04000B56 RID: 2902
		[SaveableField(203)]
		private bool _isInvertedDecision;

		// Token: 0x04000B57 RID: 2903
		[SaveableField(202)]
		private List<PolicyObject> _kingdomPolicies;

		// Token: 0x0200065B RID: 1627
		public class PolicyDecisionOutcome : DecisionOutcome
		{
			// Token: 0x0600517D RID: 20861 RVA: 0x00189FAA File Offset: 0x001881AA
			internal static void AutoGeneratedStaticCollectObjectsPolicyDecisionOutcome(object o, List<object> collectedObjects)
			{
				((KingdomPolicyDecision.PolicyDecisionOutcome)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600517E RID: 20862 RVA: 0x00189FB8 File Offset: 0x001881B8
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600517F RID: 20863 RVA: 0x00189FC1 File Offset: 0x001881C1
			internal static object AutoGeneratedGetMemberValueShouldDecisionBeEnforced(object o)
			{
				return ((KingdomPolicyDecision.PolicyDecisionOutcome)o).ShouldDecisionBeEnforced;
			}

			// Token: 0x17000F47 RID: 3911
			// (get) Token: 0x06005180 RID: 20864 RVA: 0x00189FD3 File Offset: 0x001881D3
			// (set) Token: 0x06005181 RID: 20865 RVA: 0x00189FDB File Offset: 0x001881DB
			[SaveableProperty(200)]
			public bool ShouldDecisionBeEnforced { get; private set; }

			// Token: 0x06005182 RID: 20866 RVA: 0x00189FE4 File Offset: 0x001881E4
			public override TextObject GetDecisionTitle()
			{
				TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}", null);
				textObject.SetTextVariable("SUPPORT", this.ShouldDecisionBeEnforced ? 1 : 0);
				return textObject;
			}

			// Token: 0x06005183 RID: 20867 RVA: 0x0018A009 File Offset: 0x00188209
			public override TextObject GetDecisionDescription()
			{
				if (this.ShouldDecisionBeEnforced)
				{
					return new TextObject("{=pWyxaauF}We support this proposal", null);
				}
				return new TextObject("{=BktSNgY4}We oppose this proposal", null);
			}

			// Token: 0x06005184 RID: 20868 RVA: 0x0018A02A File Offset: 0x0018822A
			public override string GetDecisionLink()
			{
				return null;
			}

			// Token: 0x06005185 RID: 20869 RVA: 0x0018A02D File Offset: 0x0018822D
			public override ImageIdentifier GetDecisionImageIdentifier()
			{
				return null;
			}

			// Token: 0x06005186 RID: 20870 RVA: 0x0018A030 File Offset: 0x00188230
			public PolicyDecisionOutcome(bool shouldBeEnforced)
			{
				this.ShouldDecisionBeEnforced = shouldBeEnforced;
			}
		}
	}
}
