using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election
{
	// Token: 0x020002CB RID: 715
	public class StartAllianceDecision : KingdomDecision
	{
		// Token: 0x06002697 RID: 9879 RVA: 0x000A1304 File Offset: 0x0009F504
		internal static void AutoGeneratedStaticCollectObjectsStartAllianceDecision(object o, List<object> collectedObjects)
		{
			((StartAllianceDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002698 RID: 9880 RVA: 0x000A1312 File Offset: 0x0009F512
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.KingdomToStartAllianceWith);
		}

		// Token: 0x06002699 RID: 9881 RVA: 0x000A1327 File Offset: 0x0009F527
		internal static object AutoGeneratedGetMemberValueKingdomToStartAllianceWith(object o)
		{
			return ((StartAllianceDecision)o).KingdomToStartAllianceWith;
		}

		// Token: 0x1700097F RID: 2431
		// (get) Token: 0x0600269A RID: 9882 RVA: 0x000A1334 File Offset: 0x0009F534
		public IAllianceCampaignBehavior AllianceCampaignBehavior
		{
			get
			{
				if (this._allianceCampaignBehavior == null)
				{
					this._allianceCampaignBehavior = Campaign.Current.GetCampaignBehavior<IAllianceCampaignBehavior>();
				}
				return this._allianceCampaignBehavior;
			}
		}

		// Token: 0x0600269B RID: 9883 RVA: 0x000A1354 File Offset: 0x0009F554
		public StartAllianceDecision(Clan proposerClan, Kingdom kingdomToStartAllianceWith)
			: base(proposerClan)
		{
			this.KingdomToStartAllianceWith = kingdomToStartAllianceWith;
		}

		// Token: 0x0600269C RID: 9884 RVA: 0x000A1364 File Offset: 0x0009F564
		public override bool IsAllowed()
		{
			TextObject textObject;
			return Campaign.Current.Models.KingdomDecisionPermissionModel.IsStartAllianceDecisionAllowedBetweenKingdoms(base.Kingdom, this.KingdomToStartAllianceWith, out textObject);
		}

		// Token: 0x0600269D RID: 9885 RVA: 0x000A1393 File Offset: 0x0009F593
		public override int GetProposalInfluenceCost()
		{
			return Campaign.Current.Models.AllianceModel.GetInfluenceCostOfProposingStartingAlliance(base.ProposerClan);
		}

		// Token: 0x0600269E RID: 9886 RVA: 0x000A13AF File Offset: 0x0009F5AF
		public override TextObject GetGeneralTitle()
		{
			TextObject textObject = new TextObject("{=aE7OQDMS}Form alliance with the {KINGDOM_NAME}", null);
			textObject.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.InformalName);
			return textObject;
		}

		// Token: 0x0600269F RID: 9887 RVA: 0x000A13D3 File Offset: 0x0009F5D3
		public override TextObject GetSupportTitle()
		{
			TextObject textObject = new TextObject("{=iOmgCFDI}Vote to form an alliance with the {KINGDOM_NAME}.", null);
			textObject.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.InformalName);
			return textObject;
		}

		// Token: 0x060026A0 RID: 9888 RVA: 0x000A13F7 File Offset: 0x0009F5F7
		public override TextObject GetChooseTitle()
		{
			TextObject textObject = new TextObject("{=KlATZEbb}Forming an Alliance with the {KINGDOM_NAME}.", null);
			textObject.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.InformalName);
			return textObject;
		}

		// Token: 0x060026A1 RID: 9889 RVA: 0x000A141B File Offset: 0x0009F61B
		public override TextObject GetSupportDescription()
		{
			TextObject textObject = new TextObject("{=wijL0mTy}{FACTION_LEADER} will decide if an alliance will be formed with the {KINGDOM_NAME}. You can pick your stance regarding this decision.", null);
			textObject.SetTextVariable("FACTION_LEADER", this.DetermineChooser().Leader.Name);
			textObject.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.InformalName);
			return textObject;
		}

		// Token: 0x060026A2 RID: 9890 RVA: 0x000A145C File Offset: 0x0009F65C
		public override TextObject GetChooseDescription()
		{
			TextObject textObject = new TextObject("{=eAhgrwkZ}As {RULER_NAME_AND_TITLE}, you must decide if an alliance will be formed with the {KINGDOM_NAME}.", null);
			textObject.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject, false);
			textObject.SetTextVariable("RULER_NAME_AND_TITLE", GameTexts.FindText("str_faction_ruler_name_with_title", base.Kingdom.Culture.StringId));
			textObject.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.InformalName);
			return textObject;
		}

		// Token: 0x060026A3 RID: 9891 RVA: 0x000A14CD File Offset: 0x0009F6CD
		public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
		{
			yield return new StartAllianceDecision.StartAllianceDecisionOutcome(true, base.Kingdom, this.KingdomToStartAllianceWith);
			yield return new StartAllianceDecision.StartAllianceDecisionOutcome(false, base.Kingdom, this.KingdomToStartAllianceWith);
			yield break;
		}

		// Token: 0x060026A4 RID: 9892 RVA: 0x000A14DD File Offset: 0x0009F6DD
		public override Clan DetermineChooser()
		{
			return base.Kingdom.RulingClan;
		}

		// Token: 0x060026A5 RID: 9893 RVA: 0x000A14EC File Offset: 0x0009F6EC
		protected override bool ShouldBeCancelledInternal()
		{
			TextObject textObject;
			return !this.CanMakeDecision(out textObject, false);
		}

		// Token: 0x060026A6 RID: 9894 RVA: 0x000A1508 File Offset: 0x0009F708
		public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			foreach (DecisionOutcome decisionOutcome in possibleOutcomes)
			{
				if (((StartAllianceDecision.StartAllianceDecisionOutcome)decisionOutcome).ShouldAllianceBeStarted)
				{
					decisionOutcome.SetSponsor(base.ProposerClan);
				}
				else
				{
					base.AssignDefaultSponsor(decisionOutcome);
				}
			}
		}

		// Token: 0x060026A7 RID: 9895 RVA: 0x000A1574 File Offset: 0x0009F774
		public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
		{
			if (((StartAllianceDecision.StartAllianceDecisionOutcome)chosenOutcome).ShouldAllianceBeStarted)
			{
				this.AllianceCampaignBehavior.StartAlliance(base.Kingdom, this.KingdomToStartAllianceWith);
			}
		}

		// Token: 0x060026A8 RID: 9896 RVA: 0x000A159A File Offset: 0x0009F79A
		public override bool OnShowDecision()
		{
			if (this.KingdomToStartAllianceWith == Clan.PlayerClan.Kingdom && !Hero.MainHero.Clan.IsUnderMercenaryService)
			{
				this.AllianceCampaignBehavior.OnAllianceOfferedToPlayerKingdom(base.Kingdom);
				return false;
			}
			return true;
		}

		// Token: 0x060026A9 RID: 9897 RVA: 0x000A15D3 File Offset: 0x0009F7D3
		public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
		{
		}

		// Token: 0x060026AA RID: 9898 RVA: 0x000A15D5 File Offset: 0x0009F7D5
		public override TextObject GetSecondaryEffects()
		{
			return new TextObject("{=!}All supporters gains some relation with each other.", null);
		}

		// Token: 0x060026AB RID: 9899 RVA: 0x000A15E4 File Offset: 0x0009F7E4
		public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, KingdomDecision.SupportStatus supportStatus, bool isShortVersion = false)
		{
			TextObject textObject;
			if (((StartAllianceDecision.StartAllianceDecisionOutcome)chosenOutcome).ShouldAllianceBeStarted)
			{
				if (base.IsSingleClanDecision())
				{
					textObject = new TextObject("{=INfHUqxT}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME}.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Majority)
				{
					textObject = new TextObject("{=FNCq25P1}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} with the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Minority)
				{
					textObject = new TextObject("{=bYmc9fi3}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} despite the opposition of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else
				{
					textObject = new TextObject("{=izwKmH2I}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} with the support of half of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
			}
			else if (base.IsSingleClanDecision())
			{
				textObject = new TextObject("{=o4IxXHnB}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME}.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Majority)
			{
				textObject = new TextObject("{=bR7MIkFi}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} with the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Minority)
			{
				textObject = new TextObject("{=F7CMsDyG}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} despite the opposition of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else
			{
				textObject = new TextObject("{=jaioXYDc}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} with the support of half of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			StringHelpers.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject, textObject, false);
			textObject.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.Name);
			return textObject;
		}

		// Token: 0x060026AC RID: 9900 RVA: 0x000A16C1 File Offset: 0x0009F8C1
		public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			return possibleOutcomes.FirstOrDefault<DecisionOutcome>((DecisionOutcome t) => ((StartAllianceDecision.StartAllianceDecisionOutcome)t).ShouldAllianceBeStarted);
		}

		// Token: 0x060026AD RID: 9901 RVA: 0x000A16E8 File Offset: 0x0009F8E8
		public float CalculateSupport(Clan clan, out TextObject hint, bool includeDescriptions = false)
		{
			return this.DetermineSupport(clan, new StartAllianceDecision.StartAllianceDecisionOutcome(true, base.Kingdom, this.KingdomToStartAllianceWith), out hint, includeDescriptions);
		}

		// Token: 0x060026AE RID: 9902 RVA: 0x000A1708 File Offset: 0x0009F908
		public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
		{
			TextObject textObject;
			return this.DetermineSupport(clan, possibleOutcome, out textObject, false);
		}

		// Token: 0x060026AF RID: 9903 RVA: 0x000A1720 File Offset: 0x0009F920
		private float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome, out TextObject hint, bool includeDescriptions)
		{
			StartAllianceDecision.StartAllianceDecisionOutcome startAllianceDecisionOutcome = (StartAllianceDecision.StartAllianceDecisionOutcome)possibleOutcome;
			float supportScoreOfStartingAllianceForClan = Campaign.Current.Models.AllianceModel.GetSupportScoreOfStartingAllianceForClan(base.Kingdom, this.KingdomToStartAllianceWith, clan, out hint, includeDescriptions);
			if (startAllianceDecisionOutcome.ShouldAllianceBeStarted)
			{
				return supportScoreOfStartingAllianceForClan;
			}
			return -supportScoreOfStartingAllianceForClan;
		}

		// Token: 0x060026B0 RID: 9904 RVA: 0x000A1763 File Offset: 0x0009F963
		public override bool CanMakeDecision(out TextObject reason, bool includeReason = false)
		{
			return Campaign.Current.Models.AllianceModel.CanMakeAlliance(base.Kingdom, this.KingdomToStartAllianceWith, base.ProposerClan, out reason, includeReason);
		}

		// Token: 0x04000B69 RID: 2921
		[SaveableField(101)]
		public readonly Kingdom KingdomToStartAllianceWith;

		// Token: 0x04000B6A RID: 2922
		private IAllianceCampaignBehavior _allianceCampaignBehavior;

		// Token: 0x02000671 RID: 1649
		public class StartAllianceDecisionOutcome : DecisionOutcome
		{
			// Token: 0x06005209 RID: 21001 RVA: 0x0018AE54 File Offset: 0x00189054
			public StartAllianceDecisionOutcome(bool shouldAllianceBeStarted, Kingdom kingdom, Kingdom kingdomToStartAllianceWith)
			{
				this.ShouldAllianceBeStarted = shouldAllianceBeStarted;
				this.Kingdom = kingdom;
				this.KingdomToStartAllianceWith = kingdomToStartAllianceWith;
			}

			// Token: 0x0600520A RID: 21002 RVA: 0x0018AE71 File Offset: 0x00189071
			public override TextObject GetDecisionTitle()
			{
				TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}", null);
				textObject.SetTextVariable("SUPPORT", this.ShouldAllianceBeStarted ? 1 : 0);
				return textObject;
			}

			// Token: 0x0600520B RID: 21003 RVA: 0x0018AE98 File Offset: 0x00189098
			public override TextObject GetDecisionDescription()
			{
				if (this.ShouldAllianceBeStarted)
				{
					TextObject textObject = new TextObject("{=k3418kiP}It is time to form alliance with {KINGDOM_NAME}.", null);
					textObject.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.Name);
					return textObject;
				}
				TextObject textObject2 = new TextObject("{=M1X2R8Uv}We oppose forming an alliance with {KINGDOM_NAME}.", null);
				textObject2.SetTextVariable("KINGDOM_NAME", this.KingdomToStartAllianceWith.Name);
				return textObject2;
			}

			// Token: 0x0600520C RID: 21004 RVA: 0x0018AEF2 File Offset: 0x001890F2
			public override string GetDecisionLink()
			{
				return null;
			}

			// Token: 0x0600520D RID: 21005 RVA: 0x0018AEF5 File Offset: 0x001890F5
			public override ImageIdentifier GetDecisionImageIdentifier()
			{
				return null;
			}

			// Token: 0x04001A23 RID: 6691
			[SaveableField(100)]
			public readonly bool ShouldAllianceBeStarted;

			// Token: 0x04001A24 RID: 6692
			[SaveableField(110)]
			public readonly Kingdom Kingdom;

			// Token: 0x04001A25 RID: 6693
			[SaveableField(120)]
			public readonly Kingdom KingdomToStartAllianceWith;
		}
	}
}
