using System;
using System.Collections.Generic;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.GameState
{
	// Token: 0x02000385 RID: 901
	public class MapStateData
	{
		// Token: 0x060034A0 RID: 13472 RVA: 0x000D90C0 File Offset: 0x000D72C0
		internal static void AutoGeneratedStaticCollectObjectsMapStateData(object o, List<object> collectedObjects)
		{
			((MapStateData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060034A1 RID: 13473 RVA: 0x000D90CE File Offset: 0x000D72CE
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x060034A2 RID: 13474 RVA: 0x000D90D0 File Offset: 0x000D72D0
		internal static object AutoGeneratedGetMemberValueGameMenuId(object o)
		{
			return ((MapStateData)o).GameMenuId;
		}

		// Token: 0x04000F10 RID: 3856
		[SaveableField(1)]
		public string GameMenuId;
	}
}
